### PR TITLE
fix: handle requests for double slash in dev

### LINKED ISSUE #12722: Invalid URL error when domain contains multiple slashes at the end
### Astro Info

```block
Astro                    v5.0.5
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Astro throws 500 Internal Server Error with "Invalid URL" when main domain contains double or more slashes at the end. This happens in development server, production build, StackBlitz. This is not a browser issue. The problem occurs at server level and can be reproduced with curl.

### What's the expected result?

- Redirect to normalized version

Instead the server crashes with 500 error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-726xsb6l-xoqxvvkc

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Fixes a bug caused by the fact that `new URL("//", "http://localhost")` is invalid: it treats the double slash as an empty protocol-relative URL. This caused a 500 error if there was a request for `http://localhost//`. Now it handles that type of URL correctly, and also redirects to `/`. This redirect is only implemented for dev, because support for it in platforms is poor, and needs special handling. For that reason we can defer rto the adapters to handle it.

Fixes #12722 

## Testing

Adds tests

### CODE REVIEW

File: packages/astro/src/core/routing/manifest/create.ts [hunk 1]
```diff
@@ -502,6 +506,27 @@ export async function createRouteManifest(
...
+			component: '/',
+			generate: () => '//',
+			pathname: '//',
+			prerender: false,
+			redirect: '/',
+			redirectRoute: routeMap.get('/'),
+			fallbackRoutes: [],
+			distURL: [],
+			origin: 'project',
+		});
```
Comment (ematipico) [inline packages/astro/src/core/routing/manifest/create.ts:528]: I would advise against creating full routes like this because many of those data might not be mandatory, and some of them need to be built using the proper functions. E.g. `getPattern` or `getRouteGenerator`.

Plus, we need to take into consideration things like `base`, `trailing slash` and more. Follow this pattern:

https://github.com/withastro/astro/blob/901c21f4f09bf61dfbb5ab04db2d7d90120383cb/packages/astro/src/core/routing/manifest/create.ts#L237-L261

It requires more code, but it's more reliable

Comment (ascorbic) [reply packages/astro/src/core/routing/manifest/create.ts:528]: I tried that at first but it didn't seem to be possible for this. Unless I'm missing something, the path isn't one that can be represented with segments. It's for a specific path, regardless of trailing slash or base rules. The pattern needs to match two or more slashes, whether or not trailing slash is enabled, and doesn't apply if base is set. Of the fields I included, it looks like `pathname` is the only one that's optional.

Comment (ematipico) [reply packages/astro/src/core/routing/manifest/create.ts:531]: Ok, then I will probably go for a solution that doesn't involve creating a new route, because this has repercussions on downstream adapters and integrations. 

Like, can't we handle these cases at the source? Like in the dev server and `App`

Comment (ascorbic) [reply packages/astro/src/core/routing/manifest/create.ts:531]: Yeah I think you're right. I did initially start implementing it like that and thought "wait why am I re-inventing redirects" but it does make sense, when these can't be properly represented as redirects

Comment (screenfluent) [reply packages/astro/src/core/routing/manifest/create.ts]: Many thanks for the patch! However I'd like to double-check. Does this fix the production issue where you get a 200 response when trying to access URLs like https://astro.build/// or https://astro.build////blog/ ?
