### PR TITLE
fix: handle other elements before the `svg` element 

### LINKED ISSUE #12500: [5.0.0-beta.9] SVG component not accepting some SVGs
### Astro Info

```block
Astro                    v5.0.0-beta.9
Node                     v23.1.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

I found that some SVGs can't be shown by the SVG component. 

The SVG file:
dragon
(from <https://www.freeimages.com/vector/dragoncraftstrokepng-5690499>)

Stack Trace:
```
TypeError: Cannot read properties of undefined (reading 'map')
    at C (file:///home/user/program/violet-visual/node_modules/.pnpm/ultrahtml@1.5.3/node_modules/ultrahtml/dist/index.js:1:4250)
    at parseSvg (file:///home/user/program/violet-visual/node_modules/.pnpm/astro@5.0.0-beta.9_rollup@4.27.3_typescript@5.6.3/node_modules/astro/dist/assets/utils/svg.js:6:16)
    at makeSvgComponent (file:///home/user/program/violet-visual/node_modules/.pnpm/astro@5.0.0-beta.9_rollup@4.27.3_typescript@5.6.3/node_modules/astro/dist/assets/utils/svg.js:11:42)
    at LoadPluginContext.load (file:///home/user/program/violet-visual/node_modules/.pnpm/astro@5.0.0-beta.9_rollup@4.27.3_typescript@5.6.3/node_modules/astro/dist/assets/vite-plugin-assets.js:179:20)
    at async EnvironmentPluginContainer.load (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/chunks/dep-D4jOq5eU.js:49089:22)
    at async loadAndTransform (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/chunks/dep-D4jOq5eU.js:43100:22)
    at async fetchModule (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/chunks/dep-D4jOq5eU.js:53213:16)
    at async SSRCompatModuleRunner.getModuleInformation (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/module-runner.js:968:73)
    at async request (file:///home/user/program/violet-visual/node_modules/.pnpm/vite@6.0.0-beta.6/node_modules/vite/dist/node/module-runner.js:986:88)
    at async eval (/home/user/program/violet-visual/src/content/blog/using-mdx.mdx:24:1)
```

### What's the expected result?

The SVG is rendered correctly.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-buzorg

(I put the SVG in `src/content/blog/using-mdx.mdx`)

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by stramel**
## Changes

Fixes #12500 

The issue was that we were assuming that the `svg` element was the first and only root node. To fix this, we now search for the `svg` element. 

## Testing

I added a test that fails without this change.

## Docs

N/A

@ematipico @natemoo-re

### CODE REVIEW

File: packages/astro/src/assets/utils/svg.ts [hunk 1]
```diff
@@ -5,7 +5,9 @@ import type { ImageMetadata } from '../types.js';
 
 function parseSvg(contents: string) {
 	const root = parse(contents);
-	const [{ attributes, children }] = root.children;
+	const { attributes, children } = root.children.find(
+		({ name, type }: { name: string; type: number }) => type === 1 /* Element */ && name === 'svg',
+	);
```
Comment (bluwy) [inline packages/astro/src/assets/utils/svg.ts:10]: (optional) perhaps we should also handle the case where we can't find any svg element

**Review by bluwy — APPROVED** [review]

File: packages/astro/src/assets/utils/svg.ts (hunk 1 above)
Comment (ematipico) [reply packages/astro/src/assets/utils/svg.ts:10]: I agree as well

**Review by ematipico — APPROVED** [review]
