### PR TITLE
Surface console output from workerd during Cloudflare prerendering

### LINKED ISSUE #16200: [Bug]: `console.log`/`console.warn` output from workerd is silently swallowed during prerendering
### Astro Info

```block
Astro                    v6.1.3
Vite                     v7.3.1
Node                     v25.8.2
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare (v13.1.7)
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using `@astrojs/cloudflare` with hybrid output (mix of prerendered and server-rendered pages), `console.log` and `console.warn` calls that execute inside workerd during the prerender phase are silently swallowed. No output appears in the build log.

The prerenderer creates its own Vite preview server with `logLevel: "error"`:

```js
// node_modules/@astrojs/cloudflare/dist/prerenderer.js, line 26-34
previewServer = await preview({
  configFile: false,
  // ...
  logLevel: "error",   // <-- suppresses info/warn output
  // ...
  plugins: [cfVitePlugin({ ...cfPluginConfig, viteEnvironment: { name: "prerender" } })]
});
```

Worker `console.log`/`console.warn` output flows through miniflare's structured logging into `ViteMiniflareLogger.info()`, which delegates to Vite's logger. Since `logLevel: "error"`, Vite drops anything below error level.

Additionally, because `configFile: false` is set, user Vite plugins cannot intercept or configure this internal preview server.

### What's the expected result?

`console.log` and `console.warn` output from workerd during prerendering should appear in the build output, just as they do during `astro dev`.

This is especially important for debugging prerender-time issues — data fetching errors, missing environment variables, or unexpected data shapes that produce incorrect HTML without any visible error.

---

### Potential fix

The prerender Vite preview server could use `logLevel: "info"` (or at least `"warn"`) so that worker console output is not suppressed:

```js
previewServer = await preview({
  configFile: false,
  // ...
  logLevel: "info",   // or "warn" as a compromise
  // ...
});
```

Alternatively, the `@cloudflare/vite-plugin` could bypass the Vite logger for worker console output and write directly to `process.stderr`, which would be independent of the Vite log level.

### Link to Minimal Reproducible Example

https://github.com/adamchal/cloudflare-prerender-logs

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Worker `console.log`/`console.warn` output during prerendering was silently swallowed because the internal Vite preview server in `@astrojs/cloudflare` used `logLevel: 'error'`. Changed to `logLevel: 'info'` so that console output from workerd is no longer suppressed.

Closes #16200

## Testing

- Tested manually

## Docs

- N/A, bug fix

### CODE REVIEW

**Comment by matthewp** [comment]
@Princesseuh mentioned this was set intentional to avoid noisy logging. Here's what's output with this change:

```
 prerendering static routes
08:30:39   ├─ /index.htmlPOST /__astro_static_paths 200 OK (2ms)
THIS IS ME LOGGING IN MY CODE!
POST /__astro_prerender 200 OK (4ms)
 (+8ms)
08:30:39 ✓ Completed in 211ms.
```

Looking to see if we can get the user logging without the request logging, but I'm doubtful.

**Comment by matthewp** [comment]
I added some filtering for the request logging, it now comes out like this:

```
 prerendering static routes
08:41:57   ├─ /index.html
THIS IS ME LOGGING IN MY CODE!
 (+9ms)
08:41:57 ✓ Completed in 214ms.

08:41:57 [build] Rearranging server assets...
08:41:57 [build] ✓ Completed in 842ms.
08:41:57 [build] Server built in 1.39s
08:41:57 [build] Complete!
```

File: packages/integrations/cloudflare/src/prerenderer.ts [hunk 1]
```diff
@@ -53,6 +53,20 @@ export function createCloudflarePrerenderer({
 			// Ensure client dir exists (CF plugin expects it for assets)
 			await mkdir(clientDir, { recursive: true });
 
+			// Create a custom logger that filters out HTTP request logs (e.g. "POST /__astro_prerender 200 OK")
+			// from the Cloudflare vite plugin while still allowing user console.log output to pass through.
+			// We strip ANSI codes before testing because the Cloudflare vite plugin wraps messages in color codes.
+			const defaultLogger = createLogger('info');
+			const ansiRe = /\x1b\[[0-9;]*m/g;
+			const requestLogRe = /^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)\s+\S+\s+\d+\s+/;
```
Comment (Princesseuh) [inline packages/integrations/cloudflare/src/prerenderer.ts]: beyond excited for someone to hit this regex accidentally and wonder why they don't see logs, ha. Would it work to only filter out logs with __astro in them?

Comment (matthewp) [reply packages/integrations/cloudflare/src/prerenderer.ts]: Seems to work, updated in 7a41aca6119c43212ca000b843a1b9e19998858a

**Review by ematipico — APPROVED** [review]

**Review by Princesseuh — APPROVED** [review]
