### PR TITLE
fix: separate data store into mutable and immutable versions

### LINKED ISSUE #11720: Astro `4.14.0` build error with Cloudflare adapter
### Astro Info

```block
Astro                    v4.14.0
Node                     v20.5.0
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/mdx
                         @astrojs/tailwind
                         @astrojs/svelte
                         @astrojs/react
                         @astrojs/solid-js
                         @astrojs/sitemap
                         @astrojs/partytown
                         astro-icon
```

### Describe the Bug

After upgrading to astrojs 4.14.0, build got an error and failed even without enabling the experimental `contentLayer` feature flag.

```
[commonjs--resolver] [plugin vite:resolve] Cannot bundle Node.js built-in "fs" imported from "node_modules\.pnpm\astro@4.14.0_@types+node@20.14.15_lightningcss@1.25.1_rollup@4.20.0_terser@5.31.6_typescript@5.5.4\node_modules\astro\dist\content\data-store.js". Consider disabling ssr.noExternal or remove the built-in dependency.
  Stack trace:
    at getRollupError (file:///D:/Projects/website/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/parseAst.js:392:41)
    at Object.error (file:///D:/Projects/website/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19707:20)
    at Object.handler (file:///D:/Projects/website/node_modules/.pnpm/vite@5.4.0_@types+node@20.14.15_lightningcss@1.25.1_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:65527:15)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Projects/website/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:19792:28)
    at async ModuleLoader.resolveId (file:///D:/Projects/website/node_modules/.pnpm/rollup@4.20.0/node_modules/rollup/dist/es/shared/node-entry.js:18869:15)
 ELIFECYCLE  Command failed with exit code 1.
```

### What's the expected result?

run `astro build` should get no error after upgrading astrojs to `4.14.0`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dovhkf?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Separates all data store mutation methods into a subclass `MutableDataStore`, leaving the base class with just the get methods. This is so the immutable version can be used in the runtime without needing node builtins. It works because it loads the initial data as a virtual module. The mutable version includes all of the filesystem handling, but isn't needed at runtime.

Fixes #11720

## Testing

Content layer tests still all pass.

### CODE REVIEW

File: packages/astro/src/content/mutable-data-store.ts [hunk 1]
```diff
@@ -0,0 +1,366 @@
+import { promises as fs, type PathLike, existsSync } from 'node:fs';
+import * as devalue from 'devalue';
+import { imageSrcToImportId, importIdToSymbolName } from '../assets/utils/resolveImports.js';
+import { AstroError, AstroErrorData } from '../core/errors/index.js';
+import { type DataEntry, DataStore, type RenderedContent } from './data-store.js';
+import { contentModuleToId } from './utils.js';
+
+const SAVE_DEBOUNCE_MS = 500;
+
+export class MutableDataStore extends DataStore {
```
Comment (ematipico) [inline packages/astro/src/content/mutable-data-store.ts:10]: Maybe we should call it `FileSystemDataStore`? Or if I misunderstood its purpose, maybe we could add a small JSDoc block that explains its purpose

**Review by ematipico — APPROVED** [review]

File: packages/astro/src/content/mutable-data-store.ts (hunk 1 above)
Comment (ascorbic) [reply packages/astro/src/content/mutable-data-store.ts:10]: The base class doesn't have any write methods, so it's the fact that this one does (so is mutable) which is the important part, rather than the fact it uses the filesystem.

**Comment by ascorbic** [comment]
!preview immutable-datastore

File: packages/astro/src/content/mutable-data-store.ts (hunk 1 above)
Comment (ascorbic) [reply packages/astro/src/content/mutable-data-store.ts:14]: I've added jsdocs to both

**Review by matthewp — APPROVED** [review]
