### PR TITLE
fix: prevent script dedup inside <template>

### LINKED ISSUE #13795: Script Ordering Iss
### Astro Info

```block
> astro info

Astro                    v5.7.10
Node                     v20.19.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  astro-sst
Integrations             astro-icon
                         htmx
                         posthogJs
                         @astrojs/partytown
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Brave, likely all

## Problem
Consider an Astro component with both HTML and a script tag:
```html
<!-- TestItem.astro -->
<h2> I'm a test </h2>
<script>
    console.log('Running a script in TestItem')
</script>
```

Suppose you want to include that component and that you are already using that component in the same page:
```html
<template>
    <TestItem/>
</template>
<TestItem/>
```

What you'll find is the script in `TestItem` _never_ runs.

## Context
I ran into this when using web components in a list. Since the list can have any/all of its items deleted, I wanted to have a template available for creating new items. Because of this issue my web component never registers, meaning items outside the template have no interactivity.

## Workaround
If you move the template definition after the component usage, the script runs. For my web component usecase, this is enough to unblock me:
```html
<TestItem/>
<template>
    <TestItem/>
</template>
``` 

## Analysis
My guess is Astro is treating the script in the template and the script outside of the template as the same and therefore only runs it once. Since the first occurrence is happening inside the template, it has no effect. Here's a direct example:
```html
<template>
	<script>
		console.log('Logging inside a template does not')
	</script>
</template>
<script>
	console.log('Logging outside a template works')
</script>
```
Note that the script inside the template _does_ run on insert:
```html
<template id="simple-script">
    <script>
        console.log('Script inside template runs after insert')
    </script>
</template>
<script>
    const templ = document.getElementById('simple-script').content.cloneNode(true)
    document.body.append(templ)
</script>
```

### What's the expected result?

I would not expect scripts inside the template to prevent scripts outside the template from running. I also would expect the scripts in the template to run on insert.

In my example, I would expect to see one log from `TestItem` when it's used bot inside and outside of a `template`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jfjh51f5?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

### LINKED ISSUE #15389: Custom web components wrapped in <template> prevent other instances from initialising
### Astro Info

```block
Astro                    v5.17.1
Vite                     v6.4.1
Node                     v25.2.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Custom web components that are wrapped in a template tags prevent further instances of the component from initialising correctly. 

Here is how I came across this issue:

1. CartLine component is rendered in a <template> tag and later cloned to create the Cart
2. CartLine component contains a <quantity-selector> custom web component which adds multiple event listeners in its connectedCallback() function
3. <quantity-selector> web component is also used later on in the document, in the AddToCart component
4. Because it's first mounted within the <template> tags, the AddToCart instance of the QuantitySelector doesn't have its event listeners initialised

Note that order is important here: If I simply mount a hidden <quantity-selector> component before the CartLine <template> tags, all instances of the <quantity-selector> are correctly initialized.

It's only when the first instance of the <quantity-selector> is found within <template> tags, do all of the instances of the <quantity-selector> fail to initialise.

### What's the expected result?

Custom web components should initialise correctly, even if the first instance is mounted with <template> tags.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/lairdkruger/astro-web-components-template-issue

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by seroperson**
Closes #15389, 
Closed #13795

When a component with a script was first used inside a `<template>`, Astro's deduplication prevented the script from rendering outside the template, breaking non-template instances. This PR makes such scripts are not deduplicated. Should be merged after https://github.com/withastro/compiler/pull/1156.

## Changes

-  Adds `templateEnter` / `templateExit` functions to be inlined by compiler inside of `<template>` tags. These functions add instructions that track `<template>` nesting depth during rendering.
- `stringifyChunk` skips dedup for scripts when `templateDepth > 0`. The script still renders inside the template but is also rendered outside for non-template instances.

## Testing

Added `astro-script-template-dedup` integration test with four cases:
- Component used inside `<template>` first, then outside: verifies script appears in both places
- Component used outside first, then inside: verifies normal dedup still works
- Two components outside, then inside: verifies normal dedup still works x2
- Nested `<template>` elements: verifies depth tracking handles nesting

## Docs

Docs aren't required as it's a bugfix.

### CODE REVIEW

File: packages/astro/src/runtime/server/render/astro/render-template.ts [hunk 1]
```diff
@@ -109,3 +115,62 @@ export function isRenderTemplateResult(obj: unknown): obj is RenderTemplateResul
...
+/**
+ * Counts the net change in HTML `<template>` nesting depth for a static HTML string
+ */
+function countTemplateDepthDelta(html: string): number {
+	let opens = 0;
+	let closes = 0;
+	const lower = html.toLowerCase();
+
+	let pos = 0;
+	while ((pos = lower.indexOf('</template', pos)) !== -1) {
```
Comment (matthewp) [inline packages/astro/src/runtime/server/render/astro/render-template.ts]: Definitely don't like doing this for every string in an Astro template.

**Review by matthewp — DISMISSED** [review]
This is a very expensive change, for something that is a bit of a corner case. I don't want to make this change this way. Will explain an alternative approach in a comment.

**Comment by matthewp** [comment]
Basically we need to know that we are "inside of a template" in order to maybe not emit the script. I think that's really only possible through a compiler change.

If you have that, you would know when you've exited all possible templates and then could emit the script. cc @Princesseuh

**Comment by seroperson** [comment]
@matthewp Thank you for the review! Oh, I wasn't aware about such ability at all. Yea, compiler-based approach looks much better. 

I filled the PR to compiler and did necessary changes here to support it. Well, then waiting compiler to be merged and then I'll update the version here.

P.S. I actually "moved" this render instruction to be inlined by compiler, so logic within this PR left mostly unchanged (except placing instructions of course).

**Comment by seroperson** [comment]
I've also mirrored the same functionality in `compiler-rs` repo: https://github.com/withastro/compiler-rs/pull/17

**Comment by ematipico** [comment]
@seroperson are the failures in CI expected?

**Comment by seroperson** [comment]
@ematipico we are waiting for the compiler to be released, then here we should bump its version and ensure everything works

File: .changeset/jolly-bars-play.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': minor
```
Comment (Princesseuh) [inline .changeset/jolly-bars-play.md]:
```suggestion
'astro': patch
```

This is only part of the minor because it requires a compiler update and stuff, but this is really a patch

**Review by Princesseuh — APPROVED** [review]
Code good!

File: .changeset/jolly-bars-play.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+---
+
+Prevent script deduplication inside `<template>` elements
```
Comment (ArmandPhilippot) [inline .changeset/jolly-bars-play.md]:
```suggestion
Prevents script deduplication inside `<template>` elements
```

**Review by ArmandPhilippot — APPROVED** [review]
A nit for consistency with [how we write changesets](https://contribute.docs.astro.build/docs-for-code-changes/changesets/) (ie. present tense verb), otherwise LGTM!

**Review by yanthomasdev — APPROVED** [review]
Docs LGTM after Armand suggestion is applied.
