### PR TITLE
Fix: components in imported markdown

### LINKED ISSUE #3134: 🐛 BUG: Components in dynamically imported markdown break prod builds
### What version of `astro` are you using?

1.0.0-beta.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm, pnpm

### What operating system are you using?

Mac

### Describe the Bug

I import a Svelte component into a markdown file using the `setup` script:

```md
---
setup: import DynamicVisual from './DynamicVisual.svelte'
---
<DynamicVisual client:load />
```
Then, I load this markdown onto a `.astro` page using `Astro.glob`:

```astro
---
const articles = await Astro.glob('../components/*.md')
---
...
{articles.map(article => <article.Content />)}
```

This raises an exception during production builds:
```bash
Error: Cannot find the built path for /src/components/DynamicVisual.svelte
      at Object.resolve (file:///Users/benholmes/Repositories/astro/packages/astro/dist/core/build/generate.js:137:15)
      at generateHydrateScript (file:///Users/benholmes/Repositories/astro/packages/astro/test/fixtures/astro-markdown-css/dist/entry.mjs:102:165)
      at renderComponent (file:///Users/benholmes/Repositories/astro/packages/astro/test/fixtures/astro-markdown-css/dist/entry.mjs:452:28)
```

**Extra details**
- this does not occur on development server
- `await import` has the same effect as `Astro.glob`
- changing the `client` directive to `client:only` has no effect
- following the stacktrace, this occurs in [the `hydration.ts` file](https://github.com/withastro/astro/blob/main/packages/astro/src/runtime/server/hydration.ts#L128-L136) where components are resolved to their bundled chunks
- digging into the `dist` result for that markdown file, I noticed the component details were in-lined instead of splitting to a separate chunk. Maybe that's the cause? Example output:

```js
// chunks/chunk.XXXX.mjs
import { e as create_ssr_component, f as escape, c as createMetadata, a as createAstro, b as createComponent, r as render, d as renderComponent } from '../entry.mjs';
import 'shorthash';
import 'html-escaper';
import 'serialize-javascript';

var DynamicVisual_svelte_svelte_type_style_lang = '';

/* test/fixtures/astro-markdown-css/src/components/DynamicVisual.svelte generated by Svelte v3.47.0 */

const css = {
	code: "button.svelte-1b7ffas{color:#f00}",
	map: null
};

const DynamicVisual = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let count = 0;
	$$result.css.add(css);
	return `<button class="${"svelte-1b7ffas"}">Count up ${escape(count)}</button>`;
});

var $$module1 = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
	__proto__: null,
	'default': DynamicVisual
}, Symbol.toStringTag, { value: 'Module' }));

const metadata = { "headers": [{ "depth": 1, "slug": "example-markdown-document-with-a-more-visuals", "text": "Example markdown document, with a more Visuals" }], "source": "\n# Example markdown document, with a more Visuals\n\n<DynamicVisual client:load />\n", "html": '<h1 id="example-markdown-document-with-a-more-visuals">Example markdown document, with a more Visuals</h1>\n<DynamicVisual client:load />' };
const frontmatter = { "astro": { "headers": [{ "depth": 1, "slug": "example-markdown-document-with-a-more-visuals", "text": "Example markdown document, with a more Visuals" }], "source": "\n# Example markdown document, with a more Visuals\n\n<DynamicVisual client:load />\n", "html": '<h1 id="example-markdown-document-with-a-more-visuals">Example markdown document, with a more Visuals</h1>\n<DynamicVisual client:load />' } };
const $$metadata = createMetadata("/src/markdown/article2.md", { modules: [{ module: $$module1, specifier: "../components/DynamicVisual.svelte", assert: {} }], hydratedComponents: [DynamicVisual], clientOnlyComponents: [], hydrationDirectives: /* @__PURE__ */ new Set(["load"]), hoisted: [] });
const $$Astro = createAstro("/src/markdown/article2.md", "https://astro.build", "file:///Users/benholmes/Repositories/astro/packages/astro/test/fixtures/astro-markdown-css/");
const $$Article2 = createComponent(async ($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$Article2;
  return render`<h1 id="example-markdown-document-with-a-more-visuals">Example markdown document, with a more Visuals</h1>
${renderComponent($$result, "DynamicVisual", DynamicVisual, { "client:load": true, "client:component-hydration": "load", "client:component-path": $$metadata.getPath(DynamicVisual), "client:component-export": $$metadata.getExport(DynamicVisual) })}`;
});

export { $$metadata, $$Article2 as default, frontmatter, metadata };
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ycz8vp-kddjya?file=src/pages/index.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes
- Fixes #3134 
- Add `$$loadMetadata` helper to all imported markdown files. This calls the module's own `load()` function to retrieve the `$$metadata` object. Yes this _does_ mean generating the `?content` module for all markdown files in your project. But no, this doesn't mean _rendering_ every markdown file!
- Add check to `preload` step for any markdown modules with the `?mdImport` flag. If any are found, merge the `$$loadMetadata` result with the parent `.astro` page.

### Why couldn't we discover nested metadata from the Metadata constructor (`metadata.ts`)?

Originally, @matthewp and I called `$$loadMetadata` from the metadata generator to discover nested metadata. This worked for static ESM imports of markdown, but broke for async imports and `Astro.glob` results. This is because our compiler does _not_ discover modules retrieved asynchronously, so a given astro file's `$$metadata` object won't contain these async markdown files. Hence the need for a Vite `moduleGraph` call during preloading.

This approach also avoids turning all our metadata generators asynchronous, which I prefer!

## Testing

Add `with-components` file to `markdown` test fixture. The existing tests for building markdown should catch prod build failures.

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/vite-plugin-markdown/index.ts [hunk 1]
```diff
@@ -151,7 +155,7 @@ ${setup}`.trim();
 
 				// Transform from `.astro` to valid `.ts`
 				let { code: tsResult } = await transform(astroResult, {
-					pathname: fileUrl.pathname.slice(config.root.pathname.length - 1),
+					pathname: '/@fs' + prependForwardSlash(fileUrl.pathname),
```
Comment (bholmesdev) [inline packages/astro/src/vite-plugin-markdown/index.ts:158]: Use same `pathname` pattern as standard `.astro` files. Without this change, markdown files might generate duplicate chunks with mismatched base paths

File: packages/astro/src/core/render/dev/index.ts [hunk 2]
```diff
@@ -80,7 +81,39 @@ export async function preload({
...
 	const mod = (await viteServer.ssrLoadModule(fileURLToPath(filePath))) as ComponentInstance;
-
+	// some modules have dependencies we should preload by hand
+	// in this case, markdown files imported asynchronously or via Astro.glob(...)
+	// we will call each md file's $$loadMetadata to discover those dependencies
+	const modGraph = await viteServer.moduleGraph.getModuleByUrl(fileURLToPath(filePath));
+	for await (let importedModule of modGraph?.importedModules ?? []) {
+		if (importedModule.id?.endsWith(MARKDOWN_IMPORT_FLAG)) {
+			const mdMod = await viteServer.ssrLoadModule(importedModule.id);
+			const mdMetadata = (await mdMod.$$loadMetadata?.()) as Metadata;
```
[the remark this answers is not in the document]
Comment (matthewp) [reply packages/astro/src/core/render/dev/index.ts:91]: Oh, rereading the PR I understand why.

File: packages/astro/src/core/render/dev/index.ts [hunk 3]
```diff
@@ -80,7 +81,42 @@ export async function preload({
...
+			if (mdMetadata) {
+				// if md metadata, merge with parent page metadata
+				const { modules, hoisted, hydratedComponents, clientOnlyComponents, hydrationDirectives } =
+					mod.$$metadata;
+				mod.$$metadata.modules = modules.concat(
```
Comment (matthewp) [inline packages/astro/src/core/render/dev/index.ts:99]: Instead of doing this immutable stuff it would be more efficient to just push the changes into the arrays. You are already modifying them.

Comment (bholmesdev) [reply packages/astro/src/core/render/dev/index.ts]: Fixed!

**Review by matthewp — APPROVED** [review]

**Review by natemoo-re — APPROVED** [review]
Given that this has no performance impact, this LGTM! 👍🏻

**Comment by bholmesdev** [comment]
Note: we got a false positive on the performance metrics. There are the actual results against [the DDT repo](https://github.com/rebelchris/daily-dev-tips). **Prerendering step specifically:**
- before change: **40s**
- after change: **70s** 😓 
☝️ Client build and route generation remain unchanged, though these are each much shorter steps.
