### PR TITLE
fix: treat images with initial slash as local, and resolve with vite

### LINKED ISSUE #12025: Image component doesn't recognize local images in the new Content Layer API
### Astro Info

```block
Astro                    v5.0.0-beta.1
Node                     v20.9.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

After migrating to the new Content Layer API, the Image component is no longer able to recognize local images when the source is provided by a content collection. This is causing issues as the component now requires manual setting of image dimensions, which should not be necessary by default.

https://docs.astro.build/en/guides/images/#images-in-content-collections

### What's the expected result?

Image component shouldn't ask for dimensions of local images

### Link to Minimal Reproducible Example

https://codesandbox.io/p/devbox/z22xn5

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Previously we treated images that start with a slash as public images, and didn;t process them. Turns out that this is changed behaviour, so we'll switch to resolving them via Vite.

Fixes #12025

## Testing

Added several test cases

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

**Review by bluwy — APPROVED** [review]
Nice pics

File: packages/astro/src/assets/utils/resolveImports.ts [hunk 1]
```diff
@@ -16,7 +16,7 @@ export function imageSrcToImportId(imageSrc: string, filePath?: string): string
 	imageSrc = removeBase(imageSrc, IMAGE_IMPORT_PREFIX);
 
 	// We only care about local imports
-	if (isRemotePath(imageSrc) || imageSrc.startsWith('/')) {
+	if (isRemotePath(imageSrc)) {
```
Comment (jcayzac) [inline packages/astro/src/assets/utils/resolveImports.ts:19]: note: `isRemote()` incorrectly assumes remote URLs start with a protocol, so the code now won't catch `//foo.com/bar.jpg` anymore, which it still should?
