### PR TITLE
fix: allow cookies to be set in rewritten responses

### LINKED ISSUE #11265: Cookie not set when response is rewritten (experimental.rewriting)
### Astro Info

```block
Astro                    v4.10.2
Node                     v20.13.1
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Using `Astro.cookie.set` does not actually set a cookie for a rewritten request.

### What's the expected result?

A cookie should be set.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xcsrpa?file=src%2Fpages%2F1.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Ensures that `set-cookie` headers are set when rewriting a request.

Fixes #11265

## Testing

Adds a test case for a rewritten request

## Docs
Just a bugfix

### CODE REVIEW

File: packages/astro/src/core/render-context.ts [hunk 1]
```diff
@@ -163,6 +163,12 @@ export class RenderContext {
 							streaming,
 							this.routeData
 						);
+
+						if (result.cookies) {
+							for (const cookie of AstroCookies.consume(result.cookies)) {
+								response.headers.append('Set-Cookie', cookie);
```
Comment (matthewp) [inline packages/astro/src/core/render-context.ts:169]: I don't think we should append the headers here. They are already appended further up in the response, here: https://github.com/withastro/astro/blob/cb4d07819f0dbdfd94bc4f084edf7720ada01323/packages/astro/src/core/app/index.ts#L346-L350

What I think is happening in this bug is that the `Response` has changed because of rewriting, so the AstroCookies object is not attached to it anymore. So what I think you can do is call [attachCookiesToResponse](https://github.com/withastro/astro/blob/main/packages/astro/src/core/cookies/response.ts#L5-L7) here and then when the cookies are consumed further up the chain they will be appended to the response there.

Comment (ascorbic) [reply packages/astro/src/core/render-context.ts]: Looks like they actually need to be merged, so I took a different approach

File: packages/astro/src/core/cookies/cookies.ts [hunk 2]
```diff
@@ -191,6 +191,19 @@ class AstroCookies implements AstroCookiesInterface {
 		}
 	}
 
+	/**
+	 * Merges a new AstroCookies instance into the current instance. Any new cookies
+	 * will be added to the current instance, overwriting any existing cookies with the same name.
+	 */
+	merge(cookies: AstroCookies) {
```
Comment (ematipico) [inline packages/astro/src/core/cookies/cookies.ts:198]: I have mixed feelings about this method, I would prefer to **return** a new instance instead of manipulating the existing one. Essentially, try to use a pure/functional approach and avoid side-effects.

I would called this method `fork` instead

File: packages/astro/src/core/render-context.ts [hunk 3]
```diff
@@ -163,6 +164,11 @@ export class RenderContext {
 							streaming,
 							this.routeData
 						);
+
+						const responseCookies = getFromResponse(response);
+						if (result.cookies && responseCookies) {
+							result.cookies?.merge(responseCookies);
```
Comment (ematipico) [inline packages/astro/src/core/render-context.ts:170]:
```suggestion
							result.cookies.merge(responseCookies);
```

Not needed I think, due to the previous check

File: packages/astro/test/fixtures/astro-cookies/src/pages/from.astro [hunk 4]
```diff
@@ -0,0 +1,4 @@
+---
+console.log('cookie value: ', Astro.cookies.get('my_cookie')?.value);
```
Comment (ematipico) [inline packages/astro/test/fixtures/astro-cookies/src/pages/from.astro:2]: Should we add another test where in the first page we set a `lorem` value, then in the rewritten page we set a `ipsum` value, and assert that the cookie has `ipsum` as value?

File: packages/astro/src/core/cookies/cookies.ts (hunk 2 above)
Comment (matthewp) [reply packages/astro/src/core/cookies/cookies.ts:198]: Why? In this case there are already 2 AstroCookies instances created (once for each response), what does adding a 3rd accomplish? This is not immutable style code, and this function is not mutating the argument, it's mutating itself.

Comment (ematipico) [reply packages/astro/src/core/cookies/cookies.ts:198]: I don't think this is the correct fix. I think the fix should be done here:

https://github.com/withastro/astro/blob/bc3c3296bfd44f6ab7cad38dc47a39355a6af4cb/packages/astro/src/core/render-context.ts#L237

And here

https://github.com/withastro/astro/blob/bc3c3296bfd44f6ab7cad38dc47a39355a6af4cb/packages/astro/src/core/render-context.ts#L432

And the code should be 

```js
this.cookies = this.cookies.fork(this.request)
```

`fork` will return a new instance of cookies, and the creation of these new cookies is confined inside the `rewrite` function, while the proposed solution seems to be more broad

Comment (matthewp) [reply packages/astro/src/core/cookies/cookies.ts:198]: Ok, that plan makes sense then. 👍

Comment (ascorbic) [reply packages/astro/src/core/cookies/cookies.ts:198]: I don't think will help with cookies that are set on the response. It only merges the request cookies.

Comment (ascorbic) [reply packages/astro/src/core/cookies/cookies.ts:198]: I'm happy to change it to a pure function, but I don't think it can be done at the point the cookies are first assigned.

Comment (ematipico) [reply packages/astro/src/core/cookies/cookies.ts:198]: What confuses me is the term "rewriting a response" from the initial issue. `Astro.rewrite`, actually, rewrites a `Request`, and you'll get a new `Response`. So I wonder how the issue is related to rewriting? I am a bit confused 😅

Comment (ascorbic) [reply packages/astro/src/core/cookies/cookies.ts:198]: It refers to responses to a rewritten request. If page `/a` has `Astro.rewrite('/b')`, and `/b` sets a cookie, currently the cookie from b is not returned.

**Review by ematipico — APPROVED** [review]

**Comment by ascorbic** [comment]
@ematipico and I had a chat and agreed this approach
