### PR TITLE
fix(vercel): ensure srcset widths are always from configured list

### LINKED ISSUE #14250: Vercel Image Optimization drops leading slash in url param
### Astro Info

```block
Astro: 4.15.6
@astrojs/vercel: 7.8.0
Node: 20.x
Package manager: npm 10.x
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

# Vercel Image Optimization: leading slash stripped from ESM image imports (Astro adapter)

## Summary
When using the Astro Vercel adapter with `imageService: true`, optimized URLs generated from **ESM-imported assets** (via `import img from './foo.jpg'`) have their leading `/` stripped. This produces malformed `/_vercel/image?url=…` requests and broken images.  

Direct string URLs are unaffected. This makes it look like “only some images fail,” depending on how they are imported.

---

## Why only some images fail
In the adapter’s server chunk, ESM-imported images take a different code path:

```js
const fileSrc = isESMImportedImage(options.src)
  ? removeLeadingForwardSlash(options.src.src) // ❌ leading slash stripped
  : options.src; // ✅ strings untouched
```

- **ESM imports** → `/` removed → URL starts with `_astro/...` → fails.  
- **String paths** → `/` preserved → URL `%2F_astro/...` → works.  

---

## Steps to Reproduce

1. Create Astro project & install adapter:
   ```bash
   npm create astro@latest vercel-image-repro
   cd vercel-image-repro
   npm i -D @astrojs/vercel
   ```

2. Configure `astro.config.mjs`:
   ```js
   import { defineConfig } from "astro/config";
   import vercel from "@astrojs/vercel";

   export default defineConfig({
     output: "server",
     adapter: vercel({ imageService: true }),
   });
   ```

3. Place `test.jpg` in `src/assets/`.

4. Add `src/pages/repro.astro`:

   ```astro
   ---
   import { Picture } from "astro:assets";
   import testImg from "../assets/test.jpg";
   const imgString = testImg.src;
   ---

   <h1>Vercel Image Optimization Repro</h1>

   <h2>Case A &mdash; ESM ImageMetadata (expected to break)</h2>
   <Picture src={testImg} widths={[800]} formats={["jpeg"]} sizes="100vw" />

   <h2>Case B &mdash; string path (expected to work)</h2>
   <img
     src={`/_vercel/image?url=${encodeURIComponent(imgString)}&w=800&q=80`}
     width="800"
   />
   ```

5. Deploy to Vercel → visit `/repro`.

---

## Expected Result
- Case A:  
  ```
  /_vercel/image?url=%2F_astro%2Ftest.ABC123.jpg&w=800&q=80
  ```
  Image loads successfully.  
- Case B:  
  ```
  /_vercel/image?url=%2F_astro%2Ftest.ABC123.jpg&w=800&q=80
  ```
  Image loads successfully.  

---

## Actual Result
- Case A (ESM):  
  ```
  /_vercel/image?url=_astro%2Ftest.ABC123.jpg&w=800&q=80
  ```
  ❌ Missing `%2F` → Vercel returns `INVALID_IMAGE_OPTIMIZE_REQUEST`.  
- Case B (string):  
  ```
  /_vercel/image?url=%2F_astro%2Ftest.ABC123.jpg&w=800&q=80
  ```
  ✅ Works.  

---

## Workaround
Switch to Sharp image service in the meantime:  
```js
adapter: vercel(),
image: { service: { entrypoint: "astro/assets/services/sharp" } }
```

---

## Suggested Fix
Remove the call to `removeLeadingForwardSlash()` for ESM sources, so URLs retain the leading `/` before encoding.  

### What's the expected result?

working images

### Link to Minimal Reproducible Example

https://astro-vercel-adapter-bug.vercel.app/repro

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

The Vercel image CDN requires that widths are from a configured list – requesting any other will give an error. The image service does this in most cases, except when the source image is smaller than the requested size. The default getSrcSet clamps the width, ensuring that no sizes are requested larger than the source image, instead requesting the actual image size if a larger size is requested. This is correct for most services except Vercel, which requires us to request the larger breakpoint from the allowlist, for which it will return the original size. 

This PR implements a custom getSrcSet for the Vercel image service that ensures the widths are always from the allowlist.

Fixes #14250

## Testing

Added tests

### CODE REVIEW

**Review by delucis — COMMENTED** [review]
Looks OK to me. I don’t see the obvious spot in the code that ensures the width is valid though? May be worth a comment so that this isn’t changed accidentally in the future.

I did wonder if there could be a way to reuse `baseService.getSrcSet()` and just filter that, but looks like there’s enough of a difference between the implementations that this makes sense.

**Comment by ascorbic** [comment]
At the point this runs, `widths` has already been validated so just contains allowed sizes. The specific fix is removing the part from baseService.getSrcSet where we handle widths larger than the source image. That's where we filter out the larger widths and add in the width of the source image, which is what breaks on Vercel.

File: packages/integrations/vercel/src/image/build-service.ts [hunk 1]
```diff
@@ -62,6 +62,80 @@ const service: ExternalImageService = {
 
 		return '/_vercel/image?' + searchParams;
 	},
+	// Adapted from the base service's getSrcSet, but always returning widths that are valid for Vercel
```
Comment (ematipico) [inline packages/integrations/vercel/src/image/build-service.ts]: Can we add a link to this list? I checked the entire file, I couldn't find a reference to that

Comment (ascorbic) [reply packages/integrations/vercel/src/image/build-service.ts]: It's the one that comes from the config

Comment (ascorbic) [reply packages/integrations/vercel/src/image/build-service.ts]: See:

https://github.com/withastro/astro/blob/6e6635a31e4fd61fe0aad67f7180e14bec153db0/packages/integrations/vercel/src/image/shared.ts#L106-L116

Comment (ascorbic) [reply packages/integrations/vercel/src/image/build-service.ts]: Added a comment
