### PR TITLE
fix: correctly copy to clipboard in `astro info`

### LINKED ISSUE #12639: Copy to clipboard doesn't work
### Astro Info

```block
Astro                    v5.0.2
Node                     v22.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When running npx astro info and pressing the Enter button without the Y key, it says 'yes,' but nothing is copied to the clipboard.

npx astro info
Astro                    v5.0.2
Node                     v22.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind

✔ Copy to clipboard? … yes

### What's the expected result?

Should be copied.

### Link to Minimal Reproducible Example

NA

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

`astro info` copy to clipboard has not been working on Mac because piping the input to `pbcopy` using `execSync` seems to not work. This PR fixes that by switching to `spawnSync` instead of `execSync`. It also adds a helper to read from the clipboard so we can check it works across platforms, and adds support for a `--copy` flag to avoid needing to prompt.

Fixes #12639

## Testing

Adds a new test suite.

### CODE REVIEW

File: packages/astro/src/cli/info/index.ts [hunk 1]
```diff
@@ -49,63 +49,110 @@ export async function printInfo({ flags }: InfoOptions) {
...
+		if (!shouldCopy) return;
+	}
+
+	try {
+		const result = spawnSync(command, args, { input: text });
+		if (result.error) {
+			throw result.error;
+		}
+		console.log(colors.green('Copied to clipboard!'));
+	} catch (err) {
```
Comment (ematipico) [inline packages/astro/src/cli/info/index.ts:109]: Unused (thank you github annotations)

File: packages/astro/src/cli/info/index.ts [hunk 2]
```diff
@@ -49,63 +49,110 @@ export async function printInfo({ flags }: InfoOptions) {
...
-	const { shouldCopy } = await prompts({
-		type: 'confirm',
-		name: 'shouldCopy',
-		message: 'Copy to clipboard?',
-		initial: true,
-	});
-	if (!shouldCopy) return;
+	if (!command) {
+		console.error(colors.red('\nClipboard command not found!'));
+		console.log('Please manually copy the text above.');
```
Comment (ematipico) [inline packages/astro/src/cli/info/index.ts:88]: Use `.info` instead. Usually `.log` is more for debugging

File: packages/astro/src/cli/info/index.ts [hunk 3]
```diff
@@ -49,63 +49,110 @@ export async function printInfo({ flags }: InfoOptions) {
...
+
+		if (!shouldCopy) return;
+	}
+
+	try {
+		const result = spawnSync(command, args, { input: text });
+		if (result.error) {
+			throw result.error;
+		}
+		console.log(colors.green('Copied to clipboard!'));
```
Comment (ematipico) [inline packages/astro/src/cli/info/index.ts:108]: Use `.info`

File: .changeset/angry-pumas-act.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Correctly copy system info to clipboard
```
Comment (ematipico) [inline .changeset/angry-pumas-act.md:5]:
```suggestion
Fixes a bug where `astro info --copy` wasn't working correctly on `macOS` systems.
```

**Review by ematipico — APPROVED** [review]
Looks good! Left some feedback. I didn't test the code myself
