### PR TITLE
Fix APIRoute type

### LINKED ISSUE #3343: 🐛 BUG: APIRoute type problems
### What version of `astro` are you using?

1.0.0-beta.27

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Zorin OS

### Describe the Bug

The [API Pages Documentation](https://docs.astro.build/en/core-concepts/astro-pages/#:~:text=optionally%20you%20can%20also%20type%20your%20api%20route%20functions%20using%20the%20apiroute%20type) demonstrates the usage of the `APIRoute` type. But it's not been exported.

But even if I manually export the `APIRoute` type editing the files inside the `astro` package, it still doesn't work properly.

Screenshot_2022-05-11_19-43-51

Currently, the below code can be used as a workaround:

image

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-egzhia?file=src%2Fpages%2Fapi%2Freproduction.ts&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
Screen Shot 2022-05-11 at 9 09 21 AM

## Changes

- Fixes #3343
- Exports `APIRoute`
- Removed deprecated signature which prevents type narrowing.

## Testing

Our TS types are currently not tested :/

## Docs

N/A, this API is already documented.

### CODE REVIEW

**Review by bholmesdev — APPROVED** [review]
A shame we're losing the `@deprecated` notice here, but I won't stop us if we're en`route` to a fix

File: packages/astro/src/runtime/server/index.ts [hunk 1]
```diff
@@ -508,7 +508,7 @@ Update your code to remove this warning.`);
 		},
 	}) as APIContext & Params;
 
-	return await handler.call(mod, proxy, request);
+	return handler.call(mod, proxy, request);
```
Comment (natemoo-re) [inline packages/astro/src/runtime/server/index.ts:511]: Does this change anything critical?

**Review by natemoo-re — APPROVED** [review]
LGTM! Noticed we dropped the `return await`, any reason for that?

File: packages/astro/src/runtime/server/index.ts (hunk 1 above)
Comment (matthewp) [reply packages/astro/src/runtime/server/index.ts:511]: No, VScode said it wasn't needed.

Comment (natemoo-re) [reply packages/astro/src/runtime/server/index.ts:511]: Cool, not blocking, just curious.

**Comment by shiftlabs1** [comment]
Please see https://github.com/withastro/astro/issues/3343#issuecomment-1133889189 . This does give errors when using async/await in a function
