### PR TITLE
Fix `AstroContainer` usage in Vitest client environments

### LINKED ISSUE #14883: Update from 5.14.1 to 5.16.0 breaks AstroContainer unit tests with happy-dom as environment
### Astro Info

```block
Astro                    v5.16.0
Vite                     v6.4.1
Node                     v24.11.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Our project is running on Astro 5.14.1 right now and uses the `experimental_AstroContainer` for a hand full of tests. As we also test some DOM stuff in our tests, we set `happy-dom` as test environment.
With the update to 5.16.0 all the tests using the `experimental_AstroContainer` component are failing with the following message:

> NoMatchingRenderer: Unable to render ``.
> No valid renderer was found for this file extension.

### What's the expected result?

The expected result is that it works as before, test are running successfully. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kldyrnhi?file=src%2Fpages%2Findex.spec.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by delucis**
## Changes

- Closes #14883
- #14751 stubbed out Astro component imports when requested in a non SSR Vite context.
- In #14883, users reported issues with this because they were rendering Astro components in Vitest tests that were run with a Vitest environment that is designed for client testing (i.e. using `happy-dom` or `jsdom`). Becuase this is a “fake”, Node.js emulation of the browser environment, Astro components were previously rendering fine in this environment, but after #14751 stopped working because our Vite plugin assumed these were “client” imports (which they are, kind of).
- This PR adds a temporary workaround to continue allowing “client” imports of Astro components when running Vitest.
- We should remove this eventually (in v6 or v7 I guess) and require people test Astro rendering in a proper SSR env.

## Testing

Manually patched with the reproduction shared in #14883 to test this fixes things. I don’t think we can easily test in our own test suites as we don’t use Vitest. We could pretend by setting a `VITEST` env variable in theory though if we think test coverage is important here.

## Docs

n/a — bug fix only. Although we could consider starting to document SSR as the “correct” Vitest environment for tests like those impacted.

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro/index.ts [hunk 1]
```diff
@@ -231,7 +231,14 @@ export default function astro({ settings, logger }: AstroPluginOptions): vite.Pl
 
 			// If an Astro component is imported in code used on the client, we return an empty
 			// module so that Vite doesn’t bundle the server-side Astro code for the client.
-			if (!options?.ssr) {
+			if (
+				!options?.ssr &&
+				// Workaround to allow tests run with Vitest in a “client” environment to still render
+				// Astro components. See https://github.com/withastro/astro/issues/14883
+				// TODO: In a future major we should remove this and require people test Astro rendering in
```
Comment (florian-lefebvre) [inline packages/astro/src/vite-plugin-astro/index.ts:238]: Do you think this should happen in v6?

**Review by florian-lefebvre — APPROVED** [review]

File: packages/astro/src/vite-plugin-astro/index.ts (hunk 1 above)
Comment (delucis) [reply packages/astro/src/vite-plugin-astro/index.ts:238]: I find it hard to judge as I only just discovered people were doing this at all 😄 

I feel like it’s not unreasonable to expect Astro rendering tests to run in an SSR env and it’s also not too hard to do: you have a lot of options from opting in a single test file with a `// @vitest-environment node` comment to splitting up your tests and using two distinct `vitest.config` files for client vs server tests.

Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/index.ts:238]: If you think we should, feel free to open a new issue and add it to the v6 milestone!

Comment (delucis) [reply packages/astro/src/vite-plugin-astro/index.ts:238]: Done! #14895
