### PR TITLE
fix(vercel): edge middleware next() drops HTTP method and body

### LINKED ISSUE #16156: Vercel edge middleware next() drops HTTP method and body — breaks POST API routes
### Astro Info

```
Astro                    v5.15.3
@astrojs/vercel          v8.2.11 (also confirmed in v10.0.3 source)
```

### What happened?

When `edgeMiddleware: true` is enabled in the Vercel adapter config, the compiled edge middleware's `next()` function does not forward the HTTP method or request body to the `/_render` serverless function. All requests are sent as GET, regardless of the original method.

This breaks POST/PUT/PATCH/DELETE API routes with a 404:

```
[WARN] [router] No API Route handler exists for the method "GET" for the route "/api/my-endpoint".
Found handlers: "POST", "config", "prerender"
```

### Root cause

In the edge middleware template (`packages/integrations/vercel/src/serverless/middleware.ts`), the `next()` function calls `fetch()` without `method` or `body`:

```js
const next = async () => {
  const { vercel, ...locals } = ctx.locals;
  const response = await fetch(new URL("/_render", request.url), {
    headers: {
      ...Object.fromEntries(request.headers.entries()),
      "x-astro-middleware-secret": "...",
      "x-astro-path": request.url.replace(origin, ""),
      "x-astro-locals": trySerializeLocals(locals),
    },
  });
  return new Response(response.body, { ... });
};
```

Since `fetch()` defaults to GET when no method is specified, any POST (or other non-GET) request that passes through the middleware via `next()` arrives at `/_render` as GET → 404.

### Suggested fix

Forward the original request method and body:

```js
const next = async () => {
  const { vercel, ...locals } = ctx.locals;
  const response = await fetch(new URL("/_render", request.url), {
    method: request.method,
    body: request.body,
    duplex: "half",
    headers: {
      ...Object.fromEntries(request.headers.entries()),
      "x-astro-middleware-secret": "...",
      "x-astro-path": request.url.replace(origin, ""),
      "x-astro-locals": trySerializeLocals(locals),
    },
  });
  return new Response(response.body, { ... });
};
```

### Secondary issue: WebAssembly in edge bundle

The compiled edge middleware bundle also includes `es-module-lexer` which uses `WebAssembly.compile()`. Vercel's edge runtime disallows Wasm, producing:

```
CompileError: WebAssembly.compile(): Wasm code generation disallowed by embedder
```

This appears to be non-fatal (the middleware still executes), but it generates error noise in logs and could cause issues depending on whether es-module-lexer's Wasm initialization is required by any code path in the bundle.

### Reproduction

1. Create an Astro project with the Vercel adapter and `edgeMiddleware: true`
2. Add a simple middleware that calls `next()` for API routes
3. Add a POST API route (`export const prerender = false`)
4. Deploy to Vercel
5. Send a POST request to the API route → 404

### Expected behavior

`next()` should forward the original HTTP method and request body to `/_render`, so non-GET API routes work correctly when edge middleware is enabled.

### PR DESCRIPTION
**Pull request by bittoby**
## Summary
Fixes #16156
- Edge middleware `next()` was calling `fetch()` without passing `method` or `body`, causing all requests to be forwarded as GET to the `/_render` serverless function
- Adds `method: request.method`, `body: request.body`, and `duplex: 'half'` to the internal `fetch()` call
- Adds a test verifying the generated middleware includes method/body forwarding

## Test plan
- [x] Existing Vercel integration tests pass (39 pass, 0 fail)
- [x] New test validates generated middleware contains `method`, `body`, and `duplex` properties
- [x] Local repro confirmed: before fix fetch has no method/body, after fix it does

### CODE REVIEW

File: packages/integrations/vercel/src/serverless/middleware.ts [hunk 1]
```diff
@@ -127,12 +127,15 @@ export default async function middleware(request, context) {
...
+			method: request.method,
 			headers: {
 				...Object.fromEntries(request.headers.entries()),
 				'${ASTRO_MIDDLEWARE_SECRET_HEADER}': '${middlewareSecret}',
 				'${ASTRO_PATH_HEADER}': request.url.replace(origin, ''),
 				'${ASTRO_LOCALS_HEADER}': trySerializeLocals(locals)
-			}
+			},
+			body: request.body,
+			duplex: 'half',
```
Comment (matthewp) [inline packages/integrations/vercel/src/serverless/middleware.ts]: why this?

Comment (Crystora) [reply packages/integrations/vercel/src/serverless/middleware.ts]: This is required by the Fetch whenever you pass a streaming body to fetch(). Without it, the runtime throws a TypeError.

**Comment by Crystora** [comment]
@matthewp 
Please review again. I fixed code to conditionally.

**Comment by Crystora** [comment]
Thanks. @matthewp
