### PR TITLE
fix: Astro info throws when xclip is not available

### LINKED ISSUE #9039: Astro info throws when xclip is not available
### Astro Info

```block
> @fflaten/website@0.0.1 astro /workspaces/Website
> astro "info"

Astro                    v3.5.0
Node                     v18.16.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             config-watcher
                         auto-import
                         @astrojs/sitemap
                         @astrojs/asides
                         astro-expressive-code
                         @astrojs/mdx
 error   Command failed: which xclip
  File:
    /workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/info/index.js:38:20
  Code:
    37 |   } else {
    > 38 |     const output = execSync("which xclip", { encoding: "utf8" });
         |                    ^
      39 |     if (output[0] !== "/") {
      40 |       return;
      41 |     }
  Stacktrace:
Error: Command failed: which xclip
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at copyToClipboard (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/info/index.js:38:20)
    at printInfo (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/info/index.js:28:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runCommand (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/index.js:69:7)
    at async cli (file:///workspaces/Website/node_modules/.pnpm/astro@3.5.0_@types+node@20.9.0_sass@1.69.5/node_modules/astro/dist/cli/index.js:144:5)
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Error is thrown by `execSync` on non-zero exit code (`xclip` was not found). Missing try/catch here: https://github.com/withastro/astro/blob/a888e985384918798e7c2f203e0dee48a4a21225/packages/astro/src/cli/info/index.ts#L53-L57

### What's the expected result?

No error

### Link to Minimal Reproducible Example

N/A

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #9039

### CODE REVIEW

**Review by dreyfus92 — COMMENTED** [review]
Hey @rishi-raj-jain, I left you a small suggestion. Let me know what you think.

File: packages/astro/src/cli/info/index.ts [hunk 1]
```diff
@@ -49,13 +49,19 @@ async function copyToClipboard(text: string) {
...
+			const output = execSync('which xclip', { encoding: 'utf8' });
+			if (output[0] !== '/') {
+				// Did not find a path for xclip, bail out!
+				return;
+			}
+			command = 'xclip -sel clipboard -l 1';
+		}
+		catch (e) {
+			// Did not find xclip, bail out!
+			return
```
Comment (dreyfus92) [inline packages/astro/src/cli/info/index.ts:63]:
```suggestion
      console.error('Did not find xclip'); 
			return
```

Comment (rishi-raj-jain) [reply packages/astro/src/cli/info/index.ts:63]: I think we just want to bail out than show console messages right, @matthewp?

Comment (vasfvitor) [reply packages/astro/src/cli/info/index.ts:63]: hey @dreyfus92, quick question, wouldn't this
```
console.error(colors.red(`\nSorry, something went wrong!`) + ` Did not find xclip.`);
console.error(e);
```
be better? and what about the `if output` block? I don't think it's needed, I guess only this is enough
```
execSync('which xclip', { encoding: 'utf8' });
command = 'xclip -sel clipboard -l 1';
```
but I'm not sure

Comment (rishi-raj-jain) [reply packages/astro/src/cli/info/index.ts:63]: - the output block is required as in case execSync exists, there's no error and we have to evaluate if there's a path present for xclip.
- right now with error handling, the intention is just to bail out I believe

Comment (dreyfus92) [reply packages/astro/src/cli/info/index.ts:63]: @vasfvitor The simple return works, but the extra logging and error handling improves transparency.

Comment (vasfvitor) [reply packages/astro/src/cli/info/index.ts:63]: thanks for the explanation

Comment (lilnasy) [reply packages/astro/src/cli/info/index.ts:63]: The error should be safe to ignore silently. I doubt many people know what xclip is to begin with, and if its absence is something to "fix", might confuse more to bring it up.

File: .changeset/hot-teachers-wave.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+bail out on xclip if not found
```
Comment (bluwy) [inline .changeset/hot-teachers-wave.md:5]:
```suggestion
Safely bail when the `xclip` command does not exist on Linux when trying to copy to clipboard with `astro info`
```

Added a little info for what's fixed.

**Review by bluwy — APPROVED** [review]
Thanks for fixing this! Please don't clear out the PR template in the future. It helps us identify what's included in the PR 🙏

**Review by matthewp — APPROVED** [review]

**Review by bluwy — APPROVED** [review]
