### PR TITLE
qol(cookies): warn when cookies are set after the headers have been sent

### LINKED ISSUE #7715: Could not delete cookie when in function scope
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

macOS

### What browser are you using?

Firefox

### Describe the Bug

Cookies can delete on non-SSR, after adding Node adapter, I found deleting a cookies in a function scope has no effect. See code example in the link provided.

In Node, it does not seem to delete the cookie permanently?

### What's the expected result?

Assume, the bug is found in Node.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nf1tnk-ca3kww?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
- Closes #7715

## Testing
Warning only. Does not affect behavior.

## Docs
Does not affect usage. Although general elaboration on streaming is overdue.

### CODE REVIEW

File: packages/astro/src/core/cookies/cookies.ts [hunk 1]
```diff
@@ -148,6 +150,13 @@ class AstroCookies implements AstroCookiesInterface {
 	 * @param options Options for the cookie, such as the path and security settings.
 	 */
 	set(key: string, value: string | Record<string, any>, options?: AstroCookieSetOptions): void {
+		if (this.#consumed) {
+			console.error(new Error(
+				"Astro.cookies.set() was called after the cookies have already been sent to the browser.\n" +
+				"This may have happened if this method was called in an imported component.\n" +
+				"Please make sure that Astro.cookies.set() is only called in the frontmatter of the main page."
+			));
+		}
```
Comment (lilnasy) [inline packages/astro/src/core/cookies/cookies.ts:159]: image

Comment (lilnasy) [reply packages/astro/src/core/cookies/cookies.ts:159]:
```suggestion
		if (this.#consumed) {
			console.error(new Error(
				"Astro.cookies.set() was called after the cookies were already sent to the browser.\n" +
				"This may have happened if this method was called in an imported component.\n" +
				"Please make sure that Astro.cookies.set() is only called in the frontmatter of the main page."
			));
		}
```

**Review by ematipico — APPROVED** [review]

File: .changeset/kind-waves-travel.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"astro": patch
+---
+
+Adds a message for a case where setting cookies will have no effect.
```
Comment (florian-lefebvre) [inline .changeset/kind-waves-travel.md:5]:
```suggestion
Adds a warning for when setting cookies will have no effect
```

File: packages/astro/src/core/cookies/cookies.ts [hunk 3]
```diff
@@ -148,6 +150,13 @@ class AstroCookies implements AstroCookiesInterface {
 	 * @param options Options for the cookie, such as the path and security settings.
 	 */
 	set(key: string, value: string | Record<string, any>, options?: AstroCookieSetOptions): void {
+		if (this.#consumed) {
+			console.error(new Error(
+				"Astro.cookies.set() was called after the cookies have already been sent to the browser.\n" +
+				"This may have happened if this method was called in an imported component.\n" +
+				"Please make sure that Astro.cookies.set() is only called in the frontmatter of the main page."
+			));
```
Comment (bluwy) [inline packages/astro/src/core/cookies/cookies.ts:158]: Should this be `console.warn` with a plain string instead according to the PR title? It feels like if we report an error, it usually means the request failed and returns 500 (or something)

Comment (ematipico) [reply packages/astro/src/core/cookies/cookies.ts]: I addressed this in [`e29b456` (#9627)](https://github.com/withastro/astro/pull/9627/commits/e29b4560bd7d331a4c3e6a6e1ec3fea90d33eda6)

Comment (lilnasy) [reply packages/astro/src/core/cookies/cookies.ts]: That's much better, but we still need to provide some context as to where `cookies.set()` was called. Instantiating the error was one way to do it.

File: .changeset/kind-waves-travel.md (hunk 2 above)
Comment (sarah11918) [reply .changeset/kind-waves-travel.md:5]: (Remove the word "for" entirely!)

File: packages/astro/src/core/cookies/cookies.ts (hunk 3 above)
Comment (lilnasy) [reply packages/astro/src/core/cookies/cookies.ts]: image
