### PR TITLE
fix: allow imports of Markdown files as raw text

### LINKED ISSUE #13025: Importing `.md` files with `?raw` does not provide the text value anymore
### Astro Info

```block
❯ astro info
Astro                    v5.1.8
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

Previously, when adding in:

```typescript
import html from "../test/index.md?raw";
```

I would get the raw output of the Markdown. Now, in the most recent versions of Astro 5, it instead gives me an Astro Component object instance

### What's the expected result?

I expect to get the raw text of the HTML via:

https://vite.dev/guide/assets#importing-asset-as-string

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-nddjj98q?file=src%2Ftest%2Findex.md,src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

The fix in #12711 caused a regression for imports for markdown files as static assets using the `?raw` param. That only worked accidentally before, but this is the proper fix.

I am just checking the id for `?raw`. I realise this could in theory miss cases where there are multiple params, but I'm not aware of any cases where that would be legitimate so didn't think it was worth the cost of adding a full query param parse on every import. I'm open to other opinions on this though.

Fixes #13025

## Testing

Added a test case

### CODE REVIEW

File: packages/astro/src/core/util.ts [hunk 1]
```diff
@@ -18,6 +18,9 @@ export function isURL(value: unknown): value is URL {
 }
 /** Check if a file is a markdown file based on its extension */
 export function isMarkdownFile(fileId: string, option?: { suffix?: string }): boolean {
+	if (fileId.endsWith('?raw')) {
+		return false;
+	}
```
Comment (ematipico) [inline packages/astro/src/core/util.ts:23]: Does `?raw` have to be at the end of the query? What if it's in the middle?

**Review by ematipico — APPROVED** [review]
Looks good, but I don't know the feature enough to I left a question

File: packages/astro/src/core/util.ts (hunk 1 above)
Comment (florian-lefebvre) [reply packages/astro/src/core/util.ts:23]: Do we need to handle other params? We have https://github.com/withastro/astro/blob/0a0b1978a7ea9902174df96852e6a676023cd128/packages/astro/src/vite-plugin-utils/index.ts#L59

Comment (ascorbic) [reply packages/astro/src/core/util.ts:23]: I covered it a bit in the PR description. In theory I _think_ it could go elsewhere in the query, but I'm not aware of a scenario where it could legitimately combined with any other. It conflicts with all of the other suffixes that I know of (`worker`, `shared-worker`, `url`). There may be ones I'm missing, and of course parsing it fully as a query string would be more robust, but the question is whether it's worth doing that for every import when it's such an edgy of edge cases.

Comment (ascorbic) [reply packages/astro/src/core/util.ts]: I've switched it to use `hasSpecialQueries`

**Review by ematipico — APPROVED** [review]
