### PR TITLE
Fix mts reloads

### LINKED ISSUE #12159: Astro not restarting dev server on change when config file is a .mts
### Astro Info

```block
Astro                    v4.15.9
Node                     v20.12.2
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/starlight
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

If you change your `astro.config.mjs` file to a `.mts` file and edit it while the astro development server is running, it will not reload when the file is saved.

### What's the expected result?

Astro should reload the server because the config file changed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gyx11g?file=astro.config.mts&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by louisescher**
## Changes

- Adds the .mts file extension to the configRE regex so it restarts when the `astro.config.mts` file changes
- Fixes #12159

## Testing

Manually tested

## Docs

N/A

### CODE REVIEW

**Review by TheOtterlord — APPROVED** [review]

File: packages/astro/src/core/dev/restart.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ async function createRestartedContainer(
 	return newContainer;
 }
 
-const configRE = /.*astro.config.(?:mjs|cjs|js|ts)$/;
+const configRE = /.*astro.config.(?:mjs|mts|cjs|js|ts)$/;
```
Comment (bluwy) [inline packages/astro/src/core/dev/restart.ts:33]: It looks like we're missing `cts` here too, can we update it here too?
```suggestion
const configRE = /.*astro.config.(?:mjs|mts|cjs|cts|js|ts)$/;
```

https://github.com/withastro/astro/blob/676b2c66ee5d991bfb8ea85ca466be690cf0e5b9/packages/astro/src/core/config/config.ts#L29-L36

**Review by ematipico — APPROVED** [review]
Looks good to me. Waiting for @bluwy approval

**Review by bluwy — APPROVED** [review]
