### PR TITLE
fix(dev): prevent comma-separating multiple Set-Cookie headers

### LINKED ISSUE #9874: Set-Cookie headers are concatenated, and are not working correctly
### Astro Info

```block
Astro                    v4.2.4
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   server
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Set cookie headers seem to be set incorrectly.

``` ts
  const headers = new Headers();
  headers.append('Set-Cookie', 'my-other-cookie=love.it!; Path=/; HttpOnly; SameSite=Lax');
  headers.append('Set-Cookie', 'my-cookie=its.very.good; Path=/; HttpOnly; SameSite=Lax');
  return new Response('hello world', { headers });
```

Will give me:

```
set-cookie: my-other-cookie=love.it!; Path=/; HttpOnly; SameSite=Lax,my-cookie=its.very.good; Path=/; HttpOnly; SameSite=Lax
```

This will only set the first `my-other-cookie` as the second cookie is concatenated with a comma and is invalid.

I tested with a simple Hono API using Vite, and set-cookie worked correctly. So I am assuming this is an Astro problem.

There are no issues when hosting on Cloudflare pages, which makes me think this is an issue with the node dev server. 

### What's the expected result?

Set-Cookie headers must not be concatenated

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-cgewux?file=src%2Fpages%2Fcookie-endpoint.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
- Closes #9874

## Testing
Added a unit test.

## Docs
Does not affect usage.

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro-server/response.ts [hunk 1]
```diff
@@ -62,16 +62,10 @@ export async function writeWebResponse(res: http.ServerResponse, webResponse: Re
...
 
-	// Undici 5.20.0+ includes a `getSetCookie` helper that returns an array of all the `set-cookies` headers.
-	// Previously, `headers.entries()` would already have these merged, but it seems like this isn't the case anymore.
 	if (headers.has('set-cookie')) {
-		if ('getSetCookie' in headers && typeof headers.getSetCookie === 'function') {
-			_headers['set-cookie'] = headers.getSetCookie().toString();
-		} else {
-			_headers['set-cookie'] = headers.get('set-cookie')!;
-		}
+		_headers['set-cookie'] = headers.getSetCookie();
```
Comment (lilnasy) [inline packages/astro/src/vite-plugin-astro-server/response.ts:68]: The fix is this one line, the rest is clerical.

File: packages/astro/test/units/vite-plugin-astro-server/response.test.js [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+	'/src/pages/index.js': `export const GET = () => {
+		const headers = new Headers();
+		headers.append('x-single', 'single');
+		headers.append('x-triple', 'one');
+		headers.append('x-triple', 'two');
+		headers.append('x-triple', 'three');
+		headers.append('Set-cookie', 'hello');
+		headers.append('Set-Cookie', 'world');
+		return new Response(null, { headers });
+	}`,
```
Comment (lilnasy) [inline packages/astro/test/units/vite-plugin-astro-server/response.test.js:23]: Copied over from the [`NodeApp` unit test](https://github.com/withastro/astro/blob/astro@4.2.7/packages/astro/test/units/app/headers.test.js#L61-L74).

**Review by matthewp — APPROVED** [review]
Well done

**Review by ematipico — APPROVED** [review]
