### PR TITLE
fix: include route prefix in vercel func names, fix #8401

### LINKED ISSUE #8401: New Vercel adapter generates conflicting lambda functions for routes with same filename but different directories
### Astro Info

```block
Astro                    v3.0.8
Node                     v18.14.2
System                   macOS (arm64)
Package Manager          yarn
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/tailwind
                         @astrojs/svelte
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

New version of vercel adapter can generate invalid output if two routes have the same file name, but different directory structure.

Consider the structure of `pages` directory below. In some lines I added vercel function names generated by the adapter:
```
├── index.astro      // -> entry.index.astro.func
├── 404.astro        // -> entry.404.astro.func
├── share
│   └── [id].astro   // -> entry._id_.astro.func
├── api
    ├── secrets.ts   // -> entry.secrets.astro.func
    └── secrets
        └── [id].ts  // -> entry._id_.astro.func <- this route produces the same vercel func name as share/[id].astro
```

For each page Vercel adapter is going to build a separate route handler. However, their names may conflict with each other, producing invalid output.

### What's the expected result?

I would expect each route to produce separate lambda function.

I narrowed the problem down to this line in Vercel adapter:
https://github.com/withastro/astro/blob/main/packages/integrations/vercel/src/serverless/adapter.ts#L211

It generates function's directory name based on the file name only. I assume this will brake for every route with the same file names nested in different directories.

I can create PR soon.

### Link to Minimal Reproducible Example

https://github.com/slawekkolodziej/secretsecret

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by slawekkolodziej**
## Changes

Recently updated Vercel adapter has a bug. If two routes have identical file names but different directory structures, the adapter will produce only one serverless function and assign it to both routes.

This PR fixes the problem.

Some more details: https://github.com/withastro/astro/issues/8401

## Testing

Within vercel adapter I created 'serverless-with-dynamic-routes' fixture and added necessary tests. If you run those tests against current `main`, the will fail.

## Docs

No need to update docs. This PR only fixes a rather major bug and brings the expected behavior.

### CODE REVIEW

**Comment by slawekkolodziej** [comment]
Since my proposed change injects route path to file name, I begun to wonder what is the maximum allowed length for serverless function name in [Vercel build output](https://vercel.com/docs/build-output-api/v3/primitives#serverless-functions)? Since I couldn't find the answer in their documentation, I had to run some manual tests.

The answer is: less than 240 characters. If `*.func` folder has 240 characters or more, Vercel responds with
```
Error: ENAMETOOLONG: name too long
```

With that in mind, I think that the proposed solution is fine for the time being, just to fix the original issue. However ideally there should be a mechanism that limits function name length.

**Comment by slawekkolodziej** [comment]
I thought about limiting the file name to a sane number of characters and adding short content hash to the end.

I like to have route included in the function name - as you said, it simplifies debugging and makes debug.

Now when I think about it, we could ditch `entry-` and `-astro` parts of function names completely, to improve monitoring even more:

Consider what my original change generates:
what-code-generates-now

After some adjustments, Vercel can accept this too:
what-we-can-have

**Comment by ematipico** [comment]
> Now when I think about it, we could ditch entry- and -astro parts of function names completely

- `entry` comes from the core; maybe we should remove it from there?
- `.astro` is just the extension of the file, you would need to remove `.js`, `.ts`, etc., right?

**Comment by slawekkolodziej** [comment]
> * `.astro` is just the extension of the file, you would need to remove `.js`, `.ts`, etc., right?

The complete file extension is `.astro.mjs`, original code already removed `.mjs`.

File: packages/integrations/vercel/src/serverless/adapter.ts [hunk 1]
```diff
@@ -207,14 +207,31 @@ You can set functionPerRoute: false to prevent surpassing the limit.`
 
 				// Multiple entrypoint support
 				if (_entryPoints.size) {
-					for (const [route, entryFile] of _entryPoints) {
-						const func = basename(entryFile.toString()).replace(/\.mjs$/, '');
+					// TODO: Currently this function directly checks for a single route 
+					// injected in packages/astro/src/assets/internal.ts Ideally this
+					// should be done dynamically
+					const isInjectedRoute = (route: RouteData) =>
+						route.pathname === '/_image';
```
Comment (ematipico) [inline packages/integrations/vercel/src/serverless/adapter.ts:214]: I think we could change the name in `isImageRoute`, and remove the `TODO`. Here we want to specially allow-list our internal `_image` endpoint.

**Comment by slawekkolodziej** [comment]
I simplified the code a bit, now my routes looks as clean as they can get 💚 

Screenshot 2023-09-05 at 14 54 57

File: packages/integrations/vercel/src/serverless/adapter.ts [hunk 2]
```diff
@@ -207,14 +207,31 @@ You can set functionPerRoute: false to prevent surpassing the limit.`
...
+
+          const getInjectedFuncName = (entryFile: URL) =>
+            basename(entryFile.toString())
+              .replace(/^entry\./, '')
+              .replace(/\.mjs$/, '');
```
Comment (ematipico) [inline packages/integrations/vercel/src/serverless/adapter.ts:219]: Why a regex? Isn't `replace("entry.", "")` enough?

**Review by ematipico — APPROVED** [review]
I left some comments. I think overall, we could release this fix.

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 2 above)
Comment (slawekkolodziej) [reply packages/integrations/vercel/src/serverless/adapter.ts:219]: This regex only matches "`entry.`" at the beginning of the string. You could ask the same question about the original `.replace(/\.mjs$/, '');` code. It could use `.replace(".mjs", "")` too.

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 1 above)
Comment (slawekkolodziej) [reply packages/integrations/vercel/src/serverless/adapter.ts:214]: Makes sense.

I wonder if there should be any comment left regarding the todo here:
https://github.com/withastro/astro/blob/main/packages/astro/src/assets/internal.ts#L14-L19, just for the reference.

Comment (bluwy) [reply packages/integrations/vercel/src/serverless/adapter.ts:214]: Maybe if `route.component` doesn't start with `src/pages/`, we can then fallback for `getInjectedFuncName`? That way we don't have to hardcode this.

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 2 above)
Comment (slawekkolodziej) [reply packages/integrations/vercel/src/serverless/adapter.ts:219]: Regarding your other comment, if we rename `isInjectedRoute` to `isImageRoute`, it would be natural to rename `getInjectedFuncName` to `getImageFuncName` too, then this function could return a fixed string.

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 1 above)
Comment (ematipico) [reply packages/integrations/vercel/src/serverless/adapter.ts:214]: Way better

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 2 above)
Comment (ematipico) [reply packages/integrations/vercel/src/serverless/adapter.ts:219]: Sorry, I ask the question in a different way: Why did you use a regex instead of a simple string? Do they have the same impact performance-wise?

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 1 above)
Comment (bluwy) [reply packages/integrations/vercel/src/serverless/adapter.ts:214]: Yup looks great! Maybe the functions can be renamed so it's clearer, but the idea and flow is good.

File: packages/integrations/vercel/src/serverless/adapter.ts (hunk 2 above)
Comment (slawekkolodziej) [reply packages/integrations/vercel/src/serverless/adapter.ts]: I used it to ensure precision. For example, it avoids incorrectly replacing 'hello.world.entry.astro.mjs' when `entryFile` doesn't start with 'entry.'. Regex allowed me to target replacements specifically at string's start. However, if you are certain that it always begins with `entry.` then that's enough!

Simple string replacement is generally faster, though the speed difference in this case is most likely negligible.

I am not that attached to this regex, I removed it. I just want this PR to get merged so I can upgrade to v3.

**Review by natemoo-re — APPROVED** [review]

**Review by matthewp — APPROVED** [review]
