### PR TITLE
fix(astro): terminal HMR path (close #8831)

### LINKED ISSUE #8831: CLI paths take the PC Root, not the project's path root.
### Astro Info

```block
"Astro                    v3.2.2\nNode                     v18.16.0\nSystem                   Windows (x64)\nPackage Manager          npm\nOutput                   server\nAdapter                  @astrojs/vercel/serverless\nIntegrations             @custom/update-webflow-js\n                         @astrojs/tailwind\n                         @astrojs/preact\n                         @astrojs/prefetch\n                         astro-robots-txt"
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

The Astro CLI during npm run dev is using my entire pc path for outputs, can this be modified to instead use the project's root path?

image

### What's the expected result?

I would think the project's root path is better! instead of the entire PC path !

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-n2mknz?file=README.md

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- #8831
- Uses fileURLToPath and nozmalizes the path between OSs

## Testing

Tested by pointing the `@example/basics` astro version to the local one (`workspace:*`), only on Windows.

## Docs

No change required

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro/hmr.ts [hunk 1]
```diff
@@ -91,7 +92,7 @@ export async function handleHotUpdate(
 	// Bugfix: sometimes style URLs get normalized and end with `lang.css=`
 	// These will cause full reloads, so filter them out here
 	const mods = [...filtered].filter((m) => !m.url.endsWith('='));
-	const file = ctx.file.replace(config.root.pathname, '/');
+	const file = relative(process.cwd(), ctx.file.replace(config.root.pathname, '/'));
```
Comment (lilnasy) [inline packages/astro/src/vite-plugin-astro/hmr.ts:95]: I think involving cwd might create unexpected results. Most users would start the dev server from the root of their projects, but they should not see something different if that is not the case.

Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:95]: could `import.meta.url` help?

Comment (lilnasy) [reply packages/astro/src/vite-plugin-astro/hmr.ts:95]: `import.meta.url` would likely be somewhere in node_modules.

It also seems like `relative()`, and `ctx.file.replace()` are attempting to do the same thing: removing the first few parts of ctx.file.

Why doesn't the `replace()` call work on Windows?

Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:95]: Pushing a fix soon but here is what happens:
```ts
{
  pathname: '/D:/DEV/PROJECTS/withastro/astro/examples/basics/',
  file: 'D:/DEV/PROJECTS/withastro/astro/packages/astro/dist/jsx-runtime/index.js'
}
```
the only thing is to prepend a slash if needed

File: packages/astro/src/vite-plugin-astro/hmr.ts [hunk 2]
```diff
@@ -91,7 +91,11 @@ export async function handleHotUpdate(
 	// Bugfix: sometimes style URLs get normalized and end with `lang.css=`
 	// These will cause full reloads, so filter them out here
 	const mods = [...filtered].filter((m) => !m.url.endsWith('='));
-	const file = ctx.file.replace(config.root.pathname, '/');
+	let file = ctx.file;
+	if (!file.startsWith('/')) {
+		file = `/${file}`
+	}
+	file = file.replace(config.root.pathname, '/')
```
Comment (lilnasy) [inline packages/astro/src/vite-plugin-astro/hmr.ts:98]: Nice! That fixes it.

It looks like it still shows the full path when the project name has a space, like in the case of the issue screenshot. Can you check what happens there?

Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts]: I handled only spaces, I don't know if there are any other special character that causes the issue

File: packages/astro/src/vite-plugin-astro/hmr.ts [hunk 3]
```diff
@@ -91,7 +91,11 @@ export async function handleHotUpdate(
 	// Bugfix: sometimes style URLs get normalized and end with `lang.css=`
 	// These will cause full reloads, so filter them out here
 	const mods = [...filtered].filter((m) => !m.url.endsWith('='));
-	const file = ctx.file.replace(config.root.pathname, '/');
+	let file = ctx.file;
+	if (!file.startsWith('/')) {
+		file = `/${file}`
+	}
+	file = file.replaceAll(' ', '%20').replace(config.root.pathname, '/')
```
[the remark this answers is not in the document]
Comment (natemoo-re) [reply packages/astro/src/vite-plugin-astro/hmr.ts:98]: [`fileURLToPath`](https://nodejs.org/api/url.html#urlfileurltopathurl) is probably what you're looking for!

[the remark this answers is not in the document]
Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:98]: Now I understand what you meant @lilnasy! Things are coming together in my head ahah

[the remark this answers is not in the document]
Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts]: We should be good now! Until I forget something else 😅

File: packages/astro/src/vite-plugin-astro/hmr.ts [hunk 4]
```diff
@@ -91,7 +91,9 @@ export async function handleHotUpdate(
 	// Bugfix: sometimes style URLs get normalized and end with `lang.css=`
 	// These will cause full reloads, so filter them out here
 	const mods = [...filtered].filter((m) => !m.url.endsWith('='));
-	const file = ctx.file.replace(config.root.pathname, '/');
+	const file = fileURLToPath(`file:///${ctx.file}`)
+		.replace(fileURLToPath(config.root), '/')
+		.replace(/\\/g, '/');
```
Comment (lilnasy) [inline packages/astro/src/vite-plugin-astro/hmr.ts:96]:
```suggestion
	const file = ctx.file.replace(fileURLToPath(config.root));
```
Was converting ctx.file path to a URL necessary? I would think converting config.root URL to path is enough.

File: .changeset/two-lamps-tell.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixes the terminal HMR path
```
Comment (lilnasy) [inline .changeset/two-lamps-tell.md:5]: Astro users will see this in the changelog, and they may not have full context about what happened.
"Fixed an issue where the dev server logged the full file path on updates."

File: packages/astro/src/vite-plugin-astro/hmr.ts (hunk 4 above)
Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:96]: I confirm you're suggestion (`ctx.file.replace(fileURLToPath(config.root), '/')`) does not work

File: .changeset/two-lamps-tell.md [hunk 6]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixed an issue where the dev server logged the full file path on updates.
```
Comment (sarah11918) [inline .changeset/two-lamps-tell.md:5]:
```suggestion
Fixes an issue where the dev server logged the full file path on updates.
```
Just standardizing our changeset tense... Docs out!

File: packages/astro/src/vite-plugin-astro/hmr.ts (hunk 4 above)
Comment (lilnasy) [inline packages/astro/src/vite-plugin-astro/hmr.ts:96]: Thanks for bearing with me so far. This looks great on Windows now!

There is one minor blemish on linux.
image

Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:96]: Do you think the following could be acceptable?
```ts
	const file = fileURLToPath(`file:///${ctx.file.substring(ctx.file.startsWith('/') ? 1 : 0)}`)
		.replace(fileURLToPath(config.root), '/')
		.replace(/\\/g, '/');
```

[the remark this answers is not in the document]
Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:96]: I'll give it a go 👍

Comment (lilnasy) [reply packages/astro/src/vite-plugin-astro/hmr.ts:96]: It could, but this is becoming kinda long. Maybe if the approach from my other comment does not work.

Comment (ematipico) [inline packages/astro/src/vite-plugin-astro/hmr.ts:96]: Can't we make the paths relative to the Astro working directory? It seems more simple...

Comment (florian-lefebvre) [reply packages/astro/src/vite-plugin-astro/hmr.ts:96]: That was my first attempt, I need to see if it can be simplified first using only one `fileURLToPath`

File: packages/astro/src/vite-plugin-astro/hmr.ts [hunk 7]
```diff
@@ -91,7 +91,7 @@ export async function handleHotUpdate(
 	// Bugfix: sometimes style URLs get normalized and end with `lang.css=`
 	// These will cause full reloads, so filter them out here
 	const mods = [...filtered].filter((m) => !m.url.endsWith('='));
-	const file = ctx.file.replace(config.root.pathname, '/');
+	const file = ctx.file.replace(fileURLToPath(config.root).replace(/\\/g, '/'), '/');
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-astro/hmr.ts:94]: Super minor, but we have a few utilities that might be helpful exported from [`@astrojs/internal-helpers/path`](https://github.com/withastro/astro/blob/main/packages/internal-helpers/src/path.ts). Namely [`slash`](https://github.com/withastro/astro/blob/0d4922dffe7d96b907db89ec502f77efd572cc56/packages/internal-helpers/src/path.ts#L92) could replace the manual regex logic here.

**Review by ematipico — APPROVED** [review]
