### PR TITLE
HMR hoisted scripts

### LINKED ISSUE #3228: 🐛 BUG: Dynamic JSX elements do not update without manually restarting the dev server
### What version of `astro` are you using?

1.0.0-beta.19

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac, Linux

### Describe the Bug

Rendering a dynamic element (taking an element string as a prop and then rendering that in JSX) works, but only the first time - changing what I pass as that prop triggers the dev server to HMR but does not actually propagate the change. The only way to propagate the change is to trigger a different fundamental change to the component, or to manually restart the dev server.

In the following example, try changing the value passed to `DynEl`. 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/rough-field-3q46gu?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Adds hoisted scripts to the module graph, so that they will trigger HMR.
- Fixes #3228

## Testing

Manually tested via an example.

## Docs

N/A, bug fix.

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro/index.ts [hunk 1]
```diff
@@ -126,6 +126,12 @@ export default function astro({ config, logging }: AstroPluginOptions): vite.Plu
 					if (typeof query.index === 'undefined') {
 						throw new Error(`Requests for hoisted scripts must include an index`);
 					}
+					// HMR hoisted script only exists to make them appear in the module graph.
+					if(opts?.ssr) {
+						return {
+							code: ''
```
Comment (FredKSchott) [inline packages/astro/src/vite-plugin-astro/index.ts:132]: nit: can this be a comment like `/* client hoisted script, empty in SSR */`? Bonus if it can also include the file path or some other useful debug info.

**Review by FredKSchott — APPROVED** [review]
LGTM with 1 small code
