### PR TITLE
fix: clone session data on .set()

### LINKED ISSUE #12881: bug / clarification: session.set is pass by reference, leading to edits after calling .set to be persisted
### Astro Info

```block
Astro                    v5.1.1
Node                     v22.12.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/node
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

This line sets the "data" value directly to be the passed in value, so if it's an object it's pass by reference:

https://github.com/withastro/astro/blob/a6a4a66f10d85363b90ff4b7cd5bdd8c2b3c81fb/packages/astro/src/core/session.ts#L163

Thus if you do something like

```ts
const allData = {secret: "word", notSecret: "stuff"}
Astro.session.set("allData", allData);
delete allData.secret
return allData;
```

The deferred saving of the session data causes the updates after the call to `.set()` to be persisted to the session store.

### What's the expected result?

When Astro does this check:
https://github.com/withastro/astro/blob/a6a4a66f10d85363b90ff4b7cd5bdd8c2b3c81fb/packages/astro/src/core/session.ts#L143

It should do the full serialization (including the URL conversion) and save that to `#data.value`, instead of doing it later:

https://github.com/withastro/astro/blob/a6a4a66f10d85363b90ff4b7cd5bdd8c2b3c81fb/packages/astro/src/core/session.ts#L224

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-muwk6ati-e1czmh2l?file=src%2Fpages%2Findex.astro

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by kaytwo**
## Changes

* Fixes #12881 by saving a clone of the set()'d object at time of set()
* Refactor unflatten and stringify so that the stringify check works for URL objects

I chose to use `parse(stringify(value))` instead of anything like `structuredClone` or trying to get fancy with the store to ensure correctness, the extra parse should not be a significant performance issue unless people start storing pathologically large session data.

## Testing

Added a new test in `sessions.test.js` that fails on main and succeeds on this branch.

That test could probably use a helper function to maintain a "cookie jar" for session, but I don't quite know the cleanest way to do that.

## Docs

No update necessary, just a bugfix. However if the powers that be decide #12881 is `wontfix`, the docs definitely need to be updated to remind users to clone their objects before calling set, or be careful with updating them after doing so.

### CODE REVIEW

File: packages/astro/src/core/session.ts [hunk 1]
```diff
@@ -138,9 +152,10 @@ export class AstroSession<TDriver extends SessionDriverName = any> {
 				message: 'The session key was not provided.',
 			});
 		}
+		let cloned: T;
 		try {
 			// Attempt to serialize the value so we can throw an error early if needed
```
Comment (ematipico) [inline packages/astro/src/core/session.ts:157]: The comment should be updated to reflect the new logic

File: packages/astro/test/sessions.test.js [hunk 2]
```diff
@@ -1,13 +1,17 @@
...
 import { loadFixture } from './test-utils.js';
+import fs from 'node:fs';
 
 describe('Astro.session', () => {
 	/** @type {import('./test-utils').Fixture} */
 	let fixture;
 
 	before(async () => {
+		// seems to be a race condition in unstorage when the session directory doesn't exist
+		await fs.promises.mkdir('.astro/session', { recursive: true });
```
Comment (ascorbic) [inline packages/astro/test/sessions.test.js:14]: We should probably be creating this in production too in that case. It could go here: 

https://github.com/kaytwo/astro/blob/6e7afe876fa8ee07457dd60e145de70aa3f9f5c3/packages/astro/src/core/session.ts#L396

File: packages/astro/src/core/session.ts (hunk 1 above)
Comment (ascorbic) [reply packages/astro/src/core/session.ts:157]: Agreed. Can you include the explanation of why we're cloning it too.

**Comment by ascorbic** [comment]
Thanks for this. The issue with the missing `.astro/sessions` dir could be a real bug, so it would be better to fix it than work around it in the test.

**Comment by ascorbic** [comment]
Ah, my mistake. We can't use fs there. I think it's ok to revert to your previous version.

**Comment by kaytwo** [comment]
reverted. I added a different "ensure the directory exists" check that is only a little bit of a hack. also added "/.astro" to .gitignore as both manually and turbo running the tests creates that directory in various places, and I didn't see anywhere else (e.g. being used as part of a test fixture) so that should be safe.

File: packages/astro/src/core/session.ts [hunk 3]
```diff
@@ -455,6 +449,13 @@ export class AstroSession<TDriver extends SessionDriverName = any> {
 			this.#storage = createStorage({
 				driver: driver(this.#config.options),
 			});
+			if (this.#config.driver === 'fs-lite') {
+				// seems to be a race condition in unstorage when the session directory doesn't exist
+				// this ensures that the directory is created before we try to use it for real sessions
+				const dummyId = crypto.randomUUID();
+				await this.#storage.setItem(dummyId, 'init');
+				await this.#storage.removeItem(dummyId);
+			}
```
Comment (ascorbic) [inline packages/astro/src/core/session.ts:458]: OK, I think I understand this now. SAo is the problem that if you try to read a session when the ddirectory hasn't been created then it has an error? I'm not happy with this workaround because we're otherwise not using the storage unless the user actually reads or writes a session. This is soemthign that should be fixed upstream: unstorage should just return undefined for gets if the directory doesn't exist, the same as if the file doesn't exist. 

Have you encountered this issue outside of tests? If not, I think the best bet is to add a workaround inside tests, and report the issue on the unstorage repo.

Comment (kaytwo) [reply packages/astro/src/core/session.ts]: Glad you pushed back on this one - found the underlying bug. `PERSIST_SYMBOL` snuck through TypeScript's type inference and it didn't yell about it not being awaited.

File: .changeset/tough-cars-yawn.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixes a bug where session data could be corrupted if it is changed after calling .set(); also fixes a bug where responses can be returned before session data is saved
```
Comment (ascorbic) [inline .changeset/tough-cars-yawn.md:5]: Can you split this into two chanegsets. You can run `pnpm changeset` again to add another one.

**Review by ascorbic — APPROVED** [review]
Great work. Thanks for tracking down all the issues. Just a single request with the changeset and we can merge this.

**Review by ascorbic — APPROVED** [review]
Great! Thanks a lot for fixing these two.
