### PR TITLE
fix: don't lose cookies in middleware sequences

### LINKED ISSUE #14262: Middleware sequence with rewrite drops cookies
### Astro Info

```block
Astro                    v5.13.3
Node                     v24.4.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Please take a look at the reproducible example in stackblitz.

```ts
//middleware.ts
import type { MiddlewareHandler } from 'astro';
import { sequence } from 'astro:middleware';

export const mid1: MiddlewareHandler = async (
  { cookies, locals, rewrite },
  next
) => {
  console.log('In middleware 1');
  cookies.set('cookie1', 'Cookie from middleware 1');
  if (!locals.rewritten) {
    console.log('Rewriting');
    locals.rewritten = true;
    return rewrite('/'); // <--- A simple rewrite for demo purposes.
  }
  return next();
};

export const mid2: MiddlewareHandler = async ({ cookies }, next) => {
  console.log('In middleware 2');
  cookies.set('cookie2', 'Cookie from middleware 2'); // <--- This cookie never makes it into the Response
  return next();
};

export const onRequest: MiddlewareHandler = sequence(mid1, mid2);
```

When a rewrite happens in one of the middleware layers, any further cookies don't make it into the response. Only the first one.

Image

Image

### What's the expected result?

I would expect that cookies set in all middleware layers would get merged into the final Response object.

Note: when not using a rewrite, all cookies make it through. This problem only occurs when a rewrite has happened.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qv8hj4sw-yc3rx6o8?file=src%2Fmiddleware.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Currently if middleware includes rewrites, only the first middleware in a sequence that sets cookies is returned to the browser, and any cookies set in subsequent middleware is lost. This PR fixes that.

Fixes #14262

## Testing

Added tests

### CODE REVIEW

File: packages/astro/src/core/middleware/sequence.ts [hunk 1]
```diff
@@ -78,7 +77,6 @@ export function sequence(...handlers: MiddlewareHandler[]): MiddlewareHandler {
 						carriedPayload = payload;
 						handleContext.request = newRequest;
 						handleContext.url = new URL(newRequest.url);
-						handleContext.cookies = new AstroCookies(newRequest);
```
Comment (ascorbic) [inline packages/astro/src/core/middleware/sequence.ts:81]: This assignment wasn't the cause of the bug, but when the bug was fixed, this broke sequences *without* rewrites. It's not needed, because the new request won't have any cookies to read as it has no headers. Instead we preserve the cookies from the original request.

File: packages/astro/test/fixtures/middleware-sequence-request-clone/src/middleware.js [hunk 2]
```diff
@@ -2,14 +2,16 @@ import { sequence, defineMiddleware } from 'astro/middleware';
 
 const middleware1 = defineMiddleware((_, next) => next('/'));
 
-const middleware2 = defineMiddleware(async ({ request }, next) => {
+const middleware2 = defineMiddleware(async ({ request, cookies }, next) => {
+	cookies.set('cookie1', 'Cookie from middleware 1');
```
Comment (Fryuni) [inline packages/astro/test/fixtures/middleware-sequence-request-clone/src/middleware.js:6]: This is middleware 2. 1 doesn't set any cookies

File: packages/astro/test/fixtures/middleware-sequence-request-clone/src/middleware.js [hunk 3]
```diff
@@ -2,14 +2,16 @@ import { sequence, defineMiddleware } from 'astro/middleware';
...
 	console.log(await request.clone().text());
 	return next();
 });
 
-const middleware3 = defineMiddleware(async ({ request }, next) => {
+const middleware3 = defineMiddleware(async ({ request, cookies }, next) => {
+	cookies.set('cookie2', 'Cookie from middleware 2');
```
Comment (Fryuni) [inline packages/astro/test/fixtures/middleware-sequence-request-clone/src/middleware.js:12]: And this is middleware 3

File: packages/astro/test/fixtures/middleware-sequence-request-clone/src/middleware.js (hunk 2 above)
Comment (ascorbic) [reply packages/astro/test/fixtures/middleware-sequence-request-clone/src/middleware.js:6]: yes yes. I think we'll be fine
