### PR TITLE
Handle builds with outDir outside of cwd

### LINKED ISSUE #4006: 🐛 BUG: outDir that doesn't have package.json with node_modules fails
### What version of `astro` are you using?

1.0.0-beta.73

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

If we create a new project and use solid-js as the baseline then change the [outDir](https://docs.astro.build/en/reference/configuration-reference/#outdir) in configuration to a relative path without a node modules, for example "../dist" an error is thrown that solid js cannot be found.

If we then `cp package.json ./package.json && cd .. && yarn` then try again the build completes successfully.

Full error:
```sh 
error   Cannot find package 'solid-js' imported from /Users/lukecollier/Projects/mull.dev/docs/entry.mjs
    at new NodeError (node:internal/errors:372:5)
    at packageResolve (node:internal/modules/esm/resolve:954:9)
    at moduleResolve (node:internal/modules/esm/resolve:1003:20)
    at defaultResolve (node:internal/modules/esm/resolve:1218:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
error Command failed with exit code 1.
```

Funnily enough in stackblitz you can `ctl + c` in the console window to run `yarn build` and another error occurs in stack blitz un-related to this issue! (Something to do with go pipelines etc)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/outdir-issue?file=astro.config.mjs

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Fix #4006

If `outDir` is out of `process.cwd()`, build the ssr output to `<cwd>/.astro` instead. This directory will be removed after the build, unless an error occurs during the build, which it's preserved for debuggability.

## Testing

No test added as the monorepo structure makes it tricky to test this edge case (brings false positive). I did test with a separate project though and it works.

## Docs

~~This PR handles static output only (`output: 'static'`). For server output, the `outDir` MUST be inside the current working directory as most integrations requires this for the deployment output to work. (e.g. netlify, vercel, cloudflare)~~

~~Should we document this? On the other hand, setting `outDir` outside of cwd feels like a special case.~~

~~/cc @withastro/maintainers-docs for feedback!~~

### CODE REVIEW

**Comment by matthewp** [comment]
Given that we cannot build outside of the projectRoot when `output: 'server'`, can we error when someone attempts it?

File: packages/astro/src/core/build/common.ts [hunk 1]
```diff
@@ -1,8 +1,10 @@
 import npath from 'path';
+import { fileURLToPath, pathToFileURL } from 'url';
 import type { AstroConfig, RouteType } from '../../@types/astro';
 import { appendForwardSlash } from '../../core/path.js';
 
 const STATUS_CODE_PAGES = new Set(['/404', '/500']);
+const FALLBACK_OUT_DIR_NAME = './.astro-temp/';
```
Comment (natemoo-re) [inline packages/astro/src/core/build/common.ts:7]: I'd be fine with `.astro`, personally? Not a huge deal but it's a bit more clean.

```suggestion
const FALLBACK_OUT_DIR_NAME = './.astro/';
```

**Review by natemoo-re — APPROVED** [review]
Looks great, had one small suggestion but not blocking in any way.

File: packages/astro/src/core/build/common.ts (hunk 1 above)
Comment (bluwy) [reply packages/astro/src/core/build/common.ts:7]: I'm fine with this too. I thought that in the case where the build fails, and `.astro-temp` is not removed (for debugging), it sends a clearer message that it's a temporary folder that can be removed.

Comment (natemoo-re) [reply packages/astro/src/core/build/common.ts:7]: That's fine with me! I'd probably add the directory to the `.gitignore` files in our examples just to be safe?

**Review by matthewp — CHANGES_REQUESTED** [review]
Let's go ahead and error when attempting this with `output: 'server'`

**Comment by bluwy** [comment]
@matthewp Actually through further testing, `output: 'server'` seem unaffected as we don't invoke the SSR output for generating pages. This seems to be fine then. The PR should be good now.

File: packages/astro/src/core/build/common.ts (hunk 1 above)
Comment (bluwy) [reply packages/astro/src/core/build/common.ts]: @natemoo-re I updated to use `.astro`. I think a `.gitignore` change shouldn't be needed at the meantime since this special directory is only created if someone specifies a `outDir` outside of the project. Perhaps if there's a request for it you can add that too.
