### PR TITLE
Fix injected route edge case

### LINKED ISSUE #7397: Unable to build Starlight documentation with Astro version `>=2.6.4`
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

_Note: I am posting this issue in this repo as advised in the #starlight Discord channel as the issue seems to be related to an Astro regression._

With Starlight, when using an Astro version `>=2.5.6`, the build fails with the following error:

```shell
Invalid pattern "../node_modules/.pnpm/@astrojs+starlight@0.1.4_astro@2.5.6/node_modules/@astrojs/starlight/404.astro.mjs" for "output.entryFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.
 error   Invalid pattern "../node_modules/.pnpm/@astrojs+starlight@0.1.4_astro@2.5.6/node_modules/@astrojs/starlight/404.astro.mjs" for "output.entryFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.
RollupError: Invalid pattern "../node_modules/.pnpm/@astrojs+starlight@0.1.4_astro@2.5.6/node_modules/@astrojs/starlight/404.astro.mjs" for "output.entryFileNames", patterns can be neither absolute nor relative paths. If you want your files to be stored in a subdirectory, write its name without a leading slash like this: subdirectory/pattern.
    at error (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:2238:30)
    at renderNamePattern (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:15477:16)
    at Chunk.getPreliminaryFileName (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:15773:24)
    at reserveEntryChunksInBundle (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:17483:19)
    at renderChunks (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:17469:5)
    at Bundle.generate (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:17692:19)
    at async eval (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:26157:27)
    at async catchUnfinishedHookActions (file://file:///home/projects/github-kwocty/node_modules/.pnpm/rollup@3.25.1/node_modules/rollup/dist/es/shared/node-entry.js:25290:16)
    at async Module.build (file://file:///home/projects/github-kwocty/node_modules/.pnpm/vite@4.3.9/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:46529:22)
    at async ssrBuild (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/core/build/static-build.js:190:10)
    at async Module.viteBuild (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/core/build/static-build.js:75:21)
    at async AstroBuilder.build (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/core/build/index.js:140:27)
    at async AstroBuilder.run (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/core/build/index.js:173:7)
    at async build (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/core/build/index.js:54:3)
    at async runCommand (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/cli/index.js:184:14)
    at async cli (file://file:///home/projects/github-kwocty/node_modules/.pnpm/astro@2.5.6/node_modules/astro/dist/cli/index.js:226:5)
 ELIFECYCLE  Command failed with exit code 1.
```

A few notes:

- `v2.5.5` works fine.
- All versions `>=2.5.6` fail even the latest one.
- Running the dev server with `astro dev` works fine.
- The project where I encountered this issue is a pnpm monorepo.
- I tried to reproduce the issue in a fresh project (which is not a monorepo) created with `pnpm create astro --template starlight` but I was not able to reproduce it.

I did not have yet the time to investigate further and git bisect to find the exact commit that introduced the issue but a quick workaround is to use Astro `v2.5.5` for now.

I provided a Stackblitz project that reproduces the issue where you can see the error by running `cd docs && pnpm build`.

The issue is also reproducible in the Starlight repo:

```shell 
$ git clone https://github.com/withastro/starlight
$ cd starlight
$ pnpm i
$ cd docs
$ pnpm build # this works fine
$ pnpm add astro@latest
$ pnpm build # this fails
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kwocty?file=docs%2Fpackage.json&view=editor

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #7397
- Fixes edge case where injected routes would emit an unsupported entry file name at build time
- Also updates our static build logging to fallback to the injected route pattern if an injected route is being generated. Previously, it would show the relative path to the injected component inside of `node_modules`

## Testing

Existing tests should pass, additional `injectRoute` from packages added

## Docs

No, bug fix only

### CODE REVIEW

File: packages/astro/src/core/build/static-build.ts [hunk 1]
```diff
@@ -418,27 +418,26 @@ async function ssrMoveAssets(opts: StaticBuildOptions) {
...
  * Output: `pages/index.astro.mjs`
+ * Input: `@astro-page:../node_modules/my-dep/injected.astro@_@astro`
+ * Output: `pages/injected.mjs`
  *
- * 1. We remove the module id prefix, `@astro-page:`
- * 2. We remove `src/`
- * 3. We replace square brackets with underscore, for example `[slug]`
- * 4. At last, we replace the extension pattern with a simple dot
- * 5. We append the `.mjs` string, so the file will always be a JS file
+ * 1. We clean the `facadeModuleId` by removing the `@astro-page:` prefix and `@_@astro` suffix
```
Comment (ematipico) [inline packages/astro/src/core/build/static-build.ts:429]: That's incorrect, what we replace is `@_@`, which was used to hide the file extension: index.astro -> index@_@astro -> index.astro

File: packages/astro/src/core/build/static-build.ts [hunk 2]
```diff
@@ -418,27 +418,26 @@ async function ssrMoveAssets(opts: StaticBuildOptions) {
...
  */
-function makeAstroPageEntryPointFileName(facadeModuleId: string) {
-	return `${facadeModuleId
+function makeAstroPageEntryPointFileName(facadeModuleId: string, pages: AllPagesData) {
+	const pageModuleId = `${facadeModuleId
 		.replace(ASTRO_PAGE_RESOLVED_MODULE_ID, '')
-		.replace('src/', '')
-		.replaceAll('[', '_')
-		.replaceAll(']', '_')
-		// this must be last
```
Comment (ematipico) [inline packages/astro/src/core/build/static-build.ts:442]: Any particular reason why this is not the last one anymore?

File: packages/astro/src/core/build/static-build.ts [hunk 3]
```diff
@@ -418,27 +418,26 @@ async function ssrMoveAssets(opts: StaticBuildOptions) {
...
 /**
- * This function takes as input the virtual module name of an astro page and transform
- * to generate an `.mjs` file:
+ * This function takes the virtual module name of any page entrypoint and
+ * transforms it to generate a final `.mjs` output file.
  *
  * Input: `@astro-page:src/pages/index@_@astro`
- *
  * Output: `pages/index.astro.mjs`
+ * Input: `@astro-page:../node_modules/my-dep/injected.astro@_@astro`
```
Comment (ematipico) [inline packages/astro/src/core/build/static-build.ts:426]: The example is incorrect, it should be `injected@_@astro`

File: packages/astro/src/core/build/static-build.ts [hunk 4]
```diff
@@ -418,27 +418,26 @@ async function ssrMoveAssets(opts: StaticBuildOptions) {
...
+function makeAstroPageEntryPointFileName(facadeModuleId: string, pages: AllPagesData) {
+	const pageModuleId = `${facadeModuleId
 		.replace(ASTRO_PAGE_RESOLVED_MODULE_ID, '')
-		.replace('src/', '')
-		.replaceAll('[', '_')
-		.replaceAll(']', '_')
-		// this must be last
-		.replace(ASTRO_PAGE_EXTENSION_POST_PATTERN, '.')}.mjs`;
+		.replace(ASTRO_PAGE_EXTENSION_POST_PATTERN, '.')}`;
+	const name = pages[pageModuleId]?.route?.route ?? pageModuleId;
```
Comment (ematipico) [inline packages/astro/src/core/build/static-build.ts:441]: I think this must be done at the end? Here `pageModuleId` has its name still mangled and it won't match any route

**Comment by ematipico** [comment]
Even though all tests should pass, I'm surprised we hit a regression. Isn't there a way to simulate a test for the issue that was filed?

File: packages/astro/src/core/build/static-build.ts (hunk 2 above)
Comment (natemoo-re) [reply packages/astro/src/core/build/static-build.ts:442]: See https://github.com/withastro/astro/pull/7399#discussion_r1232445925

File: packages/astro/test/custom-404-injected-from-dep.test.js [hunk 5]
```diff
@@ -0,0 +1,22 @@
+import { expect } from 'chai';
+import { loadFixture } from './test-utils.js';
+
+describe('Custom 404 with injectRoute from dependency', () => {
```
Comment (natemoo-re) [inline packages/astro/test/custom-404-injected-from-dep.test.js:4]: Added a specific test for #7397! The injected route will be matched to a relative path in `./node_modules` but the build should still succeed. This test verifies that this is the case.

**Review by ematipico — APPROVED** [review]
Thank you Nate!
