### PR TITLE
fix(markdoc): resolve custom attributes on built-in table tag

### LINKED ISSUE #14220: Attributes on table does not work with markdoc
### Astro Info

```block
Astro                    v5.11.1
Node                     v22.17.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         astro-expressive-code
                         @astrojs/markdoc
                         @astrojs/mdx
                         video-assets
                         content-map
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Even if I add following to markdoc.config.mjs

```
table: {
      attributes: {
        background: {
          type: String,
          matches: ["default", "transparent"],
        },
        showMore: { type: Number },
        fixedColumns: { type: Boolean },
        class: { type: String },
      },
      render: component("./src/components/common/Table.astro"),
}
```

to nodes, I get error:
`Invalid attribute background when I use {% table background="default" %}`

### What's the expected result?

I should not the error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-zqkuvhet?file=src%2Fcomponents%2FTable.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by AhmadYasser1**
## Changes

- Adds `syncTagNodeAttributes()` to `packages/integrations/markdoc/src/runtime.ts` that runs after config setup
- In Markdoc, `table` exists as both a **tag** (`{% table %}`) and a **node** (the inner table structure). Attributes on the tag propagate to the child node in the AST, so both schemas must declare the same attributes for `Markdoc.validate()` to pass
- When users configure custom attributes on `nodes.table` or `tags.table`, this function syncs the attribute declarations to the counterpart, preventing "Invalid attribute" validation errors
- Only runs for names that exist in both `Markdoc.tags` and `Markdoc.nodes` (currently only `table`)

## Testing

- Added `test/render-table-attrs.test.js` with build + dev tests using a fixture that configures `nodes.table` with a custom `background` attribute
- All 79 markdoc tests pass (77 existing + 2 new)

## Docs

- No docs changes needed. This is a bug fix that makes existing documented behavior work correctly.

Fixes #14220

### CODE REVIEW

File: packages/integrations/markdoc/src/runtime.ts [hunk 1]
```diff
@@ -98,6 +100,45 @@ export function mergeConfig(
...
+/**
+ * Sync custom attributes between tags and nodes that share the same name.
+ * In Markdoc, `table` exists as both a tag (`{% table %}`) and a node (the inner
+ * table structure). Attributes on the tag propagate to the child node in the AST,
+ * so both schemas must declare the same attributes for validation to pass.
+ * When users configure attributes on only one side, this copies them to the other.
+ */
+function syncTagNodeAttributes(config: MergedConfig): void {
+	// Use `as any` for built-in schema access since Markdoc's types don't have string index signatures
+	const builtinTags: Record<string, any> = Markdoc.tags;
```
Comment (matthewp) [inline packages/integrations/markdoc/src/runtime.ts:113]: Can you just omit the type here since it will be the type of the value you're assigning

File: packages/integrations/markdoc/src/runtime.ts [hunk 2]
```diff
@@ -98,6 +100,45 @@ export function mergeConfig(
...
+	const builtinNodes: Record<string, any> = Markdoc.nodes;
```
Comment (matthewp) [inline packages/integrations/markdoc/src/runtime.ts:114]: Same here

**Comment by AhmadYasser1** [comment]
re the type annotations on builtinTags/builtinNodes: tried removing them but it causes TS7053 errors. `Markdoc.tags` and `Markdoc.nodes` don't have a string index signature, so indexing with a dynamic key in the loop fails without the explicit `Record<string, any>`. updated the comment on those lines to explain why they're needed.

**Review by matthewp — APPROVED** [review]
