### PR TITLE
fix(build): server entry regression

### LINKED ISSUE #15261: serverEntry regression
> yeah we don't use serverEntry in the new pipeline, specifically we don't catch the new adapter entry point 
 
https://github.com/withastro/astro/blob/43f497830b3634f2496788625349d4dbd9a8d023/packages/astro/src/core/build/static-build.ts#L243-L244
https://github.com/withastro/astro/blob/5ee8e970b3b12ccc3b44c3250c34cc8698b671d6/packages/astro/src/core/build/plugins/plugin-ssr.ts#L16-L20

thx @ematipico for providing this context in Discord

### Describe the Bug

serverEntry config is not taking into consideration, and emitted build output has wrong file name e.g. `index.mjs` instead of `index.js`

### What's the expected result?

serverEntry setting should be considered and emitted build output should have correct file name

### PR DESCRIPTION
**Pull request by ematipico**
## Changes

Closes #15261 

This PR fixes two bugs: 
- `serverEntry` wasn't working with the new adapter `entryType: 'self'`. We didn't catch that because we don't test against the new adapter entry point kind.
- `serverEntry` stopped working with the CF adapter, mostly due to how the CF vite plugin now works under the hood. **I don't like the fix**, as explained in the PR, but I couldn't find a better way. Even adding `entryFilesNames` in the CF adapter couldn't work. Happy to receive advice here

## Testing

I added a new testing adapter so that we can start testing against `entryType: 'self'`.

Added new tests to check things work as expected.

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/core/build/static-build.ts [hunk 1]
```diff
@@ -240,7 +240,15 @@ async function buildEnvironments(opts: StaticBuildOptions, internals: BuildInter
...
 								routes,
 							);
-						} else if (chunkInfo.facadeModuleId === RESOLVED_SSR_VIRTUAL_MODULE_ID) {
+						} else if (
+							chunkInfo.facadeModuleId === RESOLVED_SSR_VIRTUAL_MODULE_ID ||
+							// This catches the case when the adapter uses `entryType: 'self'. When doing so,
+							// the adapter must set rollupOptions.input.
+							chunkInfo.facadeModuleId === settings?.config.vite.build?.rollupOptions?.input ||
+							// NOTE: I honestly don't like this check. It's brittle and it's code smell. If CF vite plugin
+							// decides to rename their virtual module, the feature stops working.
```
Comment (matthewp) [inline packages/astro/src/core/build/static-build.ts]:
```suggestion
							// decides to rename their virtual module, `build.serverEntry` will stop working.
```

File: packages/astro/src/core/build/static-build.ts [hunk 2]
```diff
@@ -240,7 +240,15 @@ async function buildEnvironments(opts: StaticBuildOptions, internals: BuildInter
...
+							chunkInfo.facadeModuleId === '\0' + 'virtual:cloudflare/worker-entry'
```
Comment (matthewp) [inline packages/astro/src/core/build/static-build.ts]: Here's something to try that I think might get around the hard-coding here:

1. Add a configResolved() hook and check `rollupOptions.input`. Save that value somewhere in the scope.
2. Inside here I think you can check `chunkInfo.modules` which is an array of module names, if that contains the rollupOptions.input then you know that it's an entry point chunk.

**Comment by matthewp** [comment]
While you're here can you also get rid of these lines: https://github.com/withastro/astro/blob/e6c7544f33d1d642744e9c8f352e79db27beedfc/packages/astro/src/core/build/static-build.ts#L253-L258

We no longer split renderers, the manifest, and adapters into their own separate chunks.

File: packages/astro/src/core/build/static-build.ts (hunk 2 above)
Comment (ematipico) [reply packages/astro/src/core/build/static-build.ts]: I didn't use `chunkInfo.modules` because it didn't have the information we need. But `name` has a match against `rollupOptions.input`, so I went with that
