### PR TITLE
Fix no edge functions deployed to netlify

### LINKED ISSUE #6506: Deploy to Netlify SSR(edge): got `Page Not Found` and No edge functions deployed
### What version of `astro` are you using?

2.1.2

### Are you using an SSR adapter? If so, which one?

Netlify(edge)

### What package manager are you using?

npm

### What operating system are you using?

macOS 13.0

### What browser are you using?

Chrome: 111.0.5563.64

### Describe the Bug

Works fine with `astro ^1.0.0` and `@astrojs/netlify ^1.0.0` ([sarahetter/astro-netlify-edge-starter](https://github.com/sarahetter/astro-netlify-edge-starter)).

But when I upgrade deps to `2.x` ([ddiu8081/astro-netlify-edge-starter](https://github.com/ddiu8081/astro-netlify-edge-starter)), I just got a Netlify error `Page Not Found`.

ScreenShot 2023-03-10 at 23 33 26@2x

I tried to debug. When I check deploy summary on Netlify, I saw `No edge functions deployed`:

ScreenShot 2023-03-10 at 23 36 22@2x

And this is what I got when I ran the same operation on the `@astrojs/netlify ^1.0.0` version:

ScreenShot 2023-03-10 at 23 39 00@2x

#### To reproduce:

1. Bind the repo to Netlify and deploy once time.
2. View the site online.

#### Full Deploy log:

<details><summary>View</summary>
<p>

```ruby
11:13:19 PM: build-image version: 7fd17ad8d79d1952d384fb389d8e787becff0260 (focal)
11:13:19 PM: buildbot version: 7fd17ad8d79d1952d384fb389d8e787becff0260
11:13:20 PM: Fetching cached dependencies
11:13:20 PM: Starting to download cache of 131.0MB
11:13:21 PM: Finished downloading cache in 1.243s
11:13:21 PM: Starting to extract cache
11:13:22 PM: Finished extracting cache in 691ms
11:13:22 PM: Finished fetching cache in 1.995s
11:13:22 PM: Starting to prepare the repo for build
11:13:22 PM: Preparing Git Reference refs/heads/main
11:13:23 PM: Parsing package.json dependencies
11:13:24 PM: Starting build script
11:13:24 PM: Installing dependencies
11:13:24 PM: Python version set to 2.7
11:13:24 PM: Started restoring cached Node.js version
11:13:25 PM: Finished restoring cached Node.js version
11:13:25 PM: v16.19.1 is already installed.
11:13:25 PM: Now using node v16.19.1 (npm v8.19.3)
11:13:25 PM: Enabling Node.js Corepack
11:13:26 PM: Started restoring cached build plugins
11:13:26 PM: Finished restoring cached build plugins
11:13:26 PM: Attempting Ruby version 2.7.2, read from environment
11:13:26 PM: Using Ruby version 2.7.2
11:13:26 PM: Using PHP version 8.0
11:13:26 PM: Started restoring cached corepack dependencies
11:13:26 PM: Finished restoring cached corepack dependencies
11:13:26 PM: No npm workspaces detected
11:13:26 PM: Started restoring cached node modules
11:13:26 PM: Finished restoring cached node modules
11:13:27 PM: Installing npm packages using npm version 8.19.3
11:13:28 PM: up to date, audited 427 packages in 737ms
11:13:28 PM: 161 packages are looking for funding
11:13:28 PM:   run `npm fund` for details
11:13:28 PM: 1 high severity vulnerability
11:13:28 PM: To address all issues, run:
11:13:28 PM:   npm audit fix
11:13:28 PM: Run `npm audit` for details.
11:13:28 PM: npm packages installed
11:13:28 PM: Started restoring cached go cache
11:13:28 PM: Finished restoring cached go cache
11:13:28 PM: go version go1.19.7 linux/amd64
11:13:28 PM: Detected 1 framework(s)
11:13:28 PM: "astro" at version "2.1.2"
11:13:28 PM: Section completed: initializing
11:13:30 PM: ​
11:13:30 PM:   Netlify Build                                                 
11:13:30 PM: ────────────────────────────────────────────────────────────────
11:13:30 PM: ​
11:13:30 PM: ❯ Version
11:13:30 PM:   @netlify/build 29.6.4
11:13:30 PM: ​
11:13:30 PM: ❯ Flags
11:13:30 PM:   baseRelDir: true
11:13:30 PM:   buildId: 640b490aabf310000805e5a9
11:13:30 PM:   deployId: 640b490aabf310000805e5ab
11:13:30 PM: ​
11:13:30 PM: ❯ Current directory
11:13:30 PM:   /opt/build/repo
11:13:30 PM: ​
11:13:30 PM: ❯ Config file
11:13:30 PM:   /opt/build/repo/netlify.toml
11:13:30 PM: ​
11:13:30 PM: ❯ Context
11:13:30 PM:   production
11:13:30 PM: ​
11:13:30 PM:   1. build.command from netlify.toml                            
11:13:30 PM: ────────────────────────────────────────────────────────────────
11:13:30 PM: ​
11:13:30 PM: $ npm run build
11:13:30 PM: > @example/basics@0.0.1 build
11:13:30 PM: > astro build
11:13:31 PM: 03:13:31 PM [content] No content directory found. Skipping type generation.
11:13:31 PM: 03:13:31 PM [build] output target: server
11:13:31 PM: 03:13:31 PM [build] deploy adapter: @astrojs/netlify/edge-functions
11:13:31 PM: 03:13:31 PM [build] Collecting build info...
11:13:31 PM: 03:13:31 PM [build] Completed in 101ms.
11:13:31 PM: 03:13:31 PM [build] Building server entrypoints...
11:13:33 PM: 03:13:33 PM [build] Completed in 2.43s.
11:13:33 PM: 
11:13:33 PM:  building client 
11:13:34 PM: Completed in 579ms.
11:13:34 PM: 
11:13:34 PM: 
11:13:34 PM:  finalizing server assets 
11:13:34 PM: 03:13:34 PM [build] Rearranging server assets...
11:13:34 PM: 03:13:34 PM [build] Server built in 3.19s
11:13:34 PM: 03:13:34 PM [build] Complete!
11:13:34 PM: ​
11:13:34 PM: (build.command completed in 4.4s)
11:13:34 PM: ​
11:13:34 PM:   2. Edge Functions bundling                                    
11:13:34 PM: ────────────────────────────────────────────────────────────────
11:13:34 PM: ​
11:13:35 PM: ​
11:13:35 PM: (Edge Functions bundling completed in 548ms)
11:13:35 PM: ​
11:13:35 PM:   3. Deploy site                                                
11:13:35 PM: ────────────────────────────────────────────────────────────────
11:13:35 PM: ​
11:13:35 PM: Starting post processing
11:13:35 PM: Starting to deploy site from 'dist'
11:13:35 PM: Post processing - HTML
11:13:35 PM: Calculating files to upload
11:13:35 PM: 0 new files to upload
11:13:35 PM: 0 new functions to upload
11:13:35 PM: Section completed: deploying
11:13:35 PM: Post processing - header rules
11:13:35 PM: Site deploy was successfully initiated
11:13:35 PM: ​
11:13:35 PM: (Deploy site completed in 68ms)
11:13:35 PM: Post processing - redirect rules
11:13:35 PM: ​
11:13:35 PM:   Netlify Build Complete                                        
11:13:35 PM: ────────────────────────────────────────────────────────────────
11:13:35 PM: ​
11:13:35 PM: (Netlify Build completed in 5.1s)
11:13:35 PM: Caching artifacts
11:13:35 PM: Post processing done
11:13:35 PM: Started saving node modules
11:13:35 PM: Finished saving node modules
11:13:35 PM: Started saving build plugins
11:13:35 PM: Finished saving build plugins
11:13:35 PM: Section completed: postprocessing
11:13:35 PM: Started saving corepack cache
11:13:35 PM: Finished saving corepack cache
11:13:35 PM: Started saving pip cache
11:13:35 PM: Finished saving pip cache
11:13:35 PM: Started saving emacs cask dependencies
11:13:35 PM: Finished saving emacs cask dependencies
11:13:35 PM: Started saving maven dependencies
11:13:35 PM: Finished saving maven dependencies
11:13:35 PM: Started saving boot dependencies
11:13:35 PM: Finished saving boot dependencies
11:13:35 PM: Started saving rust rustup cache
11:13:35 PM: Finished saving rust rustup cache
11:13:35 PM: Started saving go dependencies
11:13:35 PM: Finished saving go dependencies
11:13:35 PM: Build script success
11:13:35 PM: Section completed: building
11:13:36 PM: Uploading Cache of size 116.1MB
11:13:36 PM: Site is live ✨
11:13:37 PM: Section completed: cleanup
11:13:37 PM: Finished processing build request in 17.122s
```

</p>
</details>

### Link to Minimal Reproducible Example

https://github.com/ddiu8081/astro-netlify-edge-starter

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by andremralves**
## Changes

fixes #6506

- This commit changes the generated edge function file from `entry.mjs`
 back to `entry.js`
- Apparently Netlify doesn't identify edge functions when the file extension is `.mjs`
- The issue started in version 2.1.3 when the file extension was changed.
- The extension was changed because of this issue #6299 that was affecting Vercel and maybe could affect Netlify.
- But I tested version 2.1.2 of `@astrojs/netlify` using `type: "commonjs"` inside `package.json` and found no errors.

## Testing

I just changed one test that was expecting `.mjs`.

## Docs

n/a

### CODE REVIEW

File: packages/integrations/netlify/src/integration-edge-functions.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export function netlifyEdgeFunctions({ dist }: NetlifyEdgeFunctionsOptions = {})
 					build: {
 						client: outDir,
 						server: new URL('./.netlify/edge-functions/', config.root),
-						serverEntry: 'entry.mjs',
+						serverEntry: 'entry.js',
```
Comment (bluwy) [inline packages/integrations/netlify/src/integration-edge-functions.ts:125]:
```suggestion
						// Netlify expects .js and will always interpret as ESM
						serverEntry: 'entry.js',
```

Let's add a comment here so we don't regress this again.

**Review by bluwy — APPROVED** [review]
Thanks for catching this! (And sorry for causing the regression)

File: packages/integrations/netlify/src/integration-edge-functions.ts (hunk 1 above)
Comment (andremralves) [reply packages/integrations/netlify/src/integration-edge-functions.ts:126]: Good idea!
