### PR TITLE
fix(vercel): handle SVG images correctly in build image service

### LINKED ISSUE #13664: Vercel Adapter + imageService / imagesConfig breaking .SVG since Astro 5.7
### Astro Info

```block
Astro                    v5.7.4
Node                     v22.14.0
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  @astrojs/vercel
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

SVG's do not render via markdown syntax for images in .md / .mdx files with `astro 5.7.4` +  `@astrojs/vercel 8.1.3` with `imageService` enabled. 

See here: 
https://astro-5-7-4-vercel-images.vercel.app/

Image

```markdown
![Astro Logo](../assets/images/astro-logo-dark.svg)
```

```javascript
adapter: vercel({
  imageService: true,
  imagesConfig: {
    domains: [],
    sizes: [320, 640, 1280],
    formats: ["image/avif", "image/webp"],
  },
}),
```

Outputting like this:
```html
<img src="/_vercel/image?url=%28...args%29+%3D%3E+%7B%0A++++if+%28%21validateArgs%28args%29%29+%7B%0A++++++throw+new+AstroError%28%7B%0A++++++++...InvalidComponentArgs%2C%0A++++++++message%3A+InvalidComponentArgs.message%28name%29%0A++++++%7D%29%3B%0A++++%7D%0A++++return+cb%28...args%29%3B%0A++%7D&amp;w=320&amp;q=100" alt="Astro Logo" inputtedwidth="460" width="460" height="160" loading="lazy" decoding="async">
```

No problems with files that are not `.svg`, and also If I disable `imageService` / `imagesConfig` then `.svg` works again.

As mentioned by @psd-coder:

> Looks like they forgot to call function somewhere and it was converted into string :slightly_smiling_face:

```
decodeURIComponent('%28...args%29+%3D>+%7B%0A++%5B…%5D+++return+cb%28...args%29%3B%0A++%7D')

=>

'(...args)+=>+{\n++[…]+++return+cb(...args);\n++}'
```

### What's the expected result?

Expected result is a .SVG image that renders. Here is the result before adding `imageService` / `imagesConfig`:

```html
<img src="/_astro/astro-logo-dark.DIg-SQxu_1DMGgf.svg" alt="Astro Logo" width="460" height="160" loading="lazy" decoding="async">
```

https://astro-5-7-4-vercel-images-66ap6ftdi-joe-hs-projects.vercel.app/

Image

### Link to Minimal Reproducible Example

https://github.com/moonclavedev/astro-5.7.4-vercel-images/

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by moonclavedev**
Updates the Vercel build image service to correctly handle ESM-imported SVG images by returning the original source path, preventing incorrect URL generation. Also aligns the isESMImportedImage utility with the core Astro implementation.

Fixes #13664

## Changes

-   Updated `isESMImportedImage` in `packages/integrations/vercel/src/image/shared.ts` to align with the core Astro implementation, correctly identifying SVGs imported as functions.
-   Modified `getURL` in `packages/integrations/vercel/src/image/build-service.ts` to return the original `src` path for SVG images, bypassing the Vercel image processing endpoint for them.

## Testing

This change was tested manually by reproducing the scenario described in issue #13664:
1.  Created an Astro project using the Vercel adapter with `imageService: true`.
2.  Included an SVG image in a markdown file using standard markdown syntax (`Alt text`).
3.  Observed that before the change, the generated `` tag had a corrupted `src` attribute pointing to `/_vercel/image?url=(stringified function)...`.
4.  Applied the changes in this PR.
5.  Observed that after the change, the generated `` tag correctly points directly to the processed SVG file path (e.g., `/_astro/image.hash.svg`).

No automated tests were added as this addresses a specific interaction between markdown processing, ESM image imports, and the Vercel build service logic. Existing integration tests for Vercel image handling should continue to pass.

## Docs

No documentation changes are needed. This fix addresses an internal bug in the Vercel integration's image service logic and does not change any user-facing APIs or behavior (other than correcting the bug).

### CODE REVIEW

**Review by ascorbic — COMMENTED** [review]
Thanks. Could you add a test for this. There are existing image tests in the vercel package where it could be added.

File: packages/integrations/vercel/src/image/shared.ts [hunk 1]
```diff
@@ -10,7 +10,7 @@ export function getDefaultImageConfig(astroImageConfig: AstroConfig['image']): V
 }
 
 export function isESMImportedImage(src: ImageMetadata | string): src is ImageMetadata {
```
Comment (florian-lefebvre) [inline packages/integrations/vercel/src/image/shared.ts:12]: This should be removed in favor of `isESMImportedImage` exported from `astro/assets/utils`

**Review by florian-lefebvre — COMMENTED** [review]
How can we help you?

**Review by florian-lefebvre — APPROVED** [review]
