### PR TITLE
Fix: correctly transform `import.meta.env.*` in MDX

### LINKED ISSUE #4801: Code blocks in MDX render environmental variables
### What version of `astro` are you using?

1.1.1

### Are you using an SSR adapter? If so, which one?

Deno Deploy

### What package manager are you using?

pnpm

### What operating system are you using?

macOS 12

### Describe the Bug

I have some `import.meta.env` in MDX's code blocks and don't want them to be converted. (Just display import.meta.env.XXXXX)

In dev environment, the output is doing well.

However, `import.meta.env.SITE` becomes `undefined` (or the url I defined in `astro.config.mjs`);
`import.meta.env.PUBLIC_HOSTNAME` becomes `(Object.assign(import.meta.env,{HOSTNAME:process.env.HOSTNAME,})).PUBLIC_HOSTNAME` in production. 

### Link to Minimal Reproducible Example

https://codesandbox.io/s/vibrant-chandrasekhar-gbicwd?file=/src/pages/article1.mdx

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #4801 
- Avoid transforming `import.meta.env` in MDX plain text and frontmatter.
- Correctly transform `import.meta.env` in `{JSX expressions}`, variable `export`s, and HTML attributes.

## Testing

Test `import.meta.env.*` processed in expressions only, and _not_ transformed in plain text.

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
clever solution 👍

**Review by matthewp — APPROVED** [review]

**Review by delucis — APPROVED** [review]
Not `env`ious that you had to deal with this one again!

**Comment by bholmesdev** [comment]
Bumping back to draft. Breaking existing `import.meta.env` support in JSX expressions doesn't feel right to me. Definitely want things like this to work:

```js
export const canonical = import.meta.env.SITE + '/path'
```

File: packages/integrations/mdx/src/plugins.ts [hunk 1]
```diff
@@ -0,0 +1,273 @@
...
+						type: 'Literal',
+						value: importMetaEnv[envVarName],
+						raw: JSON.stringify(importMetaEnv[envVarName]),
+					};
+					Object.assign(node, envVarLiteral);
+				}
+			}
+		});
+	};
+}
```
Comment (bholmesdev) [inline packages/integrations/mdx/src/plugins.ts:43]: I renamed `data-astro-utils.ts` to `plugins.ts`, so you can safely ignore the rest of the file! This function is the new part.

**Review by matthewp — APPROVED** [review]
lgtm
