### PR TITLE
fix(cloudflare): pass waitUntil to cache providers

### LINKED ISSUE #16145: `waitUntil` not available in `onRequest` context in a `CacheProvider`
### Astro Info

```block
Astro                    v6.1.1
Vite                     v7.3.1
Node                     v24.14.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/cloudflare (v13.1.4)
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

`experimental.cache`: `waitUntil` missing from `CacheProvider.onRequest` context when using the Cloudflare adapter.

The [docs](https://docs.astro.build/en/reference/experimental-flags/route-caching/#onrequest) define `onRequest` context as:

```ts
context: { request: Request; url: URL; waitUntil?: (promise: Promise<unknown>) => void }
```

But `waitUntil` is missing in both the type and at runtime when using the Cloudflare adapter.

**`dist/core/cache/types.d.ts`** — `waitUntil` is not in the type:
```ts
onRequest?(context: {
  request: Request;
  url: URL;
}, next: MiddlewareNext): Promise<Response>;
```

**Runtime** — `typeof context.waitUntil` is `"undefined"` inside a custom provider's `onRequest`.

Without it, cache writes in Cloudflare Workers must be `await`ed before the response is sent, adding latency on every cache miss. The correct pattern — `context.waitUntil(cache.put(...))` — is currently broken.

### What's the expected result?

`context.waitUntil` should be available, matching the documented signature, so that cache writes can be handed off as background work.

### Link to Minimal Reproducible Example

https://github.com/edmelly/astro-playground

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by gllmt**
Closes #16145

## Changes

- Add optional `waitUntil` to the `CacheProvider.onRequest()` context type.
- Thread `waitUntil` through `BaseApp.render()` so adapters can pass it to runtime cache providers.
- Forward Cloudflare `ExecutionContext.waitUntil` from the adapter handler into `app.render()`.
- Add a regression test covering a custom cache provider on Cloudflare.
- Added a changeset for `astro` and `@astrojs/cloudflare`.

## Testing

- `pnpm run build`
- `node --test packages/integrations/cloudflare/test/cache-provider-wait-until.test.js`

## Docs

- No docs update added. This fixes the implementation to match the existing documented `CacheProvider.onRequest()` signature.

### CODE REVIEW

**Comment by edmelly-pg** [comment]
Thanks for this - the same fix is relevant to the other hosting integrations (Netlify + Vercel), I think (both support `waitUntil`):

https://github.com/gllmt/astro/blob/main/packages/integrations/netlify/src/ssr-function.ts#L36
https://github.com/gllmt/astro/blob/main/packages/integrations/vercel/src/serverless/entrypoint.ts#L58

**Comment by gllmt** [comment]
Thanks,  I agree the same plumbing may also apply to Netlify and Vercel.

I scoped this PR to #16145 since that issue is currently labeled `pkg: cloudflare`, but I’m happy to follow up for the other adapters as well if maintainers would prefer to cover them here.

**Comment by edmelly-pg** [comment]
Any chance of a maintainer reviewing/progressing this soon? Would be great to get this fix in. Thanks!

File: packages/integrations/cloudflare/src/utils/handler.ts [hunk 1]
```diff
@@ -122,6 +122,7 @@ export async function handle(
 	const response = await app.render(request, {
 		routeData,
 		locals,
+		waitUntil: context.waitUntil.bind(context),
```
Comment (ematipico) [inline packages/integrations/cloudflare/src/utils/handler.ts]: I believe this might be correct, but it doesn't hold against the types of `waitUntil`. You typed `waitUntil` with a small function that doesn't type the `this`.

**Review by ematipico — CHANGES_REQUESTED** [review]
The code looks good, but I'm afraid we can't merge it as is. We're adding a new API, which means:
- changesets need to be `minor` (at least the astro one)
- the changeset needs to add a more comprehensive description https://contribute.docs.astro.build/docs-for-code-changes/changesets/
-  we need **you** to send a PR to the docs repository `withastro/docs` and update this page with the new option https://docs.astro.build/en/reference/modules/astro-app/#renderoptions

File: packages/integrations/cloudflare/src/utils/handler.ts (hunk 1 above)
Comment (gllmt) [reply packages/integrations/cloudflare/src/utils/handler.ts]: Thanks, that makes sense.

I initially treated this as plumbing to match the already-documented `CacheProvider.onRequest()` context, but exposing `waitUntil` through `app.render()` / `RenderOptions` does make it a public API surface.

I’ll update the `waitUntil` typing, promote the `astro` changeset to `minor` with a fuller description, and open a docs PR against `withastro/docs` for the `astro-app` `RenderOptions` page, then link it back here.

I’ll keep the implementation scope focused on Cloudflare in this PR and can follow up separately for the other adapters if that’s preferred.

**Comment by gllmt** [comment]
Addressed the requested follow-up changes:

- updated the `waitUntil` typing so the public callback contract is explicit and the Cloudflare adapter passes a bound, typed function
- promoted the `astro` changeset to `minor` and expanded the description
- opened the docs PR for `RenderOptions.waitUntil`: withastro/docs#13744

Re-ran:
- `pnpm run build`
- `node --test packages/integrations/cloudflare/test/cache-provider-wait-until.test.js`

Docs verification:
- `pnpm check` in `withastro/docs`

I kept the implementation scope focused on Cloudflare here; happy to follow up separately for the other adapters if that’s preferred.

File: packages/integrations/cloudflare/src/utils/handler.ts (hunk 1 above)
Comment (gllmt) [reply packages/integrations/cloudflare/src/utils/handler.ts]: Updated this so the public `waitUntil` contract is a dedicated bound callback type (`this: void`), and the Cloudflare adapter now passes a bound function typed against `RenderOptions['waitUntil']` instead of leaving it as an ad-hoc callback shape.

File: .changeset/fair-walls-raise.md [hunk 2]
```diff
@@ -0,0 +1,11 @@
+astro: minor
```
Comment (ArmandPhilippot) [inline .changeset/fair-walls-raise.md:2]: The opening fence is missing:
```suggestion
---
astro: minor
```

File: .changeset/fair-walls-raise.md [hunk 3]
```diff
@@ -0,0 +1,12 @@
+---
+astro: minor
+'@astrojs/cloudflare': patch
```
Comment (ematipico) [inline .changeset/fair-walls-raise.md]:
```suggestion
'@astrojs/cloudflare': minor
```

Even though it's a "fix", we need to bump it because this version will rely on a new minor version of Astro

**Review by ematipico — APPROVED** [review]
That's great, thank you @gllmt ! The PR is good now, we will release it once we're ready to ship a new minor of Astro 🫡

**Comment by ematipico** [comment]
@gllmt need to fix linting https://github.com/withastro/astro/actions/runs/24666337658/job/72125435587?pr=16187

**Comment by gllmt** [comment]
Fixed the lint failure.

Root cause: after the Cloudflare test suite was migrated to TypeScript on this branch, this new test was still left as `cache-provider-wait-until.test.js` and still imported `./_test-utils.js`, which no longer exists. That is what `knip` was flagging in CI.

Updated it to `cache-provider-wait-until.test.ts`, switched the import to `./test-utils.ts`, and aligned the fixture/preview server typing with the rest of the Cloudflare tests.

Re-ran locally:
- `pnpm exec knip`
- `pnpm run lint:ci`
- `node --test packages/integrations/cloudflare/test/cache-provider-wait-until.test.ts`

File: .changeset/fair-walls-raise.md [hunk 4]
```diff
@@ -0,0 +1,12 @@
+---
+astro: minor
+'@astrojs/cloudflare': minor
+---
+
+Adds a `waitUntil` option to `app.render()` / `RenderOptions` so adapters can forward
+runtime background-task hooks to Astro.
```
Comment (ArmandPhilippot) [inline .changeset/fair-walls-raise.md]: nit: I don't think we need the slash here. This reads better without it and `RenderOptions` alone sounds more accurate to me. Someone could think this is a new argument for `app.render()`.

Also, I'm not a native speaker but I think this should be "so that", not just "so"?
```suggestion
Adds a `waitUntil` option to the `RenderOptions` so that adapters can forward runtime background-task hooks to Astro.
```

**Review by ArmandPhilippot — APPROVED** [review]
Just a nit for the changeset, but otherwise this LGTM! Thank you!

**Comment by not-matthias** [comment]
> ## Unable to generate the flame graphs
> The performance report has correctly been generated, but there was an internal error while generating the flame graphs for this run. We're working on fixing the issue. Feel free to contact us on Discord or at [support@codspeed.io](mailto:support@codspeed.io) if the issue persists.

Hey, we're aware of this issue. I'm currently investigating and working on a fix. I'll let you know once it's been fixed

EDIT: We've fixed the issue on our side

**Review by yanthomasdev — APPROVED** [review]
LGTM! Thanks!
