### PR TITLE
fix: explicitly set dev mode for data store

### LINKED ISSUE #12652: Empty content collections with programmatic API since 5.0.3
### Astro Info

```block
Astro                    v5.0.3
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Spotted in a similar scenario in an E2E test in the Starlight repo, it looks like using the Astro programmatic API to build a project using content collections, serving it and then starting a dev server leads to different results:

- The served production build works as expected.
- The dev server logs that the collection does not exist or is empty.

In the linked repro, the following script is immediately run:

```js
import { dev, build, preview } from 'astro';

const root = './';

await build({ logLevel: 'debug', root });
const prodServer = await preview({ logLevel: 'debug', root });

const devServer = await dev({ root });
```

The preview panel will work as expected as it's showing the production version built first and served on the port `4321`.
Manually changing the URL to switch to the dev server (there is a `4321` in the URL that can be changed to `4322`) will show a 404 error and log the mentioned error.

Note that this works fine when using Astro v5.0.2, maybe related to https://github.com/withastro/astro/pull/12640 but only a guess.

### What's the expected result?

The expected result is the same behavior in both cases.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gaqwbs?file=repro.js&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

The content layer data store is created in a different location according to whether it is running in dev or build, so that it is either cachable or watchable by the fs watcher. These are mutually exclusive for Reasons. 
This needs to be the same locaiton for both writing (during sync) and reading (during runtime). Unfortunately knowing which of these we're running is not as simple as it could be, and there have been some bugs that have emerged due to conflicts. 

We'd mostly fixed these cases in #12640, but it missed the case where dev was run programatically with NODE_ENV set to something other than development (mostly in a test environment). 

Rather than playing whackamole for all of these scenarios, this PR changes the approach so that it never uses NODE_ENV, and always explicitly sets it. Either this is done via the command used (build and sync use production, dev uses development) or at runtime uses Vite's env.command (build uses production, serve uses development). This involved some refactoring around how files are handled by data stores (which was overdue, because it was needlessly complex as it was created when there were different requirements)

Fixes #12652

## Testing

Added some tests to the astro mode suite, which helpfully messes around with these options.

### CODE REVIEW

**Comment by ascorbic** [comment]
!preview data-store-location

**Comment by delucis** [comment]
I tested the experimental release for this PR against Starlight’s end-to-end tests (which fail with Astro 5.1.x currently) and it seems to resolve things for us: https://github.com/withastro/starlight/pull/2776

File: packages/astro/src/core/sync/index.ts [hunk 1]
```diff
@@ -127,15 +130,14 @@ export async function syncInternal({
 		settings.timer.start('Sync content layer');
 		let store: MutableDataStore | undefined;
 		try {
-			const dataStoreFile = getDataStoreFile(settings);
-			if (existsSync(dataStoreFile)) {
-				store = await MutableDataStore.fromFile(dataStoreFile);
-			}
+			const dataStoreFile = getDataStoreFile(settings, isDev);
+			store = await MutableDataStore.fromFile(dataStoreFile);
```
Comment (ematipico) [inline packages/astro/src/core/sync/index.ts:134]: `existSync` is now marked unused

File: packages/astro/test/astro-mode.test.js [hunk 2]
```diff
@@ -37,10 +48,15 @@ describe('--mode', () => {
...
 		});
+
+		it('writes data store file in the correct location', async () => {
+			assert.ok(existsSync(prodDataStoreFile));
+		})
 	});
 
 	describe('build --mode testing --devOutput', () => {
 		before(async () => {
+			await deleteDataStoreFiles();
```
Comment (ematipico) [inline packages/astro/test/astro-mode.test.js:59]: Any particular reason why we use this in `before` and not in `after`?

**Review by ematipico — APPROVED** [review]

File: packages/astro/src/core/sync/index.ts [hunk 3]
```diff
@@ -116,8 +118,9 @@ export async function syncInternal({
 	force,
 	manifest,
 }: SyncOptions): Promise<void> {
+	const isDev = mode === 'development';
```
Comment (bluwy) [inline packages/astro/src/core/sync/index.ts:121]: Double checking if this is correct. In Astro, you can also technically to `astro build --devOutput` to get the development build. Do we want `isDev` `true` in that case?

The `mode` here is typed as `string` because end-users can name it anything in practice. e.g. `astro build --mode staging` or `astro build --mode staging --devOutput`.

Maybe passing the `runtimeMode` from `build()` would be more accurate for `isDev`.

File: packages/astro/test/fixtures/content-layer/src/pages/missing.astro [hunk 4]
```diff
@@ -1,7 +1,7 @@
 ---
 import { getEntry, render } from "astro:content"
 // Skipping the broken page in production so the build doesn't fail
-if(import.meta.env.PROD) {
+if(import.meta.env.PROD || import.meta.env.MODE === "production") {
```
Comment (bluwy) [inline packages/astro/test/fixtures/content-layer/src/pages/missing.astro:4]: Maybe this change isn't required anymore if we change `isDev` to base on `runtimeMode` from `build()`

Comment (bluwy) [reply packages/astro/test/fixtures/content-layer/src/pages/missing.astro:4]: `runtimeMode` is derived from `devOutput`, and `devOutput` controls this code that mutates `process.env.NODE_ENV` as either `development` or `production`.

Vite and Vite plugins rely on `process.env.NODE_ENV` to check if they're in production. e.g. `viteResolvedConfig.isProduction` is set based on `process.env.NODE_ENV === 'production'` (same for `import.meta.env.PROD`.

So in a way they're related, but `runtimeMode` itself is not accessible from Vite plugins as that's an Astro concept itself.

File: packages/astro/src/core/sync/index.ts (hunk 3 above)
Comment (ascorbic) [reply packages/astro/src/core/sync/index.ts:121]: What we're actually wanting to know is if they're running `astro dev`. It doesn't matter what the build output is: it's the only thing we care about is whether we need the chokidar watcher to see the data store.

File: packages/astro/test/fixtures/content-layer/src/pages/missing.astro (hunk 4 above)
Comment (ascorbic) [reply packages/astro/test/fixtures/content-layer/src/pages/missing.astro:4]: The thing I care about is `env.command`, so I need a way to get a consistent value for that in both contexts. I've just pushed a change to use the actual command, instead of mode etc

File: packages/astro/src/core/sync/index.ts (hunk 3 above)
Comment (bluwy) [reply packages/astro/src/core/sync/index.ts]: I think what you committed is good then if that's the case 👍
