### PR TITLE
Fix vue resetting state when using view transition persistence

### LINKED ISSUE #11854: Vue component state persistence does not work
### Astro Info

```block
Astro                    v4.14.5
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/vue
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using a Vue component with ViewTransitions, the state is not persisted as expected. A warning about a hydration mismatch is also present in the console.

It works when using `transition:persist-props`.

### What's the expected result?

When incrementing the buttons in the example and then clicking "navigate", the Vue and React example should keep the counts, but the Vue component is reset.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-jhuzfh-jxxerz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by johannesspohr**
## Changes

This change keeps track of all initialized vue islands in order to update the existing instance rather than creating a new app, which resets the state.

I'm by no means a Vue expert and there might be more elegant ways to achieve this. I tried to follow the approach of the React implementation (using a `WeakMap`), however, patching the props is a bit more difficult than in in React. I'm happy to improve it in case anybody has a better idea.

This fixes #11854,

## Testing

E2E test was added.

## Docs

As this is only a fix, I don't think documentation is needed. However, it could be pointed out that state persistence is currently broken for all frameworks except for React and Vue if I'm not mistaken.

### CODE REVIEW

File: packages/integrations/vue/client.js [hunk 1]
```diff
@@ -15,21 +18,35 @@ export default (element) =>
...
+					return content;
+				},
+			});
+			await setup(appInstance.app);
+			appInstance.app.mount(element, isHydrate);
+			appMap.set(element, appInstance);
+		} else {
+			appInstance.props = props;
+			appInstance.slots = slots;
+			appInstance.app._instance.proxy.$forceUpdate();
```
Comment (matthewp) [inline packages/integrations/vue/client.js:48]: is this how you're supposed to trigger an update? If this is private code we shouldn't do it, and try to find another way.

Comment (johannesspohr) [reply packages/integrations/vue/client.js]: I checked again and found a better way to call the `$forceUpdate` method (which is [documented](https://vuejs.org/api/component-instance.html#forceupdate)), so I don't think there is any private implementation details used any more.

**Review by matthewp — APPROVED** [review]
