### PR TITLE
Fix multiple `create-astro` registry issues

### LINKED ISSUE #7362: create astro error
### What version of `astro` are you using?

create-astro@3.1.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

```
$ pnpm create astro
.../Library/pnpm/store/v3/tmp/dlx-42001  | +159 ++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/magicdawn/Library/pnpm/store/v3
  Virtual store is at:             ../../Library/pnpm/store/v3/tmp/dlx-42001/node_modules/.pnpm
.../Library/pnpm/store/v3/tmp/dlx-42001  | Progress: resolved 159, reused 159, downloaded 0, added 159, done
undefined:1
<h1>404 Not Found</h1>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (file:///Users/magicdawn/Library/pnpm/store/v3/tmp/dlx-42001/node_modules/.pnpm/create-astro@3.1.7/node_modules/create-astro/dist/index.js:284:32)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.14.2
 ERROR  Command failed with exit code 1: create-astro

```

- create-astro@3.1.7/node_modules/create-astro/dist/index.js:284:32
- https://unpkg.com/browse/create-astro@3.1.7/dist/index.js

image

```
$ pnpm config get registry
https://registry.npmmirror.com/

$ curl -I `pnpm config get registry`/astro/latest
HTTP/1.1 200 Connection established

HTTP/2 404
server: Tengine
content-type: text/html; charset=utf-8
content-length: 22
strict-transport-security: max-age=5184000
date: Sun, 11 Jun 2023 01:37:57 GMT
vary: Origin
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
x-readtime: 0.804
ali-swift-global-savetime: 1686447477
via: cache44.l2cn3069[24,24,404-1280,M], cache42.l2cn3069[39,0], kunlun2.cn5595[59,58,404-1280,M], kunlun10.cn5595[60,0]
x-cache: MISS TCP_MISS dirn:-2:-2
x-swift-savetime: Sun, 11 Jun 2023 01:37:57 GMT
x-swift-cachetime: 1
x-swift-error: orig response 4XX error
timing-allow-origin: *
eagleid: 01c6049e16864474770991332e

$ curl -I `pnpm config get registry`astro/latest
HTTP/1.1 200 Connection established

HTTP/2 200
server: Tengine
content-type: application/json; charset=utf-8
content-length: 8239
strict-transport-security: max-age=5184000
date: Sun, 11 Jun 2023 01:37:40 GMT
vary: Origin, Accept, Accept-Encoding
request-id: 8dccb0f0-07f8-11ee-9757-8fb30df599d3
cache-control: public, max-age=300
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
x-readtime: 42.56
via: cn5595.l1, kunlun15.cn5595, l2cn3069.l2, cache11.l2cn3069, npmmirror-x86-20220823002, cache11.l2cn3069[68,67,200-0,M], cache56.l2cn3069[69,0], kunlun15.cn5595[0,0,200-0,H], kunlun20.cn5595[1,0]
ali-swift-global-savetime: 1686447460
age: 21
x-cache: HIT TCP_MEM_HIT dirn:10:1135070938
x-swift-savetime: Sun, 11 Jun 2023 01:37:40 GMT
x-swift-cachetime: 300
timing-allow-origin: *
eagleid: 01c604a816864474811333530e
```

since this code uses `registry + /astro/latest`, a trim last `/` action is need for registry.
can not rely on registry to support `<registry>//:package-name` route.

I have edited the code, but PR need test, so I turned to Issues.
https://github.com/withastro/astro/compare/main...magicdawn:astro:patch-1

### Link to Minimal Reproducible Example

none

### Participation

- [ ] I am willing to submit a pull request for this issue.

### LINKED ISSUE #7480: npm create astro@latest doesn't work
### What version of `astro` are you using?

2.7.0

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

windows

### What browser are you using?

chrome

### Describe the Bug

when I try installing Astro using this command: `npm create astro@latest`
this error appears:
`TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new NodeError (node:internal/errors:372:5)
    at new ClientRequest (node:_http_client:164:11)
    at request (node:https:353:10)
    at get (node:https:387:15)
    at file:///C:/Users/username/AppData/Local/npm-cache/_npx/abdb4b598af046c4/node_modules/create-astro/dist/index.js:259:3
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_PROTOCOL'
}`

### What's the expected result?

Astro should start installing

### Link to Minimal Reproducible Example

no link

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by jc1144096387**
## Changes

- Fixes #7480 (supports http), fixes #7362 (follows redirects + handles trailing `/`)
- In the method "getVersion", before sending request, if the registry ends with "/", trim it.
When I use the registry "https://registry.npmmirror.com/", create-astro will be failed because the request of "getVersion" gets  the 404 error and the error is not be caught.
create-astro-error

## Testing

I add the code and link the local package to global by using ``` pnpm link -g ```, and then I run ```create-astro``` again. I am successfully into creating app.
image
 

## Docs

Bug fixes only

### CODE REVIEW

File: packages/create-astro/src/messages.ts [hunk 1]
```diff
@@ -77,7 +77,11 @@ let v: string;
 export const getVersion = () =>
 	new Promise<string>(async (resolve) => {
 		if (v) return resolve(v);
-		const registry = await getRegistry();
+		let registry = await getRegistry();
+		// if the registry ends with '/', trim it.
+		if (registry.lastIndexOf('/') === registry.length - 1) {
+			registry = registry.substring(0, registry.length - 1);
```
Comment (ematipico) [inline packages/create-astro/src/messages.ts:83]: nit: You could use [`trimEnd`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trimEnd)

**Review by ematipico — APPROVED** [review]

File: .changeset/old-seahorses-fold.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'create-astro': major
```
Comment (natemoo-re) [inline .changeset/old-seahorses-fold.md:2]:
```suggestion
'create-astro': patch
```

File: .changeset/old-seahorses-fold.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
...
+---
+
+fix: getVersion Error when registry ends with '/'
```
Comment (natemoo-re) [inline .changeset/old-seahorses-fold.md:5]:
```suggestion
Update registry logic to handle registry URLs ending with '/'
```

File: packages/create-astro/src/messages.ts (hunk 1 above)
Comment (natemoo-re) [reply packages/create-astro/src/messages.ts]: Thank you very much for your help on this issue! I updated the logic to handle whitespace and trailing `/` in a centralized place.

**Review by natemoo-re — APPROVED** [review]
Thanks for kicking this off, congrats on your first PR!
