### PR TITLE
Fix `renderToFinalDestination` handling

### LINKED ISSUE #8434: I updated from v2 to V3  and now I get error when i do npm run dev
### Astro Info

```block
Astro                    v3.0.9
Node                     v18.17.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/react
                         @astrojs/tailwind
```

### If this issue only occurs in one browser, which browser is a problem?

chrome

### Describe the Bug

I updated from v2 to V3 and now I get this error when I use npm run dev. Now using node v18.17.1 (npm v10.0.0) Deleted and node modules folder and package-lock.json and used npm install while switching between versions 20.5.1, 18.14.1, 18.17.1 and still got the same error.
astro2

### What's the expected result?

I expect that the website shows up on localhost:4321

### Link to Minimal Reproducible Example

--

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #8434
- Properly handles children that return `undefined`
- Seems to happen with Markdown content mainly? Not sure why.

## Testing

Manually tested with user reproduction

## Docs

Bug fix only

### CODE REVIEW

File: packages/astro/src/runtime/server/render/any.ts [hunk 1]
```diff
@@ -18,6 +18,7 @@ export async function renderChild(destination: RenderDestination, child: any) {
 			});
 		});
 		for (const childRender of childRenders) {
+			if (!childRender) continue;
```
Comment (natemoo-re) [inline packages/astro/src/runtime/server/render/any.ts:21]: We don't have to wait for @bluwy to weigh in, but it seems like some of the `childRender` objects are `undefined` which is kind of unexpected. Not sure I fully grok why that's happening? Is it Markdown-specific?

**Review by matthewp — APPROVED** [review]

**Review by lilnasy — APPROVED** [review]
Barely familiar with this code path, but lgtm.
