### PR TITLE
Preserve all error stack lines

### LINKED ISSUE #4357: Issue using React Component - Cannot use import statement outside a module
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

Local

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I'm trying to pull in a specific npm package of a react component found here: https://www.npmjs.com/package/@rjsf/semantic-ui, for some reason I'm unable to use the component. I get this errror:

```
Cannot use import statement outside a module
    at Object.compileFunction (https://github-e2ezwj.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:341448)
    at wrapSafe (https://github-e2ezwj.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:218347)
    at Module._compile (https://github-e2ezwj.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:218715)
    at Module._extensions..js (https://github-e2ezwj.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:219743)
    at Module.load (https://github-e2ezwj.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:217769)
    at Module._load (https://github-e2ezwj.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:215340
```

Just thought i'd document this, obviously compatibility with every module is not easy but perhaps others will come across this too. Not sure why this is happening.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-e2ezwj?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Fix #4357

Preserve all error stack lines to avoid hiding important information. I'm not sure if this may expose more dirty messages, but we could monitor along as we go.

Before:
Screenshot 2022-08-17 at 5 06 47 PM

After:
Screenshot 2022-08-17 at 5 07 34 PM

Note: I also tried parsing the stack to split out the stack and frame, but it doesn't work with Vite's overlay as it expects frames to start with a `|` pipe.

## Testing

Tested manually with the repro at #4357

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/core/messages.ts [hunk 1]
```diff
@@ -235,10 +235,10 @@ export function formatErrorMessage(err: ErrorWithMetadata, args: string[] = []):
 		args.push(red(padMultilineString(err.frame, 4)));
 	}
 	if (args.length === 1 && err.stack) {
-		args.push(dim(cleanErrorStack(err.stack)));
+		args.push(dim(err.stack));
 	} else if (err.stack) {
 		args.push(`  ${bold('Stacktrace:')}`);
-		args.push(dim(cleanErrorStack(err.stack)));
+		args.push(dim(err.stack));
```
Comment (bluwy) [inline packages/astro/src/core/messages.ts:241]: `cleanErrorStack` is removed as it should already be cleaned by `collectErrorMetadata`.

**Review by natemoo-re — APPROVED** [review]
