### PR TITLE
fix: EventEmitter memory leak when serving static pages from Node.js middleware

### LINKED ISSUE #15730: Node.js middleware: 'Possible EventEmitter memory leak' warning when serving static pages / files
### Astro Info

```block
Astro                    v6.0.0-beta.17
Node                     v22.21.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/node
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using the latest (beta) version of Astro and using the Node.js adapter as middleware, I'm seeing an EventEmitter memory leak warning from Node.js when serving static pages and files.

For a minimal example, I setup a Fastify server [as shown in the docs](https://docs.astro.build/en/guides/integrations-guide/node/#middleware), and created a static page. Simply refreshing the static page a couple times triggers the memory leak warning.

The full log is:
```
(node:12345) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 
11 close listeners added to [Socket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
```

I believe the problem stems from the following code. The `createRequest` function creates some socket listeners which are added to the request object. Later, the `writeResponse` function cleans up those listeners. However, if Astro doesn't actually handle/respond to the request, it just calls the `next` function (line 106-7) without calling the `writeResponse` function, and so the socket listeners aren't cleaned up. 

https://github.com/withastro/astro/blob/cc9ee0271985226283998486ffbef6ca5c12fc07/packages/integrations/node/src/serve-app.ts#L78-L114

If I have some time, I can try to take a deeper look and submit a PR.

### What's the expected result?

The middleware should properly cleanup the socket listeners, even if it is just passing the request to the `next` function (e.g. for a static file/page).

### Link to Minimal Reproducible Example

https://github.com/fa-sharp/astro-middleware-leak

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by fa-sharp**
Fixes #15730

## Changes

- This fixes an issue in the Node.js middleware handler that was causing an EventEmitter leak warning when serving static pages and files. For the requests that were being passed on to Express / Fastify (e.g. static files / pre-rendered pages / etc.), the socket listener and AbortController cleanup wasn't being run before calling `next()`. This fix makes sure to run the cleanup function before calling `next()` (I did need to add the cleanup function to the exports from 'astro/app/node', which doesn't feel ideal).
- Ideally, these socket listeners shouldn't be created in the first place if the request is just being passed on to Express / Fastify / another handler. I did explore [another way of fixing this](https://github.com/fa-sharp/astro/tree/fix-middleware-leak) that would avoid that but it felt like it was making the code harder to reason about. I think it's worth further exploration though.
- I also see that the node adapter is getting a [major refactor](https://github.com/withastro/astro/pull/15418) so might make sense to wait before bigger changes like that.

## Testing
- Added a test that sends 30 back-to-back requests to a static page served by the Node.js middleware and Fastify. This triggers the EventEmitter leak warning and is caught by the test. This should help ensure a similar cleanup issue doesn't come up again.

## Docs
- Internal fix, no docs needed

### CODE REVIEW

File: packages/astro/src/core/app/node.ts [hunk 1]
```diff
@@ -222,6 +222,28 @@ export async function writeResponse(source: Response, destination: ServerRespons
...
+ *
+ * const server = createServer(async (req, res) => {
+ *     const request = createRequest(req);
+ *     const cleanup = getAbortControllerCleanup(req);
+ *     if (cleanup) cleanup();
+ *     // can now safely call another handler
+ * })
+ * ```
+ */
+export function getAbortControllerCleanup(req?: NodeRequest): (() => void) | undefined {
```
Comment (ematipico) [inline packages/astro/src/core/app/node.ts]: Why was this function moved? It's hard to tell if there were changes

Comment (fa-sharp) [reply packages/astro/src/core/app/node.ts]: @ematipico I moved it because it was exported and became part of the public API - that's how the file seemed to be organized (public functions, then internal functions, then deprecated public functions). I can move it back if needed. There shouldn't be any changes to the actual function.

Comment (fa-sharp) [reply packages/astro/src/core/app/node.ts]: @ematipico I merged the latest changes (including the new node adapter api) and moved that function back for clarity.

**Comment by ematipico** [comment]
~~It seems that e2e tests are failing. They are flaky, but they usually don't fail altogether. @fa-sharp can you look after it?~~ Nevermind, it seems it was an unlucky flaky failure
