### PR TITLE
Fix: `--host` flag logs when no network IPs are found

### LINKED ISSUE #3523: 🐛 BUG: Astro gives different CLI output with no --host flag and --host flag
### What version of `astro` are you using?

v1.0.0-beta.40

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

yarn

### What operating system are you using?

macOS

### Describe the Bug

When running `dev` with no `--host` flag (localhost only) the Astro CLI gives this output:
```
  🚀  astro  v1.0.0-beta.40 started in 122ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
```

However, when run with a `--host` flag the output looks like this:
```
  🚀  astro  v1.0.0-beta.40 started in 122ms
  
  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
```

Notice on the second one, there's no message about `Local` or `Network`. This led me to believe that Astro had hung and was not running at all, when in fact it was running just fine.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5q7luq?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #3523
- Preserve local network log when no network IPs are found
- Add `unable to find network to expose` message when no network IPs are found

## Testing

None added, since testing would require stubbing Node's `os` package to return an empty array. I attempted to use Sinon for this, and discovered it can't support ESM 😢 Would love to improve our testing infra for cases like this!

## Docs

N/A

### CODE REVIEW

**Review by natemoo-re — APPROVED** [review]
LGTM!

File: packages/astro/src/core/messages.ts [hunk 1]
```diff
@@ -76,42 +76,41 @@ export function devStart({
...
-	} else {
-		addresses = Object.values(os.networkInterfaces())
+
+	let local = `${localPrefix}${bold(cyan(toDisplayUrl(localAddress)))}`;
+	let network = null;
+
+	if (networkLogging === 'host-to-expose') {
+		network = `${networkPrefix}${dim('use --host to expose')}`;
+	} else if (networkLogging === 'visible') {
+		const ipv4Networks = Object.values(os.networkInterfaces())
```
Comment (matthewp) [inline packages/astro/src/core/messages.ts:86]: wow, fancy

**Review by matthewp — APPROVED** [review]
lgtm
