### PR TITLE
fix(create-astro): deprecation warning

### LINKED ISSUE #14214: DeprecationWarning when running `npm create astro@latest` with node v24.5.0
### Astro Info

```block
Astro                    v5.12.9
Node                     v24.5.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Minor issue when creating a new astro project:

```
~/dev/projects> npm create astro@latest

> npx
> "create-astro"


 astro   Launch sequence initiated.

   dir   Where should we create your new project?
         ./extinct-equator(node:94325) [DEP0187] DeprecationWarning: Passing invalid argument types to fs.existsSync is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
```

### What's the expected result?

No deprecation warning.

### Link to Minimal Reproducible Example

https://no.reproduction.required.example.com/

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #14214
- Supersedes #14219

## Testing

N/A, help needed!

## Docs

Changeset

### CODE REVIEW

File: packages/create-astro/src/actions/context.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ import { getName, getVersion } from '../messages.js';
 export interface Context {
 	help: boolean;
 	prompt: typeof prompt;
-	cwd: string;
+	cwd?: string;
```
Comment (florian-lefebvre) [inline packages/create-astro/src/actions/context.ts]: This change allows accounting for the first step where cwd isn't set, or is unlikely to be

File: packages/create-astro/src/actions/project-name.ts [hunk 2]
```diff
@@ -11,7 +11,7 @@ export async function projectName(
 	await checkCwd(ctx.cwd);
 
 	if (!ctx.cwd || !isEmpty(ctx.cwd)) {
-		if (!isEmpty(ctx.cwd)) {
+		if (ctx.cwd && !isEmpty(ctx.cwd)) {
```
Comment (florian-lefebvre) [inline packages/create-astro/src/actions/project-name.ts:14]: This is the actual fix

File: packages/create-astro/src/actions/context.ts (hunk 1 above)
Comment (ascorbic) [reply packages/create-astro/src/actions/context.ts]: There are a lot of not-null assertions that you're adding because of this. Could the types be handled better?
