### PR TITLE
Fix: refusing to accept `isSelfAccepting` for JSX

### LINKED ISSUE #3465: 🐛 BUG: React integration results in "[vite] Internal server error: Cannot set properties of undefined (setting 'isSelfAccepting')"
### What version of `astro` are you using?

1.0.0-beta.36

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Windows and Linux

### Describe the Bug

The React integration results in the following error:

```shell
00:03:25 [vite] Internal server error: Cannot set properties of undefined (setting 'isSelfAccepting')
  Plugin: vite:import-analysis
  File: /home/projects/gqaiaaarp.github/node_modules/.vite/deps/astro_client_visible_js.js?v=7ac8f471
      at ModuleGraph.updateModuleInfo (/home/projects/gqaiaaarp.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:57342:29)
      at TransformContext.transform (/home/projects/gqaiaaarp.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:57117:57)
      at async Object.transform (/home/projects/gqaiaaarp.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:38900:30)
      at async doTransform (/home/projects/gqaiaaarp.github/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:55857:29)
```

I have confirmed this happens in both an existing Astro site and a brand new one made from https://astro.new/

To reproduce create a new Astro project with React integration.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/withastro/astro/tree/latest/examples/framework-react?file=package.json&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #3465 
- Add all client runtime scripts to Vite's `optimizedDeps.include`. We exclude `hmr.js` from this list due to dependency issues in the monorepo when using `workspace:*`. I'm unable to find _exactly_ what's causing this, but the issue seems urgent enough to roll with this temporary solution.

## Testing

N/A

## Docs

N/A

### CODE REVIEW

**Review by matthewp — APPROVED** [review]

File: packages/astro/src/core/dev/index.ts [hunk 1]
```diff
@@ -33,10 +35,20 @@ export default async function dev(config: AstroConfig, options: DevOptions): Pro
 	await options.telemetry.record([]);
 	config = await runHookConfigSetup({ config, command: 'dev' });
 	const { host, port } = config.server;
+
+
```
Comment (tony-sull) [inline packages/astro/src/core/dev/index.ts:39]: super nit: remove second blank line

File: packages/astro/src/core/dev/index.ts [hunk 2]
```diff
@@ -33,10 +35,20 @@ export default async function dev(config: AstroConfig, options: DevOptions): Pro
...
+const clientRuntimeScripts = await glob(new URL('../../runtime/client/*.js', import.meta.url).pathname);
+const clientRuntimeFilePaths = clientRuntimeScripts
+.map(script => `astro/client/${path.basename(script)}`)
+// fixes duplicate dependency issue in monorepo when using astro: "workspace:*"
+.filter(filePath => filePath !== 'astro/client/hmr.js');
```
Comment (tony-sull) [inline packages/astro/src/core/dev/index.ts:44]: Would this be a problem for astro files not in our monorepo, or is `hmr.js` always ready before the client needs it?

**Review by tony-sull — COMMENTED** [review]
This fix looks good to me, just had a question about the `hmr.js` case would work outside our monorepo

File: packages/astro/src/core/dev/index.ts (hunk 2 above)
Comment (bholmesdev) [reply packages/astro/src/core/dev/index.ts]: Yep, it's always ready since we inject `hmr.js` as a hoisted script!

**Comment by okikio** [comment]
I'm still seeing this bug after updating to `v1.0.0-beta.41` 
image

@bholmesdev What do you think?

**Comment by chrisblossom** [comment]
This is still happening for me as of `v1.0.0-beta.42` if the integration `turbolinks()` is enabled in `astro.config.mjs`. @okikio is your issue as well?

**Comment by okikio** [comment]
@chrisblossom No, my `astro.config.mjs` looks like this, 
https://github.com/okikio/bundlejs/blob/astro/astro.config.mjs
