### PR TITLE
fix(i18n): parse params and props correctly with fallback

### LINKED ISSUE #12701: I18n fallbacks break path params in node adapter
### Astro Info

```block
Astro                    v5.0.3
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When running the node server, all paths with a param and a url that is configured to fall back will fail to capture the param correctly. 

There are at least two issues - both can be fixed with one change I believe, but I need some direction to guide where it should be. 
First the failure is:
```
TypeError: Missing parameter: id
    at getParameter (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:25:13)
    at file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:32:45
    at Array.map (<anonymous>)
    at getSegment (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:32:31)
    at file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:42:44
    at Array.map (<anonymous>)
    at Object.generate (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/manifest_8Y-hEi58.mjs:42:27)
    at stringifyParams (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/chunks/_@astrojs-ssr-adapter_DAm4WuN6.mjs:739:16)
    at findPathItemByKey (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/chunks/_@astrojs-ssr-adapter_DAm4WuN6.mjs:879:21)
    at getProps (file:///Users/mtwilliams/Codebase/astro-sir-i18n-params-repro/dist/server/chunks/_@astrojs-ssr-adapter_DAm4WuN6.mjs:1176:29)
```

This can be fixed by only continuing in `getProps` through the 
```
const params = getParams(route, pathname);
const matchedStaticPath = findPathItemByKey(staticPaths, params, route, logger);
```
if there are any matching static paths - that is - adding `if (staticPaths.length === 0) return {}` right before it. ⚠️ I have not tested this with a static deployment, but my reading of the code indicates these are unused anyway unless there are matching static paths, so I think it should work ⚠️ 

I tested this solution and another error occurred I need additional direction for:

The differences between the dev server and the node server make it difficult for me to ascertain where it is expected for this to be solved, but `getParams` in `packages/astro/src/core/render/params-and-props.ts` is receiving the routeData for the route it is falling back to and the original, localized pathname. That is:
```
getParams(
    {
        "route": "/products/[id]",
        "isIndex": false,
        "type": "page",
        "pattern": "^\\/products\\/([^/]+?)\\/?$",
        "segments": [
          [
            {
              "content": "products",
              "dynamic": false,
              "spread": false
            }
          ],
          [
            {
              "content": "id",
              "dynamic": true,
              "spread": false
            }
          ]
        ],
        "params": [
          "id"
        ],
        "component": "src/pages/products/[id].astro",
        "prerender": false,
        "fallbackRoutes": [
          {
            "route": "/es/products/[id]",
            "isIndex": false,
            "type": "fallback",
            "pattern": "^\\/es\\/products\\/([^/]+?)\\/?$",
            "segments": [
              [
                {
                  "content": "es",
                  "dynamic": false,
                  "spread": false
                }
              ],
              [
                {
                  "content": "products",
                  "dynamic": false,
                  "spread": false
                }
              ],
              [
                {
                  "content": "id",
                  "dynamic": true,
                  "spread": false
                }
              ]
            ],
            "params": [
              "id"
            ],
            "component": "src/pages/products/[id].astro",
            "prerender": false,
            "fallbackRoutes": [],
            "distURL": [],
            "origin": "project",
            "_meta": {
              "trailingSlash": "ignore"
            }
          }
        ],
        "distURL": [],
        "origin": "project",
        "_meta": {
          "trailingSlash": "ignore"
        }
      }, "/es/products/1"
)
```

it tries to get the params with `const paramsMatch = route.pattern.exec(decodeURIComponent(pathname));`, but this is using the pattern from the 'falled-back' route with the pathname from the localized one, so doesnt work. Dev and server environments seem to handle i18n fallbacks totally differently - it seems dev returns a full 404 render to the Vite plugin, which then handles falling back by rendering again , whereas Node just calls the render once. 

I dont see The [rewrite in RenderContext.render's lastNext](https://github.com/mtwilliams-code/astro/blob/6f4793656e6c911525c95afa570ca4a19ba11a3c/packages/astro/src/core/render-context.ts#L149) getting called from my logs - perhaps the issue is related to that? Alternatively, do we need to change the pathname like dev does to the fallback pathname?

### What's the expected result?

It should not crash on loading the page and should correctly parse out the param

### Link to Minimal Reproducible Example

https://github.com/mtwilliams-code/astro-sir-i18n-params-repro

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by mtwilliams-code**
## Changes

This modifies the logic in getParams and getProps slightly to handle i18n fallback edge cases.

1. If there are no static path matches in getProps, we return early to avoid an error that occurs in the `findPathItemByKey` call. This should be a nonbreaking change - I dont see any side effects from these calls and it returns an empty object anyway if there are no static paths. I'm not entirely sure I understand the intended behavior in all scenarios here, so feel free to correct.

2. In `getParams` If there are no param matches from `route.pattern`, we also try the patterns from `route.fallbackRoutes` so that we correctly parse out the param from the localized URL. 

Fixes #12701 

## Testing

Change to the i18n-routing-fallback fixture to allow testing SSR params and a new test added for `Fallback rewrite SSR` to validate the param is received correctly. Before this change this test will crash with 
```
12:56:12 [ERROR] TypeError: Missing parameter: id
    at getParameter (file:///Users/mtwilliams/Codebase/astro/packages/astro/test/fixtures/i18n-routing-fallback/dist/i18n-routing-fallback/server/manifest_CSai1Xy5.mjs:24:13)
    ...
    
    500 !== 200
    
        at TestContext.<anonymous> (file:///Users/mtwilliams/Codebase/astro/packages/astro/test/i18n-routing.test.js:2094:10)
        at async Test.run (node:internal/test_runner/test:574:9)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:318:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 500,
      expected: 200,
      operator: 'strictEqual'
    }
```

## Docs

This fixes a bug and restores intended behavior, so no docs necessary.

### CODE REVIEW

File: packages/astro/src/core/render/params-and-props.ts [hunk 1]
```diff
@@ -47,10 +47,11 @@ export async function getProps(opts: GetParamsAndPropsOptions): Promise<Props> {
 		base,
 	});
 
+	if (!staticPaths.length) return {};
+	const params = getParams(route, decodeURI(pathname));
 	// The pathname used here comes from the server, which already encored.
 	// Since we decided to not mess up with encoding anymore, we need to decode them back so the parameters can match
 	// the ones expected from the users
-	const params = getParams(route, decodeURI(pathname));
```
Comment (ematipico) [inline packages/astro/src/core/render/params-and-props.ts:53]: There's no need to move this line, especially because the comments belongs exactly this line you just moved. This will make the comments confusing. Please revert this tiny change.

File: packages/astro/src/core/render/params-and-props.ts [hunk 2]
```diff
@@ -77,7 +78,10 @@ export function getParams(route: RouteData, pathname: string): Params {
 	if (!route.params.length) return {};
 	// The RegExp pattern expects a decoded string, but the pathname is encoded
 	// when the URL contains non-English characters.
-	const paramsMatch = route.pattern.exec(pathname);
+	const paramsMatch =
+		route.pattern.exec(pathname) ||
+		route.fallbackRoutes.map((fallbackRoute) => fallbackRoute.pattern.exec(pathname))[0];
```
Comment (ematipico) [inline packages/astro/src/core/render/params-and-props.ts:83]: This doesn't seem correct to me. We're looping over all fallback routes and use `exec`, but we always pick the first one. Instead, we should use a for loop, and assign to `paramsMatch` that matches the route.

```js
for (const fallbackRoute in route.fallbackRoutes) {
	if (fallbackRoute.test(pathname)) {
		paramsMatch = fallbackRoute.exec(pathname);
		break;
	}
}
```

File: packages/astro/test/i18n-routing.test.js [hunk 3]
```diff
@@ -2087,4 +2087,12 @@ describe('Fallback rewrite SSR', () => {
 		const html = await response.text();
 		assert.match(html, /Hello/);
 	});
+
+	it('should render paths with path parameters correctly', async () => {
+		let request = new Request('http://example.com/new-site/fr/blog/1');
+		let response = await app.render(request);
+		assert.equal(response.status, 200);
+		const text = await response.text();
+		assert.equal(text.includes('Hello world'), true);
```
Comment (ematipico) [inline packages/astro/test/i18n-routing.test.js:2096]: Use `assert.match`

```suggestion
		assert.match(text, /Hello world/);
```

File: packages/astro/test/i18n-routing.test.js [hunk 4]
```diff
@@ -2087,4 +2087,12 @@ describe('Fallback rewrite SSR', () => {
 		const html = await response.text();
 		assert.match(html, /Hello/);
 	});
+
+	it('should render paths with path parameters correctly', async () => {
+		let request = new Request('http://example.com/new-site/fr/blog/1');
```
Comment (ematipico) [inline packages/astro/test/i18n-routing.test.js:2092]: Can we update the test with more locales? At the moment there's only `fr: 'en'`, let's add two more and make sure that the fallback of params works for all of them.

**Review by ematipico — CHANGES_REQUESTED** [review]

**Comment by mtwilliams-code** [comment]
LMK if this is too many tests

File: packages/astro/src/core/render/params-and-props.ts (hunk 2 above)
Comment (mtwilliams-code) [reply packages/astro/src/core/render/params-and-props.ts]: updated to `.find(x->x)` to get first non-null match instead of just first, which could be null

File: .changeset/selfish-paws-play.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixes bugs with parsing of params and props in i18n fallbacks that cause crashes in app server
```
Comment (ematipico) [inline .changeset/selfish-paws-play.md:5]:
```suggestion
Fixes a bug where Astro couldn't correctly parse `params` and `props` when receiving i18n fallback URLs
```

**Review by ematipico — APPROVED** [review]
This was an amazing fix, thank you @mtwilliams-code for that!
