### PR TITLE
Handle `false` properly in `class:list`

### LINKED ISSUE #3920: 🐛 BUG: `class:list` directive incorrectly adding class `false`
### What version of `@astrojs/compiler` are you using?

1.0.0-beta.37

### What package manager are you using?

yarn

### What operating system are you using?

CodeSandbox on a Mac

### Describe the Bug

The docs [say][docs] the `class:list` directive is 'inspired by @lukeed’s popular clsx helper library', but unlike clsx, the native directive seems to apply a class of `false` for falsey arguments, whereas clsx ignores falsey arguments. For example:

```js
<p class:list={[
  'foo',
  false && 'bar'
]}>
  Paragraph.
</p>
```

...renders the `<p>` element with the classes `foo` and `false`. 

If I substitute clsx for the `class:list` directive like this...

```js
<p class={clsx([
  'foo',
  false && 'bar'
])}>
  Paragraph.
</p>
```

...the `<p>` element renders with just the class `foo`, as expected.

[docs]: https://docs.astro.build/en/reference/directives-reference/#classlist

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-class-list-directive-test-xrs688?file=/src/pages/index.astro

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Fixes #3920
- `class:list` wasn't ignoring `false`, it was stringifying it to `class="false"`
- `class:list={false}` was outputting `class=""`, not it outputs `''`

## Testing

Tests updated

## Docs

N/A, bug fix only

### CODE REVIEW

File: packages/astro/src/runtime/server/index.ts [hunk 1]
```diff
@@ -545,7 +545,11 @@ Make sure to use the static attribute syntax (\`${key}={value}\`) instead of the
 
 	// support "class" from an expression passed into an element (#782)
 	if (key === 'class:list') {
-		return markHTMLString(` ${key.slice(0, -5)}="${toAttributeString(serializeListValue(value))}"`);
+		const listValue = toAttributeString(serializeListValue(value));
```
Comment (FredKSchott) [inline packages/astro/src/runtime/server/index.ts:548]: is there a reason that we don't use clhttps://www.npmjs.com/package/clsx here? It looks like we implemented this ourselves, but clsx is so battle-tested (and zero dep) I can't think of a good reason not to use it here

Not to tackle here, just calling this out to reduce our bug risk and maintenance costs

**Comment by FredKSchott** [comment]
Nice new tests!

**Review by matthewp — APPROVED** [review]

File: packages/astro/src/runtime/server/index.ts (hunk 1 above)
Comment (natemoo-re) [reply packages/astro/src/runtime/server/index.ts:548]: I don't know the original reason for not using `clsx` directly. I'll keep an eye out for any more issues that come up... certainly happy to switch in the future. For now would love to get this hotfix out.
