### PR TITLE
Fix: Windows client-side script reloads on dev server

### LINKED ISSUE #3681: 🐛 BUG: Vite's HMR not working with client-side scripts in new Beta
### What version of `astro` are you using?

1.0.0-beta.50

### Are you using an SSR adapter? If so, which one?

N/A

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

To be clear, I have searched the docs to see if this is intended behaviour but I can't see anything nothing on it. Using any Astro project returns the same result in which the Vite server must be restarted for changes in client side scripts to take effect.

I have only tested this on my Windows machine - not sure if this is OS related.

### Link to Minimal Reproducible Example

N/A: issue present on every Astro project

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #3681 
- Correct client-side script file paths with leading `/`. Before you ask: no, `/@fs/` and `/@id`/ don't work 😓 
- Pull imported modules from module graph, instead of `ctx.modules`

## Testing

TODO: e2e test

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro/index.ts [hunk 1]
```diff
@@ -246,19 +246,11 @@ export default function astro({ config, logging }: AstroPluginOptions): vite.Plu
...
 				if (!resolvedConfig.isProduction) {
-					// HACK: extract dependencies from metadata until compiler static extraction handles them
-					const metadata = transformResult.code.split('$$createMetadata(')[1].split('});\n')[0];
-					const pattern = /specifier:\s*'([^']*)'/g;
-					const deps = new Set();
-					let match;
-					while ((match = pattern.exec(metadata)?.[1])) {
-						deps.add(match);
-					}
-
```
Comment (bholmesdev) [inline packages/astro/src/vite-plugin-astro/index.ts:257]: Dead code! This appends to a `deps` array that never gets read 😅

**Comment by bholmesdev** [comment]
Well, it looks like the hotfix @natemoo-re and I discovered doesn't work outside our local test setup. I was already confused why our fix would work anyways, so I'm tabling this effort for now until @bluwy (or another Vite maintainer) is free. Pretty stumped on this one!

**Comment by bholmesdev** [comment]
Alright, tossing over to @matthewp to see what happens! Here's everything I tried (that didn't work):
- **appending `/@fs/`, `/@id/`, `/@fs//`, `/@id//` or a simple `/`** to [our generated `import`s](https://github.com/withastro/astro/pull/4645/files#diff-303c430c437c85881a1284496ace18890f77bf16222198ef02a06ed50409042cR252) and/or [our `scripts.ts` elements](https://github.com/withastro/astro/blob/main/packages/astro/src/core/render/dev/scripts.ts#L44)
- **removing our generated `import`s from `vite-plugin-astro` entirely.** These _should_ be redundant since we inject a `script` tag into the page already. Funny enough, HMR continues to work after deleting this section on Unix
- **using a root-relative path** (i.e. `/src/pages/index.astro...`) in our generated `import`s and/or `scripts.ts` elements
- **adding a `?t=[random-hash]` to our generated `import`s and/or `scripts.ts` elements

I also have some miscellaneous "woah really?" moments:
- hoisted scripts _will_ work in Stackblitz on Windows. They may be using linux subsystem under-the-hood, or something unrelated is going on 🤷 
- visiting a hoisted script's path in the dev server **with a different path** (ex. visit `http://localhost:3000/src/pages/index.astro?astro&type=script&lang.ts` when the homepage loads `/Users/.../src/pages/index.astro...`) _will_ have the most up-to-date script contents on first visit, despite the contents being out-of-date on the actual page

File: packages/astro/src/vite-plugin-astro/hmr.ts [hunk 2]
```diff
@@ -22,6 +22,7 @@ export async function handleHotUpdate(
 	ctx: HmrContext,
 	{ config, logging, compile }: HandleHotUpdateOptions
 ) {
+	const importedModules = ctx.server.moduleGraph.getModuleById(ctx.file)?.importedModules ?? [];
```
Comment (bholmesdev) [inline packages/astro/src/vite-plugin-astro/hmr.ts:25]: Weird hack! I discovered `ctx.modules` does _not_ contain any script tags on the page, but pulling directly from the module graph _will_ have these entries. Could be part of the problem.

**Review by bholmesdev — COMMENTED** [review]
I'll pretend to understand why this solves the problem with... a comment approval ✅

**Comment by matthewp** [comment]
@bholmesdev It's because Vite determines which modules to invalidate based on which files they belong to. It determines this because it expects resolveId to return the file path. 

In this case we have to make sure that it begins with `C:` (or whatever drive it is) on Windows and this does that.
