### PR TITLE
Change frontmatter injection ordering

### LINKED ISSUE #4429: Empty Markdown frontmatter at build time
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When creating custom Markdown plugins (as in the [doc](https://docs.astro.build/en/guides/markdown-content/#injecting-frontmatter)):

- Frontmatters are empty at build time.
- It seems that Markdown files are processed twice at build time.

The output is correct at the end but the lack of frontmatter makes development harder.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-vgrdek?file=content%2Farticle1.md,content%2Farticle2.md,astro.config.ts,src%2Fplugins%2FremarkGetTitle.ts,src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5099: make parsed md/mdx frontmatter available to plugins
### What version of `astro` are you using?

1.5.0

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

currently, `remark`/`rehype` plugins are only allowed to add *additional* fields to `vfile.data.astro.frontmatter`, however the parsed frontmatter from markdown/mdx sources files is not made available to plugins (i.e. `vfile.data.astro.frontmatter` is passed as an empty object).

### Link to Minimal Reproducible Example

https://github.com/stefanprobst/issue-astro-md-frontmatter/blob/main/astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #4429
- Resolves #5099 

Give remark and rehype plugins access to user frontmatter via frontmatter injection. This means `data.astro.frontmatter` is now the _complete_ Markdown or MDX document's frontmatter, rather than an empty object.

This allows plugin authors to modify existing frontmatter, or compute new properties based on other properties. For example, say you want to compute a full image URL based on an `imageSrc` slug in your document frontmatter:

```ts
export function remarkInjectSocialImagePlugin() {
  return function (tree, file) {
    const { frontmatter } = file.data.astro;
    frontmatter.socialImageSrc = new URL(
      frontmatter.imageSrc,
      'https://my-blog.com/',
    ).pathname;
  }
}
```

### Content Collections change

We have changed _inject_ frontmatter to _modify_ frontmatter in our docs to improve discoverability. This is based on support forum feedback where injection is rarely the term used.

To reflect this, the `injectedFrontmatter` property has been renamed to `remarkPluginFrontmatter`. This should clarify this plugin is still separate from the `data` export Content Collections expose today. We also expect `remarkPluginFrontmatter` to be deprecated once schemas can compute frontmatter based on file contents.

## Testing

- Update frontmatter injection tests to consider frontmatter mutation

## Docs

https://github.com/withastro/docs/pull/2250

### CODE REVIEW

File: packages/astro/src/vite-plugin-utils/index.ts [hunk 1]
```diff
@@ -36,33 +35,6 @@ export function getFileInfo(id: string, config: AstroConfig) {
 	return { fileId, fileUrl };
 }
 
-function isValidAstroData(obj: unknown): obj is MarkdownAstroData {
```
Comment (bholmesdev) [inline packages/astro/src/vite-plugin-utils/index.ts:39]: Move frontmatter injection utils to `@astrojs/markdown-remark`

**Review by matthewp — CHANGES_REQUESTED** [review]
Blocking as we are not ready to merge `major` changes into main just yet.

**Comment by matthewp** [comment]
Code looks good! Let's talk about this with the core team before merging next week.

**Review by aFuzzyBear — COMMENTED** [review]
It was interesting to see how you readjusted the order of the frontmatter process.
So its now safe to say that frontmatter is mutable via the remark tree and the output of that is what is then provided into other contexts

**Review by matthewp — APPROVED** [review]
Approved by TSC, @bholmesdev just need to fix the conflicts.

File: packages/astro/src/content/vite-plugin-content-assets.ts [hunk 2]
```diff
@@ -34,7 +34,7 @@ export function astroDelayedAssetPlugin({ mode }: { mode: string }): Plugin {
 			if (isDelayedAsset(id)) {
 				const basePath = id.split('?')[0];
 				const code = `
-					export { Content, getHeadings, _internal } from ${JSON.stringify(basePath)};
+					export { Content, getHeadings } from ${JSON.stringify(basePath)};
```
Comment (andersk) [inline packages/astro/src/content/vite-plugin-content-assets.ts:37]: It seems `frontmatter` needed to be added here where `_internal` was removed.

- #5927
