### PR TITLE
Error message: clarify "adapter does not have previewEntrypoint"

### LINKED ISSUE #5181: Confusing error message: `adapter does not have previewEntrypoint`
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

Vercel

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Now that the node adapter supports preview mode, users are getting confused by the error message that occurs if you run `astro preview` with another adapter (see [support thread](https://discord.com/channels/830184174198718474/1032146641534324736/1032146641534324736)).

Instead of referring to `previewEntrypoint`, we could state that the adapter doesn't support the preview command.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-5q7vb6?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Jutanium**
## Changes

- Clarify the error message that is shown when your adapter doesn't support `astro preview`
- Closes #5181

## Testing

Just an error message

## Docs

cc @withastro/maintainers-docs for feedback! 

I'll also make a PR to update our description of `astro preview` in the docs, which hasn't been updated since the Node adapter started supporting `astro preview`.

### CODE REVIEW

File: packages/astro/src/core/preview/index.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export default async function preview(
 		throw new Error(`[preview] No adapter found.`);
 	}
 	if (!settings.adapter.previewEntrypoint) {
-		throw new Error(`[preview] adapter does not have previewEntrypoint.`);
+		throw new Error(`[preview] This adapter does not support the preview command.`);
```
Comment (delucis) [inline packages/astro/src/core/preview/index.ts:36]: Is there enough context here for this to be clear what “this adapter” is?

If I’m reading the source correctly and the `settings.adapter` is equivalent to [this object](https://github.com/withastro/astro/blob/b77200f42399ea31b0045bc0e6bfe2c1c5ccc970/packages/integrations/node/src/index.ts#L5-L11), maybe we can even do this?

```suggestion
		throw new Error(`[preview] The ${settings.adapter.name} adapter does not support the preview command.`);
```

With the idea being an error log like:

```
[preview] The @astrojs/node adapter does not support the preview command.
```

Comment (Jutanium) [reply packages/astro/src/core/preview/index.ts:36]: Oh yes, this is much better, thank you!

**Review by natemoo-re — APPROVED** [review]
