### PR TITLE
fix: pass raw frontmatter to when parsing markdown in glob loader

### LINKED ISSUE #12778: Regression in frontmatter accessible to remark plugins in Astro 5 + Content Layer
### Astro Info

```block
Astro                    v5.0.9
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using Astro v5 with Content Layer, there is a regression in the frontmatter accessible to remark plugins that is no longer the user-defined frontmatter but the frontmatter validated by the collection schema.

Using the following collection definition with a schema only allowing a `title` property and using a transform to add an `someOtherField` additional field:

```ts
const docs = defineCollection({
  loader: glob({ pattern: "**/*.{md,mdx}", base: "./src/content/Docs" }),
  schema: z
    .object({
      title: z.string(),
    })
    .transform((data) => ({
      ...data,
      someOtherField: "Added by transform",
    })),
});
```

And the following markdown file:

```md
---
title: Test Mardown
foo: bar
---

Hello from Markdown!
```

A remark plugin accessing `file.data.astro?.frontmatter` will get the following object:

```js
{ title: 'Test Mardown', someOtherField: 'Added by transform' }
```

Using an MDX file with the same content or Astro v4, the object would be:

```js
{ title: 'Test MDX', foo: 'bar' }
```

Additional notes:

- May need to run `npm run dev -- --force` in StackBlitz to see the logs
- Here is a link to the same setup in Astro v4: https://stackblitz.com/edit/github-w2juvll6-fxyvazic?file=astro.config.mjs

### What's the expected result?

The expected result should be the same as Astro v4 and be consistent between markdown and MDX files:

```js
{ title: 'Test MDX', foo: 'bar' }
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-w2juvll6?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Fixes a regression where the glob loader is passing the parsed data to the markdown renderer, rather than raw frontmatter. This was breaking plugins.
Fixes #12778

## Testing
Add new fixture and test

### CODE REVIEW

File: packages/astro/src/content/loaders/glob.ts [hunk 1]
```diff
@@ -171,7 +171,7 @@ export function glob(globOptions: GlobOptions): Loader {
 					try {
 						rendered = await render?.({
 							id,
-							data: parsedData,
+							data,
```
Comment (ascorbic) [inline packages/astro/src/content/loaders/glob.ts:174]: The actual fix

**Review by ematipico — APPROVED** [review]
