### PR TITLE
Actions: fix 500 on empty object for Vercel serverless

### LINKED ISSUE #11515: Astro Actions .safe() function required empty object argument for Vercel deployment
### Astro Info

```block
Astro                    v4.12.2
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/vercel/serverless
Integrations             @astrojs/solid-js
```

### Describe the Bug

I have this logout action:
`const { data, error } = await actions.logoutUser.safe()`

This woks fine on local host when running dev server and when using the node adapter and running the app using entry.mjs.

But when deployed to vercel I get this error when the logout function runs:

> 17:03:11 [ERROR] SyntaxError: Unexpected end of JSON input at JSON.parse (<anonymous>) at parseJSONFromBytes (node:internal/deps/undici/undici:5584:19) at successSteps (node:internal/deps/undici/undici:5555:27) at fullyReadBody (node:internal/deps/undici/undici:1665:9) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async specConsumeBody (node:internal/deps/undici/undici:5564:7) at async Module.POST (file:///var/task/vercel/path0/.vercel/output/_functions/chunks/route_Yu3iUWSv.mjs:17:12) at async renderEndpoint (file:///var/task/vercel/path0/.vercel/output/_functions/chunks/astro/server_CBvJsTK-.mjs:45:20) at async lastNext (file:///var/task/vercel/path0/.vercel/output/_functions/entry.mjs:1031:23) at async callMiddleware (file:///var/task/vercel/path0/.vercel/output/_functions/entry.mjs:480:10) 

It's fixed by adding an empty object as a argument to the .safe() function:
`const { data, error } = await actions.logoutUser.safe({})`

Not sure if it's document somewhere that an empty object needs to be passed to .safe() when it has no other arguments or if this is a bug.

To reproduce you will need to go to my site (https://sharper-than-time-c1ti0fvty-grahf0085s-projects.vercel.app/), make an account, and click the logout button. I can only produce this on vercel so.....

This is my logout action if it matters:
  ```
logoutUser: defineAction({
    handler: (_, context) => {
      const TOKEN = import.meta.env.TOKEN

      try {
        context.cookies.set(TOKEN, '', {
          httpOnly: true,
          maxAge: 0,
          path: '/',
          secure: true,
          sameSite: 'lax',
        })

        return { cookieDeleted: true }
      } catch (error) {
        console.error('Error logging out: ', error)
        throw new Error(error.message || error)
      }
    },
  }),
```

### What's the expected result?

The logout function runs without producing an error

### Link to Minimal Reproducible Example

https://sharper-than-time-c1ti0fvty-grahf0085s-projects.vercel.app/

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

Resolves #11515. We discovered that Actions sets the `content-type` to `application/json` even when the body is `undefined`. We set `content-length` to `0` for this case, but it seems some deployment platforms (Vercel) may remove this header if it detects an empty body.

This fix removes the `content-type` when no body is present.

## Testing

- Add test for empty content type
- Add test for unexpected content type

## Docs

N/A

### CODE REVIEW

File: packages/astro/templates/actions.mjs [hunk 1]
```diff
@@ -65,15 +65,18 @@ async function handleAction(param, path, context) {
 	let body = param;
 	if (!(body instanceof FormData)) {
 		try {
-			body = param ? JSON.stringify(param) : undefined;
```
Comment (bholmesdev) [inline packages/astro/templates/actions.mjs:68]: Fixes edge case where `null` is considered an empty body. `null` is valid JSON!

**Review by bluwy — APPROVED** [review]
I think it's missing a changeset
