### PR TITLE
Fix `astro add @example-org/integration`

### LINKED ISSUE #4420: astro add <integration> doesn't work for npm organization scoped packages
### What version of `astro` are you using?

1.0.6

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

pnpm

### What operating system are you using?

Windows, MacOS

### Describe the Bug

Trying to add an integration through `pnpm astro add @example/integration` or `pnpx astro add @example/integration` throws an error `Cannot read properties of null (reading 'name')`.

npm also shows same behaviour

### Link to Minimal Reproducible Example

Will provide one if others can't reproduce

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #4420
- Correctly set integration to "third party" for unofficial integrations
- Remove duplicate `@` prepended to third part org scope

## Testing

N/A

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/core/add/index.ts [hunk 1]
```diff
@@ -637,13 +637,14 @@ export async function validateIntegrations(integrations: string[]): Promise<Inte
...
-				let pkgType: 'first-party' | 'third-party' = 'first-party';
+				let pkgJson;
+				let pkgType: 'first-party' | 'third-party';
 
-				if (!scope) {
-					const firstPartyPkgCheck = await fetchPackageJson('astrojs', name, tag);
+				if (scope && scope !== '@astrojs') {
+					pkgType = 'third-party';
+				} else {
+					const firstPartyPkgCheck = await fetchPackageJson('@astrojs', name, tag);
```
Comment (FredKSchott) [inline packages/astro/src/core/add/index.ts:647]: the `if (firstPartyPkgCheck instanceof Error) {` error handling below doesn't make sense any more. This branch is only hit if it _is_ an official Astro package.

Comment (bholmesdev) [reply packages/astro/src/core/add/index.ts:647]: @FredKSchott Ah, this is to verify if it's _actually_ a published package under `@astrojs`! Without this check, we'd attempt to add `@astrojs/potato`, `@astrojs/fake`, etc.

**Review by matthewp — APPROVED** [review]
