### PR TITLE
fix: fix `transition:name` can be unicode

### LINKED ISSUE #9803: `transition:name` can't use Chinese
### Astro Info

```block
Astro                    v4.1.0
Node                     v20.9.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/react
                         @astrojs/sitemap
                         astro-expressive-code
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

Set a element `transition:name` to `transition:name={name}`
The name is Chinese text. 

Read Astro code:

```ts
// Ensure animationName is a valid CSS identifier
function toValidIdent(name: string): string {
	return name.replace(/[^a-zA-Z0-9\-\_]/g, '_').replace(/^\_+|\_+$/g, '');
}
```

This will cause the Chinese name to be replaced with empty, resulting in multiple duplicates of the name.

image

## My website as example:
https://liruifengv.com/tags/

image

I think the same will be true for Japanese and Korean, etc.

### What's the expected result?

Expect Chinese to be used correctly as transition:name.

CSS identifiers can be Chinese、Japanese and Korean, etc.

### Link to Minimal Reproducible Example

https://liruifengv.com/tags/

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by liruifengv**
## Changes

- Close #9803
- escape `transition:name` use `cssesc` lib

## Testing

Added e2e test.
## Docs

Not need update.

### CODE REVIEW

File: packages/astro/src/runtime/server/transition.ts [hunk 1]
```diff
@@ -39,15 +39,16 @@ function toValidIdent(name: string): string {
 		null,
 		`Your transition:name ${bold(name)} is not a valid CSS identifier. It will be escaped.`
 	);
-	const result = [];
-	for (const char of name) {
-		if (/[a-zA-Z0-9_-]/.test(char)) {
-			result.push(char);
+	let result = "";
+	for (let i = 0; i < name.length; i++)  {
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:43]: That last change is a bad idea, please revert to const char of name

File: .changeset/cold-bobcats-shave.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"astro": patch
+---
+
+fix(view-transition): escaped unicode `transition:name`
```
Comment (martrapp) [inline .changeset/cold-bobcats-shave.md:5]:
```suggestion
Applies the correct escaping to identifiers used with `transition:name`.

**Comment by martrapp** [comment]
Great PR! Don't let my many comments put you off, I really appreciate your contribution!

**Comment by yisibl** [comment]
Also, need to consider emoji, additionally is there a test case to test them?

**Comment by martrapp** [comment]
> Also, need to consider emoji, additionally is there a test case to test them?

An idea for a e2e test case would be to read back the `view-transition-name` style property, e.g. test `el.style.viewTransitionName`. If the `view-transition-name` in the generated style sheet contains illegal chars, the `viewTransitionName` of the elements styles will be completely empty. In other cases it will yield the string as shown on the right side of the screenshots above, i.e. human readable. Escaped ascii characters would would be shown with there escaping slash but hex encoded code points will be shown as the character they represent.

File: packages/astro/src/runtime/server/transition.ts [hunk 3]
```diff
@@ -25,7 +28,26 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+	logger.warn(
+		null,
+		`Your transition:name ${bold(name)} is not a valid CSS identifier. It will be escaped.`
+	);
+	const result = [];
+	for (const char of name) {
+		if (/[a-zA-Z0-9_-]/.test(char)) {
+			result.push(char);
+		} else {
+			result.push(`\\${char.charCodeAt(0).toString(16)}-`);
```
[the remark this answers is not in the document]
Comment (martrapp) [reply packages/astro/src/runtime/server/transition.ts]: Sorry, i was wrong for the last example. As space isn't a valid character here, it has also to be escaped and the result of the last example must be `"\\5f00\\ \\6e90"`

File: packages/astro/src/runtime/server/transition.ts [hunk 4]
```diff
@@ -32,6 +32,7 @@ function toValidIdent(name: string): string {
 	if (/^[0-9]|^-[0-9]|^--/.test(name)) {
     throw new Error("Your transition:name is not a valid CSS identifier.");
 	}
+	// can't be a CSS keyword
 	if (['unset', 'initial', 'inherit', 'none' ].includes(name)) {
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:33]: Top! As mdn says, you can't define those. And it would definitively be a mistake to use them with `transition:name` in combination with `transition-animate` to define a new transition animation.

But you could use them as `view-transition-names` as they have a predefined meaning. At least `none` might come in handy if you want to exclude an element from the default animation.

File: packages/astro/src/runtime/server/transition.ts [hunk 5]
```diff
@@ -25,7 +28,26 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+	});
+	logger.warn(
+		null,
+		`Your transition:name ${bold(name)} is not a valid CSS identifier. It will be escaped.`
+	);
+	const result = [];
+	for (const char of name) {
+		if (/[a-zA-Z0-9_-]/.test(char)) {
+			result.push(char);
+		} else {
```
[the remark this answers is not in the document]
Comment (martrapp) [reply packages/astro/src/runtime/server/transition.ts:39]: will take me a bit ...

File: packages/astro/src/runtime/server/transition.ts [hunk 6]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
 
 // Ensure animationName is a valid CSS identifier
 function toValidIdent(name: string): string {
-	return name.replace(/[^a-zA-Z0-9\-\_]/g, '_').replace(/^\_+|\_+$/g, '');
+	// can't start with a number, - + number, or --
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:28]:
```suggestion
	// can't start with a number, - + number
```

File: packages/astro/src/runtime/server/transition.ts [hunk 7]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+	if (/^[0-9]|^-[0-9]/.test(name)) {
+    throw new Error(`Your transition:name ${name} is not a valid CSS identifier.`);
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:30]:
```suggestion
    throw new Error(`Your transition:name ${name} is not a valid CSS identifier as it starts with ${name.substring(0,2)}`);
```

File: packages/astro/src/runtime/server/transition.ts [hunk 8]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+	}
+	if (/^[a-zA-Z0-9_\\-]*$/.test(name)) {
+		return name;
+	}
+	let result = "";
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:35]:
```suggestion
	let result = "";
	let wasHexEscaped = false;
```

File: packages/astro/src/runtime/server/transition.ts [hunk 9]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+	for (const char of name)  {
+		if (/[a-zA-Z0-9_\\-]/.test(char)) {
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:37]:
```suggestion
		if (/[0-9a-fA-F]/.test(char) && wasHexEscaped) {
			result += " ";
		}
		wasHexEscaped = false;
		if (/[a-zA-Z0-9_\\-]/.test(char)) {
```

File: packages/astro/src/runtime/server/transition.ts [hunk 10]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+			result += char;
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:38]:
```suggestion
			result += char;
			continue;
```

File: packages/astro/src/runtime/server/transition.ts [hunk 11]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+		} else {
+			// TODO handle $ and other special characters
+			const suffix = char === name[name.length - 1] ? "" : "\ ";
+			result += `\\${char.codePointAt(0)!.toString(16)}${suffix}`;
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:42]:
```suggestion
		const code = char.codePointAt(0)
		if (code === undefined) {
			throw new Error(`Your transition:name ${name} is not a valid CSS identifier as it contains undefined code points`);
		}
		if (code < 0x20 || code >= 0x7f) {
			result += `\\${code.toString(16)}`;
			wasHexEscaped = true;
		} else {
			result += `\\${char}`;
		}
```

File: packages/astro/src/runtime/server/transition.ts [hunk 12]
```diff
@@ -25,7 +25,24 @@ export function createTransitionScope(result: SSRResult, hash: string) {
...
+		}
```
Comment (martrapp) [inline packages/astro/src/runtime/server/transition.ts:43]:
```suggestion
```

**Comment by natemoo-re** [comment]
I did find a potential package to handle this! [`cssesc`](https://github.com/mathiasbynens/cssesc) was written by [Mathias Bynens](https://github.com/mathiasbynens), who is very involved in standards work. 

Although the package is quite old, I'm confident that the code is stable!

I'd suggest that we try to use a package for this, and fallback to implementing our own logic only if there isn't a package out there that meets our needs.

**Comment by martrapp** [comment]
> I did find a potential package to handle this!

Excellent catch! As you can see from the linked issue, we were looking for a lib like this but failed.
```
cssesc(name, {'isIdentifier': true});
```
seems to be exactly what we need here.

**Comment by liruifengv** [comment]
> I did find a potential package to handle this! [`cssesc`](https://github.com/mathiasbynens/cssesc) was written by [Mathias Bynens](https://github.com/mathiasbynens), who is very involved in standards work. He also [wrote an article](https://mathiasbynens.be/notes/css-escapes) and built [a hosted tool](https://mothereff.in/css-escapes) to explore this topic.
> 
> Although the package is quite old, I'm confident that the code is stable!
> 
> I'd suggest that we try to use a package for this, and fallback to implementing our own logic only if there isn't a package out there that meets our needs.

Thank you! I used the package. It works!

**Comment by martrapp** [comment]
Wow over 20 conversation and at the end a one line change (+ tests and dependencies of course)
That was a fun trip, I enjoyed it!

**Review by martrapp — APPROVED** [review]
Looks very good to me now!
