### PR TITLE
fix(astro): restore Astro.site in getStaticPaths()

### LINKED ISSUE #14575: Regression: Astro.site no longer available in getStaticPaths()
### Astro Info

```block
Astro                    v5.14.6
Node                     v20.19.1
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Since version 5.13.10, `Astro.site` is undefined in `getStaticPaths()`.

This was last working in version 5.13.9. 

This looks like the most relevant change in 5.13.10: https://github.com/withastro/astro/pull/14405/files#diff-6b0c74afa525663c451fc84841ec2040e7125f74e732da4ed7584b84896a759dL52

The linked repro is the blog example with `pages/blog/[...slug].tsx]` modified to demonstrate the problem. The example will run `npm run build` automatically.

If you run `npm install astro@5.13.9 && npm run build` the problem goes away.

### What's the expected result?

It should work as it previously did, where `Astro.site` contained the URL configured in `astro.config.,mjs` in a URL object.

Note: It’s possible that things other than `getStaticPaths()` are affected, that’s just where I noticed the problem.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-r3fdruug?file=src%2Fpages%2Fblog%2F%5B...slug%5D.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by aprici7y**
Fixes #14575

## Summary
Restores `Astro.site` availability in `getStaticPaths()` by adding back the `astroGlobalArgs` compiler option that was removed in PR #14405.

## Bug
In v5.13.10, `Astro.site` became `undefined` when accessed inside `getStaticPaths()`, even when properly configured in `astro.config.mjs`.

## Root Cause
PR #14405 removed the `astroGlobalArgs` parameter from the compiler options. This parameter passes the site configuration to the Astro compiler, which injects it into the compiled component, making `Astro.site` available in the frontmatter code (including `getStaticPaths()`).

## Fix
This PR restores the single line that was removed:
```typescript
astroGlobalArgs: JSON.stringify(astroConfig.site),
```

## Testing
Verified that `Astro.site` is now correctly available in `getStaticPaths()` as a URL object with the configured site value.

### Before (v5.13.10)
- `Astro.site` in `getStaticPaths()`: `undefined`

### After (with this fix)
- `Astro.site` in `getStaticPaths()`: `URL { href: 'https://example.com/', ... }`

### CODE REVIEW

File: packages/astro/src/core/compile/compile.ts [hunk 1]
```diff
@@ -47,6 +47,7 @@ export async function compile({
 			normalizedFilename: normalizeFilename(filename, astroConfig.root),
 			sourcemap: 'both',
 			internalURL: 'astro/compiler-runtime',
+			astroGlobalArgs: JSON.stringify(astroConfig.site),
```
Comment (florian-lefebvre) [inline packages/astro/src/core/compile/compile.ts:51]:
```suggestion
			// TODO: remove in Astro v7
			astroGlobalArgs: JSON.stringify(astroConfig.site),
```

**Review by florian-lefebvre — APPROVED** [review]
Thanks!
