### PR TITLE
fix: toolbar image audit in content collections

### LINKED ISSUE #13221: Devtools mark
### Astro Info

```block
Astro                    v5.2.5
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

I added an image to the "First post" blog post

The dev toolbar tells me that the image does not use the Astro Image component. 

I inspected the image and it has the `width` and `height` set as well as lazy loading enabled. Without me adding them, manually.

NOTE: I was not able to load local images inside the Stackblitz instance, maybe you need to reproduce the issue locally.

### What's the expected result?

There's no issue inside the devtool bar.

I read the [documentation](https://docs.astro.build/en/guides/images/#images-in-markdown-files), and from my understanding Astro automatically optimises the images.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wsrbm111?file=src%2Fcontent%2Fblog%2Fmarkdown-style-guide.md

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #13221
- The dev toolbar relies on the `data-image-component` attribute for an audit
- In content collections md/mdx files, images are not created using the `<Image />` component so the attribute was not set in dev

## Testing

Manually

## Docs

Changeset

### CODE REVIEW

**Review by sarah11918 — APPROVED** [review]
Just saying I appreciate your changeset! 💜

File: packages/astro/src/content/runtime.ts [hunk 1]
```diff
@@ -700,6 +700,7 @@ async function updateImageReferencesInBody(html: string, fileName: string) {
 			...attributes,
 			src: image.src,
 			srcset: image.srcSet.attribute,
+			...(import.meta.env.DEV ? { 'data-image-component': 'true' } : {}),
```
Comment (ematipico) [inline packages/astro/src/content/runtime.ts:704]: nit: we could leave a comment to explain why this

Comment (florian-lefebvre) [reply packages/astro/src/content/runtime.ts:704]:
```suggestion
			// This attribute is used by the toolbar audit
			...(import.meta.env.DEV ? { 'data-image-component': 'true' } : {}),
```
