### PR TITLE
fix(#2846): handle destructured private env usage during SSR

### LINKED ISSUE #2846: 🐛 BUG: environment variables are not available in server-side code
### What version of `astro` are you using?

0.24.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I cannot access "private" env variables on server-side code, even the [official example](https://github.com/withastro/astro/tree/main/examples/env-vars) is broken.

[Here](https://stackblitz.com/edit/github-ubib9u?file=src%2Fpages%2Findex.astro&on=stackblitz) you should see the `DB_PASSWORD` env printed on page, but it's `undefined`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ubib9u?file=src%2Fpages%2Findex.astro&on=stackblitz

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Fixes #2846 
- We had a regression in private env variable support during SSR, this PR fixes it.
- The regression happened with destructured `import.meta.env` references. The fix was to ensure that `import.meta.env` is replaced with an `Object.assign(import.meta.env, privateVars)` call.
- For security, only private env variables that are referenced in the file will be injected statically.

## Testing

Example is working again

## Docs

N/A, bug fix only

### CODE REVIEW

File: packages/astro/src/vite-plugin-env/index.ts [hunk 1]
```diff
@@ -68,6 +71,13 @@ export default function envVitePlugin({ config: astroConfig }: EnvPluginOptions)
 				if (privateEnv) {
 					const entries = Object.entries(privateEnv).map(([key, value]) => [`import.meta.env.${key}`, value]);
 					replacements = Object.fromEntries(entries);
+					// These additional replacements are needed to match Vite
+					replacements = Object.assign(replacements, {
+						// This catches destructed `import.meta.env` calls,
+						// BUT we only want to inject private keys referenced in the file.
+						// We overwrite this value on a per-file basis.
+						'import.meta.env': `({})`,
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-env/index.ts:79]: This was the main fix, we have to replace `import.meta.env` _in addtion to_ `import.meta.env.NAME`

File: packages/astro/src/vite-plugin-env/index.ts [hunk 2]
```diff
@@ -93,7 +104,15 @@ export default function envVitePlugin({ config: astroConfig }: EnvPluginOptions)
...
 				const start = match.index;
 				const end = start + match[0].length;
-				const replacement = '' + replacements[match[1]];
+				let replacement = '' + replacements[match[1]];
+				// If we match exactly `import.meta.env`, define _only_ referenced private variables
+				if (match[0] === 'import.meta.env') {
+					replacement = `(Object.assign(import.meta.env,{`
+					for (const key of references.values()) {
+						replacement += `${key}:${privateEnv[key]},`
+					}
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-env/index.ts:113]: Importantly, we only inline secret vars that we know are referenced in the file.

File: packages/astro/test/fixtures/astro-envs/src/pages/destructured.astro [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+const { PUBLIC_PLACE, SECRET_PLACE } = import.meta.env;
```
Comment (natemoo-re) [inline packages/astro/test/fixtures/astro-envs/src/pages/destructured.astro:2]: Added a test for destructured usage

**Review by tony-sull — APPROVED** [review]
Nice!  Very cool fix for supporting destructuring without leaking any extra private variables

**Review by bholmesdev — APPROVED** [review]
Truly the `env`y of other projects 👏
