### PR TITLE
Gif animation would not loop

### LINKED ISSUE #13683: Astro converts looping animated gifs into non-looping webp
### Astro Info

```block
Astro                    v5.7.4
Node                     v22.14.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-expressive-code
                         @astrojs/mdx
                         @astrojs/sitemap
                         astro-icon
                         @altano/astro-opengraph
                         astro-typed-links
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

all browsers

### Describe the Bug

I noticed that the infinitely-looping animated gifs on my site were being converted to webp animations, and it worked well except that the animations would pause after 1 loop. It would not loop infinitely.

I determined that the webp animations loop infinitely in dev ssg builds but NOT production ssg builds. I wanted to make sure it was the actual webp file problem's fault and not my browser so I investigated further and:
  - The webp spec has [an ANIM header definition](https://developers.google.com/speed/webp/docs/riff_container#animation)
  - The loop count is: "16 bits (uint16) - The number of times to loop the animation. If it is 0, this means infinitely."
  - In a dev build, my gif is converted to a webp with a loop count integer of 0. it loops infinitely.
  - in prod build, the loop count is 1. it does NOT loop after finishing.
  - In a hex editor, I changed the webp's loop count from "1" to "0" and it started looping infinitely.

I'm not sure what the bug is here, and why it's different between dev and prod. But I have absolutely no changes to the default image service, which I assume is sharp. I did find [this `animated: true` option you can pass to the webp converter](https://sharp.pixelplumbing.com/api-output/#webp) so perhaps that's something we need to add for .gif files.

### What's the expected result?

I would expect my gifs to loop infinitely, restarting when they reach the end. I am attaching a zip file with 4 images:

1 - this is the original gif ✅
2 - dev mode output from Astro. works great ✅
3 - prod mode output from Astro. does not loop ❌
4 - prod mode output that I've edited in a hex editor to change loop count to 0. works great  ✅ 

[images.zip](https://github.com/user-attachments/files/19903910/images.zip)

### Link to Minimal Reproducible Example

stackblitz doesn't allow file upload, so I can't repro there

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by L4Ph**
## Changes
- Fixed an issue where animation would stop when converting from GIF to WebP

fix #13683 #13689 #13741 

## Testing

I looked at all the previous commits and it seemed like there were no tests, so I didn't write any.
I'll write some if necessary.

### CODE REVIEW

**Review by ematipico — COMMENTED** [review]
I doubt it's possible to test the final result, somehow. Did you test the fix manually? 
I'll create a preview release so users can test it

**Comment by L4Ph** [comment]
> I doubt it's possible to test the final result, somehow. Did you test the fix manually? 
> I'll create a preview release so users can test it 

Yes, I have confirmed that it is actually looping. (pnpm --filter @example/blog run build and preview)

**Comment by L4Ph** [comment]
https://github.com/L4Ph/astro-gif-animation-bug-repro
You can try it here.

**Review by ematipico — APPROVED** [review]

File: packages/astro/src/assets/services/sharp.ts [hunk 1]
```diff
@@ -108,7 +108,20 @@ const sharpService: LocalImageService<SharpImageServiceConfig> = {
...
+				inputBuffer[0] === 0x47 && // 'G'
+				inputBuffer[1] === 0x49 && // 'I'
+				inputBuffer[2] === 0x46 && // 'F'
+				inputBuffer[3] === 0x38 && // '8'
+				(inputBuffer[4] === 0x39 || inputBuffer[4] === 0x37) && // '9' or '7'
+				inputBuffer[5] === 0x61; // 'a'
+
+			if (transform.format === 'webp' && isGifInput) {
+				// Convert animated GIF to animated WebP with loop=0 (infinite)
+				result.webp({ quality: typeof quality === 'number' ? quality : undefined, loop: 0 });
```
Comment (fz6m) [inline packages/astro/src/assets/services/sharp.ts:121]: Not all GIF images loop forever. Should we detect the loop setting and respect it ?
