### PR TITLE
fix: correctly handle multiple wildcard path aliases

### LINKED ISSUE #13051: Multiple tsconfig path variants are not supported
### Astro Info

```block
Astro                    v5.1.3
Node                     v23.4.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap
                         @astrojs/preact
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

I have added this excerpt to tsconfig.json:

```json
"compilerOptions": {
  "baseUrl": ".",
  "paths": {
    "@/*": [
      "./src/*/index.tsx",
      "./src/*/index.astro",
      "./src/*.astro",
      "./src/*"
    ],
  }
}
```

Then I create `src/layouts/Page.astro` file

In another file, I add this import:

`import Page from "@/layouts/Page";`

It resolves in language server and autocompletes, but astro build (both prod and dev) breaks failing to find the file.
Only the first path in the array is actually used (as seen in the repro example if you swap the alias items)

Although as per [included plugin code](https://github.com/withastro/astro/blob/main/packages/astro/src/vite-plugin-config-alias/index.ts#L39), it seems that it was intended to handle multiple paths

### What's the expected result?

Each path in the array checked as in [tsconfig docs](https://www.typescriptlang.org/docs/handbook/modules/reference.html#fallbacks)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-l1fmx58y?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

A bug in the way the patterns were generated meant that if there were multiple wildcard patterns in a path alias, only the first would ever match.

Fixes #13051

## Testing

Added test cases

### CODE REVIEW

File: packages/astro/src/vite-plugin-config-alias/index.ts [hunk 1]
```diff
@@ -33,10 +33,9 @@ const getConfigAlias = (settings: AstroSettings): Alias[] | null => {
 					.join('')}$`,
 			);
 
-			/** Internal index used to calculate the matching id in a replacement. */
-			let matchId = 0;
-
 			for (const value of values) {
+				/** Internal index used to calculate the matching id in a replacement. */
+				let matchId = 0;
```
Comment (ascorbic) [inline packages/astro/src/vite-plugin-config-alias/index.ts:38]: This is the fix. The index needs resetting between paths, because it's per-regex

**Review by ematipico — APPROVED** [review]

**Review by florian-lefebvre — APPROVED** [review]
