### PR TITLE
Fix subpath support regressions

### LINKED ISSUE #1338: 🐛 BUG: pageUrlFormat: 'file' creates `.html` file
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Creating dynamic pages e.g `[user].astro` or `/user/[user].astro` when `pageUrlFormat` is set to `file` results in an `.html` file created inside the directory
```
   Pages                
 ┌ /1-bevon-westby/.html
 ├ ....
 ├ /index.html          
 ├ ....
 └ /user/10-zackariah-dallywater/.html
```
When I would have expected
```
   Pages                
 ┌ /1-bevon-westby.html
 ├ ....
 ├ /index.html          
 ├ ....
 └ /user/10-zackariah-dallywater.html
```
**Note:** When running `astro dev` logged URLs are correct e.g.
```
[access] /10-zackariah-dallywater
```
though I am unsure if this is really the case or not as the same is logged irregardless of URL format.

### Steps to Reproduce

1.  git clone https://github.com/coelmay/astro-pageurlformat-bug.git
2. cd astro-pageurlformat-bug
3. yarn
4. yarn build

### Link to Minimal Reproducible Example (Optional)

https://github.com/coelmay/astro-pageurlformat-bug

### LINKED ISSUE #2322: 🐛 BUG: Subpath builds fail
### What version of `astro` are you using?

0.22.x

### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

In moving the docs site to `/docs`, `astro build` no longer references the framework component assets correctly. The build succeeds, but no JS or CSS loads correctly in the final site.

I have not tested whether the `subpath` example is also building a broken site. Because the build succeeds, it wouldn't be caught by our smoke test.

To reproduce: build the new docs repo and try `astro preview`. If `astro preview` is also broken for subpath builds, try testing the output directly with something like `npx serve` (may need to rename `dist` to `docs` so that the serve package hosts the final build at the proper subpath.)

### Link to Minimal Reproducible Example

https://github.com/withastro/docs

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- The preview server now handles cases where a forward-slash is not included in the base correctly.
  - Non-forward slash URLs are redirected to the forward-slash variant.
- The build now always includes a relative path `'./'` for the URLs it creates.
- Closes #2322
- Closes #1338

## Testing

- Tests for the preview server were added to match what we already have for the dev server.

## Docs

N/A, bug fix.

### CODE REVIEW

**Review by natemoo-re — COMMENTED** [review]
This looks good to me with the exception of a potential missed edge case!

File: packages/astro/src/core/path.ts [hunk 1]
```diff
@@ -0,0 +1,12 @@
...
+export function appendForwardSlash(path: string) {
+  return path.endsWith('/') ? path : path + '/';
+}
+
+export function prependForwardSlash(path: string) {
+	return path[0] === '/' ? path : '/' + path;
+}
+
+export function prependDotSlash(path: string) {
+	return path[0] === '.' ? path : './' + path;
```
[the remark this answers is not in the document]
Comment (matthewp) [reply packages/astro/src/core/path.ts]: Fixed with e4d60b2db53199dc9b4c4b56e0ec7e5eb73ce957

**Review by natemoo-re — APPROVED** [review]
LGTM!

File: packages/astro/src/core/preview/index.ts [hunk 2]
```diff
@@ -33,9 +45,29 @@ export default async function preview(config: AstroConfig, { logging }: PreviewO
 			return;
 		}
 
-		send(req, req.url!.substr(base.length - 1), {
+		const requrl = removeBase(base, req.url!);
+
+		// Redirect /docs to /docs/
+		if(requrl === '/' && !req.url!.endsWith('/')) {
```
Comment (FredKSchott) [inline packages/astro/src/core/preview/index.ts:51]: we have `devOptions.trailingSlash: "always" | "never" | "ignore";` as a config value, I'd imagine that this would read from that behavior and act accordingly?

Comment (matthewp) [reply packages/astro/src/core/preview/index.ts:51]: What is the behavior of that supposed to be? Does "always" mean a trailing slash is required and 404 or does it mean that we forward to the trailing slash (this behavior)? 

Having trouble finding docs or where this was implemented.

Comment (matthewp) [reply packages/astro/src/core/preview/index.ts:51]: This is helpful: https://github.com/withastro/astro/pull/1197/files
