### PR TITLE
Fix Windows dev script proxying

### LINKED ISSUE #2053: 🐛 BUG: Vite inline script proxing broken on Windows
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Scripts don’t proxy correctly in dev on Windows:

unknown-1

unknown

### Link to Minimal Reproducible Example

(windows-only bug)

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #2053. In dev, Windows was getting bad URLs for script proxying. This behavior only existed in dev, not build, so dev tests needed to be added that we didn’t have before.

## Testing

Tests added that didn’t exist before.

## Docs

No docs changes.

### CODE REVIEW

File: packages/astro/src/core/ssr/index.ts [hunk 1]
```diff
@@ -266,7 +266,8 @@ export async function render(renderers: Renderer[], mod: ComponentInstance, ssrO
 
   // run transformIndexHtml() in dev to run Vite dev transformations
   if (mode === 'development') {
-    html = await viteServer.transformIndexHtml(viteifyURL(filePath), html, pathname);
+    const relativeURL = filePath.href.replace(astroConfig.projectRoot.href, '/');
+    html = await viteServer.transformIndexHtml(relativeURL, html, pathname);
```
Comment (drwpow) [inline packages/astro/src/core/ssr/index.ts:270]: Big change 1: use project-relative URLs to generate the script proxies.

Note that `relativeURL` will be `/index.astro`, while `pathname` will be `/`. Both are needed because Vite doesn’t know `'.astro' === '.html'`.

File: packages/astro/src/core/ssr/css.ts [hunk 2]
```diff
@@ -9,27 +9,23 @@ export const STYLE_EXTENSIONS = new Set(['.css', '.pcss', '.postcss', '.scss', '
...
   // recursively crawl module graph to get all style files imported by parent id
   function crawlCSS(entryModule: string, scanned = new Set<string>()) {
-    const moduleName = idToModuleMap.get(entryModule);
-    if (!moduleName) return;
-    if (!moduleName.id) return;
+    const moduleName = viteServer.moduleGraph.urlToModuleMap.get(entryModule);
+    if (!moduleName || !moduleName.id) return;
     // mark the entrypoint as scanned to avoid an infinite loop
-    scanned.add(moduleName.id);
+    scanned.add(moduleName.url);
```
Comment (drwpow) [inline packages/astro/src/core/ssr/css.ts:19]: Big change 2: use `url` instead of `id` in Vite’s module graph. Here’s the difference between the two, according to Vite:

### ID
- Linux/Mac: `/Users/astro/code/my-project/src/pages/index.astro`  ✅ valid in module graph & in browser
- Windows: `C:/Users/astro/code/my-project/src/pages/index.astro` ❌ valid in module graph but not valid in browser (the original bug)

### URL
- Linux/Mac: `/@fs/Users/astro/code/my-project/src/pages/index.astro` ✅ valid in module graph & in browser
- Windows: `/@fs/C:/Users/astro/code/my-project/src/pages/index.astro` ✅ valid in module graph & in browser

This PR uses URLs instead so that the same value can be placed in the browser and resolved.

File: packages/astro/src/core/util.ts [hunk 3]
```diff
@@ -77,9 +77,9 @@ export function resolveDependency(dep: string, astroConfig: AstroConfig) {
...
  * Given a file URL, return an ID that matches Vite’s module graph. Needed for resolution and stack trace fixing.
  * Must match the following format:
- * Linux/Mac:  /Users/astro/code/my-project/src/pages/index.astro
- * Windows:    C:/Users/astro/code/my-project/src/pages/index.astro
+ * Linux/Mac:  /@fs/Users/astro/code/my-project/src/pages/index.astro
+ * Windows:    /@fs/C:/Users/astro/code/my-project/src/pages/index.astro
  */
 export function viteifyURL(filePath: URL): string {
-  return slash(fileURLToPath(filePath));
+  return `/@fs${filePath.pathname}`;
```
Comment (drwpow) [inline packages/astro/src/core/util.ts:84]: Updates the `viteifyURL` function to use module graph `url` over `id`

File: packages/astro/src/core/ssr/index.ts (hunk 1 above)
Comment (drwpow) [reply packages/astro/src/core/ssr/index.ts:270]: Note the `/:/` is because `C:/` isn’t the start of a browser-compatible pathname

File: packages/astro/test/react-component.test.js [hunk 4]
```diff
@@ -4,98 +4,125 @@ import { loadFixture } from './test-utils.js';
...
-    const html = await fixture.fetch('/index.html');
-
-    // Grab the imports
-    const exp = /import\("(.+?)"\)/g;
-    let match, componentUrl;
-    while ((match = exp.exec(html))) {
-      if (match[1].includes('Research.js')) {
-        componentUrl = match[1];
-        break;
+  describe('dev', () => {
```
Comment (drwpow) [inline packages/astro/test/react-component.test.js:75]: No build tests changed; only added “dev” tests

File: packages/astro/src/core/dev/index.ts [hunk 5]
```diff
@@ -329,14 +328,7 @@ export class AstroDevServer {
...
       const statusCode = 500;
-      const mod = filePath && this.viteServer.moduleGraph.getModuleById(viteifyURL(filePath));
-      if (mod) {
-        for (const m of [mod, ...mod.importedModules]) {
-          this.viteServer.moduleGraph.invalidateModule(m);
-        }
-      } else {
-        this.viteServer.moduleGraph.invalidateAll();
-      }
+      await this.viteServer.moduleGraph.invalidateAll();
```
Comment (drwpow) [inline packages/astro/src/core/dev/index.ts:331]: Last change: when something threw an error, we were doing too much work to only invalidate some modules. If something has erred, just invalidate everything 🤷🏻.

File: packages/astro/test/react-component.test.js [hunk 6]
```diff
@@ -4,98 +4,125 @@ import { loadFixture } from './test-utils.js';
...
-  it.skip('Throws helpful error message on window SSR', async () => {
-    const html = await fixture.readFile('/window/index.html');
-    expect(html).to.include(
-      `[/window]
-    The window object is not available during server-side rendering (SSR).
-    Try using \`import.meta.env.SSR\` to write SSR-friendly code.
-    https://docs.astro.build/reference/api-reference/#importmeta`
-    );
-  });
+    // TODO: is this still a relevant test?
```
Comment (tony-sull) [inline packages/astro/test/react-component.test.js:60]: Hmm, it seems like this should still be a useful test?

Test #2 checks that `data-reactroot` isn't added to the test page's `<Hello />` component since it isn't using client hydration.  It looks like this test would be making sure that `data-reactroot` is still used on the hydrated `<Research />` component

What I'm not actually sure on is whether `data-reactroot` is still used to flag hydrated react components.  If yes, I think this and test #2 should be useful, if no I think both tests aren't helpful anymore (since test #2 would always get undefined regardless of how hydration was used)

**Review by tony-sull — APPROVED** [review]
Nice!  These fixes to handle Windows filenames and the test updates look great to me :+1: 

Added one note on a skipped test, but I'm not 100% sure on whether the test is useful or not and don't think that should block merging in these fixes

File: packages/astro/test/react-component.test.js (hunk 6 above)
Comment (drwpow) [reply packages/astro/test/react-component.test.js:60]: So this test has been skipped since the move to Vite/`0.21`. @natemoo-re what should this test look for now?

Comment (natemoo-re) [reply packages/astro/test/react-component.test.js:60]: I believe `data-reactroot` is required for hydrated components still. If this test is broken it might be a symptom of a bug we need to fix. Happy to spin off into a separate PR.

Comment (drwpow) [reply packages/astro/test/react-component.test.js:60]: Sounds good. Yeah if that could be investigated separately (ideally testing dev and build) that would be good. This test needs to be updated, but I wasn’t sure exactly how (and is unrelated to this PR).
