### PR TITLE
Fix hydration for framework components in MDX slots

### LINKED ISSUE #14518: Unable to hydrate components dynamically using `Astro.slots.render` inside `mdx`.
### Astro Info

```block
Astro                    v5.14.4
Node                     v22.20.0
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/svelte (v7.2.0)
                         @astrojs/react (v4.4.0)
                         @astrojs/mdx (v4.3.7)
```

### If this issue only occurs in one browser, which browser is a problem?

Not relevant

### Describe the Bug

Using `Astro.slots.render` inside a component that is rendered inside MDX results in broken hydration.
### What's the expected result?

Both should be able to hydrate without any problems.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/Hugos68/astro-inconsistent-hydration-behaviour

Steps:
1. Open the root page, will redirect to `/bar/mdx`
2. View the 4 links, each link will bring you to a "environment"
3. Each page shows wether the `FrameworkComponent` component (in this case Svelte, but the same happens with other frameworks) (with client:load) hydrated correctly by checking for `import.meta.env.SSR`.
4. View that on all pages it goes from `false` to `true`, which is expected, except that on `/bar/mdx` it stays on `false`.
5. Be confused 😁

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Fixes #14518
- Framework components with `client:*` directives inside named slots now correctly hydrate when using `Astro.slots.render()` in MDX
- Previously, only the first slot would hydrate; subsequent slots rendered HTML but lost hydration scripts

## Testing

Added test case in `packages/integrations/mdx/test/mdx-plus-react.test.js` that verifies both `/foo` and `/bar` pages have hydration scripts when using named slots with `Astro.slots.render()`.

## Docs

No docs changes needed - this is a bug fix for existing behavior.

### CODE REVIEW

File: packages/astro/src/runtime/server/render/slot.ts [hunk 1]
```diff
@@ -27,6 +27,21 @@ export function isSlotString(str: string): str is any {
...
 
+/**
+ * Collects instructions from a SlotString into the target array.
+ * Returns the (possibly newly created) instructions array.
+ */
+export function mergeSlotInstructions(
+	target: RenderInstruction[] | null,
+	source: SlotString,
+): RenderInstruction[] | null {
+	if (source.instructions) {
```
Comment (Fryuni) [inline packages/astro/src/runtime/server/render/slot.ts]: An empty array is truthy (`!![] => true`), which would create a new array without any real need.


```suggestion
	if (source.instructions?.length) {
```
