### PR TITLE
Fix tsconfig alias regression

### LINKED ISSUE #6613: Internal server error: Failed to resolve import "lib/getClient" from...
### What version of `astro` are you using?

2.1.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I'm using astro with TypeScript. I set `compilerOptions.baseUrl` and `import some from 'lib/thing'`. 2.1.3 works fine, but 2.1.4 broken below error

```
Internal server error: Failed to resolve import "lib/getClient" from...
```

thanks

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-u39yd1?file=package.json

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by MoustaphaDev**
## Changes

Fix #6613

## Testing

Check that Typescript file without `.ts` extension can be imported

## Docs

N/A, bug fix only

### CODE REVIEW

File: packages/astro/src/vite-plugin-config-alias/index.ts [hunk 1]
```diff
@@ -72,16 +72,19 @@ export default function configAliasVitePlugin({
...
 		},
-		resolveId(id) {
+		async resolveId(id, importer, options) {
 			if (id.startsWith('.') || id.startsWith('/')) return;
 
 			// Handle baseUrl mapping for non-relative and non-root imports.
 			// Since TypeScript only applies `baseUrl` autocompletions for files that exist
 			// in the filesystem only, we can use this heuristic to skip resolve if needed.
 			const resolved = path.posix.join(resolvedBaseUrl, id);
-			if (fs.existsSync(resolved)) {
```
Comment (MoustaphaDev) [inline packages/astro/src/vite-plugin-config-alias/index.ts:82]: When importing TypeScript files without the `.ts` extension, this condition is always false, as `/path/to/ts-flie` doesn't exist.
I thought about checking for TypeScript files but, I realized that there could be other file types that could be resolved when not specifying the extension, maybe via vite plugins pushed before the ts resolver?

Comment (ematipico) [reply packages/astro/src/vite-plugin-config-alias/index.ts:82]: Great call!

File: packages/astro/test/alias-tsconfig.test.js [hunk 2]
```diff
@@ -44,10 +44,16 @@ describe('Aliases with tsconfig.json', () => {
 
 		it('works in css @import', async () => {
 			const html = await fixture.fetch('/').then((res) => res.text());
-			console.log(html);
 			// imported css should be bundled
 			expect(html).to.include('#style-red');
 			expect(html).to.include('#style-blue');
 		});
+
+		it('can load load typescript files without .ts extension', async () => {
```
Comment (ematipico) [inline packages/astro/test/alias-tsconfig.test.js:52]: nit: ".ts or .d.ts files extensions."

**Review by ematipico — APPROVED** [review]

**Comment by MoustaphaDev** [comment]
There's a weird path issue occuring on Windows, I'll debug this on my windows machine

**Review by bluwy — APPROVED** [review]
Windows passes now! It was because it checked for absolute imports via `.startsWith('/')` which doesn't match on Windows. I've changed that to `path.isAbsolute`.

**Comment by MoustaphaDev** [comment]
Thanks for jumping in @bluwy!
