### PR TITLE
Properly compute `currentLocale` when `path` segment contains `.html`

### LINKED ISSUE #14228: i18n: `Astro.currentLocale` is default locale during SSG on index pages generated with `getStaticPaths` and `build.format: file`
### Astro Info

```block
Astro                    v5.12.9
Node                     v22.18.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

N/A

### Describe the Bug

With the following values in `astro.config.mjs`:
```
build: {
    format: 'file',
  },
output: 'static',
trailingSlash: 'never',
```
and an `i18n` config that includes a `defaultLocale` and one or more additional locales:
```
i18n: {
    defaultLocale: 'en-us',
    locales: [
      {
        path: 'en-us',
        codes: ['en-US'],
      },
      {
        path: 'es-mx',
        codes: ['es-MX'],
      },
      {
        path: 'fr-fr',
        codes: ['fr-FR'],
      },
    ],
  },
```

During SSG (`astro build`), `getStaticPaths` on an Astro page at the root/index of a route with a `[locale]` param (`/pages/[locale].astro` or `/pages/[locale]/index.astro`) makes the output of `Astro.currentLocale` fall back to the `defaultLocale` instead of the locale that matches the value of the `locale` param. On non-index routes (i.e. `/[locale]/about.astro`), `Astro.currentLocale` correctly outputs a locale that matches the value of the `locale` param.

For example, given the configuration above and `/pages/[locale]/index.astro`:
- locale `en-us` will output `en-us.html` and `Astro.currentLocale` will be `en-US`
- locale `es-mx` will output `es-mx.html` and `Astro.currentLocale` will be `en-US`
- locale `fr-fr` will output `fr-fr.html` and `Astro.currentLocale` will be `en-US`

### What's the expected result?

During SSG (`astro build`), `getStaticPaths` on an Astro page at the root/index of a route with a `[locale]` param (`/pages/[locale].astro` or `/pages/[locale]/index.astro`), `Astro.currentLocale` correctly outputs a locale that matches the value of the `locale` param.

For example, given the configuration above and `/pages/[locale]/index.astro`:
- locale `en-us` will output `en-us.html` and `Astro.currentLocale` will be `en-US`
- locale `es-mx` will output `es-mx.html` and `Astro.currentLocale` will be `es-MX`
- locale `fr-fr` will output `fr-fr.html` and `Astro.currentLocale` will be `fr-FR`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-kpnpjbu2?file=src%2Fpages%2Findex.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by jonmichaeldarby**
## Changes

- Adds `normalizeThePath` utility function to remove `.html` from the end of a path or path segment, if it exists, otherwise returns the path or path segment unmodified
- Introduces `normalizeThePath` to `pathHasLocale` and `computeCurrentLocale` to normalize path segments in these functions
- Fixes #14228, where index pages have an incorrect `currentLocale` during SSG under certain conditions:
  - page uses a param and `getStaticPaths` (like `/pages/[locale]/index.astro` or `/pages/[locale].astro`)
  - config has `build.format: file` and `output: static`
- Adds tests to cover the cases described above

## Testing

This change was tested by running the newly introduced tests via `node --test packages/astro/test/i18n-routing.test.js`

## Docs

This corrects a bug and makes `Astro.currentLocale` behave as expected and currently documented under the conditions described above.

### CODE REVIEW

File: packages/astro/src/i18n/index.ts [hunk 1]
```diff
@@ -19,12 +19,13 @@ export function requestHasLocale(locales: Locales) {
 export function pathHasLocale(path: string, locales: Locales): boolean {
 	const segments = path.split('/');
 	for (const segment of segments) {
+		const normalizedSegment = normalizeThePath(segment);
```
Comment (ematipico) [inline packages/astro/src/i18n/index.ts]: This function is only used here, so there's no need to have a function. We can add a `.map` after the `split` at line 20 and have the mapping logic there.

Also, since this happens for a specific case e.g. `fr-fr.html`, we could leave a comment that explains the `.html` check

**Review by ematipico — COMMENTED** [review]
The solution and tests and looks good. Just left a minor comment regarding the solution

File: .changeset/weak-maps-give.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Properly compute currentLocale when path segment contains .html
```
Comment (ematipico) [inline .changeset/weak-maps-give.md]: Can you reword the changeset in a way that it's more clear for end-users? If I was one, I wouldn't understand what "use case" we just fixed

Comment (jonmichaeldarby) [reply .changeset/weak-maps-give.md]: Thank you for the feedback. I refined the language in the latest commit. Please let me know if this is more clear.

File: packages/astro/src/i18n/index.ts (hunk 1 above)
Comment (jonmichaeldarby) [reply packages/astro/src/i18n/index.ts]: `normalizeThePath` is also used in `packages/astro/src/i18n/utils.ts`, so I think the function improves maintainability by ensuring the same normalization is applied consistently in both places. Doing the replacement inline could cause drift between the two implementations. Happy to change it if you disagree.

Thank you for the suggestion to use `.map`, that is much more straightforward and clear. I updated both implementations and added comments.

File: .changeset/weak-maps-give.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Ensure `Astro.currentLocale` returns a configured locale (instead of the `defaultLocale`) during SSG on pages that use a locale param and `getStaticPaths` (such as `[locale].astro` or `[locale]/index.astro`, which produce `[locale].html`) by removing `.html` from the path before locale checks.
```
Comment (delucis) [inline .changeset/weak-maps-give.md]: I think we can probably simplify this for clarity:

```suggestion
Ensures `Astro.currentLocale` returns the correct locale during SSG for pages that use a locale param (such as `[locale].astro` or `[locale]/index.astro`, which produce `[locale].html`)
```

- “correct locale” is probably enough to communicate the fix
- removed `getStaticPaths` mention as we already mentioned SSG, so `getStaticPaths` is implied
- removed details of the internal code change as that’s an implementation detail and we aim for the changelogs to be user facing, explaining what changed for them, rather than for us
