### PR TITLE
fix(cli): prevent production install on add cmd

### LINKED ISSUE #8037: `astro add` causes dev dependencies to be removed from node_modules
### What version of `astro` are you using?

2.10.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### What browser are you using?

Firefox

### Describe the Bug

Using `astro add` causes a weird issue, where any existing installed dev dependencies will be removed from `node_modules`.

Stackblitz has repro instructions, but here's some you can also use locally.

1. new project (`npm create astro@latest`)
2. install a dev dependency (e.g. `npm i daisyui -D`)
3. check it exists in node_modules
4. use astro add (e.g. `npx astro add react -y`)
5. check to find the dev dependency missing from node_modules, but still in the package.json

### What's the expected result?

Dev dependencies to still be present, after using `astro add`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3sk8rq?file=md!README.md&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by xstevenyung**
## Changes

- force `NODE_ENV=development` on installation command run when using `astro add` command to prevent installation to remove `devDependencies`

## Testing

no real way to test

## Docs

no need

fix #8037

### CODE REVIEW

File: packages/astro/src/cli/add/index.ts [hunk 1]
```diff
@@ -700,7 +700,7 @@ async function tryToInstallIntegrations({
 						...inheritedFlags,
 						...installCommand.dependencies,
 					],
-					{ cwd }
+					{ cwd, env: { NODE_ENV: 'development' } }
```
Comment (bluwy) [inline packages/astro/src/cli/add/index.ts:703]: Interesting! We actually set the `NODE_ENV` here so the config file is loaded correctly:

https://github.com/withastro/astro/blob/0d4922dffe7d96b907db89ec502f77efd572cc56/packages/astro/src/cli/index.ts#L127

On this line, could we set `NODE_ENV: undefined` instead to reset the value? Also would be great to add an additional comment explaining why we need it.

Comment (xstevenyung) [reply packages/astro/src/cli/add/index.ts]: the reset seems to work with `undefined`.
i also added a comment to explain why we are doing this 👍

**Comment by jacobthesheep** [comment]
Can’t wait for this PR to be merged

**Review by ematipico — APPROVED** [review]

**Comment by ematipico** [comment]
@xstevenyung can you add a changeset via `pnpm changeset`?

**Comment by xstevenyung** [comment]
added the changeset as a minor bump

File: .changeset/great-queens-yawn.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': minor
```
Comment (bluwy) [inline .changeset/great-queens-yawn.md:2]: I think this should be a patch since it's causing an unexpected behaviour before. We usually reserve minors for new features.

Comment (bluwy) [reply .changeset/great-queens-yawn.md:2]:
```suggestion
'astro': patch
```

**Review by bluwy — APPROVED** [review]
