### PR TITLE
fix(dev): preserve query params when base path is stripped

### LINKED ISSUE #15095: Query params trigger 404 error in dev
### Astro Info

```block
Astro                    v5.16.6
Vite                     v6.4.1
Node                     v24.12.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/solid-js (v5.1.3)
                         @astrojs/sitemap (v3.6.0)
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When `trailingSlash` is set to anything other than `ignore`, query params cause a 404 page in `dev` mode.

Reproduction steps:
1. Set the `base` path in the config  
2. Set `trailingSlash` to `never`  
3. Navigate to the index page (now at the base path) – works fine  
4. Add query params to the URL and refresh – results in a 404 error

### What's the expected result?

Page loads fine

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-svbaysc1?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by eureka0928**
Fixes #15095

## Changes

- What does this change?

Updated `baseMiddleware` to ensure that after stripping the base path, the resulting URL always starts with `/` when it's not empty. This preserves query parameters and ensures proper URL parsing downstream.

**After:**
```typescript
let newUrl = url.replace(devRoot, devRootReplacement);
// Ensure the URL is a valid path (e.g., /base?foo=bar -> /?foo=bar, not ?foo=bar)
if (newUrl !== '' && !newUrl.startsWith('/')) {
    newUrl = '/' + newUrl;
}
req.url = newUrl;
```

- `packages/astro/src/vite-plugin-astro-server/base.ts`: Added logic to prepend `/` when the stripped URL doesn't start with `/` and isn't empty
- `packages/astro/src/vite-plugin-astro-server/request.ts`: Already had normalization logic that handles the empty string pathname case (no changes needed)
- `packages/astro/test/units/routing/trailing-slash.test.js`: Test already exists for this scenario (issue #15095)

## Testing

The fix ensures that:
1. `/base?query=test` → strips to `/?query=test` → normalizes to empty string pathname for route matching ✅
2. `/base` → strips to empty string → normalizes correctly ✅
3. `/base/` → strips to `/` → normalizes correctly ✅

- tested with minimal example

{01D2EAEA-075C-46BD-A5E4-D6BE4694A946}
{BEBBE330-54BE-4976-950F-B6ECB59B73BC}
{2D884BBA-C1FE-490C-BCC6-467CE5C35C21}

## Docs

Contribution by Gittensor, see my contribution statistics at https://gittensor.io/miners/details?githubId=42954461

### CODE REVIEW

**Comment by fury0928** [comment]
@florian-lefebvre can you review my PR? please give me feedback
Thank you for your time

**Comment by florian-lefebvre** [comment]
Hi, some tests are not passing. Can you fix them first?

**Comment by fury0928** [comment]
@florian-lefebvre I’ve added the test screenshot; please review it again.
All tests have passed.
Thank you for your time.

File: packages/astro/src/vite-plugin-astro-server/base.ts [hunk 1]
```diff
@@ -13,10 +13,20 @@ export function baseMiddleware(
...
+		const site = config.site ? new URL(config.base, config.site) : undefined;
+		devRootURL = new URL(config.base, 'http://localhost');
+		devRoot = site ? site.pathname : devRootURL.pathname;
+		devRootReplacement = devRoot.endsWith('/') ? '/' : '';
+	} catch {
+		// If base is invalid, default to '/'
+		devRootURL = new URL('/', 'http://localhost');
+		devRoot = '/';
+		devRootReplacement = '/';
+	}
```
Comment (florian-lefebvre) [inline packages/astro/src/vite-plugin-astro-server/base.ts]: Instead of a try/catch, could it be possible to have the previous code but with `config.base || '/'`

File: .changeset/bumpy-cats-sneeze.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixes an issue where requests with query parameters to the base path would return a 404 error in dev mode when `trailingSlash` is set to `'never'` or `'always'`. The `baseMiddleware` now ensures URLs always start with `/` after stripping the base path, preserving query parameters for proper route matching.
```
Comment (florian-lefebvre) [inline .changeset/bumpy-cats-sneeze.md]:
```suggestion
Fixes an issue where requests with query parameters to the `base` path would return a 404 if trailingSlash was not 'ignore' in development
```

File: packages/astro/src/vite-plugin-astro-server/base.ts [hunk 3]
```diff
@@ -13,8 +13,9 @@ export function baseMiddleware(
 	logger: Logger,
 ): vite.Connect.NextHandleFunction {
 	const { config } = settings;
-	const site = config.site ? new URL(config.base, config.site) : undefined;
-	const devRootURL = new URL(config.base, 'http://localhost');
+	const base = config.base || '/';
```
Comment (florian-lefebvre) [inline packages/astro/src/vite-plugin-astro-server/base.ts:17]:
```suggestion
	// The base may be an empty string by now, causing the URL creation to fail. We provide a default instead
	const base = config.base || '/';
```

File: .changeset/bumpy-cats-sneeze.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixes an issue where requests with query parameters to the `base` path would return a 404 if trailingSlash was not 'ignore' in development
```
Comment (florian-lefebvre) [inline .changeset/bumpy-cats-sneeze.md]:
```suggestion
Fixes an issue where requests with query parameters to the `base` path would return a 404 if trailingSlash was not `'ignore'` in development
```

**Comment by fury0928** [comment]
Hi @florian-lefebvre would you review once more?
I noticed this test error is not related to my changes...
{B1A9B721-ED47-4D65-9B52-09632B8A2D2D}

**Comment by grundmanise** [comment]
Thanks @eureka928  for your work. But I'm still seeing this issue. It seems to be resolved on the dev server, but the problem still happens once the project is built. It behaves the same way, breaking with `trailingSlash: "never"` for URLs like `http://localhost:4321/directory?foo=bar`.

It might be connected, so I wanted to add here that it seems this note:
>Additionally, Astro will internally manipulate the configured value of config.base before making it available to integrations. The value of config.base as read by integrations will also be determined by your trailingSlash configuration in the same way.

from https://docs.astro.build/en/reference/configuration-reference/#base might not actually be the case, and I can see the base with a trailing slash when for `item.url` within the `sitemap` plugin's `serialize` method:
```
    sitemap({
      serialize(item) {
        console.log(item.url); // Will have trailing slash at the base path even with `trailingSlash: "never"`
        return item;
      },
    }),
   ```
   
   Might still be a separate issue, but wanted to share here in case that's related.
