### PR TITLE
[@astrojs/image]: Fix <Picture /> component with query string

### LINKED ISSUE #4996: [@astrojs/image]: Picture not working with query parameter
### What version of `astro` are you using?

1.4.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When running `build` with a picture and a query parameter in src I get the following error:
`Error: Expected one of: heic, heif, avif, jpeg, jpg, jpe, tile, dz, png, raw, tiff, tif, webp, gif, jp2, jpx, j2k, j2c for format but received jpg?test=test of type string`

To determine the file extension the query parameter should be ignore. It works in dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qnk2xr-4dvsmq?file=src%2Fpages%2Findex.astro&on=stackblitz

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by panwauu**
## Changes

- When the file extension is created the query parameters are removed
- By removing the query parameters only after the dot of the file extension, we should not have any problem with question marks in filenames/paths/...

## Testing

- Was not yet able to run tests yet (Happy for any help)
- [image-ssr-build.test.js](https://github.com/withastro/astro/blob/671fca7dac5847b91c9b3357742cca8a80cccede/packages/integrations/image/test/image-ssr-build.test.js#L59) does include a test with query string the other tests dont. Should we maybe unify all the tests that we always test the same images in all image-ssr-build/dev/ssg and also picture?

## Docs

As it is a bugfix, there is no documentation added.

Fixes #4996

### CODE REVIEW

**Comment by tony-sull** [comment]
Thanks for opening this PR, always great to see a new issue and a bug fix PR opened at the same time!

I'm really curious why this is passing in the `<Image />` test but doesn't work for `<Picture />`, let me dig in a little more and see exactly what's going on.

:100: agree it would be nice to have the tests refactored a little more to align what images are used.  A few cases only make sense for `<Image />` like the "no transforms" test case, but that shouldn't block a good refactor here

**Comment by tony-sull** [comment]
Ah ha, `getPicture()` has to do an `extname` check that isn't needed for `getImage()` and it wasn't account for query params

@panwauu You were spot on with the `removeQueryParams()` check, I just moved it down a level into `basename` in case another code path ever hits it directly with query params.  I didn't refactor the test suite but that's a great idea, in the meantime I added a couple missing test cases to the SSG picture suite

Feel free to reach out if you're interested in working on a test refactor here!  Happy to help get you setup to run the tests locally and walk through how they're working today 🙌

File: packages/integrations/image/src/utils/paths.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ function removeExtname(src: string) {
 }
 
 function basename(src: string) {
-	return src.replace(/^.*[\\\/]/, '');
+	return removeQueryString(src.replace(/^.*[\\\/]/, ''));
```
Comment (tony-sull) [inline packages/integrations/image/src/utils/paths.ts:35]: This is the bug fix, `basename` should be stripping off query params

**Review by tony-sull — APPROVED** [review]
