### PR TITLE
fix(astro): prevent crash on unexpected file in pages

### LINKED ISSUE #2033: 🐛 BUG: astro build crashes with cryptic error if *.module.css file inside pages/
### What version of `astro` are you using?

0.21.4

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

1. Place (by mistake) a file with the `.module.css` extension inside the `src/pages` directory
2. Run `astro build` 
3. astro crashes with the following error:

```
Cannot read properties of undefined (reading 'getAllHydratedComponentPaths')
TypeError: Cannot read properties of undefined (reading 'getAllHydratedComponentPaths')
```
Astro should either ignore the file or output a clearer error to warn the user that the file format is not supported in that location. Not that `astro dev` runs without issues.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-b3v7bi?file=src/pages/styles.module.css

### PR DESCRIPTION
**Pull request by ludofischer**
Fix #2033

## Changes
* Prevent a crash with unhandled file types in `src/pages`
* Skip files in `src/pages` when extension is not '.astro' or '.md'

## Testing

Added a new test case to `packages/astro/test/route-manifest.test.js`. 
## Docs

No, bug fix only.

### CODE REVIEW

File: packages/astro/src/core/ssr/routing.ts [hunk 1]
```diff
@@ -86,6 +86,7 @@ interface Item {
 export function createRouteManifest({ config, cwd }: { config: AstroConfig; cwd?: string }, logging: LogOptions): ManifestData {
   const components: string[] = [];
   const routes: RouteData[] = [];
+  const validExtensions: Set<string> = new Set(['.astro', '.md']);
```
Comment (drwpow) [inline packages/astro/src/core/ssr/routing.ts:89]: 👍🏻

**Review by drwpow — APPROVED** [review]
This LGTM! Nice test, too.
