### PR TITLE
fix(vercel): validate densities-based srcset widths against configured sizes

### LINKED ISSUE #14366: `@astrojs/vercel@8.2.7` does not check sizes config when densities is used
### Astro Info

```block
Astro                    v5.13.7
Node                     v22.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

While using the `@astrojs/vercel@8.2.7` adapter, the `<Image />` component from `astro:assets` will output widths in the `srcset` that are not valid according to the `sizes` property in `imagesConfig` when using the `densities` prop.

### What's the expected result?

Compare against `@astrojs/vercel@8.2.6` which is working here: 
https://github.com/mass8326/issue-astro-vercel-image-service-sizes/tree/main
https://astro-vercel-image-service-downgrade.vercel.app

### Link to Minimal Reproducible Example

See last image on the page here:
https://github.com/mass8326/issue-astro-vercel-image-service-sizes/tree/production
https://astro-vercel-image-service-sizes.vercel.app

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

When using densities with the Vercel image adapter, calculated widths were not being validated against the configured sizes list. This caused Vercel to reject invalid widths, resulting in broken images.

For example, with configured sizes [640, 750, 828, 1080, 1200, 1920, 2048, 3840] and width=600 with densities=[1, 1.5, 2], the calculated widths [600, 900, 1200] were used directly instead of being mapped to valid sizes [640, 828, 1200].

This fix ensures all densities-calculated widths are mapped to the nearest configured width, matching the behavior already implemented for the widths prop.

Fixes #14366

## Testing

- Test case added

## Docs

N/A, bug fix

### CODE REVIEW

File: packages/integrations/vercel/src/image/build-service.ts [hunk 1]
```diff
@@ -114,13 +118,43 @@ const service: ExternalImageService = {
...
+				};
+			});
+
+			// Dedupe widths but keep all density descriptors by grouping
+			const widthToDescriptors = new Map<number, string[]>();
+			for (const { width, descriptor } of allWidths) {
+				if (!widthToDescriptors.has(width)) {
+					widthToDescriptors.set(width, []);
+				}
+				widthToDescriptors.get(width)!.push(descriptor);
```
Comment (Princesseuh) [inline packages/integrations/vercel/src/image/build-service.ts:151]: surprised this non-null assertion doesn't trigger a linting thing

**Review by Princesseuh — APPROVED** [review]
Looks fine as far as I can tell
