### PR TITLE
Pass children to client components even if they do not render them

### LINKED ISSUE #642: 🐛 BUG: Component children aren't hydrated if they were conditionally hidden during the build
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

If a React or Preact component takes in `children` and then conditionally hides/shows the children based on internal state, if the children are initially hidden during the build they won't be available for client-side hydration.

### Steps to Reproduce

a. Clone the https://github.com/tony-sull/repro-react-conditional-hydrate
2. yarn && yarn start
d. Error! The react component hydrated, but the "Hello React!" message never shows because it wasn't included included in the built HTML

Alternate: copy the `examples/framework-{preact/react}` project.  Update the counter to only show the message when the count is above 0, `<div className="children">{count > 0 && children}</div>`

### Link to Minimal Reproducible Example (Optional)

https://github.com/tony-sull/repro-react-conditional-hydrate

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Fixes #642
- When a client component doesn't render `<astro-fragment>` but there are children, we know that means they did not render the children.
- Instead we add a `<template data-astro-template>` inside of the `<astro-root>`. In the client the HTML inside of this template becomes the children passed to the client component.

## Testing

Tests added.

## Docs

Not needed, bug fix.

### CODE REVIEW

**Review by jonathantneal — APPROVED** [review]
Interesting, clever fix.

**Review by natemoo-re — APPROVED** [review]
Woah. Clever fix! LGTM.

File: packages/astro/src/runtime/client/media.ts [hunk 1]
```diff
@@ -5,7 +5,23 @@ import type { GetHydrateCallback, HydrateOptions } from '../../@types/astro';
...
+	if(roots.length === 0) {
+		throw new Error(`Unable to find the root for the component ${options.name}`);
+	}
+
+	let innerHTML: string | null = null;
+  let fragment = roots[0].querySelector(`astro-fragment`);
+  if(fragment == null) {
+		// If there is no child fragment, check to see if there is a template.
+		// This happens if children were passed but the client component did not render any.
+    let template = roots[0].querySelector(`template[data-astro-template]`);
```
Comment (matthewp) [inline packages/astro/src/runtime/client/media.ts:17]: Note to self, this is going to check for this template any time there is not an astro-fragment. We can probably short circuit this check so it's only done when needed.

**Comment by matthewp** [comment]
Put this back to draft as I want to make one small change but need to test it locally first.

**Review by tony-sull — APPROVED** [review]
Nice, that's a very cool fix!

**Review by natemoo-re — APPROVED** [review]
Looks good!
