### PR TITLE
qol(routing): warn when api route method doesn't match the casing of an export

### LINKED ISSUE #9496: Upgrading to v4 make tRPC api requests fail in 404 error
### Astro Info

```block
Astro                    v4.0.7
Node                     v21.2.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Trying to integrate a fresh Astro 4 instalation with tRPC, following the official [docs here](https://trpc.io/docs/server/adapters/fetch#example-apps) is not working.

This issue has been also mentioned [here](https://discord.com/channels/830184174198718474/830184175176122389/1187470627356024993) and [here](https://discord.com/channels/830184174198718474/830184175176122389/1187470978058563654)

### What's the expected result?

Return a successful response when accessing 
http://localhost:4321/trpc/test or any other method under the endpoint.

### Link to Minimal Reproducible Example

https://github.com/cmnstmntmn/astro-trpc

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes

- Closes #9496
- improve messaging for getting the case wrong

## Testing

Does not affect behavior, just messaging - existing tests should pass.

## Docs

Does not affect usage.

### CODE REVIEW

File: packages/astro/src/runtime/server/endpoint.ts [hunk 1]
```diff
@@ -23,38 +11,33 @@ export async function renderEndpoint(
...
 			)} requests are not available for a static site. Update your config to \`output: 'server'\` or \`output: 'hybrid'\` to enable.`
 		);
 	}
-	if (!handler || typeof handler !== 'function') {
+	if (typeof handler !== 'function') {
+		logger.warn(
+			'router',
+			`No API Route handler exists for the method "${method}" for the route ${url.pathname}.\n` +
+			`Found handlers: ${Object.keys(mod).map(method => JSON.stringify(method)).join(', ')}\n`
+		);
```
Comment (lilnasy) [inline packages/astro/src/runtime/server/endpoint.ts:30]: image

File: .changeset/tidy-dogs-remain.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Adds helpful message for when the API Route export is not uppercase.
```
Comment (VoxelMC) [inline .changeset/tidy-dogs-remain.md:5]:
```suggestion
Adds a helpful warning message for when an exported API Route is not uppercase.
```
Possible rewording for the changeset, I hope it helps :)

File: packages/astro/src/runtime/server/endpoint.ts [hunk 3]
```diff
@@ -23,38 +11,34 @@ export async function renderEndpoint(
...
 			)} requests are not available for a static site. Update your config to \`output: 'server'\` or \`output: 'hybrid'\` to enable.`
 		);
 	}
-	if (!handler || typeof handler !== 'function') {
+	if (typeof handler !== 'function') {
+		logger.warn(
+			'router',
+			`No API Route handler exists for the method "${method}" for the route ${url.pathname}.\n` +
+			`Found handlers: ${Object.keys(mod).map(exp => JSON.stringify(exp)).join(', ')}\n` +
+			('all' in mod ? `One of the exported handlers is "all" (lowercase), did you mean to export 'ALL'?\n` : '')
```
Comment (VoxelMC) [inline packages/astro/src/runtime/server/endpoint.ts:30]: Just wondering why `all` is the only case to handle, and not any of the other verbs?

I would assume that, if the user reads "get" in the `Found handlers:` log, it should be enough.

**Review by VoxelMC — COMMENTED** [review]
Hello! I have never reviewed here, so I am sorry if anything I have said is out of scope.

These changes look very helpful for someone who has just upgraded to v4.0! I especially like the `Found handlers:` log, which will be great now that there are no deprecation notices on lowercase methods anymore.

I have left a couple of comments on my opinions. I hope they are helpful :)

File: .changeset/tidy-dogs-remain.md (hunk 2 above)
Comment (lilnasy) [reply .changeset/tidy-dogs-remain.md:5]: Much better, thanks!

File: packages/astro/src/runtime/server/endpoint.ts (hunk 3 above)
Comment (lilnasy) [reply packages/astro/src/runtime/server/endpoint.ts:30]: The most recent user to run into this was exporting "all". I agree this message should expand to "get", "post" depending what the current request's method is.

**Review by bluwy — APPROVED** [review]
I like the new warnings! Looks great

File: packages/astro/src/runtime/server/endpoint.ts (hunk 3 above)
Comment (ematipico) [inline packages/astro/src/runtime/server/endpoint.ts:30]: We **removed** the support lower-case functions in v4 (they were deprecated in v3), so we shouldn't show a warning anymore, otherwise it sounds like we still support it.

Comment (lilnasy) [reply packages/astro/src/runtime/server/endpoint.ts:30]: This message would only be shown when `pages/x.ts` existed but `/x` failed to match a handler. I think at that point, it's safe to say the user could use a helpful nudge.

Comment (ematipico) [reply packages/astro/src/runtime/server/endpoint.ts:30]: To be more precise, I talk about the `all` check. We don't support that anymore, so we shouldn't write **new** code around that. New developers would see this line and won't understand why it is there.

**Review by matthewp — APPROVED** [review]
