### PR TITLE
fix: exclude Vite requests from trailing slash handling

### LINKED ISSUE #13094: Redirect to 404 when fetching src files on dev server
### Astro Info

```block
Astro                    v5.2.0
Node                     v18.20.3
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/alpinejs
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

The dev server redirects the src files request and causes a vite internal server error after upgrading to Astro v5.2.0.

// Without the `trailingSlash` config, `src` file requests redirect to 404.
Image

// When `trailingSlash` is set to `'always'`, requests to `@vite/client` return 404.
Image
Image

### What's the expected result?

Return 200 and it would not break the page on dev server.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-4nxjmnm3?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Skips internal Vite requests when checking trailing slashes

Fixes #13094

## Testing
Adding tests now

### CODE REVIEW

**Review by florian-lefebvre — APPROVED** [review]

File: packages/astro/src/vite-plugin-astro-server/trailing-slash.ts [hunk 1]
```diff
@@ -22,6 +22,9 @@ export function trailingSlashMiddleware(settings: AstroSettings): vite.Connect.N
 			/* malformed uri */
 			return next(e);
 		}
+		if(pathname.startsWith('/_') || pathname.startsWith('/@')) {
```
Comment (ematipico) [inline packages/astro/src/vite-plugin-astro-server/trailing-slash.ts:25]: I would use `@vite` to avoid a possible clash with other tools or user-defined endpoints.

**Review by ematipico — APPROVED** [review]
I left a minor nit; it's good nonetheless!

File: packages/astro/src/vite-plugin-astro-server/trailing-slash.ts (hunk 1 above)
Comment (ascorbic) [reply packages/astro/src/vite-plugin-astro-server/trailing-slash.ts:25]: There's also `@id` and `@fs` and possibly others though. The failure mode is to just not show the helpful error page, so I'd rather err on the side of skipping too many

Comment (ematipico) [reply packages/astro/src/vite-plugin-astro-server/trailing-slash.ts:25]: 😭
