### PR TITLE
Only attach SVG component in SSR

### LINKED ISSUE #14577: Importing SVGs in client components incorrectly bundles server-side runtime and Zod, inflating bundle size
### Astro Info

```block
Astro                    v5.14.6
Node                     v22.14.0
System                   Linux (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When an SVG is imported directly within a client-side component (e.g., a React component with a client:* directive), Astro's build process incorrectly includes a significant portion of its server-side runtime (astro/dist/runtime/server) and its dependencies, most notably the zod, into the final client-side JS bundle. Imported asset does not necessarily need to be used and simply importing it is enough to trigger the behavior.

This results in a much larger bundle size than necessary. In a minimal reproduction, the component's JavaScript chunk grows from ~800 bytes to ~64KB, with the majority of the added code being unused on the client.

### What's the expected result?

Importing a static asset like an SVG into a client-side component should only add the asset's path (or metadata) to the bundle. It should not create a dependency on Astro's server-side runtime or unrelated libraries like zod. The final client bundle should remain minimal, containing only the component's logic and its direct, client-side dependencies.

---

### Steps to Reproduce

I have created an mvp that isolates this behavior and compares it against an idiomatic workaround.

**1. File Structure:**

```
.
├── astro.config.mjs
├── package.json
└── src/
    ├── assets/
    │   └── blob.svg
    ├── components/
    │   ├── SvgAsset.tsx            # <-- The leaky component
    │   └── SvgAssetIdiomatic.tsx   # <-- The correct, idiomatic component
    └── pages/
        └── index.astro
```

**2. `package.json` Dependencies:**

```json
{
  "devDependencies": {
    "@astrojs/react": "^4.4.0",
    "astro": "^5.14.6",
    "react": "^19",
    "react-dom": "^19",
    "@types/react": "^19",
    "@types/react-dom": "^19",
    "rollup-plugin-visualizer": "^6.0.5",
    "typescript": "^5.9.3"
  }
}
```

**3. `astro.config.mjs`: (with rollup-plugin-visualizer to see the issue)**

```javascript
import react from '@astrojs/react';
import { defineConfig } from 'astro/config';

export default defineConfig({
  output: 'static',
  integrations: [react()],
  vite: {
    plugins: [
      visualizer({
        filename: './bundle-stats.html',
        open: true,
      }),
    ],
  },
  sourcemap: false,
  minify: true,
});
```

**4. `src/pages/index.astro`:** (Switch between idiomatic and leaky versions)

```astro
---
import { SvgAsset } from '../components/SvgAsset';
// import { SvgAssetIdiomatic } from '../components/SvgAssetIdiomatic';
// import svg from '../assets/blob.svg';
---
<html lang="en">
  <body>
    <!-- Leaky version -->
    <SvgAsset client:load />

    <!-- Idiomatic version -->
    <!-- <SvgAssetIdiomatic src={svg.src} client:load /> -->
  </body>
</html>
```

**5. `src/components/SvgAsset.tsx`:** (The leaky component)

```tsx
import svg from '../assets/blob.svg'; // <-- This import is the trigger, even without usage in jsx

export const SvgAsset = () => {
  return <img src={svg.src} width={200} height={200} />;
};
```

**6. `src/components/SvgAssetIdiomatic.tsx`:** (The "correct", idiomatic component)

```tsx
// Receives the src path as a simple prop, no direct asset import.
export const SvgAssetIdiomatic = ({ src }: { src: string }) => {
  return <img src={src} width={200} height={200} />;
};
```

**7. Build and Compare:**

Run `yarn build` and observe the generated file sizes in the `dist/_astro` directory.

| Component             | JS Chunk Size | Contains `zod` and Astro Runtime? |
| --------------------- | ------------- | --------------------------------- |
| `SvgAsset.js`         | **~64 KB**    | Yes                               |
| `SvgAssetIdiomatic.js`| **~800 bytes**| No                                |

#### Leaky: 
```bash
$ ls -laRh ./dist/
./dist/:
total 24K
drwxrwxr-x 3 user user 4.0K Oct 19 18:03 .
drwxrwxr-x 9 user user 4.0K Oct 19 18:03 ..
drwxrwxr-x 2 user user 4.0K Oct 19 18:03 _astro
-rw-rw-r-- 1 user user  749 Oct 19 18:03 favicon.svg
-rw-rw-r-- 1 user user 4.4K Oct 19 18:03 index.html

./dist/_astro:
total 268K
drwxrwxr-x 2 user user 4.0K Oct 19 18:03 .
drwxrwxr-x 3 user user 4.0K Oct 19 18:03 ..
-rw-rw-r-- 1 user user  466 Oct 19 18:03 blob.8oQT23o1.svg
-rw-rw-r-- 1 user user 191K Oct 19 18:03 client.Bx7k8SOM.js
-rw-rw-r-- 1 user user  64K Oct 19 18:03 SvgAsset.CthMt7Gs.js
```

#### With zod leak patch: (more on that below)

```bash
$ ls -laRh ./dist/
./dist/:
total 24K
drwxrwxr-x 3 user user 4.0K Oct 19 18:32 .
drwxrwxr-x 9 user user 4.0K Oct 19 18:32 ..
drwxrwxr-x 2 user user 4.0K Oct 19 18:32 _astro
-rw-rw-r-- 1 user user  749 Oct 19 18:32 favicon.svg
-rw-rw-r-- 1 user user 4.4K Oct 19 18:32 index.html

./dist/_astro:
total 216K
drwxrwxr-x 2 user user 4.0K Oct 19 18:32 .
drwxrwxr-x 3 user user 4.0K Oct 19 18:32 ..
-rw-rw-r-- 1 user user  466 Oct 19 18:32 blob.8oQT23o1.svg
-rw-rw-r-- 1 user user 191K Oct 19 18:32 client.Bx7k8SOM.js
# Still has 11KB of extra size
-rw-rw-r-- 1 user user  11K Oct 19 18:32 SvgAsset.DUn8c5kd.js 
```

#### Expected:
```bash
$ ls -laRh ./dist/
./dist/:
total 24K
drwxrwxr-x 3 user user 4.0K Oct 19 18:03 .
drwxrwxr-x 9 user user 4.0K Oct 19 18:03 ..
drwxrwxr-x 2 user user 4.0K Oct 19 18:03 _astro
-rw-rw-r-- 1 user user  749 Oct 19 18:03 favicon.svg
-rw-rw-r-- 1 user user 4.5K Oct 19 18:03 index.html

./dist/_astro:
total 208K
drwxrwxr-x 2 user user 4.0K Oct 19 18:03 .
drwxrwxr-x 3 user user 4.0K Oct 19 18:03 ..
-rw-rw-r-- 1 user user  466 Oct 19 18:03 blob.8oQT23o1.svg
-rw-rw-r-- 1 user user 191K Oct 19 18:03 client.Bx7k8SOM.js
# Expected size
-rw-rw-r-- 1 user user  802 Oct 19 18:03 SvgAssetIdiomatic.CaxcG2tI.js
```

The total `dist` folder size increases by ~60KB due to this issue.

### Visualization

**With the leaky SVG import (`SvgAsset.tsx`):**
The bundle contains large blocks for `zod` and `astro/dist/runtime/server`.

Image

**After Applying a Partial Fix (`/* @__PURE__ */`):**
The `zod` types block is successfully removed, but a significant portion of the `astro/dist` runtime remains.

Image

**Without the leaky SVG import (using the idiomatic prop-passing approach):**
The `zod` and server runtime blocks are completely gone, and the bundle is minimal as expected.

Image

### Investigation & Root Cause

A deep dive into the source code and build output reveals a specific tree-shaking failure.

1.  **The Trigger:** Importing an SVG inside a client component (`SvgAsset.tsx`) causes Astro to transform the import into an **Astro Component Factory**. This creates a dependency on Astro's server-side runtime.

Doing `console.log(svg)` at build time shows:
```js
[Function (anonymous)] {
isAstroComponentFactory: true,
moduleId: undefined,
propagation: undefined,
src: '/_astro/blob.8oQT23o1.svg',
width: 200,
height: 200,
format: 'svg'
}
```

Doing `console.log(svg)` at runtime (inside component) shows:
```js
function n(a)
format: "svg"
height: 200
isAstroComponentFactory: true
length: 0
moduleId: undefined
name: ""
propagation: undefined
src: "/_astro/blob.8oQT23o1.svg"
toJSON: function value()
width: 200
```

2.  **The Leaky Dependency:** The server runtime depends on configuration validation schemas from `src/core/csp/config.ts`, which are built using `zod`. This pulls `zod` into the dependency graph for the client bundle.

3.  **Tree-Shaking Failure:** The most revealing part is *how* the `zod` code appears in the final bundle. The original source code defines schemas like this:
    ```typescript
    // astro/src/core/csp/config.ts
    export const cspAlgorithmSchema = z.enum(...);
    ```

Image

Image
    
Build output contains this:

Image

In the client bundle, the variable assignment (`const cspAlgorithmSchema =`) is correctly removed because it's unused. However, the function call itself remains as a top-level call with no assignment (`z.enum(...);`), because the bundler cannot prove it is pure and free of side effects.

4.  **Confirming the Fix:** Manually editing `node_modules/astro/dist/core/csp/config.js` to add `/* @__PURE__ */` annotations to the Zod schema definitions confirms the issue. With this change, `zod` is successfully tree-shaken from the final bundle. However, the rest of the `astro/dist/runtime/server` code (**~11KB**) still remains, indicating a broader issue with server-only code not being fully eliminated from client builds.

Image

Image

The ideal solution would be for the client-side representation of an imported asset to be a plain data object, which would break the dependency on the server runtime altogether and prevent this entire class of tree-shaking issues.

My current suggestion is to leave those /* PURE */ annotations in leaky places to fix the part of the problem which adds the most of the size, however:
- I'm not sure if this breaks anything with SSR and astro being bundled there (although docs states: `Rollup will tree-shake i.e. remove the call unless the return value is used in some code that is not tree-shaken`, so this should have no side effects, except for being confusing for devs interacting with the code).
- It could be better to fix the root cause of SSR runtime being put into static client side bundle by reconsidering how svg import is processed or split parts of the SSR runtime into separate tree-shakable isolated files.

Thus I'm not initiating a pull request of any kind yet.

### Link to Minimal Reproducible Example

https://github.com/SanariSan/astro-bundle-inflation-bug

### Participation

- [x] I am willing to submit a pull request for this issue. (if the `pure` solution is acceptable, otherwise I'd pass further R&D to the team)

### LINKED ISSUE #14615: Error hydrating: picocolors does not provide an export named 'default'
### Astro Info

```block
Astro                    v5.15.1
Vite                     v6.4.1
Node                     v20.19.1
System                   Linux (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node (v9.5.0)
Integrations             @astrojs/react (v4.4.0)
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

After updating from 5.14.8 to 5.15.1, an error started appearing in the browser console.

> [astro-island] Error hydrating /src/components/Header.tsx SyntaxError: The requested module '/node_modules/picocolors/picocolors.browser.js?v=70bfba13' does not provide an export named 'default' (at endpoint.js?v=70bfba13:1:8)

I’m checking it with `npm run dev`.

#### Updates

~~Essentially, is this the same issue as https://github.com/withastro/astro/issues/14577 ?~~

It seems to occur even when using images other than SVG, such as PNG, in a client component.

### What's the expected result?

No errors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-v3vslw94?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by delucis**
## Changes

- Closes #14615 
- Closes #14577
- This PR updates the assets Vite plugin to only attach the Astro component to SVG imports in SSR. Currently the component is attached for all contexts.

## Testing

- I tested by applying this using `pnpm patch` in the reproductions for both the above issues, and it fixed both cases.
- Existing tests should pass.
- I’ve added a test that checks that a React component which imports an SVG does not have a large bundle size after `astro build`. Running this test on `main` results in a bundle of 66&nbsp;KB. On the PR branch, the bundle is under 1&nbsp;KB.
- There’s a similar test added for the dev server which checks that the SVG module doesn’t contain any `import` statements, i.e. it only exports the image metadata.

## Docs

n/a — bug fix

### CODE REVIEW

File: packages/astro/src/assets/vite-plugin-assets.ts [hunk 1]
```diff
@@ -241,16 +241,17 @@ export default function assets({ fs, settings, sync, logger }: Options): vite.Pl
 						});
 					}
 
-					if (id.endsWith('.svg')) {
```
Comment (florian-lefebvre) [inline packages/astro/src/assets/vite-plugin-assets.ts:244]: I think we should still emit something like this on the client tho:
```ts
export default Object.assign(function () {
	throw new Error('Cannot use SVG component on the client')
}, imageMetadata)
```

Comment (delucis) [reply packages/astro/src/assets/vite-plugin-assets.ts:244]: But they might just be using the metadata which is fine right?

Comment (delucis) [reply packages/astro/src/assets/vite-plugin-assets.ts:244]: Ah, I see, you're saying that calling the root would error. Yes, I guess we could. Still means extra client code for people though.

And I think they'd hit SSR errors first? i.e. this change still means the Astro component code is attached in client components when rendering on the server. So I guess usage will already break except maybe for `client:only` components.

Comment (florian-lefebvre) [reply packages/astro/src/assets/vite-plugin-assets.ts:244]: The error would probably be a bit cryptic tho? I think erroring with an "intentional" error is better but yeah that adds a tiny bit of js.

EDIT: that means they would get "X is not a function" I guess?

Comment (delucis) [reply packages/astro/src/assets/vite-plugin-assets.ts:244]: > that means they would get "X is not a function" I guess?

Yeah exactly. But for any component (except `client:only` ones) the server render would _already_ have failed before, so adding this to the client doesn’t really help in most cases I don’t think.

Comment (florian-lefebvre) [reply packages/astro/src/assets/vite-plugin-assets.ts:244]: I agree but I think it doesn't mean we can't make it friendlier! People get tricked regularly

Comment (delucis) [reply packages/astro/src/assets/vite-plugin-assets.ts:244]: Sure, but a) it should be done for the _server_ side version as highest priority because mostly that will fail first and the client code will never even be hit and b) that can be done in a separate PR (it’s an issue with the current behaviour already and this PR doesn’t touch any of the generated SSR code).

(And I’d argue adding client code to a production build for logging this error for user misuse would be a mistake, because it penalises everyone using the feature correctly, so if we did do it for the client module, we’d have to make sure it was dev-only.)
