### PR TITLE
fix: astrodb vite plugin throws in vitest and cannot seed database

### LINKED ISSUE #11414: getViteConfig throws in Vitest - Cannot read properties of undefined (reading 'ASTRO_DATABASE_FILE')
### Astro Info

```block
Astro                    v4.11.5
Node                     v20.10.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro:db
                         @astrojs/db/file-url
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

There's an error if I run vitest with astro's `getViteConfig`:
```
➜  astrodb-vitest-repro git:(main) px vitest run
20:46:26 [types] Added src/env.d.ts type declarations.

 RUN  v1.6.0 /home/hl/ws/test/astrodb-vitest-repro

20:46:26 [astro:db] New local database created.
20:46:26 [ERROR] [astro:db] Cannot read properties of undefined (reading 'ASTRO_DATABASE_FILE')
 ✓ src/test.test.ts (1)
   ✓ test

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  20:46:26
   Duration  584ms (transform 8ms, setup 0ms, collect 8ms, tests 1ms, environment 0ms, prepare 43ms)
```

Moreover, if I import the db in the test file (`import { db } from "astro:db"`) and set vitest's `poolOptions.threads.singleThread` to true, the test will fail half of the time.

### What's the expected result?

No error should be showing when running vitest.

### Link to Minimal Reproducible Example

https://github.com/haivuw/astrodb-vitest-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by haivuw**
## Changes

Fixes #11414

`import.meta.env` is undefined in the virtual module which make it throw and the database is not seeded. 

## Testing

Tested by linking local @astrojs/db in my other project. Db was seeded ok.

## Docs

just a minor bug fix

### CODE REVIEW

**Comment by haivuw** [comment]
I couldn't run tests https://github.com/withastro/astro/issues/11441

**Comment by marpe** [comment]
Just ran into this issue, would be nice to have this merged.

**Comment by matthewp** [comment]
@haivuw can you update this PR

**Comment by haivuw** [comment]
@matthewp I resolved the conflicts but this test failed:
https://github.com/withastro/astro/blob/ff522b96a01391a29b44f820dfcc2a2176d871e7/packages/db/test/local-prod.test.js#L37C3-L37C4

The path to local db is malformed: /D:/a/astro/astro/packages/db/testixtures�asicsdistastro.db

```
✖ failing tests:

test at file:\D:\a\astro\astro\packages\db\test\local-prod.test.js:50:3
✖ Can render page
  'test did not finish before its parent and was cancelled'

test at file:\D:\a\astro\astro\packages\db\test\local-prod.test.js:37:2
✖ build (not remote) with DATABASE_FILE env (relative file path) (683.227ms)
  [astro:db] Could not load astro:db (imported by test/fixtures/local-prod/src/pages/index.astro): Failed to connect to database: `Unable to open connection to local database /D:/a/astro/astro/packages/db/testixturesasicsdistastro.db: 14`
  Error: Failed to connect to database: `Unable to open connection to local database /D:/a/astro/astro/packages/db/testixturesasicsdistastro.db: 14`
      at new Database (D:\a\astro\astro\node_modules\.pnpm\libsql@0.4.5\node_modules\libsql\index.js:83:17)
      at _createClient (file:///D:/a/astro/astro/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/sqlite3.js:47:16)
      at _createClient (file:///D:/a/astro/astro/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/node.js:21:16)
      at Module.createClient (file:///D:/a/astro/astro/node_modules/.pnpm/@libsql+client@0.14.0/node_modules/@libsql/client/lib-esm/node.js:11:12)
      at Module.createLocalDatabaseClient (D:/a/astro/astro/packages/db/dist/runtime/db-client.js:25:40)
      at eval (astro:db:seed:8:34)
      at async instantiateModule (file:///D:/a/astro/astro/node_modules/.pnpm/vite@5.4.9_@types+node@18.19.50_sass@1.79.5/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52961:5) {
    code: 'PLUGIN_ERROR',
    pluginCode: '',
    plugin: 'astro:db',
    hook: 'load',
```

I don't have the capacity to make sure all tests pass right now. So this is as far as I can do.

File: packages/db/src/core/integration/vite-plugin-db.ts [hunk 1]
```diff
@@ -124,12 +124,14 @@ export function getLocalVirtualModContents({
 	tables: DBTables;
 	root: URL;
 }) {
+	const { ASTRO_DATABASE_FILE } = getAstroEnv();
+	const envDbUrl = ASTRO_DATABASE_FILE ? `'${ASTRO_DATABASE_FILE}'` : undefined;
```
Comment (ematipico) [inline packages/db/src/core/integration/vite-plugin-db.ts:128]: I don't think you need to stringify the string, because it's already a string. We already to such here:

https://github.com/withastro/astro/blob/ff522b96a01391a29b44f820dfcc2a2176d871e7/packages/db/src/core/integration/vite-plugin-db.ts#L211-L212

File: .changeset/lemon-beans-admire.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'@astrojs/db': patch
+---
+
+Fix astro:db:seed cannot access env ASTRO_DATABASE_FILE
```
Comment (ematipico) [inline .changeset/lemon-beans-admire.md:5]:
```suggestion
Fixes a bug where `astro:db:seed` couldn't access to the environment variable `ASTRO_DATABASE_FILE`
```

**Review by ematipico — CHANGES_REQUESTED** [review]

File: packages/db/src/core/integration/vite-plugin-db.ts (hunk 1 above)
Comment (haivuw) [reply packages/db/src/core/integration/vite-plugin-db.ts:128]: It will be
```ts
const dbUrl = normalizeDatabaseUrl(file://local.db, ${JSON.stringify(dbUrl)});
```
without stringification.

But I just realized I could have used JSON.stringify, so I'll update.

Comment (ematipico) [reply packages/db/src/core/integration/vite-plugin-db.ts:128]: I see. The failing test is definitely weird though, I wonder what's causing the failure

Comment (haivuw) [reply packages/db/src/core/integration/vite-plugin-db.ts]: I think the test passed before because ASTRO_DATABASE_URL was not passed to the plugin at all.

And this line of the test generates a malformed URL on Windows:
https://github.com/withastro/astro/blob/ff522b96a01391a29b44f820dfcc2a2176d871e7/packages/db/test/local-prod.test.js#L39

Comment (haivuw) [reply packages/db/src/core/integration/vite-plugin-db.ts]: Hopefully someone with Windows machine can fix that.

Comment (haivuw) [reply packages/db/src/core/integration/vite-plugin-db.ts]: Wait it passed now 💀

Comment (haivuw) [reply packages/db/src/core/integration/vite-plugin-db.ts]: I'm not sure what magic JSON.stringify does here.

**Review by ematipico — APPROVED** [review]
