### PR TITLE
Set action input default values from zod if FormData key is not present

### LINKED ISSUE #11659: [FEATURE] - default values for input schema for Server Actions
### Astro Info

```block
Astro                    v4.13.1
Node                     v22.4.0
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/node
Integrations             @clerk/astro/integration
                         @astrojs/react
                         @astrojs/tailwind
                         astro:db
                         @astrojs/db/file-url
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

I have a FormSchema, that I use for the client and on the server. The input for a server action doesn't return a default value where I was expecting it. I discovered this because I wanted to pass in an array of Files to upload to a bucket but the server kept saying that my input for `images` is invalid. 

So I did a little investigation and found the part that would fix my use case and opened a [PR](https://github.com/withastro/astro/pull/11655). I've since taken it down so I'm raising this issue instead.

Ultimately, what I wanted was a list of Files from the client in the server action and it was throwing an error because the `.default()` method was not being handled.

```
export const PropertyFormSchema = z.object({
  images: z.array(z.instanceof(File)).default([]),
});
```

```
defineAction({
    accept: "form",
    input: PropertyFormSchema,
    handler: async (input, context) => {}
})
```

### What's the expected result?

I expected this input to handle this correctly:

`z.array(z.instanceof(File)).default([])` to return an empty array or a list of Files.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7qnawk?file=src%2Fcomponents%2FPropertyForm.tsx

Couldn't reproduce on stackblitz. Seems like I can't perform server actions on there.

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by billy-le**
## Changes

- What does this change?

Resolves #11659

This changes `formDataToObject` to allow default values to be set from zod.

## Testing

Add tests to capture changes. I ran unit tests for this specific change and it passes. Not sure if the whole project tests are working correctly since I was getting some failures.

### CODE REVIEW

**Comment by billy-le** [comment]
Adding some context on why I added this:

I was working on server actions and I have a file input that accepts multiple files. I'm using zod with a property of `z.array(z.instanceOf(File)).default([])` Whenever I submitted the FormData to my action, I kept getting an error because the `formDataToObject` validator skipped over instances of z.ZodDefault and where it was expecting an array, but converted it to an object.

It looks like the `z.ZodDefault` wasn't accounted for so I thought I would add this bit.

There might be a case when someone could chain a bunch of `z...default('').default('')` and it will produce the same error that I had but it seems minor at the moment.

File: packages/astro/src/actions/runtime/virtual/server.ts [hunk 1]
```diff
@@ -137,6 +137,21 @@ export function formDataToObject<T extends z.AnyZodObject>(
...
+   		// else continue to get correct zod class
+		if(validator instanceof z.ZodDefault) {
+			if(!formData.has(key)) {
+				obj[key] = validator._def.defaultValue();
+				continue;
+			}
+
+			while (validator instanceof z.ZodOptional || validator instanceof z.ZodNullable) {
+				validator = validator._def.innerType;
+			}
```
Comment (bholmesdev) [inline packages/astro/src/actions/runtime/virtual/server.ts:151]: I'm noticing this `while` loop is copied from the clause above. Is there a need to repeat here? Or is there a way to move the check for `default` above the initial `while` loop to catch it from there?

File: .changeset/nervous-garlics-beam.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Set action input default values from zod if FormData key is not present
```
Comment (bholmesdev) [inline .changeset/nervous-garlics-beam.md:5]:
```suggestion
Fixes Astro Actions `input` validation when using `default` values with a form input.
```

Noticed the changeset described what code changes we made internally, instead of what was fixed _as a user._ Rephrased to describe the fix!

**Review by bholmesdev — COMMENTED** [review]
Sorry, that was my (de)fault for not checking against `default` validators. Great fix! Just a couple comments

File: packages/astro/src/actions/runtime/virtual/server.ts (hunk 1 above)
Comment (billy-le) [reply packages/astro/src/actions/runtime/virtual/server.ts:151]: Oh yeah, that could be improved.  The reason for the repeat is that someone could infinitely chain these methods together in any order. I will need to figure out a way to recursively check all instances that capture that.

I have noticed here that we're only going to be checking for these 3 instances, however, someone could chain other instances like `.nullabe()`, `.or()`, etc. which might throw errors.

I'm unsure what's the best way to handle that but in this case, I can fix this one issue with `.default()` for the time being.

**Comment by billy-le** [comment]
Hey @bholmesdev, I've updated my code. Let me know if there's anything you think I might have missed!

**Review by ematipico — APPROVED** [review]
