### PR TITLE
Preserve Cloudflare miniflare instance across dev server config restarts

### LINKED ISSUE #15524: Using Fonts and CloudFlare Adapter causes an Expected `miniflare` to be defined error
### Astro Info

```block
Astro                    v6.0.0-beta.11
Vite                     v7.3.1
Node                     v24.13.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/cloudflare (v13.0.0-beta.7)
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using the fonts API with cloudflare adapter, I get a `[ERROR] [vite] Internal server error: Expected `miniflare` to be defined` when I load the index page when in dev mode. 

Full stack trace
```
15:13:05 [ERROR] [vite] Internal server error: Expected `miniflare` to be defined
      at get miniflare (ossified-halo/node_modules/.pnpm/@cloudflare+vite-plugin@1.25.0_vite@7.3.1_workerd@1.20260212.0_wrangler@4.65.0_@cloudflare+workers-types@4.20260214.0_/node_modules/@cloudflare/vite-plugin/dist/index.mjs:1734:3)
      at ossified-halo/node_modules/.pnpm/@cloudflare+vite-plugin@1.25.0_vite@7.3.1_workerd@1.20260212.0_wrangler@4.65.0_@cloudflare+workers-types@4.20260214.0_/node_modules/@cloudflare/vite-plugin/dist/index.mjs:26347:18
      at ossified-halo/node_modules/.pnpm/@cloudflare+vite-plugin@1.25.0_vite@7.3.1_workerd@1.20260212.0_wrangler@4.65.0_@cloudflare+workers-types@4.20260214.0_/node_modules/@cloudflare/vite-plugin/dist/index.mjs:1593:25
      at call (ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:10605:5)
      at next (ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:10558:4)
      at ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:22365:28
      at viteServeStaticMiddleware (ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:22451:4)
      at call (ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:10605:5)
      at next (ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:10558:4)
      at viteServeRawFsMiddleware (ossified-halo/node_modules/.pnpm/vite@7.3.1/node_modules/vite/dist/node/chunks/config.js:22484:10)
```

### What's the expected result?

Pages load. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-auwgrqay

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
Closes #15524

## Changes

- When `astro.config.mjs` changes in dev mode, Astro previously tore down the entire Vite server and created a brand new one. The Cloudflare adapter ties miniflare's lifetime to the Vite server instance, so this caused miniflare to be disposed and recreated — triggering `Expected 'miniflare' to be defined` errors on the next request, and 404s while the new instance was initializing.
- Instead of tearing down the server, Astro now performs a Vite in-place restart on config changes: it rebuilds the Astro plugin list from the new config, patches it onto the existing server via `vite.resolveConfig`, then calls Vite's native `restartServer()`. Vite mutates the existing server object in place and passes `previousEnvironments` to plugins, giving the Cloudflare adapter the opportunity to reuse its existing miniflare instance rather than dispose it.
- As a side effect, this significantly simplifies the dev restart code. The `vite-plugin-restart.ts` intermediary plugin and the separate `handleServerRestart` path are removed — plugin-triggered restarts now go through Vite natively without Astro intercepting them.

## Testing

- Manually tested with a minimal Astro + Cloudflare adapter project: editing `astro.config.mjs` multiple times in a row no longer produces miniflare errors or 404s.
- Added a test verifying the same `viteServer` instance is reused across a config file restart (proving no new server is created).
- Added a test verifying watcher listener count stays stable across multiple restarts (guards against listener accumulation regression).
- Existing tests updated to reflect the new restart behavior; all pass.

## Docs

No docs update needed — this is a bug fix with no user-facing API changes.

### CODE REVIEW

File: packages/astro/src/core/dev/restart.ts [hunk 1]
```diff
@@ -72,46 +53,79 @@ function shouldRestartContainer(
...
 	container.restartInFlight = true;
 
 	try {
-		const { astroConfig } = await resolveConfig(container.inlineConfig, 'dev', container.fs);
-		if (astroConfig.security.csp) {
-			logger.warn(
-				'config',
-				"Astro's Content Security Policy (CSP) does not work in development mode. To verify your CSP implementation, build the project and run the preview server.",
-			);
-		}
```
Comment (Princesseuh) [inline packages/astro/src/core/dev/restart.ts:86]: seems like we lost this, not sure if we want to keep it or not.

Comment (matthewp) [reply packages/astro/src/core/dev/restart.ts:86]: I didn't do this intentionally, I thought it was duplicated of the Shiki one but can see that it's not. Doesn't this just always add a warning for all CSP users in dev? @ematipico Can we remove this? Better for docs I think?

Comment (ematipico) [reply packages/astro/src/core/dev/restart.ts:86]: Not really. First, this isn't the only logging we have. There are two instances.
Second, the configuration gets re evaluated at the restart, hence we need to show the logging again.

We already document the limitations. I don't have strong opinions about the logging. 

If you want to remove it, you must remove the other logging too

Comment (matthewp) [reply packages/astro/src/core/dev/restart.ts:86]: The Shiki logging? I think that one makes sense to keep because using Shiki with CSP isn't supported. The user can fix this by not using Shiki.

But in this case the user can't "fix" anything, it's just a warning that they shouldn't expect CSP to work. So there's nothing they can do to get rid of the warning (other than disabling CSP!)

Make sense?
