### PR TITLE
fix: prevent font copying when stopping dev server with q+enter

### LINKED ISSUE #15091: "dist\_astro\fonts" folder with font files is created in dev when using experimental fonts API and "q+enter" to stop dev server
### Astro Info

```block
Astro                    v5.16.6
Vite                     v6.4.1
Node                     v24.12.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using the experimental Fonts API, in dev, using the "q+enter" combo to stop the dev server shows the following message (depending on the number of font weights in use; 2 in this example):

`[assets] Copying fonts (4 files)...`

Additionally, a "dist\_astro\fonts" directory is created in the project folder which is populated by a woff and woff2 file for each font weight (2 font weights = 4 files as shown above).

Development mode should not be creating a "dist" folder, as I understand it. Using "ctrl+c" to stop the dev server does NOT show that message or create the files. Only "q+enter" does.

[More info](https://discord.com/channels/830184174198718474/1455650533468667934)

Thanks.

### What's the expected result?

Using "q+enter" to stop the dev server should:
Not display a message.
Not create a  "dist\_astro\fonts" folder or copy font files to it.

Reproducible Example Notes:

- It appears Stackblitz cannot download fonts from Google Fonts. So it is not a 100% completely accurate test. If there is a way to configure Stackblitz to download fonts from Google Fonts, please let me know.
- The "dist" folder is created when typing "q+enter" in the Stackblitz terminal, but it contains no font files since no font files were able to be downloaded from Google Fonts.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ezwwqufb

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by kedarvartak**
## Changes

- Closes #15091
- Added `isBuild` check in `buildEnd()` hook to prevent font copying during dev server shutdown
- Font copying now only occurs during `astro build`, not when stopping dev server with q+enter
- Added test case to verify no dist folder is created when dev server stops
- Changeset added: `fix-dev-quit-fonts-dist-creation.md`

## Testing

- Added test: "Does not create dist folder or copy fonts when dev server stops"
- Manual verification that q+enter no longer creates dist folder or copies fonts
- Verified fonts still work correctly in dev mode
- Verified astro build still copies fonts as expected

## Docs

No docs changes needed. This fixes incorrect behavior in dev mode. User-facing behavior remains the same.

### CODE REVIEW

File: packages/astro/src/assets/fonts/vite-plugin-fonts.ts [hunk 1]
```diff
@@ -308,38 +308,44 @@ export function fontsPlugin({ settings, sync, logger }: Options): Plugin {
...
+		if (sync || settings.config.experimental.fonts!.length === 0) {
+			cleanup();
+			return;
+		}
+
+		// Only copy fonts during build, not when dev server is shutting down
+		if (!isBuild) {
+			cleanup();
+			return;
+		}
```
Comment (florian-lefebvre) [inline packages/astro/src/assets/fonts/vite-plugin-fonts.ts]: Could we just merge both conditions?

**Comment by florian-lefebvre** [comment]
The test is failing, can you look into that?

File: packages/astro/src/assets/fonts/vite-plugin-fonts.ts (hunk 1 above)
Comment (kedarvartak) [reply packages/astro/src/assets/fonts/vite-plugin-fonts.ts]: updated

**Comment by florian-lefebvre** [comment]
Ping me when tests pass and I'll be happy to review!
