### PR TITLE
Fix: better collection entry devalue error

### LINKED ISSUE #6764: using z.transform() with dayjs throw a DevalueError
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

nodejs

### What package manager are you using?

pnpm

### What operating system are you using?

linux

### What browser are you using?

Brave

### Describe the Bug

When you define a schema in the content folder that transform an input into a dayjs instance, it throws an error.
It does work fine with standard DateTime object, which is weird because we can JSON.stringify both dayjs and DateTime instances.

```ts
import dayjs from 'dayjs';

const blog = defineCollection({
  // Type-check frontmatter using a schema
  schema: z.object({
    title: z.string(),
    description: z.string(),
    // Transform string to Date object
    pubDate: z
      .string()
      .refine((date) => dayjs(date, 'DD-MM-YYYY').isValid())
      .transform((date) => dayjs(date, 'DD-MM-YYYY')),
    updatedDate: z
      .string()
      .refine((date) => dayjs(date, 'DD-MM-YYYY').isValid())
      .optional()
      .transform((date) => (date ? dayjs(date, 'DD-MM-YYYY') : undefined)),
    heroImage: z.string().optional(),
  }),
});
```

```sh
DevalueError: Cannot stringify arbitrary non-POJOs
    at walk (file://file:///home/projects/withastro-astro-bv7iav/node_modules/.pnpm/devalue@4.3.0/node_modules/devalue/src/uneval.js:101:13)
    at walk (file://file:///home/projects/withastro-astro-bv7iav/node_modules/.pnpm/devalue@4.3.0/node_modules/devalue/src/uneval.js:116:7)
    at Module.uneval (file://file:///home/projects/withastro-astro-bv7iav/node_modules/.pnpm/devalue@4.3.0/node_modules/devalue/src/uneval.js:123:2)
    at Context.load (file://file:///home/projects/withastro-astro-bv7iav/node_modules/.pnpm/astro@2.1.9/node_modules/astro/dist/content/vite-plugin-content-imports.js:79:31)
    at async Object.load (file://file:///home/projects/withastro-astro-bv7iav/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:43409:32)
    at async loadAndTransform (file://file:///home/projects/withastro-astro-bv7iav/node_modules/.pnpm/vite@4.2.1/node_modules/vite/dist/node/chunks/dep-79892de8.js:41087:24)
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-bv7iav?file=src/content/config.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #6764 
- Add readable error message for unsupported `transform()` return values. We unfortunately support _any_ return value from a transform, since all data needs to be serialized at build time to avoid shipping your content config to SSR environments.

image

## Testing

Manual testing

## Docs

New error data entry

### CODE REVIEW

File: packages/astro/src/content/vite-plugin-content-imports.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export function astroContentImportPlugin({
 					const code = escapeViteEnvReferences(`
 export const id = ${JSON.stringify(id)};
 export const collection = ${JSON.stringify(collection)};
-export const data = ${devalue.uneval(data) /* TODO: reuse astro props serializer */};
```
Comment (bholmesdev) [inline packages/astro/src/content/vite-plugin-content-imports.ts:97]: Why _not_ use Astro's props serializer: it's overly forgiving for anything that isn't valid HTML. Example: it parses DayJS objects successfully, but silently strips all functions without an error. devalue is much more strict in what is and isn't supported, which should mean better error messages!

**Review by sarah11918 — APPROVED** [review]

**Review by natemoo-re — APPROVED** [review]
LGTM!
