### PR TITLE
Fix missing styles

### LINKED ISSUE #2101: 🐛 BUG: Prod built html file doesn't have any css styles
### What version of `astro` are you using?

0.21.8

### What package manager are you using?

npm

### What operating system are you using?

stackblitz

### Describe the Bug

The page `page-1` uses two layouts. Both layouts import their own css file. 

In dev-server, the page has proper styling. When the app is prod built, `dist/page-1/index.html` has no link tags for any css. 

Additional observations
- The `dist/page-1/index.html` has unnecessary classes added to its markup. I haven't written any css in `<style>` tags, for Astro to use scoped css classes. 
- There is an empty js file `dist/assets/page-1.hash.js` . My repo has no js. Thankfully the js file is not linked-to from any html file. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qoihup?file=src/pages/page-1.astro

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #2101. For some reason when we try to skip empty CSS files, we also skip necessary CSS files (this is probably due to a deeper issue with the translation from JS imports into CSS, and dumping things too early). This PR makes a tradeoff: it regresses emitting empty CSS files, but it fixes necessary CSS files sometimes missing.

## Testing

Tests added

## Docs

Bugfix

### CODE REVIEW

File: packages/astro/src/core/ssr/css.ts [hunk 1]
```diff
@@ -30,8 +28,9 @@ export function getStylesForURL(filePath: URL, viteServer: vite.ViteDevServer):
         css.add(importedModule.url); // note: return `url`s for HTML (not .id, which will break Windows)
       }
       crawlCSS(importedModule.id, scanned);
-      scanned.add(importedModule.id);
     }
+
+    scanned.add(moduleName.id);
```
Comment (drwpow) [inline packages/astro/src/core/ssr/css.ts:33]: This change is just cleanup (we don’t need to try to add modules multiple times to `scanned`; also wait until scanned is done to skip it); not affecting the PR.

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 2]
```diff
@@ -124,7 +124,7 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
         }
       }
 
-      if (!chunkCSS) return null; // don’t output empty .css files
+      // if (!chunkCSS) return null; // don’t output empty .css files
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-css/index.ts:127]: Temporary fix: comment this line out

File: packages/astro/test/astro-css-bundling-nested-layouts.test.js [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+
+describe('nested layouts', () => {
+  let fixture;
+
+  before(async () => {
+    fixture = await loadFixture({ projectRoot: './fixtures/astro-css-bundling-nested-layouts/' });
+    await fixture.build();
+  });
+
+  it('page-1 has all CSS', async () => {
```
Comment (drwpow) [inline packages/astro/test/astro-css-bundling-nested-layouts.test.js:13]: Test added to fix regression…

File: packages/astro/test/astro-css-bundling-import.test.js [hunk 4]
```diff
@@ -32,7 +32,8 @@ describe('CSS Bundling (ESM import)', () => {
     expect(css.indexOf('p{color:green}')).to.be.greaterThan(css.indexOf('p{color:#00f}'));
   });
 
-  it('no empty CSS files', async () => {
+  // TODO: re-enable this
+  it.skip('no empty CSS files', async () => {
```
Comment (drwpow) [inline packages/astro/test/astro-css-bundling-import.test.js:36]: … however another test was skipped to fix

File: packages/astro/src/core/ssr/css.ts [hunk 5]
```diff
@@ -30,7 +30,6 @@ export function getStylesForURL(filePath: URL, viteServer: vite.ViteDevServer):
         css.add(importedModule.url); // note: return `url`s for HTML (not .id, which will break Windows)
       }
       crawlCSS(importedModule.id, scanned);
-      scanned.add(importedModule.id);
```
Comment (drwpow) [inline packages/astro/src/core/ssr/css.ts:33]: This is just cleanup: we don’t need to add a module ID to `scanned` twice

**Review by matthewp — APPROVED** [review]
lgtm
