### PR TITLE
Improve CSS import ordering, fix empty CSS outputs

### LINKED ISSUE #2060: 🐛 BUG: CSS Bundling sometimes generates empty files, also in indeterminate order
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Discord context / error here: https://discord.com/channels/830184174198718474/915171425931907102/915171431631953940

The summary is two-fold:

1. When CSS is imported in a very-specific order (either by `<link>` or `import 'styles.css'` in frontmatter), CSS doesn’t get built in that same order (even if it did in dev).
2. When a page doesn’t have unique styles, an empty CSS file will sometimes be created.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qoihup?file=src/pages/page-2.astro

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #2060 (hopefully for real)

A previous cut of this PR accidentally assumed that a certain asset map was in order when it wasn’t. The reality is that Rollup chunks are all processed in parallel, and they can be encountered in any order.

So this PR relies on HTML ordering to determine stylesheet ordering. Tests were added to make sure it works as intended.

Also, it prevents empty CSS from being generated (which is somewhat of an edge case and not super common, but can be frustrating when it does happen)

## Testing

Tests added

## Docs
🐛 Bugfix

### CODE REVIEW

File: packages/astro/src/vite-plugin-build-html/index.ts [hunk 1]
```diff
@@ -169,6 +170,11 @@ export function rollupPluginAstroBuildHTML(options: PluginOptions): VitePlugin {
             const jsSource = assetImports.map((sid) => `import '${sid}';`).join('\n');
             astroPageStyleMap.set(pageStyleId, jsSource);
             assetInput.add(pageStyleId);
+
+            // preserve asset order in the order we encounter them
+            for (const assetHref of assetImports) {
+              if (!pageStyleImportOrder.includes(assetHref)) pageStyleImportOrder.push(assetHref);
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-html/index.ts:176]: First, we get assets in HTML order (if an asset appears multiple times, we take the first appearance)

File: packages/astro/src/vite-plugin-build-html/index.ts [hunk 2]
```diff
@@ -253,17 +259,46 @@ export function rollupPluginAstroBuildHTML(options: PluginOptions): VitePlugin {
         assetIdMap.set(assetPath, referenceId);
       }
 
+      // Sort CSS in order of appearance in HTML
+      // This is needed because bundling is an async process where the chunks may
+      // be processed in any order. So we have to do a little bit of work to determine
+      // chunk order based off of HTML scanning in options() earlier
+      const sortedCSSChunks = [...pureCSSChunks];
+      sortedCSSChunks.sort((a, b) => {
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-html/index.ts:267]: Next, we have to do 2 sorts.

The first re-sorts the chunks in the HTML order derived above. This is basically the “global ordering.”

File: packages/astro/src/vite-plugin-build-html/index.ts [hunk 3]
```diff
@@ -253,17 +259,46 @@ export function rollupPluginAstroBuildHTML(options: PluginOptions): VitePlugin {
...
       // link tags for CSS.
-      for (const chunk of pureCSSChunks) {
-        const chunkReferenceIds: string[] = [];
-        for (const [specifier, chunkRefID] of chunkToReferenceIdMap.entries()) {
-          if (chunk.imports.includes(specifier) || specifier === chunk.fileName) {
-            chunkReferenceIds.push(chunkRefID);
-          }
+      for (const chunk of sortedCSSChunks) {
+        const chunkModules = [chunk.fileName, ...chunk.imports];
+        chunkModules.sort((a, b) => {
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-html/index.ts:288]: The next sort is within each chunk: we take each chunk’s dependencies, and sort them according to the “global ordering” above. This produces consistent ordering. It’s this final sorting that determines the build HTML ordering (which, again, will hopefully match the original ordering collected in the beginning of this file before bundling)

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 4]
```diff
@@ -124,6 +124,8 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
         }
       }
 
+      if (!chunkCSS) return null; // don’t output empty .css files
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-css/index.ts:127]: Lastly, this just prevents empty CSS from being omitted. This wasn’t possible before as `vite-plugin-build-html` would assume all chunks existed; now with safer checking there we can simply skip emitting empty chunks without issue.

File: packages/astro/src/vite-plugin-build-html/index.ts [hunk 5]
```diff
@@ -253,17 +259,43 @@ export function rollupPluginAstroBuildHTML(options: PluginOptions): VitePlugin {
         assetIdMap.set(assetPath, referenceId);
       }
 
+      // Sort CSS in order of appearance in HTML (pageStyleImportOrder)
+      // This is the “global ordering” used below
+      const sortedCSSChunks = [...pureCSSChunks];
+      sortedCSSChunks.sort((a, b) => {
+        let aIndex = Math.min(
+          ...Object.keys(a.modules).map((id) => {
+            const i = pageStyleImportOrder.findIndex((url) => id.endsWith(url));
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-html/index.ts:268]: Note: `id.endsWith(url)` may be a bit brittle, but fortunately we’re only sorting. If we can’t figure out the order of a module, we don’t remove it; we just keep it in whatever order we found it.

File: packages/astro/src/vite-plugin-build-html/index.ts (hunk 1 above)
Comment (drwpow) [reply packages/astro/src/vite-plugin-build-html/index.ts:176]: Of course, this isn’t perfect! It’s very possible that some pages won’t agree on the ordering of some CSS. But because we’re bundling, there’s no perfect answer there—the only solution is to not bundle CSS at all. So while this sorting won’t solve _everyone’s_ problems, it will at least improve CSS ordering as much as we can while still bundling.

**Review by natemoo-re — APPROVED** [review]
LGTM!

File: packages/astro/test/astro-css-bundling-import.test.js [hunk 6]
```diff
@@ -10,7 +10,7 @@ describe('CSS Bundling (ESM import)', () => {
     await fixture.build();
   });
 
-  it.skip('CSS output in import order', async () => {
+  it('CSS output in import order', async () => {
```
Comment (drwpow) [inline packages/astro/test/astro-css-bundling-import.test.js:13]: CSS ordering test un-skipped (hopefully for good)!

File: packages/astro/test/astro-css-bundling-import.test.js [hunk 7]
```diff
@@ -29,11 +29,10 @@ describe('CSS Bundling (ESM import)', () => {
     expect(css.indexOf('p{color:green}')).to.be.greaterThan(css.indexOf('p{color:red}'));
 
     // test 2: insure green comes after blue (page-1.css)
-    expect(css.indexOf('p{color:green}')).to.be.greaterThan(css.indexOf('p{color:red}'));
+    expect(css.indexOf('p{color:green}')).to.be.greaterThan(css.indexOf('p{color:#00f}'));
   });
 
-  // TODO: need more investigation to fix this
-  it.skip('no empty CSS files', async () => {
+  it('no empty CSS files', async () => {
```
Comment (drwpow) [inline packages/astro/test/astro-css-bundling-import.test.js:35]: Empty CSS test un-skipped
