### PR TITLE
fix: clear the content layer cache when the Astro config changes

### LINKED ISSUE #12761: Invalidate content layer cache when config changes
Currently the content layer cache is invalidated if the content config or Astro version changes. However there are other config options that need it to be invalidated too. We will need to find a safe way to hash the config.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Currently the content layer cache is invalidated if the content config or Astro version changes. However this causes problems if there are changes in the Astro config that also affect the stored data. This can include things like markdown settings, but potentially lots of other things.

The apporach this PR takes is to hash everything except integrations, adapters and vite config. It switches the digest function to use a safe stringify function in case the Astro config includes circular refs.

Closes #12761

## Testing

Adds a test case

### CODE REVIEW

File: packages/astro/src/content/utils.ts [hunk 1]
```diff
@@ -832,3 +832,26 @@ export function contentModuleToId(fileName: string) {
...
+			(newValue as Record<string, unknown>)[key2] = safeStringifyReplacer(seen)(key2, value2);
+		}
+		seen.delete(value);
+		return newValue;
+	};
+}
+export function safeStringify(value: unknown) {
+	const seen = new WeakSet();
+	return JSON.stringify(value, safeStringifyReplacer(seen));
+}
```
Comment (delucis) [inline packages/astro/src/content/utils.ts:857]: Could we use [`deterministic-object-hash`](https://github.com/zbauman3/Deterministic-Object-Hash) instead of this? It’s already an `astro` dep used for hashing image transforms.

**Review by delucis — COMMENTED** [review]
Tests are failing but looks good to me in principle!

**Review by ematipico — COMMENTED** [review]
I think we should change how we hash the config.

File: packages/astro/src/content/content-layer.ts [hunk 2]
```diff
@@ -1,10 +1,12 @@
 import { promises as fs, existsSync } from 'node:fs';
+import { deterministicString } from 'deterministic-object-hash';
 import PQueue from 'p-queue';
 import type { FSWatcher } from 'vite';
 import xxhash from 'xxhash-wasm';
 import { AstroError, AstroErrorData } from '../core/errors/index.js';
 import type { Logger } from '../core/logger/core.js';
 import type { AstroSettings } from '../types/astro.js';
+
```
Comment (delucis) [inline packages/astro/src/content/content-layer.ts:9]: Micro-nit, but I’m guessing this was introduced accidentally?
```suggestion
```

**Review by delucis — APPROVED** [review]
LGTM!

**Comment by delucis** [comment]
Ah, hang on. Seeing “Maximum call stack exceeded” in the object hasher in tests:

error logging reading Maximum call stack exceeded for repeated calls to deterministicString

Node 18 only for some reason, but could still be problematic I guess.

**Comment by ascorbic** [comment]
Oh that isn't good! I'll look into it tomorrow

**Comment by ascorbic** [comment]
I'm going to switch back to the safe stringify approach because it looks like deterministic-object-hash doesn't have any circular dependency handling or any other handling of excessively deep objects. That's fine for simple things like the image transforms, but astro config can be complex.

**Review by ematipico — APPROVED** [review]
