### PR TITLE
Fix cached inline modules

### LINKED ISSUE #2004: 🐛 BUG: getting `roots[0] is undefined` after browser reload when doing client-side hydration
### What version of `astro` are you using?

0.21.3

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Hello! First of all, thank you for creating this thing! I want to report a bug -- or, at least at the time of writing, I think it is.

Client-side hydration stops working (?) after a browser reload, after starting `yarn start` for the first time.

## Reproduction in Codesandbox

As shown in the link below, https://codesandbox.io/s/unruffled-perlman-ggl0v?file=/src/pages/index.astro, the steps is to:

1. Open the Codesandbox
2. Wait until the counter starts ticking, or just save a random file, e.g. in `/src/pages/index.astro`. This will trigger the build and restart the Node server (or so, I believe). At the same time, the interval will start ticking.
3. Reload the browser page **inside** the Codesandbox
4. See the count returns back to 0, but it won't start ticking. I think it should keep working anyway? Not sure. Anyway, there is this error in the browser console (not the Codesandbox one):

```
Uncaught (in promise) TypeError: roots[0] is undefined
    onVisible visible.ts:10
    <anonymous> index.astro:2
```

## Alternative reproduction

I have prepared an alternative GitHub repository for this purpose: https://github.com/imballinst/astro-bug-repro/tree/client-hydration-react-1

1. Clone the repository
2. Install dependencies using `yarn`
3. `yarn start`
4. When the browser first opens, the interval will run properly
5. After the browser is reloaded, then the timer will stop ticking.

I tried to find the root cause, then I find that for the first time render, the `astro-root` element is this:

```
<astro-root uid="SrAbR">
```

I also placed a `console.log` in the `node_modules/astro/dist/runtime/client/visible.js` file to check the `astroId`. It outputs this in my browser:

```
[vite] connecting... client.ts:22:8
SrAbR visible.ts:9:8
[vite] connected. client.ts:52:14
```

However, after browser reload, the `astro-root` element became this:

```
<astro-root uid="2a6uG6">
```

While that happens, the `astroId` in the `onVisible` function stood the same:

```
[vite] connecting... client.ts:22:8
[vite] connected. client.ts:52:14
SrAbR visible.ts:9:8
```

Hence, probably that's the reason why `roots[0]` throws error, because `roots` is `undefined`. If there are more information that I need to give, please let me know. Thanks again!

**EDIT:** apparently this only happens when we are doing anything `Date` related in the `.astro` file... curious.
**EDIT2:** if I remove the `Date` stuff in the `.astro` file and use the `Date` only in the `.jsx` files, it also causes the same kind of errors.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/unruffled-perlman-ggl0v?file=/src/pages/index.astro

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Fixes #2004 
- Upstream fix: https://github.com/vitejs/vite/pull/5891
- What was happening was that our astroid is the hash of the HTML produced by a component. If that HTML ever changes the astroid changes. However since Vite's dev HTML plugin turns the inline scripts into external scripts and caches them, the changed astroid was never reflected in the proxy modules.
- Fix is to invalidate the module when the script changes; a bug in Vite. There is an upstream fix listed above.

## Testing

No, we don't have dev tests that change the value of a module, which would be needed to test this.

## Docs

Bug fix only

### CODE REVIEW

File: packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js [hunk 1]
```diff
@@ -56982,8 +56982,10 @@ const devHtmlHook = async (html, { path: htmlPath, server, originalUrl }) => {
                     .join('');
                 // add HTML Proxy to Map
                 addToHTMLProxyCache(config, url, scriptModuleIndex, contents);
-                // inline js module. convert to src="proxy"
-                s.overwrite(node.loc.start.offset, node.loc.end.offset, `<script type="module" src="${config.base + url.slice(1)}?html-proxy&index=${scriptModuleIndex}.js"></script>`);
+                const modulePath = `${config.base + htmlPath.slice(1)}?html-proxy&index=${scriptModuleIndex}.js`;
+                // invalidate the module so the newly cached contents will be served
+                server === null || server === void 0 ? void 0 : server.moduleGraph.invalidateId(config.root + modulePath);
```
Comment (jonathantneal) [inline packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56987]: It took me a minute to get this one.

With a loose suggestion:
```suggestion
                if (server != null) server.moduleGraph.invalidateId(config.root + modulePath);
```

Or, with a loose suggestion:
```suggestion
                if (server !== null && server !== undefined) server.moduleGraph.invalidateId(config.root + modulePath);
```

File: packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js [hunk 2]
```diff
@@ -57113,6 +57115,12 @@ class ModuleGraph {
         mod.ssrTransformResult = null;
         invalidateSSRModule(mod, seen);
     }
+    invalidateId(id) {
+        const mod = this.idToModuleMap.get(id);
+        if (mod) {
+            this.invalidateModule(mod);
+        }
+    }
```
Comment (jonathantneal) [inline packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:57123]: 👍

**Review by jonathantneal — COMMENTED** [review]
Only one thing really stands out.

File: packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js (hunk 1 above)
Comment (matthewp) [reply packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56987]: I wrote this as `server?.moduleGraph.invalidate`.... the code you are seeing here is generated by the build. All of the code in `vendor/vite` isn't particularly readable for that reason.

Comment (jonathantneal) [reply packages/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:56987]: Oh! Totally then.

**Review by jonathantneal — APPROVED** [review]
