### PR TITLE
Prevent /undefined catch-all routes in dev

### LINKED ISSUE #4796: getStaticPaths() with `undefined` slug creates actual "/undefined" route
### What version of `astro` are you using?

1.2.4, 1.2.6

### Are you using an SSR adapter? If so, which one?

none yet

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Following the docs (https://docs.astro.build/en/core-concepts/routing/#example-dynamically-create-a-top-level-root-page) and #3990 (https://github.com/withastro/astro/issues/3990#issuecomment-1211216446) to create a top level root page via `undefined` slug renders an actual "/undefined" route.

Happens on localhost, just the same way as in the linked repro at https://withastro-astro-zoqwkc--3000.local-corp.webcontainer.io/undefined

The /undefined route can certainly be worked around using HTTP redirects in production, but generating it is probably not what should be happening in the first place.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-zoqwkc?file=src/pages/[...slug].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Fix #4796 

In dev, for pages declared like `pages/[...slug].astro`, if `slug` is `undefined`, only serve at `http://localhost:3000` and `http://localhost:3000/`. Don't serve `http://localhost:3000/undefined`

This PR makes `undefined` and `"undefined"` as 2 distinct static paths to differentiate them, by not stringifying `undefined`.

Note: In build, `http://localhost:3000/undefined` is never built. So this PR makes dev consistent with build.

## Testing

Added a test under `routing-priority`

## Docs

N/A.

### CODE REVIEW

File: packages/astro/src/core/render/route-cache.ts [hunk 1]
```diff
@@ -108,13 +108,9 @@ export class RouteCache {
...
-	let matchedStaticPath = staticPaths.keyed.get(paramsKey);
+	const matchedStaticPath = staticPaths.keyed.get(paramsKey);
 	if (matchedStaticPath) {
 		return matchedStaticPath;
 	}
-
 	debug('findPathItemByKey', `Unexpected cache miss looking for ${paramsKey}`);
-	matchedStaticPath = staticPaths.find(
-		({ params: _params }) => JSON.stringify(_params) === paramsKey
-	);
```
Comment (bluwy) [inline packages/astro/src/core/render/route-cache.ts:119]: This part of the code seems unused.

**Review by matthewp — APPROVED** [review]
