### PR TITLE
[@astrojs/image] support additional resize options

### LINKED ISSUE #4341: `@astrojs/image` should support `sharp` crop strategies such as `attention` to find high entropy spots to center on
### What version of `astro` are you using?

1.0.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

`astro-imagetools` supported choosing the crop-strategy that `sharp` takes when cropping an image, https://sharp.pixelplumbing.com/api-resize#resize, which meant that an image of a lighthouse centered on the lighthouse, while now it simply naively cropped from the bottom and the right of the image, cutting off the lighthouse.

<table>
<tr>
	<td>Original
	<td>New
<tr>
	<td>

image
</td>
	<td>

image
</td>
</table>

I realize that `astro-imagetools` is a community maintained library rather than a 1st party integration, but it'd be great to have feature parity to make migrating to `@astrojs/image` seamless

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-4341-9rp30y?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by obennaci**
## Changes

Add support for additional Sharp resize options; `fit`, `position`, `background`, ~`kernel`~, ~`withoutReduction`~ and ~`withoutEnlargement`~.

Fixes #4341 

## Testing

Manually so far.

## Docs

- [x] Adding the new props/options to docs

### CODE REVIEW

**Comment by matthewp** [comment]
@obennaci still marked as draft, is this ready?

**Comment by obennaci** [comment]
Should be good now :+1:

**Comment by tony-sull** [comment]
Thanks for opening this, @obennaci!

Looks like I missed the #4341 issue while traveling last week 👀  We're actually still a little too early in the `@astrojs/image` integration to add more complex transforms to the API right now, unfortunately.

We're working on making [`Squoosh`](https://www.npmjs.com/package/@squoosh/lib) the default image transformer to add support for web containers and Stackblitz.  Sharp will still be an option, but we may paint ourselves into a corner adding support for sharp-specific features early on

I'm going to close this PR for now only because the integration needs a bit more time to bake to make sure the core API surface is the right basis for a 1.0 version of the integration.  Hopefully we can pull this back up pretty soon though to revisit how to add more fine-grained transform controls here!

**Comment by tony-sull** [comment]
Reopening this PR, we're further down the path towards the Squoosh migration now and I think we should be fine here to add more specific resize options 🥳 

@obennaci if you don't mind, I'll get this branch caught up to main and prepped for a final review and merge

PR #4642 came through today and shock loose the sharp vs. Squoosh concerns for me.  The APIs are close enough that it won't be a problem to have a few specific checks where the Squoosh loader can just warn that a specific transform option is only supported in sharp

**Comment by obennaci** [comment]
Happy to hear that, can't wait 🥳

File: packages/integrations/image/src/loaders/index.ts [hunk 1]
```diff
@@ -75,6 +102,44 @@ export interface TransformOptions {
...
+	 * @default false
+	 */
+	withoutEnlargement?: boolean;
+	/**
+	 * Prevent reducing if the image's width or height are already greater than
+	 * the specified dimensions.
+	 *
+	 * @default false
+	 */
+	withoutReduction?: boolean;
```
Comment (tony-sull) [inline packages/integrations/image/src/loaders/index.ts:142]: I'd lean towards removing these options for now and just trust the width/height provided by users

I could see adding these in the future, but I'm a little worried how much extra noise the lower-level flags will adds to our docs and support threads 😅

**Review by tony-sull — CHANGES_REQUESTED** [review]
Excited to bring this one back now that we have a better idea of how it will work with Squoosh!

We'll need to add docs and test coverage before merging this in, happy to help answer any questions you have or pick the docs/testing work up on my end to get this across the finish line :+1:

File: packages/integrations/image/src/loaders/index.ts (hunk 1 above)
Comment (obennaci) [reply packages/integrations/image/src/loaders/index.ts]: Definitely felt like too much when adding them :+1:

Only when with it because they were the only remaining options.

**Comment by Jutanium** [comment]
On the docs side, it's worth defining the `CropFit` and `CropPosition` types, as it currently isn't clear what they represent. You can define them once on the page, and then link to them each time.

File: packages/integrations/image/src/loaders/index.ts (hunk 1 above)
Comment (tony-sull) [reply packages/integrations/image/src/loaders/index.ts]: Yeah it's probably not a bad idea to remove `kernel` for now as well 🤷

Both sharp and Squoosh support it so that's not a concern at least, but for the sake of our docs that may be a flag we add later if a specific user request comes in for that level of control

**Review by tony-sull — APPROVED** [review]
This is excellent, thanks for all the updates here!  I'm just running a quick test locally against the astro.build project and then we'll merge this in ready for the next release 🎉
