### PR TITLE
Enforce consistent import order of CSS

### LINKED ISSUE #2060: 🐛 BUG: CSS Bundling sometimes generates empty files, also in indeterminate order
### What version of `astro` are you using?

0.21.5

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

Discord context / error here: https://discord.com/channels/830184174198718474/915171425931907102/915171431631953940

The summary is two-fold:

1. When CSS is imported in a very-specific order (either by `<link>` or `import 'styles.css'` in frontmatter), CSS doesn’t get built in that same order (even if it did in dev).
2. When a page doesn’t have unique styles, an empty CSS file will sometimes be created.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qoihup?file=src/pages/page-2.astro

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Partially fixes #2060 (there’s a remaining problem where sometimes empty `.css` files are generated, which can be tackled in a followup if this works well).

This is a tricky issue! The basic idea is that build rearranges styles from dev. While there’s no perfect fix here, this at least takes a step in the direction of fewer surprises on deploy.

Essentially, dev collects styles in a reasonable order that the user may expect. Up until the very last bit, where styles are put into a map and pulled back out in a different order. This PR only changes that part.

## Testing

Test added

## Docs

No docs needed

### CODE REVIEW

File: packages/astro/src/vite-plugin-build-html/index.ts [hunk 1]
```diff
@@ -256,11 +256,10 @@ export function rollupPluginAstroBuildHTML(options: PluginOptions): VitePlugin {
       // Create a mapping of chunks to dependent chunks, used to add the proper
       // link tags for CSS.
       for (const chunk of pureCSSChunks) {
-        const referenceId = chunkToReferenceIdMap.get(chunk.fileName)!;
-        const chunkReferenceIds = [referenceId];
-        for (const imp of chunk.imports) {
-          if (chunkToReferenceIdMap.has(imp)) {
-            chunkReferenceIds.push(chunkToReferenceIdMap.get(imp)!);
+        const chunkReferenceIds: string[] = [];
+        for (const [specifier, chunkRefID] of chunkToReferenceIdMap.entries()) {
```
Comment (drwpow) [inline packages/astro/src/vite-plugin-build-html/index.ts:260]: This is the main change: `chunkToReferenceMap` contains the correct import order. When we use that, we more-or-less get styles in the order imported.

`chunk.imports` seems to be more-or-less in alphabetical order. So iterating over that will cause styles to be rearranged on build.

File: packages/astro/test/astro-css-bundling-import.test.js [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+
+    // test 1: insure green comes after red (site.css)
+    expect(css.indexOf('p{color:green}')).to.be.greaterThan(css.indexOf('p{color:red}'));
+
+    // test 2: insure green comes after blue (page-1.css)
+    expect(css.indexOf('p{color:green}')).to.be.greaterThan(css.indexOf('p{color:red}'));
+  });
+
+  // TODO: need more investigation to fix this
+  it.skip('no empty CSS files', async () => {
```
Comment (drwpow) [inline packages/astro/test/astro-css-bundling-import.test.js:36]: TODO: tackle generating empty `.css` files (slightly-separate issue that may take more work)

File: packages/astro/src/vite-plugin-build-html/index.ts (hunk 1 above)
Comment (matthewp) [reply packages/astro/src/vite-plugin-build-html/index.ts:260]: Ah, good catch.

**Review by matthewp — APPROVED** [review]
Looks good! And great tests.
