### PR TITLE
Fix `*/` breaking HTML comments in Markdown

### LINKED ISSUE #3476: 🐛 BUG: HTML comments in Markdown containing `*/` anywhere break the compiler
### What version of `astro` are you using?

1.0.0-beta.36

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

The Markdown parser in Astro 1.0.0-beta.36 attempts to wrap HTML comments with JS block comments.

Unfortunately, this breaks the compiler as soon as the comment contains a closing JS block comment sequence (`*/`) anywhere.

This was still working in beta 17.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-gx2mt3-ldzc8s?file=src/pages/index.md

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by hippotastic**
## Changes

- Fixes #3476.
- Injects a zero-width space character into nested `*/` sequences when wrapping HTML comments to JS comments.

## Testing

- I added a new test case to verify the fixed behavior.

## Docs

- No visible change, just a bugfix.

### CODE REVIEW

File: packages/astro/src/vite-plugin-markdown/index.ts [hunk 1]
```diff
@@ -129,10 +129,11 @@ export default function markdown({ config }: AstroPluginOptions): Plugin {
 				// Extract special frontmatter keys
 				let { data: frontmatter, content: markdownContent } = matter(source);
 
-				// Turn HTML comments into JS comments
+				// Turn HTML comments into JS comments while preventing nested `*/` sequences
+				// from ending the JS comment by injecting a zero-width space
 				markdownContent = markdownContent.replace(
 					/<\s*!--([^-->]*)(.*?)-->/gs,
-					(whole) => `{/*${whole}*/}`
+					(whole) => `{/*${whole.replace(/\*\//g, '*\u200b/')}*/}`
```
Comment (aFuzzyBear) [inline packages/astro/src/vite-plugin-markdown/index.ts:136]: So the problem was with the end `*\` not being properly escaped 🧐

Great catch 🦛💚

**Review by aFuzzyBear — COMMENTED** [review]
This looks good.

@bholmesdev  could you take a look over this one when you got a second dude 👊

If we can get this in, it would make for a very happy 🦛

File: packages/astro/src/vite-plugin-markdown/index.ts (hunk 1 above)
Comment (hippotastic) [reply packages/astro/src/vite-plugin-markdown/index.ts:136]: Thanks! Yeah, the old code wrapped this Markdown code...

```mdx
<!--This text contains which apparen*/tly breaks the compiler in Beta 36.-->
```

...with JS comments like this:

```mdx
This text {/*<!--contains which apparen*/tly breaks the compiler in Beta 36.-->*/}
```

And as you can see in the syntax highlighting above, the contained unescaped `*/` sequence terminated the comment block early, causing the rest to be interpreted as invalid JS code.

My fix escapes the middle `*/` by inserting a zero-width space character into it. I did this to keep the visual result the same but still prevent it from terminating the comment. Unfortunately there seems to be no "proper" way of escaping the end of a block comment, so this is just what I came up with which works. I'm happy with other ways of escaping, too, in case someone wants to change this.

**Review by bholmesdev — APPROVED** [review]
Siimple, well tested. A `comment`able effort!
