### PR TITLE
fix: too many files opened for collections with many entries

### LINKED ISSUE #6311: EMFILE error with large content collections (2k+)
### What version of `astro` are you using?

2.0.14

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

```> square-shell@0.0.1 dev
> astro dev

  🚀  astro  v2.0.14 started in 269ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
12:05:22 PM [content] Watching src/content/ for changes
 error   EMFILE: too many open files, open '/Users/john/Downloads/astro-many-files-error/src/content/collection/file-1918.md'
Error: EMFILE: too many open files, open '/Users/john/Downloads/astro-many-files-error/src/content/collection/file-1918.md'
```

This error occurs when you try to start the dev server with many content entries. It also occurs when using the Vercel SSR adapter.

I think this is caused when the content types generator is initialized and checks for 'slug' values in all of the content entries at once.

### Link to Minimal Reproducible Example

https://github.com/wbjohn/astro-many-files-error

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by wbjohn**
## Changes

Fixes #6311
Events in the content type generator are handled serially instead of all at once. It was necessary to change the type definition because there's no way to prevent the array of promises from executing all at once.

## Testing

Passes existing tests.

## Docs

No docs needed.

### CODE REVIEW

File: packages/astro/src/content/types-generator.ts [hunk 1]
```diff
@@ -41,6 +41,11 @@ type CreateContentGeneratorParams = {
 
 type EventOpts = { logLevel: 'info' | 'warn' };
 
+type EventWithOptions = {
+	event: ContentEvent;
```
Comment (natemoo-re) [inline packages/astro/src/content/types-generator.ts:45]: Small nit, but `event.type` will be more readable than using `event.event` everywhere
```suggestion
	type: ContentEvent;
```

File: packages/astro/src/content/types-generator.ts [hunk 2]
```diff
@@ -65,7 +70,11 @@ export async function createContentTypesGenerator({
 			return { typesGenerated: false, reason: 'no-content-dir' };
 		}
 
-		events.push(handleEvent({ name: 'add', entry: contentPaths.config.url }, { logLevel: 'warn' }));
+		events.push({
+			event: { name: 'add', entry: contentPaths.config.url },
```
Comment (natemoo-re) [inline packages/astro/src/content/types-generator.ts:74]:
```suggestion
			type: { name: 'add', entry: contentPaths.config.url },
```

File: packages/astro/src/content/types-generator.ts [hunk 3]
```diff
@@ -80,7 +89,7 @@ export async function createContentTypesGenerator({
 				(e) => !e.href.startsWith(contentPaths.config.url.href)
 			);
 		for (const entry of entries) {
-			events.push(handleEvent({ name: 'add', entry }, { logLevel: 'warn' }));
+			events.push({ event: { name: 'add', entry }, opts: { logLevel: 'warn' } });
```
Comment (natemoo-re) [inline packages/astro/src/content/types-generator.ts:92]:
```suggestion
			events.push({ type: { name: 'add', entry }, opts: { logLevel: 'warn' } });
```

File: packages/astro/src/content/types-generator.ts [hunk 4]
```diff
@@ -204,12 +213,15 @@ export async function createContentTypesGenerator({
 
 	function queueEvent(rawEvent: RawContentEvent, opts?: EventOpts) {
 		const event = {
-			entry: pathToFileURL(rawEvent.entry),
-			name: rawEvent.name,
+			event: {
```
Comment (natemoo-re) [inline packages/astro/src/content/types-generator.ts:216]:
```suggestion
			type: {
```

File: packages/astro/src/content/types-generator.ts [hunk 5]
```diff
@@ -204,12 +213,15 @@ export async function createContentTypesGenerator({
...
+				entry: pathToFileURL(rawEvent.entry),
+				name: rawEvent.name,
+			},
+			opts,
 		};
-		if (!event.entry.pathname.startsWith(contentPaths.contentDir.pathname)) return;
+		if (!event.event.entry.pathname.startsWith(contentPaths.contentDir.pathname)) return;
```
Comment (natemoo-re) [inline packages/astro/src/content/types-generator.ts:222]:
```suggestion
		if (!event.type.entry.pathname.startsWith(contentPaths.contentDir.pathname)) return;
```

File: packages/astro/src/content/types-generator.ts [hunk 6]
```diff
@@ -220,7 +232,13 @@ export async function createContentTypesGenerator({
 
 	async function runEvents(opts?: EventOpts) {
 		const logLevel = opts?.logLevel ?? 'info';
-		const eventResponses = await Promise.all(events);
+		const eventResponses = [];
+
+		for (const event of events) {
+			const response = await handleEvent(event.event, event.opts);
```
Comment (natemoo-re) [inline packages/astro/src/content/types-generator.ts:238]:
```suggestion
			const response = await handleEvent(event.type, event.opts);
```

**Review by natemoo-re — COMMENTED** [review]
Just a thought on renaming `event.event` to `event.type`
