### PR TITLE
fix: export lang types for use in custom component

### LINKED ISSUE #14009: Code#lang types not exported
### Astro Info

```block
Astro                    v5.10.1
Node                     v24.2.0
System                   macOS (arm64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @vite-pwa/astro-integration
                         @playform/compress
                         @kindspells/astro-shield
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

```ts
---
const fetchedCode = await fetchCode();
const code: string = fetchedCode.content;
const language: string = fetchedCode.language; // `fetchedCode` is something like { content: string; language: string }
---
<Code code={code} lang={language} />
                  ^^^^ Type 'string' is not assignable to type 'BundledLanguage | SpecialLanguage | LanguageRegistration'. ​ts(2322)
```

I'm writing a Component to embed GitHub code from my repo/gists into my website. Because of the strict nature of my code base I need to be able to specify a more strict type for `language` than just a `string`. Astro doesn't expose the `BundledLanguage | SpecialLanguage | LanguageRegistration` to me anywhere that I can see. And since `shiki@3.7.0` is a dependency of astro, not my project I don't have safe access to those types.

### What's the expected result?

I expect that Astro would either not require a narrow type for the `lang` attribute, or would expose that type so that end-users can access it directly.

I will admit that this is a problem of my own making. I want to be super strict with my types, but I also don't want have to write or install (much) code just to make the linters and tsc happy. 

If you provide me with some indication of how you think best to resolve this issue I am happy to submit a PR to Astro. For now I'm just disabling the complaint with a comment.

### Link to Minimal Reproducible Example

https://github.com/rgant/rob.gant.ninja/blob/2cb3e593b9cc751c778c3c39198bf98f1227d7e9/src/components/github-embed.astro

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Grisoly**
## Changes

- Exported BundledLanguage, SpecialLanguage, and LanguageRegistration types from Astro's public API.
- Enables users to type-check the lang prop in custom components without workarounds.
- Fixes #14009.

## Testing

- Manually verified that the types can be imported from astro in a test project.
- Confirmed that valid values (e.g., 'ts') pass type checking and invalid values fail.

## Docs

No user-facing docs changes required, but this improves DX for custom code block components.
Consider adding a note in the component API docs about the new type exports.

 /cc @withastro/maintainers-docs for feedback!

- No user-facing documentation changes are needed because this PR only exports internal types for advanced TypeScript usage. The public API and user experience remain unchanged for most users.

### CODE REVIEW

**Comment by Grisoly** [comment]
The remaining CI failures appear to be unrelated to my changes (mostly fork/infra issues). Please let me know if you need me to rebase or address anything specific.

**Review by florian-lefebvre — CHANGES_REQUESTED** [review]
Types are exported from another file. Can you instead do the following?
- Create a new type called `CodeLanguage` in `src/types.d.ts` that is an union of the 3 types you have here
- Remove the file you created
- Update `components/Code.astro` to use this new type

**Comment by Grisoly** [comment]
@florian-lefebvre I've implemented the requested changes:

1. Removed direct re-exports (No longer exporting shiki types directly from index.ts)
2. Created `CodeLanguage` union type (Added to `packages/astro/types.d.ts` with all three language types in alphabetical order)
3. Updated `Code.astro`  (that now uses the new `CodeLanguage` type instead of direct shiki imports)
4. Deleted index.ts file 

The implementation now follows the suggested specifications and gives type-safe access to supported code languages without Typescript suppressions.

File: packages/astro/types.d.ts [hunk 1]
```diff
@@ -30,3 +31,9 @@ export type Polymorphic<P extends { as: HTMLTag }> = PolymorphicAttributes<
 >;
 
 export type ComponentProps<T extends (args: any) => any> = Simplify<Parameters<T>[0]>;
+
+/**
+ * The language type for code highlighting.
+ * Supports all languages listed here: https://shiki.style/languages
+ */
```
Comment (florian-lefebvre) [inline packages/astro/types.d.ts]:
```suggestion
```

File: .changeset/clever-numbers-sink.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+     Export lang types (BundledLanguage, SpecialLanguage, LanguageRegistration) from Astro for use in custom components. Fixes #14009.
```
Comment (florian-lefebvre) [inline .changeset/clever-numbers-sink.md]:
``````suggestion
Exposes the `Code` component `lang` prop type:

```ts
import type { CodeLanguage } from "astro/types";
```
``````

**Review by florian-lefebvre — APPROVED** [review]
Thanks!

File: packages/astro/types.d.ts [hunk 3]
```diff
@@ -1,6 +1,7 @@
 import './astro-jsx';
 import type { OmitIndexSignature, Simplify } from './dist/type-utils.js';
 import type { AstroBuiltinAttributes } from './dist/types/public/elements.js';
+import type { BundledLanguage, SpecialLanguage, LanguageRegistration } from 'shiki';
```
Comment (florian-lefebvre) [inline packages/astro/types.d.ts]: I think we need to move this to a file in `src/types/public` instead, I need to investigate

**Review by florian-lefebvre — APPROVED** [review]
