### PR TITLE
fix(node): add missing error logging

### LINKED ISSUE #11200: No logs on Internal Server Error in node adapter
### Astro Info

```block
Astro                    v4.9.2
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/preact
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

#10285 introduced a try catch which swallows some of the errors making it very hard to know what was the root cause of 500. You should always either log or rethrow in a catch block.

### What's the expected result?

All errors should be logged.

### Link to Minimal Reproducible Example

Any app with node adapter

```
npm create astro@latest
cd repro
npx astro add node
npm run build
node dist/server/entry.mjs

# in second terminal
curl localhost:4321 -H 'X-Forwarded-Host: example.com, example2.com' 
# no logs in first terminal
```

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by dkobierski**
## Changes

Fixes #11200
Adds missing error logging in catch block.

## Testing

Testing not needed

## Docs

N/A

### CODE REVIEW

File: packages/integrations/node/src/serve-app.ts [hunk 1]
```diff
@@ -25,6 +25,8 @@ export function createAppHandler(app: NodeApp): RequestHandler {
 		try {
 			request = NodeApp.createRequest(req);
 		} catch (err) {
+			logger.error(`Could not render ${req.url}`);
+			console.error(err);
```
Comment (ematipico) [inline packages/integrations/node/src/serve-app.ts:29]: Why don't we use our logger to log the actual error?

Comment (dkobierski) [reply packages/integrations/node/src/serve-app.ts:29]: I've just used the same approach as [here](https://github.com/withastro/astro/blob/368e4ced10b7a629c9ad94800ccf2a1243038921/packages/integrations/node/src/middleware.ts#L33).  I'm happy to change it.

**Review by ematipico — APPROVED** [review]
