### PR TITLE
fix: audit list window covered by tooltip and highlight

### LINKED ISSUE #11114: Dev toolbar axe app hidden by popups and hightlights
### Describe the Bug

Accessibility toolbar can be rendered unusable due to overlapping overlays and hover tips

Ironically it can actually create an accessibility issue, when there are many overlapping highlight overlays the contrast ratio of the text in the main window drops.
Screenshot 2024-05-22 at 1 07 04 AM
Screenshot 2024-05-22 at 12 59 04 AM

### What's the expected result?

Not sure exactly, but I think the main window should always be on top and maybe when one of the list items is selected all are highlights are hidden 

### Link to Minimal Reproducible Example

Can be reproduced with a fresh starlight install

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by jpwienekus**
## Changes

This fixes pop-ups and highlights rendering over the audit list window. 

Fixes #11114 

## Testing
Added e2e test.

### CODE REVIEW

File: packages/astro/src/runtime/client/dev-toolbar/apps/audit/ui/audit-list-window.ts [hunk 1]
```diff
@@ -83,7 +83,7 @@ export class DevToolbarAuditListWindow extends HTMLElement {
 					"Noto Color Emoji";
 				color: rgba(191, 193, 201, 1);
 				position: fixed;
-				z-index: 999999999;
+				z-index: 2000000009;
```
Comment (jpwienekus) [inline packages/astro/src/runtime/client/dev-toolbar/apps/audit/ui/audit-list-window.ts:86]: Highlights have a z-index of 2000000000, tooltips have a z-index of 2000000001

Updated the z-index here to 2000000009 for rare cases where the audit list window is rendered in the same space as the dev toolbar, which has a z-index of 2000000010 

I suspect the visibility of the dev toolbar would be higher than the audit list window.

File: packages/astro/e2e/fixtures/dev-toolbar/src/pages/tooltip-position.astro [hunk 2]
```diff
@@ -4,7 +4,7 @@
 
 <div>
   <button role="top-left">Top left</button>
-  <button role="top-right">Top right</button>
+  <button role="button">Top right</button>
```
Comment (jpwienekus) [inline packages/astro/e2e/fixtures/dev-toolbar/src/pages/tooltip-position.astro:7]: Updated this since the button is now behind the audit list window, preventing the hover from being triggered. Any other suggestions?

**Review by ascorbic — APPROVED** [review]
Thanks!
