### PR TITLE
Use IE conditional comment placeholders for server island start markers

### LINKED ISSUE #11995: Bug: Unintended DOM Manipulation in Server Island Component Replacement
### Astro Info

```block
Astro                    v0.0.0-si-get-20240815175345
Node                     v20.13.1
System                   Windows (x64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/node
Integrations             @astrojs/react
                         @astrojs/tailwind
                         astro-compress
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

There appears to be a potential bug in the DOM manipulation logic for replacing server island components. The current implementation may, under certain conditions, remove unintended parts of the DOM, potentially clearing the entire page content.

```
while(script.previousSibling &&
    script.previousSibling.nodeType !== 8 &&
    script.previousSibling.data !== 'server-island-start') {
    script.previousSibling.remove();
}
script.previousSibling?.remove();
```

here I found this code, it is designed to remove all sibling nodes preceding the current script element until it encounters a comment node (nodeType === 8) with the content 'server-island-start'. However, if this comment `<!--server-island-start-->` node is missing or improperly positioned, the loop continues to remove elements, potentially clearing the entire page content.

image

## Reproduction

Clone this repo https://github.com/twodft/server-islands-reprod 
build and the preview those page: 

- http://localhost:4321/bug/bug This page got wrong, obviously
- http://localhost:4321/ This page works fine since `<!--server-island-start-->` did not removed by astro compress
- http://localhost:4321/bug/test This page also works fine, because server island component is wrapped with a parent div, `<div><CustomerReviews server:defer /></div>`

### What's the expected result?

The astro server island script should only replace the content of its corresponding server island component, leaving the rest of the page intact.

### Link to Minimal Reproducible Example

https://github.com/twodft/server-islands-reprod

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by markjaquith**
## Changes

fixes #11995

cc: @matthewp — we talked about this on Twitter.

Swaps the generic HTML comment placeholders with IE conditional comments. These placeholders have existed for a long time, and are much less likely to be removed by HTML minifiers, because they have traditionally been used to change the behavior of a site.

A similar fix was implemented in [Livewire](https://github.com/livewire/livewire/commit/b666304652006f3491987c92d53724bc14035d6a) to work around Cloudflare HTML minification removing the HTML comment placeholders Livewire was inserting for a similar purpose.

## Testing

No tests changed, since it's just changing the content of an HTML comment. I haven't been able to set up the original commenter's complete environment for a complete fix verification, but I did look at the source code for the minifier library they were using, and that library has code to not remove IE conditional comments.

## Docs

No documentation needed... the feature should just work more reliably now when Astro output is touched by HTML minifiers.

### CODE REVIEW

File: packages/astro/src/runtime/server/render/server-islands.ts [hunk 1]
```diff
@@ -47,7 +47,7 @@ export function renderServerIsland(
 				}
 			}
 
-			destination.write('<!--server-island-start-->');
```
Comment (markjaquith) [inline packages/astro/src/runtime/server/render/server-islands.ts:50]: `astro` here isn't anything special... it just needs to be a condition that evaluates to false. I wasn't sure about putting `server-island-start` in the condition part, because I was worried the dashes might break the regex minification libraries rely on to identify these conditional comments. As a bonus, it identifies "hey, Astro put this weird comment here" to anyone who might happen to see it and wonder. But this could be `if false` or `if serverislandstart` just as easily.

**Comment by markjaquith** [comment]
I changed this from a `minor` to a `patch` change, as I regard it as being backward compatible. Someone will have to manually update the label, I guess they don't get updated if you change that.

File: packages/astro/src/runtime/server/render/server-islands.ts (hunk 1 above)
Comment (Princesseuh) [reply packages/astro/src/runtime/server/render/server-islands.ts:50]: Fine with me!

**Comment by Princesseuh** [comment]
The changeset here should be patch anyway, as the feature it updates is experimental on this branch.

**Review by Princesseuh — APPROVED** [review]

**Review by matthewp — APPROVED** [review]
I can't believe the fix is this simple 😅 Thanks so much @markjaquith
