### PR TITLE
Fix loading of styles in static build

### LINKED ISSUE #2602: 🐛 BUG: Styles not applied in dev with the static build flag
### What version of `astro` are you using?

0.23.0-next.9

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Styles are not applied, because the id is not resolved correctly. Regression occurred here: https://github.com/withastro/astro/commit/ec6f148fc8623c6549885af70512839c08905fdb

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-bucnjz-5eszf8?file=package.json&on=stackblitz

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Fixes #2602
- We resolve style ids to be root-relative so that the Vite CSS plugin correctly resolves relative imports. A regression in https://github.com/withastro/astro/commit/ec6f148fc8623c6549885af70512839c08905fdb made it so that the query params were removed.

## Testing

Test added

## Docs

Bug fix only

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro/index.ts [hunk 1]
```diff
@@ -29,6 +29,11 @@ export default function astro({ config, logging }: AstroPluginOptions): vite.Plu
 		}
 		return filename;
 	}
+	function relativeToRoot(pathname: string) {
+		const arg = startsWithForwardSlash(pathname) ? '.' + pathname : pathname;
+		const url = new URL(arg, config.projectRoot);
+		return slash(fileURLToPath(url)) + url.search;
```
Comment (jonathantneal) [inline packages/astro/src/vite-plugin-astro/index.ts:35]: Q. Is there a difference between `slash(fileURLToPath(url))` and `url.pathname`? My understand is that `URL` would be the same as the `slash`’d version of the possibly-windows-style path.

Comment (matthewp) [reply packages/astro/src/vite-plugin-astro/index.ts:35]: Yes, `url.pathname` will contain `%20` for a space whereas `fileURLToPath` removes the encoding and puts a space in. We ran into this bug before and its why the `packages/astro/test/fixtures/static build` project contains a space.
