### PR TITLE
[@astrojs/image] Handle query params in remote image URLs during SSG builds

### LINKED ISSUE #4317: astrojs/image does not remove URL variables from remote image URLs
### What version of `astro` are you using?

1.0.4

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Currently in `@astrojs/image`, when using a remote image with URL variables (e.g. `https://example.com/123?access_token=abc`) gets resolved to the following local URL: `/_image/123?access_token=abc`.

This should be `/_image/123`, so that the access token is not leaked, and also just to save some space. The image is reachable by `/_image/123` already, the URL variables are not used in any way.

Slightly related: It seems that (in my experience) all generated URLs end with `.undefined`. Also something to look at?

Note regarding the linked example: It seems that `@astrojs/image` does not work in Stackblitz, so you'll have to run the example locally. Also note that you have to run `npm run build` to see the final generated URL (not `npm run dev`).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qse61x?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by tony-sull**
## Changes

Closes #4317 

When building optimized images for SSG builds, any query params used for remote images should be stripped out from the final built HTML

Note that during `astro dev` and for SSR builds the query params are still needed to make sure the remote image can be fetched properly

## Testing

Added `dev` and `build` test coverage for remote image query params in SSG and SSR

## Docs

Bug fix only

### CODE REVIEW

**Comment by FredKSchott** [comment]
Just confirming that this doesn’t strip them from the _requested_ image, and that example.com/image.png?id=1 doesn’t overwrite or conflict with `...?id=2`

**Comment by tony-sull** [comment]
@FredKSchott that's correct - the querystring is kept when pulling the original image by URL, it's only stripped off when building the `src` value and filename for `dist`

File: packages/integrations/image/src/utils/paths.ts [hunk 1]
```diff
@@ -5,13 +5,19 @@ import type { TransformOptions } from '../loaders/index.js';
...
 export function ensureDir(dir: string) {
 	fs.mkdirSync(dir, { recursive: true });
 }
 
 export function propsToFilename({ src, width, height, format }: TransformOptions) {
-	const ext = path.extname(src);
-	let filename = src.replace(ext, '');
+	let filename = removeQueryString(src);
+	const ext = path.extname(filename);
+	filename = filename.replace(ext, '');
```
Comment (matthewp) [inline packages/integrations/image/src/utils/paths.ts:20]: probably unlikely to happen but this replaces the first substring of the extension so if you had `foo.js.bar.js` it would become `foo.bar.js`. Using `lastIndexOf` to find where the extension is located and then substringing up to that point would be more technically correct I think.

Comment (tony-sull) [reply packages/integrations/image/src/utils/paths.ts]: Great catch, I handled that for stripping the querystring but forgot to move that over to `lastIndexOf + substring` for the extension

fixed in the latest commit :+1:

**Review by matthewp — APPROVED** [review]
