### PR TITLE
fix: do not generate a stub for content types

### LINKED ISSUE #12901: `astro:content` types missing after `astro.config` file save
### Astro Info

```block
Astro                    v5.1.2
Node                     v22.11.0
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Having a Content Layer config file present ie `/src/content.config.ts`, on saving the astro config file `/astro.config.mjs`, the `astro:content` types are no longer available, resulting in eg `Module '"astro:content"' has no exported member 'render'.` ts error.

I've noticed, that on astro config file save, the `/.astro/content.d.ts` file is emtied but not populated again, and it runs [this code branch](https://github.com/withastro/astro/blob/astro%405.1.2/packages/astro/src/core/sync/index.ts#L151-L166).

In effect similar to #12555.

### What's the expected result?

`astro:content` types not being lost during development.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-db2q7n7n?file=astro.config.mjs

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #12901
- We only generate a reference instead of the stub, which was overriding the generated types in rare cases

## Testing

Should pass

## Docs

N/A

### CODE REVIEW

**Review by ematipico — APPROVED** [review]

File: packages/astro/src/types/astro.ts [hunk 1]
```diff
@@ -64,7 +64,8 @@ export interface AstroSettings {
 	latestAstroVersion: string | undefined;
 	serverIslandMap: NonNullable<SSRManifest['serverIslandMap']>;
 	serverIslandNameMap: NonNullable<SSRManifest['serverIslandNameMap']>;
-	injectedTypes: Array<InjectedType>;
+	// This makes content optional. Internal only so it's optional on InjectedType
```
Comment (florian-lefebvre) [inline packages/astro/src/types/astro.ts:67]:
```suggestion
	// This makes content optional. Internal only so it's not optional on InjectedType
```
