### PR TITLE
fix: post API routes in SSG should warn or error during dev mode

### LINKED ISSUE #4875: `post` API routes in SSG should warn or error during dev mode
### What version of `astro` are you using?

1.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

You can export a `post()` API route during SSG. This works during dev mode, but is ignored during build. Since this is a discrepancy between dev and build, we should warn or error if used in dev mode.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-xb2gcs?file=src%2Fpages%2Findex.astro,src%2Fpages%2Ftest.json.ts&on=stackblitz

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fixes #4875

### CODE REVIEW

File: packages/astro/src/runtime/server/endpoint.ts [hunk 1]
```diff
@@ -18,9 +18,21 @@ function getHandlerFromModule(mod: EndpointHandler, method: string) {
...
+	request: Request,
+	params: Params,
+	ssr?: boolean
+) {
 	const chosenMethod = request.method?.toLowerCase();
 	const handler = getHandlerFromModule(mod, chosenMethod);
+	if (!ssr && ssr === false && chosenMethod && chosenMethod === 'post') {
+		// eslint-disable-next-line no-console
+		console.warn(`
+post method in API routes without output: 'server' in astro.config.mjs doesn't work. Note that the post route will be ignored during the build time.
```
Comment (matthewp) [inline packages/astro/src/runtime/server/endpoint.ts:32]:
```suggestion
${chosenMethod} requests are not available when building a static site. Update your config to `output: 'server'` to handle ${chosenMethod} requests.
```

File: packages/astro/src/runtime/server/endpoint.ts [hunk 2]
```diff
@@ -18,9 +18,21 @@ function getHandlerFromModule(mod: EndpointHandler, method: string) {
...
+
+Update your code to remove this warning.`);
```
Comment (matthewp) [inline packages/astro/src/runtime/server/endpoint.ts:34]: If you go with the suggestion I would remove this line.

File: packages/astro/src/runtime/server/endpoint.ts [hunk 3]
```diff
@@ -18,9 +18,21 @@ function getHandlerFromModule(mod: EndpointHandler, method: string) {
...
-export async function renderEndpoint(mod: EndpointHandler, request: Request, params: Params) {
+export async function renderEndpoint(
+	mod: EndpointHandler,
+	request: Request,
+	params: Params,
+	ssr?: boolean
+) {
 	const chosenMethod = request.method?.toLowerCase();
 	const handler = getHandlerFromModule(mod, chosenMethod);
+	if (!ssr && ssr === false && chosenMethod && chosenMethod === 'post') {
```
Comment (matthewp) [inline packages/astro/src/runtime/server/endpoint.ts:29]: We really should be doing this if `chosenMethod !== 'get'`

**Review by matthewp — APPROVED** [review]

**Review by okikio — APPROVED** [review]
Looks good to me
