### PR TITLE
fix(ssr): correctly call the middleware when rendering error pages

### LINKED ISSUE #7881: Middleware not called for non-custom 404 page
### What version of `astro` are you using?

2.9.6

### Are you using an SSR adapter? If so, which one?

Node

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Safari

### Describe the Bug

When you have `middleware.ts` setup, and a **custom** 404 page, the middleware will get called when you hit a 404 page. However, if you don't have a custom 404 page but rely on the default, the middleware won't get called.

Wondering if this is a deliberate decision?

### What's the expected result?

Consistency between the custom and non-custom 404 page. Both should call the middleware.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-pt4enm?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ematipico**
## Changes

Closes https://github.com/withastro/astro/issues/8154

This fix goes into `next` because it requires some infrastructure that we have there but not in `main`.

This PR removes the `onRequest` function from the "ComponentInstance", instead we move its resolution inside the pipeline. The middleware now becomes 100% detached from a page/route. 

This change fits perfectly because the SSR build already creates a `middleware.mjs` file, and we already save the `middlewareEntryPoint` file.

## Testing

I created a new test case.

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/core/redirects/component.ts [hunk 1]
```diff
@@ -12,6 +12,5 @@ export const RedirectComponentInstance: ComponentInstance = {
 
 export const RedirectSinglePageBuiltModule: SinglePageBuiltModule = {
 	page: () => Promise.resolve(RedirectComponentInstance),
-	onRequest: (ctx, next) => next(),
```
Comment (ematipico) [inline packages/astro/src/core/redirects/component.ts:15]: As you can see, there's no need for this stub anymore.

File: packages/astro/src/core/build/plugins/plugin-manifest.ts [hunk 2]
```diff
@@ -245,6 +250,7 @@ function buildManifest(
 		clientDirectives: Array.from(settings.clientDirectives),
 		entryModules,
 		assets: staticFiles.map(prefixAssetPath),
+		middlewareEntryPoint: internals.middlewareEntryPoint?.toString() ?? undefined,
```
Comment (ematipico) [inline packages/astro/src/core/build/plugins/plugin-manifest.ts:253]: We saved the entry point in the SSR manifest, as it was a route.

File: packages/astro/test/fixtures/middleware-dev/src/pages/404.astro [hunk 3]
```diff
@@ -0,0 +1,6 @@
+---
```
Comment (lilnasy) [inline packages/astro/test/fixtures/middleware-dev/src/pages/404.astro:1]: If 404.astro exists, this issue might be fixing #8154, **not** #7881. I think the older issue may even be intended behavior.

Comment (ematipico) [reply packages/astro/test/fixtures/middleware-dev/src/pages/404.astro:1]: @lilnasy why do you think #7881 should be the intended behaviour? Genuinely asking! You might be onto something

Comment (lilnasy) [reply packages/astro/test/fixtures/middleware-dev/src/pages/404.astro:1]: I'm thinking about the cases where an adapter tries to handle unmatched requests by bypassing the core app.

Some serverless platforms may not even call `app.render()`: if they find no matching route and no prerendered page, they might fallback to a platform-specific 404 page.

On a different note, if we were to wrap middleware around our default response (`new Response(null, { status: 404 })`), it would likely cause another wave of issues because I doubt many users are accounting for `next()`'s body being null.

Comment (ematipico) [reply packages/astro/test/fixtures/middleware-dev/src/pages/404.astro:1]: That makes total sense! I agree with every point.
