### PR TITLE
Prevent CSS from being added to pages not using it

### LINKED ISSUE #2908: 🐛 BUG: <style global> appears on pages that it shouldn't, build only
### What version of `astro` are you using?

0.25.2

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

When upgrading Astro.build to v0.25, I encountered a weird styling issue. Global styles from the blog page were appearing on the home page, breaking the homepage appearance.

Reverting [this commit](https://github.com/withastro/astro.build/commit/9e1d1dc469365a80df8eba56c21a79e391e4acc3) will re-introduce the error.

Screen Shot 2022-03-27 at 5 06 33 PM

Unclear if this was introduced by upgrading to v0.25, OR if the upgrade combined [the fix](https://github.com/withastro/astro.build/commit/17cdf6ec3038228698e5ef05f3c828a37bf75017#diff-7f2bb650ebd4f62eed5e3c6f8b11553b541064b5a9ef01c815cb148e716090beR31-R33) for https://github.com/withastro/astro/issues/2904 introduced the regression.

### Link to Minimal Reproducible Example

https://github.com/withastro/astro.build/commit/9e1d1dc469365a80df8eba56c21a79e391e4acc3

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Since we are bundling into a single file for the build now, we need to do CSS slightly differently.
- This changes the static build so that at the end of the build it walks the module graph and collects the CSS for each page and builds a bundle based on that, rather than relying on Rollup's chunking; there is only 1 chunk so that way can't work now.
- Fixes #2908

## Testing

Test added

## Docs

N/A, bug fix.

### CODE REVIEW

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 1]
```diff
@@ -156,6 +176,34 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
...
+							minify: true,
+						});
+						const referenceId = this.emitFile({
+							name: 'entry' + '.css',
+							type: 'asset',
+							source: minifiedCSS,
+						});
+						const fileName = this.getFileName(referenceId);
+
+						getPageDataByViteID(internals, id)?.css.add(fileName);
```
Comment (FredKSchott) [inline packages/astro/src/vite-plugin-build-css/index.ts:202]: worth an error if `getPageDataByViteID(internals, id)` doesn't appear? I can imagine this being error-worthy vs. silently failing

Comment (matthewp) [reply packages/astro/src/vite-plugin-build-css/index.ts:202]: No, we've already verified that this is a page's module with the `hasPageDataByViteID` check. Can add a clarifying comment.

File: packages/astro/src/vite-plugin-build-css/index.ts [hunk 2]
```diff
@@ -156,6 +176,34 @@ export function rollupPluginAstroBuildCSS(options: PluginOptions): VitePlugin {
 				.replace(/\./g, '\\.');
 			const emptyChunkRE = new RegExp(opts.format === 'es' ? `\\bimport\\s*"[^"]*(?:${emptyChunkFiles})";\n?` : `\\brequire\\(\\s*"[^"]*(?:${emptyChunkFiles})"\\);\n?`, 'g');
 
+			// Crawl the module graph to find CSS chunks to create
+			if(!legacy) {
+				for(const id of this.getModuleIds()) {
```
Comment (FredKSchott) [inline packages/astro/src/vite-plugin-build-css/index.ts:181]: if you move this into a separate function, it might be a bit easier to document / more self-documenting. Normally I'd call this a nit, but this sounds big & important enough that more documentation would be a good idea.

```js
if (!legacy) {
  this.addImportedStyles()
}

// ...

/** Use this comment to talk about why this is required **/
addImportedStyles() {

}
```

**Review by FredKSchott — APPROVED** [review]
LGTM! Small comments around docs and defensive coding
