### PR TITLE
Remove duplicate CSS in dev

### LINKED ISSUE #5817: CSS Sourcemap Duplication of References in Dev
### What version of `astro` are you using?

1.9.1

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

This is part of an old closed issue that needs addressing since Astro 1.0.0-beta42. 
Original issue: https://github.com/withastro/astro/issues/3647

I thought it might work itself out with future Astro versions. Even with Astro 2 beta which utilizes Vite v4, the issue persists.

With CSS sourcemaps enabled, there is duplicate CSS being referenced from both the css file and page file. This can make debugging css extremely tedious. I thought maybe it was a Vite bug. After using Vite as standalone compiler and Sveltekit 1.0, that doesn't seem to be the case as there is no CSS sourcemap duplication with these libraries. 

```js
// astro.config.mjs
vite: {
    css: {
      devSourcemap: true,
    },
  },
```
Screenshot 2023-01-10 at 11 45 47 AM

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-g7v2dq

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #5817
- Better handling for CSS in dev
- Includes the Vite ID of SSR'd styles so they can be removed once Vite takes over on the client

## Testing

- E2E test added for default handling
- E2E test added to confirm this also works when `vite.css.devSourcemap` is enabled

## Docs

Bug fix only

### CODE REVIEW

File: packages/astro/src/core/render/dev/index.ts [hunk 1]
```diff
@@ -133,7 +133,11 @@ async function getScriptsAndStyles({ env, filePath }: GetScriptsAndStylesParams)
 		});
 		// But we still want to inject the styles to avoid FOUC
 		styles.add({
-			props: {},
+			props: {
+				type: 'text/css',
```
Comment (matthewp) [inline packages/astro/src/core/render/dev/index.ts:137]: is this because vite needs the attributes to match? if not, `type` is not need on script or style, `<style>` is always text/css.

Comment (natemoo-re) [reply packages/astro/src/core/render/dev/index.ts:137]: No, `data-astro-dev-id` is the only _necessary_ change here. I just added this for consistency with the styles Vite injects.

**Review by matthewp — APPROVED** [review]
