### PR TITLE
Fixes a style issue of `client:only` components in DEV mode during view transitions.

### LINKED ISSUE #10466: CSS imported into (solid) islands is not loaded on subsequent page loads when using view transitions and client:only in dev
### Astro Info

```block
Astro                    v4.5.5
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/tailwind
                         @astrojs/solid-js
                         @astrojs/mdx
                         @sentry/astro
```

### If this issue only occurs in one browser, which browser is a problem?

I have seen this happen in both Chrome and Firefox.

### Describe the Bug

When importing CSS into a solid island (may be other islands too, I haven't tested other frameworks), the CSS loads fine on the initial page load, but when you navigate away and come back (with view transitions) the CSS is not loaded properly and the page looks broken.

This only appears to affect `client:only` (at least when using `client:visible` the CSS always loads correctly).

The included example sets builds on the official solid example. Click on the `Another page` link and then click the `Counter` link.

The fix is to move the CSS import from `Counter.tsx` to `index.astro`, then the CSS is always loaded properly under every circumstance, including with view transitions and `client:only`.

### What's the expected result?

CSS imported in islands should load properly when navigating around the site using view transitions and `client:only`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-eqw3jl?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by martrapp**
## Changes

fixes #10466 

Originally fixed for client:only components that use transition:persist in #8840.
It turns out that the styles were also missing when navigating back to pages with non-persisted `client:only` components.

## Testing

e2e tests successful

## Docs

bug fix, n.a.

### CODE REVIEW

File: packages/astro/src/transitions/router.ts [hunk 1]
```diff
@@ -696,18 +696,13 @@ async function prepareForClientOnlyComponents(newDocument: Document, toLocation:
...
-				.forEach((s) => s.removeAttribute(PERSIST_ATTR));
-
 			// Collect the vite ids of all styles present in the next head
 			const viteIds = [...nextHead.querySelectorAll(`style[${VITE_ID}]`)].map((style) =>
 				style.getAttribute(VITE_ID)
 			);
 			// Copy required styles to the new document if they are from hydration.
 			viteIds.forEach((id) => {
-				const style = document.head.querySelector(`style[${VITE_ID}="${id}"]`);
+				const style = nextHead.querySelector(`style[${VITE_ID}="${id}"]`);
```
Comment (martrapp) [inline packages/astro/src/transitions/router.ts:705]: Instead of copying the styles from the last page, we no copy from the iframe. This also works for non-persisted `client:only` components.

File: packages/astro/src/transitions/router.ts [hunk 2]
```diff
@@ -696,18 +696,13 @@ async function prepareForClientOnlyComponents(newDocument: Document, toLocation:
 
 		const nextHead = nextPage.contentDocument?.head;
 		if (nextHead) {
-			// Clear former persist marks
-			document.head
-				.querySelectorAll(`style[${PERSIST_ATTR}=""]`)
-				.forEach((s) => s.removeAttribute(PERSIST_ATTR));
-
```
Comment (martrapp) [inline packages/astro/src/transitions/router.ts:703]: This was a remnant of an earlier approach.

**Review by matthewp — APPROVED** [review]
