### PR TITLE
fix: update Cloudflare adapter's default image service

### LINKED ISSUE #15319: Astro v6 + CloudFlare adapter + `<Image>` in dev mode throws error
### Astro Info

```block
Astro                    v6.0.0-beta.3
Vite                     v7.3.1
Node                     v24.13.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/cloudflare (v13.0.0-beta.1)
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

A newly created project using the current beta of Astro and the Cloudflare adapter, upgraded to current v6 beta releases, throws an error in the browser when there is an `<Image>` component on a page, in `astro dev` mode only (`build` + `preview` works correctly.)

## Steps to reproduce

1. Clone the reproduction repository below
2. Run `pnpm install`
3. Run `pnpm run dev`
4. Open `http://localhost:4321` in your browser

### Actual result

Error:

```
The file does not exist at "[PATH TO PROJECT]/node_modules/.vite/deps_ssr/chunk-BB2NZPL6.js?v=c17d9a8e" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.

    at CustomModuleRunner.cachedModule (workers/runner-worker.js:1196:20)
    at request (workers/runner-worker.js:1123:83)
    at null.<anonymous> (/home/ndc/projects/astro-cloudflare-image-repro/node_modules/.vite/deps_ssr/chunk-FCOL542Q.js:1:1)
    at Object.runInlinedModule (workers/runner-worker.js:1314:4)
    at CustomModuleRunner.directRequest (workers/runner-worker.js:1166:59)
    at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1084:73)
    at null.<anonymous> (/home/ndc/projects/astro-cloudflare-image-repro/node_modules/.vite/deps_ssr/chunk-HKIE33OW.js:1:1)
    at Object.runInlinedModule (workers/runner-worker.js:1314:4)
    at CustomModuleRunner.directRequest (workers/runner-worker.js:1166:59)
    at CustomModuleRunner.cachedRequest (workers/runner-worker.js:1084:73)
```

### What's the expected result?

You should see an image in the browser.

### Additional notes

Building the project with

```
pnpm run build
pnpm run preview
```

Does NOT manifest the error (the page with the image is shown correctly.)

Apologies for the GitHub repro, as with #15194 I couldn't get `workerd` to run in stackblitz.

### Link to Minimal Reproducible Example

https://github.com/n3dst4/astro-cloudflare-image-repro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by rururux**
fixes #15319, fixes https://github.com/withastro/astro/issues/15437

From @Princesseuh:

Updates the default option for the Cloudflare adapter to use the bindings by default, and fix the dev experience on all the other settings. In v6 sharp cannot work in dev anymore because it doesn't run in workerd, so everything became passthrough.

Additionally, this PR changes how we do the picomatch excludes to ensure we don't import CJS at runtime in the endpoint. Sucks that picomatch is still in CJS.

Docs: https://github.com/withastro/docs/pull/13267

<details>
<summary> Original comment here </summary>

## Changes

Previously, an error occurred when using the Cloudflare adapter in combination with the `<Image />` component. This issue is caused by Astro's default behavior: when no image entrypoint is specified in a development environment, it defaults to `astro/assets/endpoint/dev`.
https://github.com/withastro/astro/blob/840fbf9e4abc7f847e23da8d67904ffde4d95fff/packages/astro/src/assets/endpoint/config.ts#L24-L29
Since this default dev entrypoint depends on Vite, it attempts to bundle Vite as a dependency during the development server build, leading to the error.
https://github.com/withastro/astro/blob/840fbf9e4abc7f847e23da8d67904ffde4d95fff/packages/astro/src/assets/endpoint/dev.ts#L6
To resolve this, I have updated the Cloudflare adapter to automatically use `@astrojs/cloudflare/image-endpoint` as the image entrypoint for development.
There might be a more optimal way to specify this configuration, but I couldn't come up with a better alternative at this time.
I am submitting this PR as-is for initial review.

## Testing

I have updated `compile-image-service.test.js`, which is affected by this change, to include tests for the development server.
While it may be necessary to add tests covering all [`imageService`](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#imageservice) options, I have left it as is for now to facilitate the review process.

## Docs
N/A

</details>

### CODE REVIEW

File: packages/integrations/cloudflare/src/utils/image-config.ts [hunk 1]
```diff
@@ -14,6 +14,10 @@ export function setImageConfig(
 	command: HookParameters<'astro:config:setup'>['command'],
 	logger: AstroIntegrationLogger,
 ) {
+	if (command === 'dev' && config.endpoint.entrypoint === undefined) {
+		config.endpoint.entrypoint = '@astrojs/cloudflare/image-endpoint';
```
Comment (florian-lefebvre) [inline packages/integrations/cloudflare/src/utils/image-config.ts]: Mutating probably isn't fine as it would mutate the whole Astro config. I think it would be better to follow the pattern below of returning a copy instead

Comment (rururux) [reply packages/integrations/cloudflare/src/utils/image-config.ts]: Thank you for your review!
Which approach do you think is more appropriate?

1.
```diff
+ const clonedConfig = structuredClone(config)
- if (command === 'dev' && config.endpoint.entrypoint === undefined) {
- 	config.endpoint.entrypoint = '@astrojs/cloudflare/image-endpoint';
+ if (command === 'dev' && clonedConfig.endpoint.entrypoint === undefined) {
+ 	clonedConfig.endpoint.entrypoint = '@astrojs/cloudflare/image-endpoint';
}
```

2.
```diff
export function setImageConfig(
	service: ImageService,
	config: AstroConfig['image'],
	command: HookParameters<'astro:config:setup'>['command'],
	logger: AstroIntegrationLogger,
) {
+ 	const updatedConfig = {
+ 		...config,
+ 		endpoint: {
+ 			...config.endpoint,
+ 			entrypoint: config.endpoint.entrypoint ?? '@astrojs/cloudflare/image-endpoint',
+ 		},
+ 	}

	switch (service) {
		case 'passthrough':
```

3.
```ts
// Other approaches
```

---

If my understanding is correct, honestly, I’m afraid that the following approach might overwrite `config.endpoint.route` with undefined if it was originally specified:
```ts
return { ...config, endpoint: { entrypoint: '...' } }
```

Comment (florian-lefebvre) [reply packages/integrations/cloudflare/src/utils/image-config.ts]: Yeah I think approach 1 would work well. Why do you think it could be overriden?

Comment (rururux) [reply packages/integrations/cloudflare/src/utils/image-config.ts]: Sorry for the confusion! I was just thinking about the behavior of the spread operator.

In a pattern like `{ ...config, endpoint: { entrypoint: '...' } }`, the `endpoint` object is replaced entirely, so properties like `route` would be lost.
That's what I was worried about.

Since Approach 1 avoids that by mutating a deep clone, I think it's the safest way to go. I'll proceed with that!

**Comment by OliverSpeir** [comment]
Why not keep compile as the default? doesn't this fix compile in dev as well?

**Comment by Princesseuh** [comment]
> Why not keep compile as the default? doesn't this fix compile in dev as well?

~~No, in v6 since the dev runs in workerd sharp never actually works. The flag isn't enough because of the native deps and what not. The current config right now just results in broken images in dev, no matter what you do.~~

Realized I misread this, yes compile now works in dev by using passthrough, but it's not an amazing default experience to have image optimization be noop so bindings should lead to a better experience

**Comment by alexanderniebuhr** [comment]
I was planning to do the same, but I think it is not enough to just switch it.
IIRC the binding one only works if you [enable Image Transformation](https://developers.cloudflare.com/images/get-started/#enable-transformations-on-your-zone) for the Domain in the Cloudflare dashboard.
That means when users just deploy without enabling that feature on the dns zone (which has a free tier, but is a pay by usage) it wouldn't work on production. *(correct me when i'm wrong)*

Also doesn't we already require `nodejs_compat` because of some ALS stuff? 🤔

**Comment by matthewp** [comment]
This PR is missing a changeset `pnpm changeset`

**Comment by Princesseuh** [comment]
I'll do the changeset once I actually know what we're doing. What the PR actually does has already changed twice since its creation

**Review by OliverSpeir — APPROVED** [review]

**Comment by OliverSpeir** [comment]
I don't mean to hijack this, we can move the https://github.com/withastro/astro/pull/15435/commits/66a44d7de3930e6c908c2425ec4e1413de0295ca out of here if we want but I figured it's easier to keep all in context at least to get some feedback 

the idea is this will fix compile and then it opens the quesiton up if we do fix compile and everything works properly which do we want as the default? Netlify adapter I think now defaults to the equivalent of `cloudflare-binding` which skips transforming images at build time

**Comment by alexanderniebuhr** [comment]
I still think `cloudflare-binding` is the correct default option.

File: .changeset/cloudflare-image-component.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+"@astrojs/cloudflare": minor
```
Comment (sarah11918) [inline .changeset/cloudflare-image-component.md]: Just checking that changing a default setting is a potentially a breaking change, and probably a major?

Will note that this requires an entry in the specific Cloudflare upgrade guide, so if you want to follow the pattern for other major upgrades and simply write a one-liner, then link to the docs there, that would be fine!

**Comment by OliverSpeir** [comment]
Here's a little ai overview of the commit, because its a bit dense 

<details>
<summary>Commit Breakdown: `66a44d7` — feat: fix/improve compile</summary>

  ### 1. Refactor `generate.ts` to decouple from `App` instance
  **`packages/astro/src/assets/build/generate.ts`**

  `prepareAssetsGenerationEnv` now takes `StaticBuildOptions` directly instead of needing an `App` instance. This
  matters because Cloudflare's prerenderer doesn't create a default Astro `App` — it runs in workerd with its own
  `createApp()`. The generation pipeline just needs config/logger/paths, not the full app.

  ### 2. Vendor `deterministic-string`, move hash utils to runtime-agnostic modules
  **`packages/astro/src/assets/utils/deterministic-string.ts`**, **`packages/astro/src/assets/utils/hash.ts`**

  The `deterministic-object-hash` package pulled in `node:crypto`, which requires `nodejs_compat` in workerd. This
   commit vendors only the `deterministicString` function (excluding the async `deterministicHash` that uses
  `node:crypto`), and moves `hashTransform` + `propsToFilename` into a standalone `hash.ts` with pure-string
  replacements for `path.posix.basename/dirname/extname` — zero `node:` imports. This means `astro/assets` can be
  imported in workerd without triggering nodejs_compat requirements.

  ### 3. Move teardown after asset generation
  **`packages/astro/src/core/build/generate.ts:185-196`**

  The ordering is now: **render pages → `collectStaticImages()` → `teardown()` → generate images with Sharp**.
  Previously teardown happened before image generation. This is critical because `collectStaticImages` needs to
  fetch the image list from the workerd preview server (which teardown shuts down).

  ### 4. Extend `AstroPrerenderer` with `collectStaticImages`
  **`packages/astro/src/types/public/integrations.ts:196`**

  New optional method on the prerenderer interface:
  ```ts
  collectStaticImages?: () => Promise<AssetsGlobalStaticImagesList>;
  ```
  This lets adapters contribute images discovered in their runtime back to the Node-side generation pipeline. The
  core pipeline merges these into `staticImageList` before running Sharp transforms.

  ### 5. Rename image service, add workerd stub
  **`image-service.ts` → `image-service-external.ts`**, **new `image-service-workerd.ts`**

  The old `image-service.ts` (Cloudflare URL-based transforms) is renamed to `image-service-external.ts` for
  clarity. The new `image-service-workerd.ts` extends `baseService` with a passthrough `transform()`. It's the
  **URL generation stub**: it handles `getURL`/`getHTMLAttributes`/`addStaticImage` inside workerd without
  importing Sharp. The actual pixel work happens later on the Node side via Sharp.

  ### 6. Provision IMAGES binding in dev for `compile` mode
  **`packages/integrations/cloudflare/src/index.ts:97-106`**

  In dev, `compile` mode needs the IMAGES binding so the `image-transform-endpoint` can use miniflare's local
  image transforms. Without this, dev would need Sharp in workerd, which works but spews confusing compatibility
  warnings. At build time, `compile` uses Sharp on the Node side instead, so the binding isn't needed.

  ### 7. Split image service config into build-time and runtime
  **`packages/integrations/cloudflare/src/utils/image-config.ts:19-36`**

  `normalizeImageServiceConfig` now splits a single `imageService` option into `{ buildService, runtimeService }`.
   This supports the compound config `{ build: 'compile', runtime?: 'cloudflare-binding' | 'passthrough' }` —
  compile-time Sharp transforms at build, with a separate runtime strategy for SSR routes.

  ### 8. Virtual config plugin provides `compileImageConfig` and `isPrerender` flags
  **`packages/integrations/cloudflare/src/vite-plugin-config.ts`**

  The `virtual:astro-cloudflare:config` virtual module now exports `compileImageConfig` (the
  base/assetsPrefix/entrypoint config needed to install `addStaticImage`) and `isPrerender` (true when the Vite
  environment is `'prerender'`). These are consumed by `handler.ts` to conditionally enable the collection and
  endpoint machinery.

  ### 9. How the static image collection and endpoint works

  This is the core mechanism of the PR. Static images accumulate as a
  **side effect of rendering pages** in workerd, and then Node **pulls** the collected list out via an internal
  endpoint.

  #### Collection (side effect of rendering)

  When `isPrerender` is true and `compileImageConfig` is set, every incoming request to the worker installs
  `addStaticImage` on `globalThis.astroAsset`:

  **`handler.ts:41-45`** — entry point, conditionally installs the collector:
  ```ts
  if (isPrerender) {
      if (compileImageConfig) {
          const { installAddStaticImage } = await import('./static-image-collection.js');
          installAddStaticImage(compileImageConfig);
      }
      // ... route to internal endpoints
  }
  ```

  **`static-image-collection.ts:11-65`** — `installAddStaticImage` sets `globalThis.astroAsset.addStaticImage`,
  which mirrors `vite-plugin-assets.ts` logic but with zero `node:` imports. When Astro components render
  `<Image>` tags during prerendering, the framework calls `addStaticImage()`, which hashes the transform and
  records `{ finalPath, transform }` into `globalThis.astroAsset.staticImages` (a `Map`).

  So by the time all pages have been rendered via `/__astro_prerender`, `globalThis.astroAsset.staticImages`
  contains every image transform discovered during prerendering.

  When the Node-side build is done rendering pages, it calls `prerenderer.collectStaticImages()`:

  **`prerenderer.ts:126-158`** — sends a POST to `/__astro_static_images` on the preview server:
  ```ts
  const response = await fetch(`${serverUrl}${STATIC_IMAGES_ENDPOINT}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
  });
  ```

  This request hits the preview server (started at `prerenderer.ts:60-74` via Vite's `preview()`), the Cloudflare
  Vite plugin routes it into workerd, and `handler.ts:52-55` matches it:

  ```ts
  if (isStaticImagesRequest(request)) {
      return handleStaticImagesRequest() as unknown as CfResponse;
  }
  ```

  **`prerender.ts:90-114`** (utils) — `handleStaticImagesRequest()` serializes
  `globalThis.astroAsset.staticImages` into JSON and returns it:
  ```ts
  export function handleStaticImagesRequest(): Response {
      const staticImages = globalThis.astroAsset?.staticImages;
      // ... serialize Map entries to JSON array
      return new Response(JSON.stringify(entries), { ... });
  }
  ```

  #### Back on the Node side

  **`prerenderer.ts:141-157`** — after receiving the JSON, the adapter:
  1. Deserializes the entries back into an `AssetsGlobalStaticImagesList` Map
  2. **Swaps the image service to Sharp**: `globalThis.astroAsset.imageService = sharpService` — workerd used the
  passthrough stub, but the Node pipeline needs Sharp for actual transforms

  **`generate.ts:187-192`** — the core build merges adapter images into the static image list:
  ```ts
  if (prerenderer.collectStaticImages) {
      const adapterImages = await prerenderer.collectStaticImages();
      for (const [path, entry] of adapterImages) {
          staticImageList.set(path, entry);
      }
  }
  ```

  Then teardown happens at `:196`, and the standard Sharp generation pipeline runs at `:203-288`.

  #### Internal prerender endpoints
  **`packages/integrations/cloudflare/src/utils/prerender-constants.ts`**

  Three internal endpoints, all only active when `isPrerender` is true:
  - `/__astro_static_paths` — returns routes that need prerendering
  - `/__astro_prerender` — renders a single page
  - `/__astro_static_images` — drains the collected static image list from workerd
  
  </details>

**Review by sarah11918 — COMMENTED** [review]
Ugh, apparently I had a pending review comment here

**Review by matthewp — APPROVED** [review]
Very clever approach to generating the list in the workerd side and then passing back over to Node.js side for sharp processing. Very nicely done!

**Comment by florian-lefebvre** [comment]
Does this also fix #15437?

**Comment by Princesseuh** [comment]
> Does this also fix #15437?

Yes

**Comment by ematipico** [comment]
@rururux i'm ready to merge the PR once the conflicts are resolved

**Comment by rururux** [comment]
Sorry, I was a bit slow to react! 😅 Thanks for jumping in and handling this, @Princesseuh!

**Comment by sarah11918** [comment]
Will note that something came up while preparing the docs that I think is relevant to ask here! https://github.com/withastro/docs/pull/13267#discussion_r2840546420

File: packages/astro/package.json [hunk 3]
```diff
@@ -131,7 +131,7 @@
     "common-ancestor-path": "^2.0.0",
     "cookie": "^1.1.1",
     "cssesc": "^3.0.0",
-    "deterministic-object-hash": "^2.0.2",
+    "debug": "^4.4.3",
```
Comment (rururux) [inline packages/astro/package.json]: Do we still need this debug package?
If I understand correctly, I believe it was removed in this PR.
https://github.com/withastro/astro/pull/15565/changes#diff-31a85c0b4c5526a896f02b675a49f1f942ec15fa815f6326edc4f74248aa0048

File: .changeset/cloudflare-image-component.md [hunk 4]
```diff
@@ -0,0 +1,5 @@
+---
+"@astrojs/cloudflare": major
+---
+
+Changes the default image service from `compile` to `cloudflare-binding`. Image services options that resulted in broken images in development due to Node JS incompatiblities have now been updated to use the passthrough image service in dev mode.
```
Comment (sarah11918) [inline .changeset/cloudflare-image-component.md]:
```suggestion
Changes the default image service from `compile` to `cloudflare-binding`. Image services options that resulted in broken images in development due to Node JS incompatiblities have now been updated to use the noop passthrough image service in dev mode. - ([Cloudflare v13 and Astro6 upgrade guidance](https://v6.docs.astro.build/en/guides/integrations-guide/cloudflare/#changed-imageservice-default))
```
Let's just make sure people can get to the upgrade guide guidance!

File: .changeset/cloudflare-image-service-object.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+"@astrojs/cloudflare": minor
+---
+
+Adds support for configuring the image service as an object with separate `build` and `runtime` options. It is now possible to set both a build time and runtime service independently. Currently, `'compile'` is the only available build time option. The supported runtime options are `'passthrough'` (default) and `'cloudflare-binding'`.
```
Comment (sarah11918) [inline .changeset/cloudflare-image-service-object.md]:
``````suggestion
Adds support for configuring the image service as an object with separate `build` and `runtime` options

It is now possible to set both a build time and runtime service independently. Currently, `'compile'` is the only available build time option. The supported runtime options are `'passthrough'` (default) and `'cloudflare-binding'`:

```js title="astro.config.mjs" ins={6}
import { defineConfig } from 'astro/config';
import cloudflare from '@astrojs/cloudflare';

export default defineConfig({
  adapter: cloudflare({
    imageService: { build: 'compile', runtime: 'cloudflare-binding' }
  }),
});

See the [Cloudflare adapter `imageService` docs](/en/guides/integrations-guide/cloudflare/#imageservice) for more information about configuring your image service.
``````
For a minor, we do like to both show an example and link to the new docs. How about this?

File: .changeset/cloudflare-image-service-object.md [hunk 6]
```diff
@@ -0,0 +1,19 @@
+---
+"@astrojs/cloudflare": minor
+---
+
+Adds support for configuring the image service as an object with separate `build` and `runtime` options
+
+It is now possible to set both a build time and runtime service independently. Currently, `'compile'` is the only available build time option. The supported runtime options are `'passthrough'` (default) and `'cloudflare-binding'`:
```
Comment (sarah11918) [inline .changeset/cloudflare-image-service-object.md]:
```suggestion
It is now possible to set both a build-time and runtime service independently. Currently, `'compile'` is the only available build time option. The supported runtime options are `'passthrough'` (default) and `'cloudflare-binding'`:
```
In before Yan!

**Comment by rururux** [comment]
When I first opened this pull request, I never imagined it would grow into something this big. Thank you all so much!
