### PR TITLE
fix(preact): include server.js in SSR optimizeDeps for Cloudflare

### LINKED ISSUE #15361: v6 + Cloudflare + Preact `useEffect` doesn't work in local dev
### Astro Info

```block
Astro                    v6.0.0-beta.6
Node                     v24.12.0
System                   macOS (arm64)
Package Manager          bun
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/preact
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

If you use the v6 beta of `astro` with the Cloudflare adapter (also using the beta version) and then try to add some kind of Preact (I saw the same issue for the React integration on first-load but never again thereafter) client component that uses `useEffect` with a `client:load` directive it will fail to render both the client component and anything else below it in the render tree.

This only seems to affect the local Astro development server. If you generate a build and run `wrangler dev` it will work and render just fine.

### What's the expected result?

Ideally this should work similar to v5 where you can use `client:load` directive on any client component, including those with a `useEffect`.

### Link to Minimal Reproducible Example

https://github.com/nurodev/repro-astro-v6-use-effect-on-load

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Fix Preact components failing to render in Cloudflare dev mode
- Include `@astrojs/preact/server.js` in Vite's `optimizeDeps`
- Previously, `server.js` was explicitly excluded, causing `preact-render-to-string` to load a separate Preact instance from user components, breaking hooks
- Fixes #15361

## Testing

- Added e2e test for Preact component with `useEffect` and `client:load` in the Cloudflare fixture

## Docs

No docs changes needed - this is a bug fix for existing functionality.

### CODE REVIEW

File: packages/integrations/preact/src/index.ts [hunk 1]
```diff
@@ -68,9 +72,7 @@ function configEnvironmentPlugin(compat: boolean | undefined): Plugin {
 		name: '@astrojs/preact:environment',
 		configEnvironment(environmentName, options) {
 			const environmentOptions: EnvironmentOptions = {
-				optimizeDeps: {
-					exclude: ['@astrojs/preact/server.js'],
-				},
+				optimizeDeps: {},
```
Comment (ematipico) [inline packages/integrations/preact/src/index.ts:77]: I don't understand why we didn't add the new code **here**, which is the plugin in charge for configuring the environment.

Comment (matthewp) [reply packages/integrations/preact/src/index.ts:77]: I don't fully understand either to be honest, I did try putting it here but the dep is not optimized. Perhaps something else is overriding the config? I'm not sure.

Comment (ematipico) [reply packages/integrations/preact/src/index.ts:77]: Ok, it's worth leaving a comment then

Comment (matthewp) [reply packages/integrations/preact/src/index.ts:77]: yeah good call, will do.

File: packages/integrations/preact/src/index.ts [hunk 2]
```diff
@@ -34,7 +34,11 @@ export default function ({ include, exclude, compat, devtools }: Options = {}):
 					},
 				});
 
-				const viteConfig: ViteUserConfig = {};
+				const viteConfig: ViteUserConfig = {
+					optimizeDeps: {
+						include: ['@astrojs/preact/server.js'],
```
Comment (matthewp) [inline packages/integrations/preact/src/index.ts:41]:
```suggestion
						// Ideally would be environment config, but
						// putting it there does not result in it being optimized
						include: ['@astrojs/preact/server.js'],
```

File: packages/integrations/preact/src/index.ts (hunk 1 above)
Comment (matthewp) [reply packages/integrations/preact/src/index.ts:77]: Added here: e2b0fa971841c834e1f81d77c40783ff841d4771

**Review by ematipico — APPROVED** [review]
