### PR TITLE
fix(core): append assetQueryParams to inter-chunk JS imports (#15964)

### LINKED ISSUE #15964: Skew protection assetQueryParams not applied to hoisted scripts and inter-chunk JS imports (Vercel)
### Astro Info

```block
Astro                    v5.18.1
Vite                     v6.4.1
Node                     v22.22.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node (v9.5.5)
Integrations             @astrojs/vue (v5.1.4)
                         @storyblok/astro (v7.3.9)
                         client:hashchange
```

### If this issue only occurs in one browser, which browser is a problem?

N/A (server-side rendering on Vercel)

### Describe the Bug

When using `@astrojs/vercel` with `skewProtection: true`, the adapter's `assetQueryParams` (e.g. `?dpl=<VERCEL_DEPLOYMENT_ID>`) are not applied consistently to all client-side assets. We traced three distinct code paths where `?dpl=` is missing:

### 1. `<astro-island>` hydration attributes (`component-url`, `renderer-url`)

`AppPipeline.headElements()` in `packages/astro/src/core/app/pipeline.ts` calls `createModuleScriptElement(script)` without passing `queryParams`. The `resolve()` function in `App` looks up `manifest.entryModules` which contained raw bundle paths without `assetQueryParams`.

**Addressed by https://github.com/withastro/astro/pull/15931** (shipping in `astro@6.0.6`), which applies `appendAssetQuery()` to `entryModules` during manifest serialization.

### 2. Hoisted `<script>` tags from `.astro` components

When an `.astro` component (e.g. a layout partial) contains a `<script>` tag, Astro bundles it as a "discovered script" and resolves it at runtime via:

```
renderScript() → result.resolve(id) → manifest.entryModules[id] → createAssetLink()
```

This shares the same `entryModules` code path as island URL resolution, so **PR #15931 should also fix this**. However, the PR's test coverage only asserts `component-url` and `renderer-url` on `<astro-island>` — it doesn't explicitly test hoisted `<script src="...">` tags. Since hoisted scripts in layout partials are a very common pattern, adding a test case for them would help prevent regressions.

### 3. Relative imports inside JS chunks (NOT addressed by PR #15931)

When Vite code-splits the client bundle, the resulting chunks contain relative import statements like:

```js
import{a}from"./chunk.Abc123.js"
import"./dep.Xyz789.js"
import("./lazy.Qrs456.js")
```

These live inside compiled `.js` file content, not in the HTML output, and are therefore not affected by `assetQueryParams` at all. Without `?dpl=`, a browser loading `chunk-A.js?dpl=xxx` will resolve its deep imports *without* the `?dpl=` param, causing them to be served from the latest deployment instead of the pinned one — breaking skew protection for the entire dependency tree.

**This is fundamentally a Vite/Rollup output concern**, not an Astro HTML-rendering issue, so PR #15931 does not cover it. We currently work around this with a custom Vite `generateBundle` plugin that post-processes all chunk code to append `?dpl=` to relative `.js` import paths after minification.

## Questions

1. Can you confirm that PR #15931 covers hoisted component scripts (case 2) in addition to island hydration URLs?
2. Is there a planned approach for handling inter-chunk JS imports (case 3) at the adapter level?

### What's the expected result?

When `skewProtection: true` is enabled, **all** client-side asset references should include `?dpl=<VERCEL_DEPLOYMENT_ID>`:

- `<astro-island component-url="/_astro/Foo.hash.js?dpl=...">` ✅ (fixed by PR #15931)
- `<script type="module" src="/_astro/boot.hash.js?dpl=...">` ❓ (likely fixed, needs confirmation)
- `import"./chunk.hash.js?dpl=..."` inside JS chunks ❌ (not addressed)

Without this, any asset loaded without `?dpl=` bypasses skew protection and may be served from a different deployment, causing version mismatches at runtime.

### Link to Minimal Reproducible Example

https://github.com/philipprothmann2iterate/astro-vercel-skew-protection-js-imports

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by tmimmanuel**
## Changes

- Fixes Case 3 from #15964: inter-chunk JS imports inside client bundles were missing `assetQueryParams` (e.g., `?dpl=<VERCEL_DEPLOYMENT_ID>`), breaking Vercel skew protection for code-split apps
- Adds a new Vite `renderChunk` plugin (`plugin-chunk-imports.ts`) that rewrites relative import paths in client chunks to include the configured query parameters
- Plugin only runs on client chunks, and is a complete no-op when `assetQueryParams` is not configured
- PR #15931 fixed island hydration URLs and hoisted scripts (Cases 1 & 2) but could not reach imports baked inside compiled JS — this PR completes the fix

**Before:**
```js
import{g as t}from"./shared.DuaLvmHQ.js"
```

**After:**
```js
import{g as t}from"./shared.DuaLvmHQ.js?dpl=deploy-abc123"
```

Closes #15964

## Testing

- [x] New test: `appends assetQueryParams to relative imports inside client JS chunks`
- [x] All 5 existing `asset-query-params` tests pass
- [x] Built JS chunks verified to contain `?dpl=` on relative `from"./..."` imports
- [x] Plugin is a no-op when no `assetQueryParams` configured (no regression for non-Vercel builds)

## Docs

No docs changes needed.

### CODE REVIEW

**Comment by matthewp** [comment]
can we use es-module-lexer for this? we already use it in some places like here: https://github.com/withastro/astro/blob/23d60dee6eae3d7148ef87f8b44c3d7470fef0ed/packages/integrations/mdx/src/vite-plugin-mdx-postprocess.ts#L4



Definitely want to make sure we're getting both static and dynamic imports.

**Comment by tmimmanuel** [comment]
> can we use es-module-lexer for this? we already use it in some places like here:
> 
> https://github.com/withastro/astro/blob/23d60dee6eae3d7148ef87f8b44c3d7470fef0ed/packages/integrations/mdx/src/vite-plugin-mdx-postprocess.ts#L4
> 
> Definitely want to make sure we're getting both static and dynamic imports.

@matthewp Thanks for the review! I'll refactor to use `es-module-lexer` instead of regex — makes sense to keep it consistent with the rest of the codebase. Will update the PR shortly.

**Comment by tmimmanuel** [comment]
Hi, @matthewp 
I think current test failures are not from my code change.
Can you review again please? Thanks. 🙏

**Comment by matthewp** [comment]
No it's a flaky test, I'll rerun it.

**Comment by matthewp** [comment]
Fixes https://github.com/withastro/astro/issues/14775

**Comment by tmimmanuel** [comment]
Hi @matthewp 
Thanks for your review. CI tests are passed. Please review again.

**Comment by matthewp** [comment]
@tmimmanuel Code looks good, can you add a changeset? `pnpm run changeset`. This page explains how to write them: https://contribute.docs.astro.build/docs-for-code-changes/changesets/

**Comment by tmimmanuel** [comment]
@matthewp
I added a changeset and CI tests are passed. Please review again. Thanks.

**Comment by tmimmanuel** [comment]
@matthewp
I added a changeset and CI tests are passed. Can you review again please?

File: packages/astro/src/core/build/plugins/plugin-chunk-imports.ts [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+
+		async renderChunk(code, _chunk) {
+			if (!code.includes('./')) {
+				return null;
+			}
+
+			await init;
+			const [imports] = parse(code);
+
+			// Filter to relative JS imports only
```
Comment (matthewp) [inline packages/astro/src/core/build/plugins/plugin-chunk-imports.ts:36]: why filter to only relative imports?

Comment (tmimmanuel) [reply packages/astro/src/core/build/plugins/plugin-chunk-imports.ts:36]: I think Vite only generates relative paths for inter-chunk references in bundled output. But please let me know if there's a case I might be missing.

Comment (matthewp) [reply packages/astro/src/core/build/plugins/plugin-chunk-imports.ts:36]: Ah yeah that's right, ok this is good.

**Comment by tmimmanuel** [comment]
@matthewp Thanks.
