### PR TITLE
fix: avoid full-reload in scss modules

### LINKED ISSUE #14869: SCSS file changes trigger full page reload instead of HMR
### Astro Info

```block
Astro                    v5.14.3
Vite                     v6.3.6
Node                     v22.14.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  @astrojs/node (v9.4.4)
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

When modifying `.scss` files during development, Astro triggers a full page reload instead of hot module replacement (HMR). This disrupts the development workflow as it loses current state and scroll position.

If I write:

```ts
 if (import.meta.hot) {
     import.meta.hot.on('vite:beforeFullReload', (payload) => {
       console.log(payload);
     })
}
```

After save a `.scss` file, this log appears:

```ts
{type: 'full-reload'}
```

### What's the expected result?

Changes to `.scss` files should trigger CSS-only hot updates without a full page reload.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-f9txtpa5?file=src%2Fcomponents%2FExample.module.scss

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by aralroca**
Fixes https://github.com/withastro/astro/issues/14869

## Changes

Fixed an issue where saving SCSS modules (`.module.scss`) triggered a full page reload in Astro dev mode.

Now, hot-reloading updates styles in place without a full reload.

## Tests

I haven't found any tests for this existing plugin to add the test case. Open to feedback.

### CODE REVIEW

**Comment by aralroca** [comment]
I need some reviewer @Princesseuh 🙏

**Comment by Princesseuh** [comment]
Hello! I'll be reviewing and merging this on Monday, apologies for the delay. Busy times!

File: packages/astro/src/vite-plugin-hmr-reload/index.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import type { EnvironmentModuleNode, Plugin } from 'vite';
 
-const STYLE_EXT_REGEX = /\.(css|scss|sass|less|styl|pcss)$/i;
+const STYLE_EXT_REGEX = /\.(?:css|scss|sass|less|styl|pcss)$/i;
```
Comment (aralroca) [inline packages/astro/src/vite-plugin-hmr-reload/index.ts:6]: thanks for the improvement @Princesseuh

Comment (Princesseuh) [reply packages/astro/src/vite-plugin-hmr-reload/index.ts:6]: No worries, I just need to test it some more and we'll be ready to merge!

Comment (Princesseuh) [reply packages/astro/src/vite-plugin-hmr-reload/index.ts]: No worries, I just need to test it some more and we'll be ready to merge!

**Comment by Princesseuh** [comment]
So I tried this locally, and I'm not sure your solution actually works. I added a test for scss modules that at least for me locally, does not seem to pass, we'll see what CI has to say. Running it in dev, it also does full page refreshes on change.

Edit: Yeah, the E2E test for SCSS modules does not pass, this doesn't fix it. Let me know if you're willing to keep working on this to fix it or if we should close this PR

**Comment by aralroca** [comment]
> So I tried this locally, and I'm not sure your solution actually works. I added a test for scss modules that at least for me locally, does not seem to pass, we'll see what CI has to say. Running it in dev, it also does full page refreshes on change.
> 
> Edit: Yeah, the E2E test for SCSS modules does not pass, this doesn't fix it. Let me know if you're willing to keep working on this to fix it or if we should close this PR

I've tested it directly by linking to our project: Astro with Preact and SCSS modules, and it fixes the full reload. Do you mean that there are cases where another full reload from another place is executed? I can help by creating a repo with a minimal reproduction of the bug. Modifying the SCSS file with that avoids the full reload.

**Comment by Princesseuh** [comment]
I tried it in the e2e tests by running it manually and changing the value, it always refreshed the page. You can see the test failure as well, so this isn't just me.

If this is intended to fix another situation than the one on the e2e test (I added both a test for normal scss files and for scss modules, the former works) let me know!

**Comment by Princesseuh** [comment]
Closing due to inactivity, please feel free to re-open if you pick this back up!

**Comment by aralroca** [comment]
Please reopen it @Princesseuh. I will take a look and create the failing test that this PR fixes.

**Comment by aralroca** [comment]
Hey @Princesseuh! I investigated why the SCSS modules test was failing, the issue is that CSS module class name hashes are content-dependent, so when the color changes, the hash changes too. In a pure server-rendered `.astro` page the HTML class names become stale (no client-side re-render to update them), which is why the test never saw the new color.                                                                                                                                                                                        
                                                                                       
The fix itself (returning `[]` from the SSR `hotUpdate` handler to prevent propagation) was correct all along, the test just needed to use a Preact component with `client:load` to match the real-world scenario from #14869. The framework's HMR boundary handles the re-render with the new class names.                                                                                                                                                                                                                                                    
  
 Updated the test and all 6 HMR tests pass consistently now. Could you take another look when you get a chance?  🙏 Thanks!

File: packages/astro/src/vite-plugin-hmr-reload/index.ts [hunk 2]
```diff
@@ -45,6 +63,15 @@ export default function hmrReload(): Plugin {
 					server.ws.send({ type: 'full-reload' });
 					return [];
 				}
+
+				// When style modules were skipped, return an empty array to prevent Vite's
+				// default SSR HMR propagation. Without this, Vite would propagate through the
+				// module graph to .astro importers, find no HMR acceptor, and trigger a
+				// full page reload. The client environment handles CSS HMR natively through
+				// framework-specific HMR boundaries (e.g. Preact, React, Vue components).
```
Comment (matthewp) [inline packages/astro/src/vite-plugin-hmr-reload/index.ts]: what about pages without framework components on them? We don't handle CSS HMR there do we?

Comment (aralroca) [reply packages/astro/src/vite-plugin-hmr-reload/index.ts]: Good catch on the wording! Pages without framework components are already covered — the `scss-external` test page is exactly that case (plain Astro page with `<style>@import</style>`, no framework component at all). Vite's client-side CSS HMR handles style updates natively regardless of whether framework components are present.

The code comment was misleading though — just pushed a fix to clarify that this works for all pages via Vite's built-in style update mechanism, not just through framework HMR boundaries.

Comment (matthewp) [reply packages/astro/src/vite-plugin-hmr-reload/index.ts]: Thanks, can you do a `pnpm install` again and check in the lockfile? Currently causing CI to fail.

**Review by matthewp — APPROVED** [review]

**Review by Princesseuh — APPROVED** [review]
