### PR TITLE
Replace `class:list` implementation with `clsx`

### LINKED ISSUE #7747: class:list broken
### What version of `astro` are you using?

2.6.1 and above

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

yarn

### What operating system are you using?

macOS

### What browser are you using?

all of them

### Describe the Bug

when passing to an Astro component, `class` and `class:list` are passed as regular props instead of the magical class merging feature similar to `clsx`.

### What's the expected result?

`class` and `class:list` should work together as the famous `clsx` utility as advertised on the doc site.

### Link to Minimal Reproducible Example

https://codesandbox.io/p/sandbox/youthful-lamarr-l9l375?file=/package-lock.json:1256,6-1256,24

### Participation

- [X] I am willing to submit a pull request for this issue **if somebody knowledgeable would give some pointers where to start looking**

### LINKED ISSUE #8108: class:list will be sorted
### What version of `astro` are you using?

2.8.5

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm,pnpm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

If there are numbers in the php statement, the class name will be sorted.

image

build:
image

### What's the expected result?

can it be kept as it is

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-sdeict-afdy3k?file=src%2Fpages%2Findex.astro,dist%2Findex.html

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by natemoo-re**
## Changes

- Closes #7747, closes #8108
- Brings back @FredKSchott's proposed changes from #3935
- Replaces custom `class:list` implementation with popular, battle-tested [`clsx`](https://github.com/lukeed/clsx) library

## Testing

Test added to ensure #7747 does not regress

## Docs

Need to add to migration guide and also update `class:list` note.

/cc @withastro/maintainers-docs for changeset feedback!

### CODE REVIEW

File: packages/astro/src/runtime/server/render/component.ts [hunk 1]
```diff
@@ -473,6 +477,18 @@ export async function renderComponent(
 	return await renderFrameworkComponent(result, displayName, Component, props, slots);
 }
 
+function normalizeProps(props: Record<string, any>): Record<string, any> {
+	if ('class:list' in props) {
```
Comment (natemoo-re) [inline packages/astro/src/runtime/server/render/component.ts:481]:
```suggestion
	if (props['class:list'] !== undefined) {
```

Checked the benchmarks, `props['class:list'] !== undefined` is _slightly_ faster than `typeof props['class:list'] !== 'undefined'`

**Review by matthewp — APPROVED** [review]
