### PR TITLE
fix: set correct statusText for custom error pages

### LINKED ISSUE #13259: Custom 404 page returns invalid `404 OK` status in server mode
### Astro Info

```block
Astro                    v5.3.0
Node                     v22.14.0
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using server-side rendering (SSR) with a custom `src/pages/404.astro` page, the server responds with a `404 OK` status code. (Development and production environemnts)

This issue occurs in both development and production environments.

The issue can be resolved by explicitly setting the response status in the 404 page:

```js
Astro.response.status = 404
Astro.response.statusText = 'Not Found'
```

Note: The default 404 page provided by Astro behaves correctly.

### What's the expected result?

The server should respond with a `404 Not Found` status code when serving the custom 404 page.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-28wvkirt?file=src%2Fpages%2F404.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Currently if a user has a custom `404.astro` or `500.astro` we set the correct status code in the response, but not the correct status text, instead leaving the default `OK`. This PR ensures the correct text is set too.

Fixes #13259

## Testing

Added tests

### CODE REVIEW

File: packages/astro/src/runtime/server/render/page.ts [hunk 1]
```diff
@@ -81,14 +81,18 @@ export async function renderPage(
...
+		statusText = 'Not Found';
 	} else if (route?.route === '/500') {
 		status = 500;
-	}
+		statusText = 'Internal Server Error';		
+	} 
+
 	if (status) {
-		return new Response(body, { ...init, headers, status });
+		return new Response(body, { ...init, headers, status, statusText });
```
Comment (florian-lefebvre) [inline packages/astro/src/runtime/server/render/page.ts:95]: What if there's a custom status text? this would override it I think
