### PR TITLE
Fix client:visible for duplicate component instances

### LINKED ISSUE #1963: 📘 DOC: Theme Toggle doesn't work
The Theme Toggle switch (light/dark) on docs.astro.build doesn't seem to do anything. I clicked the sun and moon emoji and nothing happens.

I tried both latest Firefox and Chrome.

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #1963. Our `client:visible` intersection observer would observe all our components, but when it came to multiple instances of the same component would only listen for the first instance. This caused a problem in our docs when we have 2 components on the page and the first is hidden, but the second isn’t. The first would get evaluated, IntersectionObserver would correctly determine it wasn’t in view, then it would exit rather than see if another instance of that component was visible.

## Testing

Tested manually in dev & build. Testable here:

👀 https://deploy-preview-1999--astro-docs-2.netlify.app/getting-started/

## Docs

No docs needed

### CODE REVIEW

File: docs/src/components/RightSidebar/ThemeToggleButton.tsx [hunk 1]
```diff
@@ -30,10 +30,10 @@ const icons = [
   </svg>,
 ];
 
-const ThemeToggle: FunctionalComponent = () => {
+function ThemeToggle() {
   const [theme, setTheme] = useState(() => {
     if (import.meta.env.SSR) {
-      return undefined;
+      return 'light';
```
Comment (drwpow) [inline docs/src/components/RightSidebar/ThemeToggleButton.tsx:36]: Returning `undefined` just loaded the page without either selected. Seemed like weird behavior.

File: packages/astro/src/runtime/client/visible.ts [hunk 2]
```diff
@@ -16,11 +16,13 @@ export default async function onVisible(astroId: string, _options: HydrateOption
     }
   };
 
-  const io = new IntersectionObserver(([entry]) => {
-    if (!entry.isIntersecting) return;
-    // As soon as we hydrate, disconnect this IntersectionObserver for every `astro-root`
-    io.disconnect();
-    cb();
+  const io = new IntersectionObserver((entries) => {
```
Comment (drwpow) [inline packages/astro/src/runtime/client/visible.ts:19]: Turns out if you only listen if the first element is visible, it listens!

Comment (drwpow) [reply packages/astro/src/runtime/client/visible.ts:19]: Is there any reason we were only listening for the first match before?

File: docs/src/components/RightSidebar/ThemeToggleButton.tsx [hunk 3]
```diff
@@ -30,10 +30,10 @@ const icons = [
   </svg>,
 ];
 
-const ThemeToggle: FunctionalComponent = () => {
+function ThemeToggle() {
```
Comment (drwpow) [inline docs/src/components/RightSidebar/ThemeToggleButton.tsx:33]: These other changes here were to address TypeScript errors / lint warnings.

**Review by jonathantneal — APPROVED** [review]

File: docs/src/components/RightSidebar/ThemeToggleButton.tsx (hunk 1 above)
Comment (natemoo-re) [reply docs/src/components/RightSidebar/ThemeToggleButton.tsx:36]: I think this is correct behavior, it's meant to respect your system preference by default.

File: packages/astro/src/runtime/client/visible.ts (hunk 2 above)
Comment (natemoo-re) [reply packages/astro/src/runtime/client/visible.ts:19]: Oh! I uh... kinda forgot that this could multiple entries could ever be returned. Makes sense!

File: docs/src/components/RightSidebar/ThemeToggleButton.tsx (hunk 1 above)
Comment (drwpow) [reply docs/src/components/RightSidebar/ThemeToggleButton.tsx:36]: Oh. Hm. How would the system preference highlight the icon below? We have that `window.matchMedia` check below which should handle that?

Comment (drwpow) [reply docs/src/components/RightSidebar/ThemeToggleButton.tsx:36]: I’ll revert, then. Maybe neither icon being highlighted is OK until it’s hydrated

Comment (natemoo-re) [reply docs/src/components/RightSidebar/ThemeToggleButton.tsx]: We used to have an icon for system preference. It got removed along the way. It should exist in some form, but can be a follow-up.

File: packages/astro/src/runtime/client/visible.ts (hunk 2 above)
Comment (drwpow) [reply packages/astro/src/runtime/client/visible.ts:19]: I mean, that works for most scenarios! This is such an edge case. You had to have 2 instances of a component on-page, and the _first_ had to be hidden. Funny our docs had this

File: docs/src/components/RightSidebar/ThemeToggleButton.tsx (hunk 1 above)
Comment (drwpow) [reply docs/src/components/RightSidebar/ThemeToggleButton.tsx]: WFM. I’ll leave this as-is then and we can address later.
