### PR TITLE
fix: strip query string before checking md extension

### LINKED ISSUE #12711: BUG: Search parameters with an .md extension break astro
### Astro Info

```block
Astro                    v5.0.4
Node                     v21.1.0
System                   Linux (x64)
Package Manager          bun
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When a page has a search parameter with a value that has a '.md' suffix, astro breaks:

image

This doesn't happen with other file extensions (as far as I've tested), only with '.md' files.

To reproduce locally, go clone this repo:
https://github.com/alarbada/astro-bug

install dependencies and go to 'http://localhost:4321/my/page?page=hello.md'. It will fail.

### What's the expected result?

Astro showing the corresponding page.

### Link to Minimal Reproducible Example

https://github.com/alarbada/astro-bug

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Currently the markdown vite plugin just checks if the id ends in a makrdown extension. This breaks if the id includes a query param. This PR strips the query string before checking.

Fixes #12711

## Testing

Added test

### CODE REVIEW

**Review by ematipico — APPROVED** [review]
Looks good!

File: packages/astro/src/core/util.ts [hunk 1]
```diff
@@ -18,9 +18,11 @@ export function isURL(value: unknown): value is URL {
 }
 /** Check if a file is a markdown file based on its extension */
 export function isMarkdownFile(fileId: string, option?: { suffix?: string }): boolean {
+	// Strip query string
+	const id = fileId.split("?")[0];
```
Comment (Princesseuh) [inline packages/astro/src/core/util.ts:22]: Don't we have a stripQueryParams util somewhere?

Comment (ascorbic) [reply packages/astro/src/core/util.ts:22]: I couldn't find one. There's `getFileInfo` which does return an id with the params stripped - and which the markdown plugin calls immediately after, but it does lots of other stuff which is probably overkill for something that will be called on every module. Better to have something extra simple when it's in the kinda-hot path.

Comment (ematipico) [reply packages/astro/src/core/util.ts:22]: We do! :) `removeQueryString`

Comment (ascorbic) [reply packages/astro/src/core/util.ts:22]: Oh!
