### PR TITLE
Log error if failed to fetch remote image

### LINKED ISSUE #5392: I can't catch an error in the `loadRemoteImage` function when the fetch function occurs error
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

none

### What package manager are you using?

pnpm

### What operating system are you using?

mac

### Describe the Bug

I can't catch an error in the `loadRemoteImage` function when the fetch function occurs error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-lmp1qc?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by wulinsheng123**
## Changes

I can't catch an error in the loadRemoteImage function when the fetch function occurs error

fix #5392

### CODE REVIEW

File: packages/integrations/image/src/endpoint.ts [hunk 1]
```diff
@@ -14,7 +14,8 @@ async function loadRemoteImage(src: URL) {
 		}
 
 		return Buffer.from(await res.arrayBuffer());
-	} catch {
+	} catch (err: unknown) {
+		console.error(err)
```
Comment (bluwy) [inline packages/integrations/image/src/endpoint.ts:18]: We don't report the full error, but it's currently being handled at 

https://github.com/withastro/astro/blob/eab4a0279fd28163cea9da2b010c5ccde5645e6f/packages/integrations/image/src/endpoint.ts#L35-L37

too. Are you seeing any errors that need this specific log?

Comment (bluwy) [reply packages/integrations/image/src/endpoint.ts:18]: https://github.com/withastro/astro/issues/5392#issuecomment-1313425804

Comment (bluwy) [inline packages/integrations/image/src/endpoint.ts:18]: I think we should do the same at https://github.com/withastro/astro/blob/eab4a0279fd28163cea9da2b010c5ccde5645e6f/packages/integrations/image/src/build/ssg.ts#L55

**Review by bluwy — APPROVED** [review]
