### PR TITLE
fix: Installs underneath a path containing leading underscores

### LINKED ISSUE #7406: `CollectionDoesNotExistError` on fresh install of "Astro Starter Kit: Blog"
### What version of `astro` are you using?

2.6.4

### Are you using an SSR adapter? If so, which one?

No

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

Chrome

### Describe the Bug

I installed the "Starter Kit: Blog" from https://github.com/withastro/astro/tree/main/examples/blog

When I run `npm run dev`, the dev server starts and I can visit the site on `localhost:3000`. The home (`/`) and `/about/` pages work as expected, but on the `/blog/` page, I am getting a `CollectionDoesNotExistError`:

image

Any idea what's happening here? I haven't changed anything, just `npm create astro@latest -- --template blog` and said "yes" to all questions. The weird thing is that the [demo on stackblitz](https://stackblitz.com/github/withastro/astro/tree/latest/examples/blog?file=README.md) works just fine...

### Link to Minimal Reproducible Example

https://github.com/hirasso/astro-starter-kit-blog

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by hirasso**
Fixes #7406 

Makes it possible to run astro underneath a path that contains leading underscores, like e.g. `/_my/path/to/site/`.

## Changes

- Make the glob patterns in the `astroContentVirtualModPlugin` relative to the content directory

## Testing

I really don't know how I should test this using a written test. Tested it manually instead.

Still, out of curiosity I ran `pnpm run test`. There were a few tests that were failing for me, regardless of the proposed change from this PR.

## Docs

This is a bugfix, no docs needed I guess

### CODE REVIEW

File: packages/astro/src/content/vite-plugin-content-virtual-mod.ts [hunk 1]
```diff
@@ -209,5 +210,6 @@ const UnexpectedLookupMapError = new AstroError({
 
 function globWithUnderscoresIgnored(relContentDir: string, exts: string[]): string[] {
 	const extGlob = getExtGlob(exts);
-	return [`${relContentDir}/**/*${extGlob}`, `!**/_*/**${extGlob}`, `!**/_*${extGlob}`];
+	const contentDir = appendForwardSlash(relContentDir.trim());
```
Comment (bluwy) [inline packages/astro/src/content/vite-plugin-content-virtual-mod.ts:213]: Do we need the `trim()` here?

**Review by bluwy — COMMENTED** [review]
Thanks for fixing this! The test should work fine, but maybe you're seeing flaky tests locally. I'm fine with not having tests for this for now though since it relies on an underscore outside the project filesystem.

File: packages/astro/src/content/vite-plugin-content-virtual-mod.ts (hunk 1 above)
Comment (hirasso) [reply packages/astro/src/content/vite-plugin-content-virtual-mod.ts:213]: I don't know :) Just added as a late sanitization, in case `relContentDir` will ever contain leading or trailing slashes.

Should I remove it?

Comment (bluwy) [reply packages/astro/src/content/vite-plugin-content-virtual-mod.ts:213]: Yeah I don't think it's needed here, we can trust the path that's coming in.

Comment (hirasso) [reply packages/astro/src/content/vite-plugin-content-virtual-mod.ts]: Removed it

**Review by bluwy — APPROVED** [review]
Awesome
