### PR TITLE
fix(cloudflare): workers types

### LINKED ISSUE #15363: Wrong request type required by the astro handler when using a custom Cloudflare worker entrypoint
### Astro Info

```block
Astro                    v6.0.0-beta.6
Node                     v22.13.1
System                   macOS (arm64)
Package Manager          bun
Output                   server
Adapter                  @astrojs/cloudflare (^13.0.0-beta.3)
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

I'm using a custom entry-point to render either custom 
or astro handler by following the specs here: https://v6.docs.astro.build/en/guides/integrations-guide/cloudflare/#changed-custom-entrypoint-api

```ts
import handler from "@astrojs/cloudflare/entrypoints/server";


// -- Export default Worker
export default {
  async fetch(
    request: Request,
    env: Env,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const url = new URL(request.url);

    // -- Proxy API calls to bknd
    if (url.pathname.startsWith("/api")) {
      // return custom
    }

    // -- Return Astro handler
    return handler.fetch(request, env, ctx); // <--- request is not having the right expected type
  },
} satisfies ExportedHandler<Env>;
```

lint error:

Image

```
Argument of type 'Request<unknown, CfProperties<unknown>>' is not assignable to parameter of type 'Request<unknown, IncomingRequestCfProperties<unknown>>'.
  Type 'CfProperties<unknown>' is not assignable to type 'IncomingRequestCfProperties<unknown>'.
    Type 'RequestInitCfProperties' is not assignable to type 'IncomingRequestCfProperties<unknown>'.
      Type 'RequestInitCfProperties' is missing the following properties from type 'IncomingRequestCfPropertiesBase': colo, edgeRequestKeepAliveStatus, httpProtocol, requestPriority, and 2 more.
```

### What's the expected result?

Use the same Cloudflare request type for the @astrojs/cloudflare handler request

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-461d5lmx?file=src%2Fworker.ts

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #15363
- I tried a few things and it turns out because we have references to `@cloudflare/workers-types` when building etc, we can avoid doing weird things with types
- It also allowed removing the `Request` type augmentation we were doing as part of `astro sync`, because `wrangler types` already handles it

## Testing

Manually in repro, manually in the custom-entryfile fixture, preview release tested with user's repro

## Docs

Changeset

### CODE REVIEW

File: packages/integrations/cloudflare/src/utils/handler.ts [hunk 1]
```diff
@@ -38,14 +40,12 @@ export async function handle(
...
 	if (app.isDev()) {
-		const result = await app.devMatch(
-			app.getPathnameFromRequest(request as Request & Parameters<ExportedHandlerFetchHandler>[0]),
-		);
+		const result = await app.devMatch(app.getPathnameFromRequest(request));
 		if (result) {
 			routeData = result.routeData;
 		}
 	} else {
-		routeData = app.match(request as Request & Parameters<ExportedHandlerFetchHandler>[0]);
```
Comment (matthewp) [inline packages/integrations/cloudflare/src/utils/handler.ts:48]: 🙌
