### PR TITLE
fix(dev): dont reroute endpoint responses

### LINKED ISSUE #9829: Custom error pages are not served in production
### Astro Info

```block
Astro                    v4.2.4
Node                     v20.10.0
System                   macOS (arm64)
Package Manager          unknown
Output                   hybrid
Adapter                  @astrojs/node
Integrations             astro-i18next
                         @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Given an endpoint returning `return new Response(null, { status: 404 })`,
I've noticed different behaviours when serving the site with `astro dev` or `astro preview`.

astro dev: custom 404 page is shown
astro preview: blank page is shown

It also works as expected, when a 404 Response is returned in the code-fence of Astro page, but not in an endpoint.

### What's the expected result?

If in production the endpoint returns a response with 404 status and the custom 404 page is present, it should show up

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-s7uxf1?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes
- fix #9829 

## Testing
Added a case to dev-routing.test.js

## Docs
Does not affect behavior

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro-server/route.ts [hunk 1]
```diff
@@ -342,7 +343,7 @@ export async function handleRoute({
 			})
 		);
 	}
-	if (response.status === 404 && has404Route(manifestData)) {
+	if (response.status === 404 && has404Route(manifestData) && response.headers.get(REROUTE_DIRECTIVE_HEADER) !== "no") {
```
Comment (lilnasy) [inline packages/astro/src/vite-plugin-astro-server/route.ts:346]: The fix is here, the rest is clerical.

File: packages/astro/src/runtime/server/consts.ts [hunk 2]
```diff
@@ -0,0 +1 @@
+export const REROUTE_DIRECTIVE_HEADER = 'X-Astro-Reroute';
```
Comment (natemoo-re) [inline packages/astro/src/runtime/server/consts.ts:1]: I like this!

**Review by natemoo-re — APPROVED** [review]
LGTM! Thanks for the fix.

**Review by ematipico — APPROVED** [review]
