### PR TITLE
Fix .html.astro file routing in dev

### LINKED ISSUE #5068: Routing with catch-all in folder name
### What version of `astro` are you using?

1.4.7

### Are you using an SSR adapter? If so, which one?

@matthewp/astro-fastify

### What package manager are you using?

yarn

### What operating system are you using?

Linux / Gitpod

### Describe the Bug

I'm trying to create routes with a catch-all in the path not in file : 
```
|- pages
   |- index.astro
   |- [...breadcrumbs]
      |- [collectionSlug].astro
      |- [productSlug].html.astro
```

Note the `.html` at the end of the second file. I used that to distinguish my category page and my product page.
With this setup, the suffix is ignored and all request goes to `[collectionSlug].astro`
This works without catch-all in folder name.
The goal is to have a SEO friendly url with collection breadcrumbs (`/my/parent/category` => category, `/my/parent/category/my-product.html` => product)
And if I change the suffix with `.dhtml` by example this works 🤨 
Any idea ?

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-prkeiw

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Fix #5068

Differentiate between `[id].astro` and `[id].html.astro` files when routing, similar to other extensions (`.html` was specially handled before).

## Testing

Added new tests

## Docs

N/A. Bug fix.

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro-server/route.ts [hunk 1]
```diff
@@ -57,12 +65,18 @@ export async function matchRoute(
...
 				route: maybeRoute,
 				filePath,
+				resolvedPathname: pathname,
 				preloadedComponent,
 				mod,
 			};
 		}
 	}
 
+	const altPathname = pathname.replace(/(index)?\.html$/, '');
```
Comment (matthewp) [inline packages/astro/src/vite-plugin-astro-server/route.ts:75]: can you add some comments around this? I think I understand why this is being done but probably won't remember a month from now!

Comment (bluwy) [reply packages/astro/src/vite-plugin-astro-server/route.ts:78]: Added comments in [d2785c3](https://github.com/withastro/astro/pull/5346/commits/d2785c3fb8d469f9958d5fdb9b44ee53e223d4d8)

**Review by natemoo-re — APPROVED** [review]
Makes sense, nice fix!

**Review by matthewp — APPROVED** [review]
