### PR TITLE
fix(language-server): rewrite Astro component auto-import names

### LINKED ISSUE #14683: Bug: experimental assets: `Import declaration conflicts with local declaration of 'Image'.`
### What version of `astro` are you using?

2.6.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### What browser are you using?

VSCode

### Describe the Bug

Please download the project from stackblitz and use VSCode (I am on Mac, personally).  The error does not appear in stackblitz.  However, if you download the project, install dependencies locally, and open the demo `image.astro` file, you will find the following type error:

> Import declaration conflicts with local declaration of 'Image'.

This error occurs even when the [Astro VSCode extension](https://marketplace.visualstudio.com/items?itemName=astro-build.astro-vscode) is the only extension installed.

image

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-at6m8s-t6usix?file=src%2Fpages%2Fimage.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by felmonon**
## Summary
- keep generated `AstroComponent` suffixes in the internal TSX output used by the language server
- rewrite `.astro` auto-import completion labels and resolved import edits back to the expected component name
- add regression coverage for the `.astro` auto-import completion path and the shared import-text rewrite helpers

Fixes #14683.

## Testing
- pnpm -C packages/language-tools/language-server build
- pnpm -C packages/language-tools/ts-plugin build
- pnpm -C packages/language-tools/language-server exec astro-scripts test "test/{typescript/completions.test.ts,typescript/diagnostics.test.ts,units/utils.test.ts}" --teardown-test ./test/misc/teardown.ts --tsx true --setup ./test/setup.js
- pnpm -C packages/language-tools/language-server test *(fails locally in existing `AstroCheck` fixture tests because `@astrojs/svelte` and `@astrojs/vue` are not installed in this environment; the TypeScript/completion suites above pass)*

### CODE REVIEW

**Review by Princesseuh — DISMISSED** [review]
This is not the proper way to do it, because changing the component name will cause auto import to return something unexpected. Instead, we should always return the AstroComponent suffixes, but patch auto-import to not add it. You can use the Vue language-tools as reference, IIRC they still do it.

**Comment by felmonon** [comment]
Implemented the rework you asked for.

This keeps the generated `AstroComponent` suffixes in the internal TSX output and rewrites the language-server `.astro` auto-import completion labels plus resolved import edits back to the expected component name instead.

I also dropped the ts-plugin-side rename and updated the language-server coverage around the completion path.

**Comment by felmonon** [comment]
Quick nudge on this when you have a chance. I reworked it to keep the internal `AstroComponent` suffixes and patch the `.astro` auto-import labels/import edits instead, per the review direction, and CI is green now. Happy to adjust further if needed.

**Comment by Princesseuh** [comment]
I just tried it in local, looks great, but I noticed this issue:

image

It seems like TypeScript does not see the import anymore and recommends the auto-import, despite it already being imported. Not sure what causes this!

**Comment by felmonon** [comment]
Tracked this down to the completion filtering rather than the TSX rename itself.

When the file already had `import Image from '../components/Image.astro'`, we were still surfacing the same `../components/Image.astro` auto-import candidate after stripping the `AstroComponent` suffix, which made it look like TS was ignoring the existing import. I pushed a follow-up that suppresses same-source `.astro` auto-import suggestions once that component is already imported, and added a regression for that case.

Validation:
- `./node_modules/.bin/astro-scripts test "test/{typescript/completions.test.ts,units/utils.test.ts}" --teardown-test ./test/misc/teardown.ts --tsx true --setup ./test/setup.js`

File: packages/language-tools/language-server/src/core/utils.ts [hunk 1]
```diff
@@ -73,15 +73,18 @@ export function classNameFromFilename(filename: string): string {
...
 		// If we don't have a match here, it usually means the file has a weird name that couldn't be expressed with valid identifier characters
 		if (!m1) {
-			if (basename === '404') return 'FourOhFour';
+			if (basename === '404') return 'FourOhFourAstroComponent';
 			return fullMatch;
 		}
-		return isDynamic ? `_${m1}_` : m1[0].toUpperCase() + m1.slice(1);
+
+		const componentName = isDynamic ? `_${m1}_` : m1[0].toUpperCase() + m1.slice(1);
+		return `${componentName}AstroComponent`;
```
Comment (Princesseuh) [inline packages/language-tools/language-server/src/core/utils.ts:88]: Since the base output already has a suffix in the form of __AstroComponent_ is it worth it to still have this suffix here?

Comment (felmonon) [reply packages/language-tools/language-server/src/core/utils.ts:88]: I think it is still useful to keep a suffix here, because the internal TSX symbol still needs to stay distinct from the user-facing component/import name to avoid recreating the original collision. The normalization to `AstroComponent` is also what the new completion/import rewrite path is keyed on right now, so keeping the raw `__AstroComponent_` form would mean changing those helpers too, not just this one line.

If you would rather keep the raw compiler suffix and make the rewrite logic handle that directly, I can do that too. My intent here was to keep an internal suffix while still presenting plain `Image` in the `.astro` auto-import UX.

**Review by Princesseuh — APPROVED** [review]
Thank you for fixing this! Apologies for the delay on approvals, busy times.
