### PR TITLE
Fix: React - Use "createRoot" instead of "hydrateRoot" for `client:only`

### LINKED ISSUE #3010: 🐛 BUG: React component hydration error when loaded with `client:only`
### What version of `astro` are you using?

1.0.0-beta.2

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

`@astrojs/react`: `0.1.0`

React components loaded with `client:only` show a hydration error:

Screen Shot 2022-04-06 at 3 06 20 PM

The component still works, it just makes React unhappy. `client:only` skips the component at build time, so there's nothing to hydrate. React components rendered with`client:only` should probably use `createRoot` instead of `hydrateRoot`:

https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/integrations/react/client.js#L6

Though in looking at the code, there is a `suppressHydrationWarning` flag - is that related?: https://github.com/withastro/astro/blob/1335797903a57716e9a02b0ffd8ca636b3883c62/packages/integrations/react/client.js#L10

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2hpcon

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes
- Resolves #3010
- Update Astro core to surface `client` directive to client renderers
- Update React `client.js` to use `createRoot` on `client:only` instead of suppressing hydration warnings (spoiler: they aren't suppressed!)
- Update React `client-17.js` to use `render` on `client:only` instead of suppressing hydration warnings

## Testing

N/A, check your console 😉 

## Docs

N/A

### CODE REVIEW

**Comment by bholmesdev** [comment]
...I've received word we fundamentally _can't_ use `render` instead of `hydrate` due to problems with children. Sadly closing this PR for a different fix 😢 
cc @natemoo-re

**Review by matthewp — APPROVED** [review]
lgtm

**Comment by bholmesdev** [comment]
Welp, turns out  we _can_ use this from personal testing! Nested component islands and children are just as stable using `createRoot` over `hydrateRoot` for `client:only` specifically. Deferring to @natemoo-re in case there's nuance I'm missing here.

File: packages/integrations/react/client-v17.js [hunk 1]
```diff
@@ -1,15 +1,18 @@
...
+			props,
 			children != null
-				? createElement(StaticHtml, { value: children, suppressHydrationWarning: true })
+				? createElement(StaticHtml, { value: children })
 				: children
-		),
-		element
-	);
+		);
+		if (client === 'only') {
```
Comment (natemoo-re) [inline packages/integrations/react/client-v17.js:14]: Is `client` undefined?

**Review by natemoo-re — COMMENTED** [review]
LGTM! Few comments about future-proofing the last argument.

**Review by natemoo-re — APPROVED** [review]
Good to merge!

File: packages/integrations/react/client-v17.js (hunk 1 above)
Comment (bholmesdev) [reply packages/integrations/react/client-v17.js:14]: Forgot to pass the param 🤦 Fixed!
