### PR TITLE
fix: error overlay message escape

### LINKED ISSUE #12191: Dev server error page: HTML in code comments gets rendered in error message (no escaping of <)
### Astro Info

```block
Astro                    v4.16.0
Node                     v18.20.3
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             @astrojs/vue
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

It's a minor issue that only happens in development, so not a big deal.

This code in my editor with a syntax error:
image

Led to this dev stacktrace:
image

I made a StackBlitz, if you edit the code on the left you can see the input element blinking into existence on the page, and the window.alert() code seems to be run on the server (as it shows a hint about browser APIs?) which doesn't sound great because that code is in a comment in the original file.

https://stackblitz.com/edit/github-ncvven?file=src%2Fcomponents%2FCounter.vue

GIF of what I see on my screen:
344970260-0c0be2fa-6468-4315-ab8d-793ea11bc886

I initially made the report above some time ago, today I also recreated the same issue in an updated StackBlitz: https://stackblitz.com/edit/withastro-astro-qrcwoa?file=src%2Fcomponents%2FCounter.vue

This latest one has the latest versions of Astro and Vue, and its `astro info` is reported above.

### What's the expected result?

Code in comments should not be rendered or executed.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-qrcwoa?file=src%2Fcomponents%2FCounter.vue

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #12191

## Testing

Manual

## Docs

N/A

### CODE REVIEW

File: packages/astro/src/core/errors/overlay.ts [hunk 1]
```diff
@@ -608,7 +608,10 @@ class ErrorOverlay extends HTMLElement {
 
 		this.text('#name', err.name);
 		this.text('#title', err.title);
-		this.text('#message-content', err.message, true);
+    // Only set as html if escaped. We're only sure it's escaped if name is part
+    // of the error, ie. we transformed it as we wanted.
+    // TODO: capture error at the source and transform it there
```
Comment (florian-lefebvre) [inline packages/astro/src/core/errors/overlay.ts:613]: @Princesseuh I tried many things but couldn't find from where the error on initial render is  coming. Basically the flow is as follow:
1. you have failing code: escaped
2. you update your failing code but it's still failing, you save
3. on initial render, it's not escaped (the error has not been enhanced by us yet, where does  it come from??)
4. after 200ms, enhanced error is used (escaped)

**Review by ematipico — APPROVED** [review]

**Comment by Princesseuh** [comment]
I pushed an alternative fix, I'm not 100% sure of what I'm doing. It seems like on HMR upgrade, if any of the Vite processing thingy fails, Vite emits an error through the websocket that doesn't go through any of our usual error stuff. My method patches the .send method directly, but perhaps there's another way to do this properly? cc @bluwy

I'll note that Vite lose a lot of information from errors when doing this, so trying to enhance might not even be relevant in the first place as we can't achieve much.
