### PR TITLE
fix(create-astro): @astrojs/check and typescript addition

### LINKED ISSUE #9791: `create astro` does not add additional dependencies in certain cases
### Astro Info

```block
Astro                    v4.2.3
Node                     v18.19.0
System                   Windows (x64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             astro-env
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When running `pnpm create astro@latest` and choosing the following options:
- TS: Yes
- Strictness: Strict
- Install deps: No

`@astrojs/check` and `typescript` are not added as `devDependencies`.

### What's the expected result?

Well, just add them to the `package.json`: https://github.com/withastro/astro/blob/main/packages%2Fcreate-astro%2Fsrc%2Factions%2Ftypescript.ts#L93-L97

### Link to Minimal Reproducible Example

N/A

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #9791
- Fixes `@astrojs/check` and `typescript` addition to `package.json` dependencies when the user has decided not to auto-install dependencies

Not sure if it solves https://github.com/withastro/astro/issues/9791#issuecomment-1906722419 though

## Testing

Not tested

## Docs

N/A

### CODE REVIEW

File: packages/create-astro/src/actions/typescript.ts [hunk 1]
```diff
@@ -107,8 +114,19 @@ const FILES_TO_UPDATE = {
...
 			}
+
+			if (!options.ctx.install || !installSucceeded) {
+				const [astroCheckVersion, typescriptVersion] = await Promise.all([
+					getVersion(options.ctx.packageManager, '@astrojs/check'),
+					getVersion(options.ctx.packageManager, 'typescript'),
+				]);
+				parsedPackageJson.dependencies ??= {}
+				parsedPackageJson.dependencies['@astrojs/check'] = astroCheckVersion;
+				parsedPackageJson.dependencies.typescript = typescriptVersion;
```
Comment (natemoo-re) [inline packages/create-astro/src/actions/typescript.ts:126]: We probably want to use a `^` instead of pinning an exact version
```suggestion
				parsedPackageJson.dependencies['@astrojs/check'] = `^${astroCheckVersion}`;
				parsedPackageJson.dependencies.typescript = `^${typescriptVersion}`;
```

File: packages/create-astro/src/actions/typescript.ts [hunk 2]
```diff
@@ -90,11 +90,18 @@ const FILES_TO_UPDATE = {
...
+				const { exitCode } = await shell(
+					options.ctx.packageManager,
+					['add', '@astrojs/check', 'typescript'],
+					{
+						cwd: path.dirname(file),
+						stdio: 'ignore',
+					}
+				);
+				installSucceeded = exitCode === 0;
+			}
```
Comment (natemoo-re) [inline packages/create-astro/src/actions/typescript.ts:104]: This entire block can probably be removed! We shouldn't run installation code in this step. If we add the packages to the dependencies, they may/may not be installed by the `install` step anyway.

**Review by natemoo-re — COMMENTED** [review]
Thanks for working on this! Looks good, just a few suggestions.

File: packages/create-astro/src/actions/typescript.ts (hunk 1 above)
Comment (florian-lefebvre) [reply packages/create-astro/src/actions/typescript.ts:126]: I was not sure about the format of `getVersion` return 👍

**Review by natemoo-re — APPROVED** [review]
Great updates, thank you for the PR!

**Comment by jacobdalamb** [comment]
@natemoo-re does this pr solve solve my [comment](https://github.com/withastro/astro/issues/9791#issuecomment-1906722419)? If not I will open a new issue.

**Comment by natemoo-re** [comment]
> @natemoo-re does this pr solve solve my [comment](https://github.com/withastro/astro/issues/9791#issuecomment-1906722419)? If not I will open a new issue.

@jacobdalamb thanks for double checking! Yes, this PR does also fix the behavior with the `-y` or `-n` flags.
