### PR TITLE
fix: stream Fragment sync siblings before async children resolve

### LINKED ISSUE #13283: Async Children of Fragments block earlier sibling elements from being streamed
### Astro Info

```block
N/A — see the minimum reproducible example
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When streaming a response, if there are any promises inside of a fragment, then none of the elements in that fragment are rendered until after the promise resolves.

```astro
<Fragment>
	<p>
		I should show up before the promise resolves, but I don’t!
	</p>
	{promise.then(() => (<p>I show up after the promise resolves</p>))}
</Fragment>
```

Parent elements don’t normally wait for all their children, if instead of a fragment, we use a div then the first element renders right away.

```astro
<div>
	<p>
		I should show up before the promise resolves, and I do!
	</p>
	{promise.then(() => (<p>I show up after the promise resolves</p>))}
</div>
```

### What's the expected result?

Children of fragments should not wait for sibling elements that return promises to be resolved before being streamed in the response.

```astro
<!-- This here -->
<Fragment>
	<p>
		I should show up before the promise resolves, but I don’t!
	</p>
	{promise.then(() => (<p>I show up after the promise resolves</p>))}
</Fragment>

<!-- And this here should work the same -->
<p>
	I should show up before the promise resolves, but I don’t!
</p>
{promise.then(() => (<p>I show up after the promise resolves</p>))}
```

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vqmrwtqv?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by dataCenter430**
## Changes

- `renderFragmentComponent` was calling `renderSlotToString`, which eagerly  awaited the entire slot content into a string before returning a `RenderInstance`.  This caused sync siblings inside a `<Fragment>` to block until all async children  resolved, unlike `<div>` and bare template expressions which streamed immediately.
- Fix: replace `renderSlotToString` with `renderSlot`, so Fragment children go  through the same `renderChild` -> buffered async pipeline every other element uses.
- Fixes #13283 

## Testing

- Added unit test in `test/units/render/html-primitives.test.js` verifying sync  content flushes to the destination before a deferred Promise resolves.
- Added integration tests in `test/streaming.test.js` using a fixture page that  mirrors the issue's exact reproduction — asserts sync content arrives in an  earlier stream chunk than the async child.
- All 99 existing + new tests pass.

## Docs

No docs change needed

### CODE REVIEW

**Comment by dataCenter430** [comment]
Hi, @matthewp 
Would you plesae review the PR when you have a chance?
Please share your feedback for this.
Thank you.

File: packages/astro/src/runtime/server/render/component.ts [hunk 1]
```diff
@@ -483,7 +483,7 @@ export function renderComponent(
 	}
 
 	if (isFragmentComponent(Component)) {
-		return renderFragmentComponent(result, slots).catch(handleCancellation);
+		return renderFragmentComponent(result, slots);
```
Comment (ematipico) [inline packages/astro/src/runtime/server/render/component.ts:486]: Why was this changed?

File: packages/astro/test/streaming.test.js [hunk 2]
```diff
@@ -90,6 +90,71 @@ describe('Streaming', () => {
...
+	before(async () => {
+		fixture = await loadFixture({
+			root: './fixtures/streaming/',
+			adapter: testAdapter(),
+			output: 'server',
+		});
+		await fixture.build();
+	});
+
+	it('sync sibling inside Fragment streams before async child resolves', async () => {
```
Comment (ematipico) [inline packages/astro/test/streaming.test.js:107]: Both `it` are testing the same thing (text of two fragments and order). Can't we use only one?

File: packages/astro/src/runtime/server/render/component.ts (hunk 1 above)
Comment (dataCenter430) [reply packages/astro/src/runtime/server/render/component.ts:486]: thanks for your review. Good query!
The old `renderFragmentComponent` was `async,` returning `Promise<RenderInstance>.` `.catch(handleCancellation)` silenced errors when `result.cancelled` (client disconnected). 
After the fix the function is synchronous - it returns `RenderInstance` directly - so there is no Promise and `.catch` cannot be attached. This is correct and consistent: `isAstroComponentFactory` also returns without `.catch`.

File: packages/astro/test/streaming.test.js (hunk 2 above)
Comment (dataCenter430) [reply packages/astro/test/streaming.test.js:107]: The second test was redundant. The first already checks:
- both IDs are present in output (`syncChunkIndex !== -1`, `asyncChunkIndex !== -1`)
- sync arrives in an earlier chunk than async (strictly stronger than checking position in the joined string)

The second test checked the same things on the joined string. :) It's been removed. 
Thanks.

File: .changeset/rhrc-kpon-ngct.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fix sync siblings inside `<Fragment>` being blocked from streaming when async children are present. Previously, `renderFragmentComponent` called `renderSlotToString` which eagerly awaited the entire slot into a string, preventing earlier sync content from flushing to the stream. It now uses `renderSlot` so Fragment children go through the same buffered async pipeline as all other elements.
```
Comment (ematipico) [inline .changeset/rhrc-kpon-ngct.md]: Please reword the changeset. Changesets are meant for end users, not us developers. Here's some tips on how to write them: https://contribute.docs.astro.build/docs-for-code-changes/changesets/#tips-and-examples

Comment (dataCenter430) [reply .changeset/rhrc-kpon-ngct.md]: Now it's clear and concise as you wanted.
thanks again.
