### PR TITLE
fix: remove legacy content collections

### LINKED ISSUE #14361: Remove content layer backward compat
That includes:

- Removing `legacy.contentCollections`
- Removing the auto backward compat for sites without content config
- Remove **any** backward compat

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Closes #14361.

This PR removes a number of APIs and options related to legacy content collections that were deprecated in Astro 5, including:

- The `legacy.collections` option, which was added in Astro 5 and caused the old content collections system to be used instead of the new one.
- Deprecated functions from `astro:content`: `getEntryBySlug` and `getDataEntryById` are both replaced by `getEntry()`, which is a drop-in replacement for both.
- Support for the old `src/content/config.*` file location. You must now use `src/content.config.*`.
- Automatically generating collections when a `src/content/` directory is present and no content config file exists. You must now explicitly define collections in `src/content.config.*`.
- Support for collections without a loader. You must now use the `glob()` loader to create collections from filesystem content. This will also mean that generated entries use the new entry format:
  - The `id` field is now a slug, not a filename. You can access the filename via `entry.filePath`, which is the path relative to the site root.
  - There is no longer a `slug` field – use `id` instead.
  - You can no longer call `entry.render()` on content entries. Use `render(entry)` instead, imported from `astro:content`.

## Testing
Literally hundreds of updated tests! We never updated lots of the fixtures in Astro 5, instead relying on the legacy support. This PR takes the plunge and does the update.

A lot of tests are failing in `next`, so it's not always 100% clear if there are more that need updating. I think I've found them all though.

## Docs

The docs already reflect the current behaviour. The upgrade guide is in progress.

### CODE REVIEW

File: packages/astro/src/content/config.ts [hunk 1]
```diff
@@ -182,23 +182,28 @@ export function defineCollection<S extends BaseSchema>(
...
-			typeof config.loader === 'object' &&
-			typeof config.loader.load !== 'function' &&
-			('loadEntry' in config.loader || 'loadCollection' in config.loader)
-		) {
-			throw new AstroUserError(
-				`Live content collections must be defined in "src/live.config.ts" file. Check your collection definitions in "${importerFilename ?? 'your content config file'}" to ensure you are not using a live loader.`,
-			);
-		}
-		config.type = CONTENT_LAYER_TYPE;
+	// TODO: add links to the migration guide in these errors
```
Comment (florian-lefebvre) [inline packages/astro/src/content/config.ts]: FYI there's still this todo here
