### PR TITLE
fix: cache raw cookie value and decode when getting

### LINKED ISSUE #13078: Cookies from header not parsed by AstroCookies
### Astro Info

```block
Astro                    v5.1.10
Node                     v20.17.0
System                   Linux (x64)
Package Manager          unknown
Output                   server
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When inside of a middleware calling `context.cookies.get('test', { decode })` the decode function is not invoked and the cookie value is still encoded.

The cookie is set within the request header. In the linked minimal reproducible example the page must be reloaded to set the cookie.

### What's the expected result?

I would expect that `context.cookies.get` will parse and decode cookie values from request header.

### Link to Minimal Reproducible Example

https://stackblitz.com/~/github.com/tstern-bolindalabs/just-the-basics

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

Currently, when a cookie is first parsed from the header the value is cached. This means that if subsequent requests pass a different decode function it will be ignored. This PR changes the behaviour to cache the raw cookie values, and then decode them when getting them. This means the passed decode function will always be used.

Fixes #13078

### CODE REVIEW

File: packages/astro/src/core/cookies/cookies.ts [hunk 1]
```diff
@@ -117,11 +119,13 @@ class AstroCookies implements AstroCookiesInterface {
 			}
 		}
 
-		const values = this.#ensureParsed(options);
+		const decode = options?.decode ?? decodeURIComponent
```
Comment (ematipico) [inline packages/astro/src/core/cookies/cookies.ts:122]: I don't understand this part. Why do we use `decodeURIComponent`? The previous code didn't use it, and the PR doesn't mention it. What am I missing?

**Review by ematipico — COMMENTED** [review]
Can we add a test to avoid possible future regressions?

File: packages/astro/src/core/cookies/cookies.ts (hunk 1 above)
Comment (ascorbic) [reply packages/astro/src/core/cookies/cookies.ts:122]: It's the default in the `cookie` library if you don't pass in anything. That's why we pass an identity function to `parse`

Comment (ascorbic) [reply packages/astro/src/core/cookies/cookies.ts:122]: I've added a comment

**Review by ematipico — APPROVED** [review]
Thank you!
