### PR TITLE
fix(render): avoid script dedup state consumption in inert template c…

### LINKED ISSUE #16525: Bug: SSR script/runtime dedup flags are committed before executable-context confirmation
### Astro Info

```block
<paste output of `astro info` here>


## If this issue only occurs in one browser, which browser is a problem?

N/A (server/runtime emission logic)
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

There appears to be a shared bug pattern in Astro SSR script/runtime dedup logic: global "already rendered" flags are committed before confirming the script/runtime is being emitted into executable DOM context.

From current `main` source inspection, these paths still look context-blind at the point state is flipped:

- `determineIfNeedsHydrationScript()` in `packages/astro/src/runtime/server/scripts.ts`
- `determinesIfNeedsDirectiveScript()` in `packages/astro/src/runtime/server/scripts.ts`
- `rendererSpecificHydrationScripts` dedup path in `packages/astro/src/runtime/server/render/common.ts`
- `hasRenderedServerIslandRuntime` in `packages/astro/src/runtime/server/render/common.ts`

Because dedup is toggled globally at first encounter, a first hit inside an inert/non-executable context can prevent required script/runtime output in a later executable placement.

### What's the expected result?

Dedup state should only be committed once Astro confirms the script/runtime is emitted into an executable DOM context (or dedup should be scoped per effective render context), so later valid placements are not incorrectly skipped.

In other words:

- encountering a hydration/directive/island runtime path in an inert location should not consume the global "already rendered" state
- a subsequent executable location should still emit the required script/runtime exactly once

## Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9p8z3w1k?file=README.md

_(Replace with your real minimal repro before filing. If useful, I can draft a concrete repro layout for this issue.)_

## Participation

- [ ] I am willing to submit a pull request for this issue.

### Link to Minimal Reproducible Example

safdasdf

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by enjoyandlove**
Closes #16525
## Changes
- Fix SSR script/runtime dedup state being committed before emission context is known.
- Delay dedup state updates until the script/runtime is actually emitted into an executable DOM context.
- Prevent first encounters in inert/non-executable contexts from incorrectly suppressing later valid emissions.
- Apply the same context-aware behavior across hydration, directive, renderer-specific hydration scripts, and server island runtime paths.
- Add focused regression coverage for inert-first then executable-later render order to ensure required runtime scripts emit exactly once.
- Add a changeset for `astro` describing the SSR runtime emission correctness fix.

## Testing

- Added regression tests that reproduce inert-context-first rendering and verify later executable contexts still emit required scripts/runtimes.
- Verified scripts/runtimes are emitted exactly once in executable contexts (no duplicate output).
- Ran targeted package tests for `packages/astro` relevant to SSR/runtime emission paths.
- Ran lint/format checks for touched files.

## Docs

- No docs changes needed.
- This is an internal SSR/runtime emission correctness fix and does not introduce new user-facing APIs or configuration.

### CODE REVIEW

**Comment by enjoyandlove** [comment]
Hi @ematipico ,
I’ve completed the requested fixes. At your convenience, could you please review the updated PRs?
Thank you for your time and consideration.

**Comment by matthewp** [comment]
These tests are too low-level and I can't tell what they actually fix. You should be able to create some tests like in units/app/ that create components that replicate the problem.

**Review by matthewp — CHANGES_REQUESTED** [review]
Please add component-level tests so its more clear the circumstances that this fixes.

**Comment by enjoyandlove** [comment]
Hi @matthewp,
I’ve addressed the requested changes. When you have a moment, could you please review the PR again?
Thank you for your time and consideration.

File: packages/astro/src/runtime/server/render/common.ts [hunk 1]
```diff
@@ -61,6 +61,20 @@ function stringifyChunk(
 		switch (instruction.type) {
 			case 'directive': {
 				const { hydration } = instruction;
+				// Script tags inside <template> are inert and won't execute, so
+				// encountering hydration instructions here must not consume global
+				// dedup state needed by executable contexts later in the document.
+				if (result._metadata.templateDepth > 0) {
```
Comment (matthewp) [inline packages/astro/src/runtime/server/render/common.ts]: Why not put this logic inside of `determineIfNeedsHydrationScript` and `determinesIfNeedsDirectiveScript` this new block of code isn't needed?

**Comment by enjoyandlove** [comment]
Hi, @matthewp! 
Thank you for your guidance. I have submitted the pull request assigned to me.
Please let me know if you have any additional suggestions or ideas for improvement.
Best regards,

**Comment by matthewp** [comment]
Also fixes #13801

**Review by matthewp — APPROVED** [review]
