### PR TITLE
Narrow the type of Params

### LINKED ISSUE #5442: Astro.params.foo is typed as string|number|undefined, but it can only be string|undefined, which forces extra TypeScript typing
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

node

### What package manager are you using?

npm

### What operating system are you using?

Linux (WSL)

### Describe the Bug

https://github.com/withastro/astro/blob/4b188132ef68f8d9951cec86418ef50bb4df4a96/packages/astro/src/%40types/astro.ts#L1149 says that `Astro.params` can contain numbers, which https://docs.astro.build/en/reference/api-reference/#params says doesn't actually happen. This forces TypeScript programs to either handle a `number` type that never actually happens or to cast it away.

I believe #3087 introduced this in order to loosen typing in `getStaticPaths()`, which produces `Params` instances, but it broke consumption of the types. You probably need two different types for inbound vs outbound.

Run `astro check` in https://stackblitz.com/edit/github-fht7tc?file=src/pages/products/[name].astro to see the error.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fht7tc?file=src/pages/products/[name].astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Pimm**
Fixes #5442.

/cc @tony-sull & @bholmesdev

## Changes

[#3087 changed the type of `Params`](//github.com/withastro/astro/pull/3087) from `Record<string, string | undefined>` to `Record<string, string | number | undefined>` to formerly allow `getStaticPaths` to return numbers.

However, as the change was made to `Params` and not `GetStaticPathsResult` or `GetStaticPathsItem`, it also affects `Astro.params`.

This PR essentially moves the change made in #3087 from `Params` to `GetStaticPathsItem`, reverting the type of `Astro.params` while keeping the type of `getStaticPaths`.

**Note** that while looking into this, I [found this comment](https://github.com/withastro/astro/issues/4309#issuecomment-1239779706) by @bholmesdev:

> * if you pass a number to `params.year` in your `getStaticPaths`, it should _still_ be a number when destructuring `Astro.params`. If not, that's a bug.
> * if you created an **SSR dynamic route** like `[year].astro`, `year` will _always_ be a `string` (even if it could be parsed to a number). This is where string -> number conversion would be manual.

In my experience, `Astro.params` never contains numbers, not even in static mode. While reviewing, please consider that this PR changes the types to match the behaviour, although judging by this comment, we might want to change the behaviour to match the types instead.

## Testing

This is testable like so:
```typescript
const artist: string | undefined = Astro.params.artist;
```
I haven't found any type definition tests to which this one could be added.

## Docs

From what I understand, this change is [in line with the current docs](https://docs.astro.build/en/reference/api-reference/#params):

> `params` are encoded into the URL, so only strings are supported as values.

### CODE REVIEW

File: packages/astro/src/core/routing/params.ts [hunk 1]
```diff
@@ -27,12 +27,12 @@ export function getParams(array: string[]) {
...
  * that can be used to match request routes
  */
-export function stringifyParams(params: Params, routeComponent: string) {
+export function stringifyParams(params: GetStaticPathsItem['params'], routeComponent: string) {
 	// validate parameter values then stringify each value
 	const validatedParams = Object.entries(params).reduce((acc, next) => {
 		validateGetStaticPathsParameter(next, routeComponent);
 		const [key, value] = next;
-		acc[key] = typeof value === 'undefined' ? undefined : `${value}`;
+		acc[key] = value?.toString();
```
Comment (Pimm) [inline packages/astro/src/core/routing/params.ts:35]: This is more concise and works for `undefined`, numbers, and strings, but does require support for the `?.` operator. Since this support was added in Node.js 14.0.0, this should be OK.

**Review by bluwy — APPROVED** [review]

**Review by bholmesdev — APPROVED** [review]
I `par`am very impressed! Great change 👍

**Comment by sarah11918** [comment]
While our API reference page does in fact say that `params` must be strings, we have this in our new Error reference guide:

Screenshot 2022-11-28 18 10 11
https://docs.astro.build/en/reference/error-reference/#invalid-value-for-getstaticpaths-route-parameter

So, no objections from docs if we're now all rallying behind Team String, but our error reference will have to change to match. (cc @Princesseuh @matthewp  )

**Comment by Pimm** [comment]
Thanks @sarah11918.

The error reference looks correct to me as-is. `getStaticPaths` may still return numbers (although those numbers will reincarnate as strings in `Astro.params`).
