### PR TITLE
[Markdoc] `headings` and heading IDs

### LINKED ISSUE #6855: Getting headings from a markdoc file using the render() method returns an empty object.
### What version of `astro` are you using?

2.3.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### What browser are you using?

Edge

### Describe the Bug

When I try to get the headings from a markdoc file using the `render()` method, it returns an empty object.

```ts
import { getEntryBySlug } from 'astro:content';

const entry = await getEntryBySlug('blog', 'post-1');
const { Content, headings } = await entry.render();

console.log(headings) // []
console.log(typeof headings) // object
```

`post-1` at `src/content/blog/post-1.mdoc` contains a few different level of headings and they rendered as expected by `Content`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vwtxh9

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #6855 
- Generate heading IDs for all Markdoc headings
- Populate the `headings` array from the `render()` function
  - Create a new `@astrojs/markdoc/runtime` export that exposes a `collectHeadings` utility
  - Add a `getHeadings()` function to all `.mdoc` modules. This approach will call transform **twice** (once for the Content component, once for `getHeadings()`). This is due to a fundamental limitation of allowing Markdoc variables as component props. A TODO for a future exploration is noted in the source code.
- Expose a `defaultNodes` object to use when modifying `nodes` from the Markdoc config

## Testing

- Test heading IDs and TOC
- Test rendering component Astro components

## Docs

Update Node headings example in the README. In the future, we may need to document each node case-by-case!

### CODE REVIEW

File: packages/integrations/markdoc/src/nodes/heading.ts [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import Markdoc, { type Schema } from '@markdoc/markdoc';
+import { getTextContent } from '../runtime.js';
+
+// Or replace this with your own function
+function generateId(attributes: Record<string, any>, textContent: string): string {
+	if (attributes.id && typeof attributes.id === 'string') {
+		return attributes.id;
+	}
+	return textContent.replace(/[?]/g, '').replace(/\s+/g, '-').toLowerCase();
+}
```
Comment (bluwy) [inline packages/integrations/markdoc/src/nodes/heading.ts:10]: For the default slug logic, should we use `github-slugger` so it's consistent with the `rehype-slug`? ([implementation](https://github.com/rehypejs/rehype-slug/blob/1c61632f1526c6b59c80530ed334d4a094c7a091/index.js#L33))

File: packages/integrations/markdoc/src/index.ts [hunk 2]
```diff
@@ -88,36 +88,44 @@ export default function markdocIntegration(legacyConfig?: any): AstroIntegration
...
+		? `import _userConfig from ${JSON.stringify(
+				markdocConfigResult.fileUrl.pathname
+		  )};\nconst userConfig = _userConfig ?? {};`
+		: 'const userConfig = {};'
+}${
+							astroConfig.experimental.assets
+								? `\nimport { experimentalAssetsConfig } from '@astrojs/markdoc/experimental-assets-config';\nuserConfig.nodes = { ...experimentalAssetsConfig.nodes, ...userConfig.nodes };`
+								: ''
+						}
+const stringifiedAst = ${JSON.stringify(JSON.stringify(ast))};
```
Comment (bluwy) [inline packages/integrations/markdoc/src/index.ts:106]: It would be nice to preserve the double stringify comment here

File: packages/integrations/markdoc/package.json [hunk 3]
```diff
@@ -21,7 +21,7 @@
   "exports": {
     ".": "./dist/index.js",
     "./components": "./components/index.ts",
-    "./default-config": "./dist/default-config.js",
+    "./runtime": "./dist/runtime.js",
```
Comment (ematipico) [inline packages/integrations/markdoc/package.json:24]: Isn't this a breaking change? Genuine question

File: packages/integrations/markdoc/src/runtime.ts [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+export function collectHeadings(children: RenderableTreeNode[]): MarkdownHeading[] {
+	let collectedHeadings: MarkdownHeading[] = [];
+	for (const node of children) {
+		if (typeof node !== 'object' || !Markdoc.Tag.isTag(node)) continue;
+
+		if (node.attributes.__collectHeading === true && typeof node.attributes.level === 'number') {
+			collectedHeadings.push({
+				slug: node.attributes.id,
+				depth: node.attributes.level,
+				text: getTextContent(node.children),
```
Comment (ematipico) [inline packages/integrations/markdoc/src/runtime.ts:59]: `getTextContent(node.children)` is called twice on the same `node.children`, conditionally. Is there a way to call it **once** instead?

File: packages/integrations/markdoc/src/runtime.ts [hunk 5]
```diff
@@ -0,0 +1,76 @@
...
+		for (const level of headingLevels) {
+			if (node.name === 'h' + level) {
+				collectedHeadings.push({
+					slug: node.attributes.id,
+					depth: level,
+					text: getTextContent(node.children),
+				});
+			}
+		}
+		collectedHeadings.concat(collectHeadings(node.children));
```
Comment (ematipico) [inline packages/integrations/markdoc/src/runtime.ts:73]: Do we care about the order of how we find the headings? If we don't, I believe we can avoid recursion by using a simple queue

```js
const queue = [...node.children];

while (queue.length > 0) {
	const node = queue.shift();
	// do stuff
	// now process children
	queue.push(...node.children);
}

```

Comment (bholmesdev) [reply packages/integrations/markdoc/src/runtime.ts:75]: Hm, we _do_ want all headings to be in-order by how they appear in the document. I'm a bit confused how we could avoid recursion with a queue here?

File: packages/integrations/markdoc/src/runtime.ts (hunk 4 above)
Comment (bholmesdev) [reply packages/integrations/markdoc/src/runtime.ts:61]: With the `continue` statement, this can only be called once though right?

File: packages/integrations/markdoc/package.json (hunk 3 above)
Comment (bholmesdev) [reply packages/integrations/markdoc/package.json:24]: Probably safer to make this a breaking minor! Neither of these exports are documented, so the change is internal. Though users could have been package splunking

File: packages/integrations/markdoc/src/runtime.ts [hunk 6]
```diff
@@ -0,0 +1,76 @@
...
+/**
+ * Get text content as a string from a Markdoc transform AST
+ */
+export function getTextContent(childNodes: RenderableTreeNode[]): string {
+	let text = '';
+	for (const node of childNodes) {
+		if (typeof node === 'string' || typeof node === 'number') {
+			text += node;
+		} else if (typeof node === 'object' && Markdoc.Tag.isTag(node)) {
+			text += getTextContent(node.children);
```
[the remark this answers is not in the document]
Comment (bholmesdev) [reply packages/integrations/markdoc/src/runtime.ts:40]: Expecting a "transform markdoc trees to linear lists" PR 😉

File: .changeset/pretty-students-try.md [hunk 7]
```diff
@@ -0,0 +1,6 @@
+---
+'@astrojs/markdoc': patch
```
Comment (bholmesdev) [inline .changeset/pretty-students-try.md:2]:
```suggestion
'@astrojs/markdoc': minor
```

File: packages/integrations/markdoc/src/runtime.ts (hunk 4 above)
Comment (ematipico) [reply packages/integrations/markdoc/src/runtime.ts:61]: Oh, I missed that! :)

**Review by ematipico — APPROVED** [review]
Let's ship it! 🚢

**Review by bluwy — APPROVED** [review]

**Comment by sarah11918** [comment]
Just a quick heads up @bholmesdev  that I literally saw this merge as I was looking at the README!  Reminder for next time!  :heart:

**Review by sarah11918 — COMMENTED** [review]
Late to the party (whomp, whomp) but README docs are great!  :tada:

**Comment by bholmesdev** [comment]
@sarah11918 CRAP I 100% forgot to tag you on this 😓 Assumed we'd reviewed it with all the docs PRs flying around. If you want to leave comments here for me to address in a fast follow, happy to do so

**Comment by sarah11918** [comment]
Sorry @bholmesdev - I was prioritizing the specific "merge on release" docs I'd been given (and, didn't know Markdoc was something to be released for 2.5) so I assumed this was a "regular" PR, and was just clearning out all the Astro Docs Maintainer pings now. Docs are great though! No worries!
