### PR TITLE
Fix public files taking priority over API routes in build

### LINKED ISSUE #15165: APIRoute vs public files follow different precedence in dev and build
### Astro Info

```block
Astro                    v5.16.6
Vite                     v6.4.1
Node                     v22.18.0
System                   Windows (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/sitemap (v3.6.0)
```

### If this issue only occurs in one browser, which browser is a problem?

all

### Describe the Bug

If filename of a file in `public/` dir is same as filename produced by `APIRoute` in root,

## Example
`public/robots.txt` exists
`src/pages/robots.txt.ts` exists

Difference in behaviour:
1. `astro dev`: public route takes precedence
2. `astro build`: pages route takes precedence

Normal behaviour if no conflicting routes (i.e., only one of those files exists)

### What's the expected result?

Not documented as per my knowledge: https://docs.astro.build/en/guides/routing/#route-priority-order

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-rfjccbca

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Fixes an issue where API routes would overwrite public files during build
- Public files now correctly take priority over generated routes in both dev and build modes
- Added `checkPublicConflict()` function in `generate.ts` that skips writing generated routes when a public file with the same name exists

Fixes #15165

## Testing

- Added tests for both dev and build modes in `astro-public.test.js`
- Added test fixtures: `public/robots.txt` and `src/pages/robots.txt.ts`

## Docs

No docs needed - this fixes a bug to match existing documented behavior.

### CODE REVIEW

**Review by delucis — APPROVED** [review]
Approving conceptually! Makes sense to me that public files should win in this case.

File: packages/astro/src/core/build/generate.ts [hunk 1]
```diff
@@ -634,3 +640,29 @@ function getPrettyRouteName(route: RouteData): string {
...
+	logger: Logger,
+): boolean {
+	const outFilePath = fileURLToPath(outFile);
+	const outRoot = fileURLToPath(
+		settings.buildOutput === 'static' ? settings.config.outDir : settings.config.build.client,
+	);
+	const relativePath = outFilePath.slice(outRoot.length);
+	const publicFilePath = new URL(relativePath, settings.config.publicDir);
+	if (fs.existsSync(publicFilePath)) {
+		logger.warn(
```
Comment (Princesseuh) [inline packages/astro/src/core/build/generate.ts:661]: I'm not sure if this should be a warning or an error, but happy either way personally.
