### PR TITLE
fix(rendering): allow framework renders to be cancelled

### LINKED ISSUE #10367: Server crashes due to multiple runtime errors in Astro component (Astro + React)
### Astro Info

```block
Astro                    v4.4.15
Node                     v18.19.0
System                   macOS (x64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/node
Integrations             @astrojs/react
```

### If this issue only occurs in one browser, which browser is a problem?

All browsers

### Describe the Bug

When rendering an Astro component (`index.astro`), if there is an error in a React component preceded by another runtime error, it will result in a server crash.

Example:
```
---
// index.astro
import ReactComp from '../components/react-comp';

const foo = { bar: null } as unknown as { bar: { baz: string[] } };
---

<!-- React component has to error first -->
<ReactComp foo={foo} />
{ foo.bar.baz.length > 0 && (
  <div />
)}
```

### Steps to reproduce
1. Run `npm run build`
2. Run `npm run preview`
3. Go to localhost
4. Go to `/` page, server crashes.

### What's the expected result?

Should not crash the server no matter how the error happen.

### Link to Minimal Reproducible Example

https://github.com/frendyguo/astro-react-runtime-error-crash

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by lilnasy**
## Changes

- Fixes #10367 in a runtime-agnostic way, but only for ~70% of the similar cases.
- `renderTemplate()` did not complete - an error was thrown before we could get references to the expressions.
- Luckily, `renderComponent()` allowed us to get a reference the promise that would reject, and we could handle it.

## Testing
- Adapter the repro case into `node --test test/streaming.test.js`.

## Docs
- Does not affect usage.

### CODE REVIEW

File: packages/astro/src/runtime/server/render/component.ts [hunk 1]
```diff
@@ -478,7 +478,11 @@ export async function renderComponent(
 		return renderAstroComponent(result, displayName, Component, props, slots);
 	}
 
-	return await renderFrameworkComponent(result, displayName, Component, props, slots);
+	return await renderFrameworkComponent(result, displayName, Component, props, slots)
+		.catch(e => {
+			if (result.cancelled) return { render() {} };
+			throw e;
+		});
```
Comment (lilnasy) [inline packages/astro/src/runtime/server/render/component.ts:485]: The fix is here, the rest is clerical.

File: packages/astro/test/streaming.test.js [hunk 2]
```diff
@@ -2,11 +2,9 @@ import assert from 'node:assert/strict';
 import { after, before, describe, it } from 'node:test';
 import * as cheerio from 'cheerio';
 import testAdapter from './test-adapter.js';
-import { isWindows, loadFixture, streamAsyncIterator } from './test-utils.js';
+import { loadFixture, streamAsyncIterator } from './test-utils.js';
 
 describe('Streaming', () => {
-	if (isWindows) return;
-
```
Comment (lilnasy) [inline packages/astro/test/streaming.test.js:9]: Theses tests do not need to be skipped.

Comment (lilnasy) [inline packages/astro/test/streaming.test.js:9]: Theses tests do not need to be skipped.

File: packages/astro/test/streaming.test.js [hunk 3]
```diff
@@ -2,11 +2,9 @@ import assert from 'node:assert/strict';
 import { after, before, describe, it } from 'node:test';
 import * as cheerio from 'cheerio';
 import testAdapter from './test-adapter.js';
-import { isWindows, loadFixture, streamAsyncIterator } from './test-utils.js';
+import { loadFixture, streamAsyncIterator } from './test-utils.js';
 
 describe('Streaming', () => {
-	if (isWindows) return;
```
Comment (lilnasy) [inline packages/astro/test/streaming.test.js:8]: The test suite passes on windows. Was there another reason these were skipped?

File: packages/astro/src/runtime/server/render/component.ts (hunk 1 above)
Comment (bluwy) [reply packages/astro/src/runtime/server/render/component.ts:485]: Should we handle this catch for the entire code in `renderComponent` instead? Other components may error asynchronously too.

One of the caveats I figured with this technique is that we now have to ensure every async render APIs used in the template needs this special handling, but perhaps it's not too bad, we don't have many async APIs.

Comment (lilnasy) [reply packages/astro/src/runtime/server/render/component.ts:485]: > Should we handle this catch for the entire code in renderComponent instead?

Yeah, that's a good idea.

> One of the caveats I figured with this technique is that we now have to ensure every async render APIs used in the template needs this special handling

That isn't sufficient either - there could be offshoot promises created by the user or a library. The blanket fix would be handling unhandled rejections similar to the dev mode. The problem there is listening for them doesn't seem to have a standard way across runtimes - it will be per adapter. I'll open a PR for node tomorrow.

Comment (bluwy) [reply packages/astro/src/runtime/server/render/component.ts:485]: Yeah that's true. I think for those cases, we should recommend not passing in promises instead. I think it's rare for someone to do that, so I'm not too concerned if it happens.

I'm not too sure yet if adapters should be injecting the unhandledrejections by default though. It can happen anywhere in the code (e.g. third-party libraries), so it should be up to users to handle it themselves.

Comment (lilnasy) [reply packages/astro/src/runtime/server/render/component.ts:485]: That's true, and we should prevent crashes in those situation - nothing more.

File: packages/astro/test/streaming.test.js (hunk 3 above)
Comment (ematipico) [reply packages/astro/test/streaming.test.js:8]: No idea, to be honest. But if it passes, happy days!

File: packages/astro/src/core/render-context.ts [hunk 4]
```diff
@@ -89,34 +89,38 @@ export class RenderContext {
...
 
-		const lastNext =
-			type === 'endpoint'
-				? () => renderEndpoint(componentInstance as any, apiContext, serverLike, logger)
-				: type === 'redirect'
-					? () => renderRedirect(this)
-					: type === 'page'
-						? async () => {
+		const lastNext = async () => {
+			if (routeData.type === 'endpoint') return renderEndpoint(componentInstance as any, apiContext, serverLike, logger);
```
Comment (ematipico) [inline packages/astro/src/core/render-context.ts:93]: We should use a `switch (routeData.type)` here. If we add a new variant to `type`, TS and ESlint will be both errors and prevent the build.

**Review by ematipico — APPROVED** [review]

File: packages/astro/src/runtime/server/render/component.ts (hunk 1 above)
Comment (lilnasy) [reply packages/astro/src/runtime/server/render/component.ts]: > Should we handle this catch for the entire code in renderComponent instead?

Added cancellation handling for all async work in `renderComponent()`.

File: packages/astro/src/runtime/server/render/component.ts [hunk 5]
```diff
@@ -459,26 +459,35 @@ export async function renderComponent(
...
 	}
 
-	return await renderFrameworkComponent(result, displayName, Component, props, slots);
+	return await renderFrameworkComponent(result, displayName, Component, props, slots)
+		.catch(handleCancellation);
+
+	function handleCancellation(e: unknown) {
+		if (result.cancelled) return { render() {} };
+		throw e;
+	}
```
Comment (bluwy) [inline packages/astro/src/runtime/server/render/component.ts:490]: I was thinking we can wrap this entire function body with a `try..catch`, but this also works for me.

**Review by bluwy — APPROVED** [review]
