### PR TITLE
fix: `passthroughImageService` generate webp

### LINKED ISSUE #14721: passthroughImageService() does not prevent WebP conversion for Image component in Astro 5.15.2
### Astro Info

```block
Astro                    v5.15.2
Vite                     v6.4.1
Node                     v24.8.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/preact (v4.1.2)
                         @astrojs/sitemap (v3.6.0)
```

### If this issue only occurs in one browser, which browser is a problem?

N/A - This is a build-time issue

### Describe the Bug

When using `passthroughImageService()` in astro.config.ts, images imported and used with the `Image` component from `astro:assets` are still being converted to WebP format during build, despite the expectation that all image optimization should be disabled.

### Configuration in astro.config.ts:

```typescript
import { defineConfig, passthroughImageService } from "astro/config";

export default defineConfig({
  image: {
    service: passthroughImageService(),
  },
  // ... other config
});
```

### Component usage:

```astro
---
import { Image } from "astro:assets";
import image1 from "./image1.jpg";
---

<Image src={image1} alt="Hero Image" />
```

### Actual behavior:

After running `pnpm build`, the output in `dist/_astro/` contains:

- WebP files: `image1.MoQXd5Vo_1yvslA.webp`
- Original JPG files: `image1.MoQXd5Vo_1yvslA.jpg` (also generated)

However, the generated HTML uses the WebP version:

```html
<img src="/_astro/image1.MoQXd5Vo_1yvslA.webp" alt="Hero Image" ... />
```

Build logs show "generating optimized images" step with 481 WebP files being created:

```
generating optimized images
19:12:19   ▶ /_astro/banner.Diz8Q35Q_CxSSV.webp (before: 109kB, after: 109kB) (+4ms) (1/481)
19:12:19   ▶ /_astro/_about-fair1.8fWoa9p1_dtbvN.webp (before: 298kB, after: 298kB) (+4ms) (2/481)
...
19:12:20 ✓ Completed in 330ms.
```

Even with `passthroughImageService()` configured, the image optimization step still runs and converts all images to WebP.

## What's the expected result?

When `passthroughImageService()` is configured, the `Image` component should output images in their original format without any conversion or optimization. The build should:

1. **Not create WebP versions** of the images
2. **Use the original image format** (JPG, PNG, etc.) in the generated HTML
3. **Skip the "generating optimized images" step** entirely, or at minimum not perform format conversion

According to the Astro documentation, `passthroughImageService` is intended to bypass all image optimization, including format conversion. The expected HTML output should be:

```html
<img src="/_astro/image1.MoQXd5Vo_1yvslA.jpg" alt="Hero Image" ... />
```

The build logs should not show any "generating optimized images" step, or if it does, it should show that images are being passed through without modification:

```
generating optimized images
19:12:19   ▶ /_astro/image1.jpg (passthrough, no optimization) (+1ms) (1/481)
```

### Link to Minimal Reproducible Example

Note: Creating a minimal reproduction on StackBlitz is challenging for this issue as it's a build-time problem that requires inspecting the `dist/` directory output, which is difficult to verify in browser-based development environments.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ktym4a**
## Changes

Close #14721 

- Fixed an issue which `passthroughImageService` was generating images in `WebP` format.
- Change to not call `validateOptions` when `ESMImportedImage`

## Testing

- Added fixture and test code

## Docs

- I don't think we need to add, but Behavior is changed.

### CODE REVIEW

File: packages/astro/src/assets/services/noop.ts [hunk 1]
```diff
@@ -1,9 +1,19 @@
...
 	propertiesToHash: ['src'],
+	validateOptions(options, imageConfig) {
+		if (isESMImportedImage(options.src)) {
+			return {
+				src: options.src,
+				format: options.src.format,
+			};
+		}
+		return baseService.validateOptions?.(options, imageConfig) ?? options;
+	},
```
Comment (ktym4a) [inline packages/astro/src/assets/services/noop.ts]: I'm not sure if we should just override format then pass to `validateOptions` something like this.

```ts
if (isESMImportedImage(options.src)) {
    options.format = options.src.format;
}
return baseService.validateOptions?.(options, imageConfig) ?? options;
```

Comment (Princesseuh) [reply packages/astro/src/assets/services/noop.ts]: I don't 100% remember this code, but would this work?
```suggestion
	validateOptions(options, imageConfig) {
		const newOptions = baseService.validateOptions?.(options, imageConfig) ?? options;
		delete newOptions.format;
		
		return newOptions;
	},
```

Comment (ktym4a) [reply packages/astro/src/assets/services/noop.ts]: @Princesseuh 
thanks!
it works, so I changed to https://github.com/withastro/astro/pull/14776/commits/39c2469e9517e4afdfd00f33dae06c6068b08b60

**Comment by Princesseuh** [comment]
Test failure looks unrelated, awesome work

**Review by Princesseuh — APPROVED** [review]
