### PR TITLE
fix: remove value and writable properties from headers descriptor

### LINKED ISSUE #12548: Build fails with `Invalid property descriptor` when using Cloudflare adapter with modified `Request` headers prototype
### Astro Info

```block
Astro                    v4.16.16
Node                     v20.18.0
System                   Linux (x64)
Package Manager          pnpm
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using the Cloudflare adapter in an Astro project, importing certain plugins (such as `better-auth/plugins`) results in an unexpected modification of the `Request` prototype.

Specifically, the `Request.headers` object is extended with a `map` property. This modification causes a build error during prerendering (`astro build` with `export const prerender = true`), resulting in the following error message:

```bash
Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
```

The error is thrown in the [`/core/request`](https://github.com/withastro/astro/blob/main/packages/astro/src/core/request.ts) file,  when attempting to redefine the `headers` property of the `Request` object.

```ts
const request = new Request(url, {
	method: method,
	headers: headersObj,
	// body is made available only if the request is for a page that will be on-demand rendered
	body: staticLike ? null : body,
});

if (staticLike) {
	// Warn when accessing headers in SSG mode
	const _headers = request.headers;
	const headersDesc = Object.getOwnPropertyDescriptor(request, 'headers') || {};
	Object.defineProperty(request, 'headers', {
		...headersDesc,
		get() {
			logger.warn(
				null,
				`\`Astro.request.headers\` is unavailable in "static" output mode, and in prerendered pages within "hybrid" and "server" output modes. If you need access to request headers, make sure that \`output\` is configured as either \`"server"\` or \`output: "hybrid"\` in your config file, and that the page accessing the headers is rendered on-demand.`,
			);
			return _headers;
		},
	});
} else if (clientAddress) {
	// clientAddress is stored to be read by RenderContext, only if the request is for a page that will be on-demand rendered
	Reflect.set(request, clientAddressSymbol, clientAddress);
}
```

The issue arises because the `headers` property already has a value, and the build logic tries to add a getter to it in order to show a warning when accessing the headers. This combination of both having a value and adding a getter causes the `Invalid property descriptor` error, resulting in the build failing.

For additional details, please refer to the related issue I created in the `better-auth` repository: [better-auth issue #681](https://github.com/better-auth/better-auth/issues/681).

### What's the expected result?

The build completes without errors.

### Link to Minimal Reproducible Example

https://github.com/avanderbergh/better-auth-astro-issue

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by avanderbergh**
Fixes #12548 

- Ensure that any existing value and writable properties are deleted from the headers descriptor before adding getters and setters.
- This prevents the error: `Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>`

## Changes

- Removed the `value` and `writable` properties from the `headers` descriptor before defining getters and setters for the `headers` property on the `Request` object.
- Updated the `Object.defineProperty` call to prevent the `Invalid property descriptor` error during prerendering.
- Added a setter to `request.headers` to allow updating `_headers` if needed.
  
## Testing

This change was tested by building the Astro project with `prerender = true` and confirming that the build completes without the `Invalid property descriptor` error.

No automated tests have been added since this affects the internal build handling of the `Request` headers property, but manual testing confirms the fix.

## Docs

No documentation changes are needed for this fix, as this is an internal implementation detail that does not affect user-facing API or behavior directly.

/cc @withastro/maintainers-docs for feedback if required.

### CODE REVIEW

File: packages/astro/src/core/request.ts [hunk 1]
```diff
@@ -76,8 +76,13 @@ export function createRequest({
 
 	if (staticLike) {
 		// Warn when accessing headers in SSG mode
-		const _headers = request.headers;
+		let _headers = request.headers;
 		const headersDesc = Object.getOwnPropertyDescriptor(request, 'headers') || {};
+
+		// We need to delete any existing descriptor's value and writable properties because we're adding getters and setters.
+		delete headersDesc.value;
+		delete headersDesc.writable;
```
Comment (bluwy) [inline packages/astro/src/core/request.ts:84]: Could we do something like
```suggestion
		const { ...headersDesc, value, writable } = Object.getOwnPropertyDescriptor(request, 'headers') || {};
```

Or alternatively only pass specific properties in the `defineProperty` call below? Using `delete` is usually more expensive than either of the two approaches above, so would be nice to avoid that if possible.

File: .changeset/tame-hats-fold.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': major
```
Comment (bluwy) [inline .changeset/tame-hats-fold.md:2]:
```suggestion
'astro': patch
```

I believe this is a bug fix

File: packages/astro/src/core/request.ts (hunk 1 above)
Comment (avanderbergh) [reply packages/astro/src/core/request.ts]: Agreed!

**Review by bluwy — APPROVED** [review]
Thanks for fixing this!

**Comment by avanderbergh** [comment]
@bluwy Hey, I just fixed a merge conflict by rebasing on `main`, hope that's the right way...

Does it need a new approval now? 😅

**Comment by bluwy** [comment]
No problem. LGTM!

**Comment by avanderbergh** [comment]
Thank you! 🙌🏻
