### PR TITLE
Fix: component styles within imported markdown files

### LINKED ISSUE #3054: 🐛 BUG: Markdown-imported component styles do not get applied when `Astro.glob().Content` is used
### What version of `astro` are you using?

1.0.0-beta.5

### What package manager are you using?

yarn / pnpm

### What operating system are you using?

Linux

### Describe the Bug

1. Create a `src/markdowns/file.md` file with the following:
```md
---
setup: import Styled from "../components/StyledCompoent.astro"
---
<Styled></Styled>
```
2. Create a `src/components/StyledCompoent.astro` with the following
```astro
<h1> This should be red </h1>
<style>
  h1 {color:red;}
</style>
```
3. Replace `index.astro` with
```astro
---
	let pages = await Astro.glob("../markdowns/*.md")
---
<html lang="en">
	<head>
	</head>
	<body>
		{pages.map(page=> (
			<page.Content />
		))}
	</body>
</html>
```
4. `dev` or `build` the project

## Expected
There is a red `<h1>` component

## Actual
There is a black `<h1>` component

Adding the following line to the `index.astro` frontmatter
```js
import Styled from "../components/StyledCompoent.astro"
```
will side-effect import the styles, and I get the expected, red `<h1>`.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/pedantic-archimedes-p3k2n0?file=/src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes
- resolves #3054 
- Instead of applying a path prefix on imported markdown files, apply a flag to the suffix. This allows Vite to resolve the markdown file in the module graph, so we can parse imported styles on our end

## Testing

TODO

## Docs

N/A

### CODE REVIEW

**Comment by bholmesdev** [comment]
**Update: this PR doesn't fix production builds!**

This specifically has to do with our deferred markdown `load`. The change in the PR _is_ necessary for this to work at all. But by replacing `async function load()` to pull in a static ESM import instead of an async import, it works. We don't want to introduce eager loading of markdown just for style processing, but it makes our CSS crawling logic out-of-sync.

The sequence is this:
load page -> crawl CSS -> deferred markdown load
But we want:
load page -> deferred markdown load -> crawl CSS

File: packages/astro/src/vite-plugin-markdown/index.ts [hunk 1]
```diff
@@ -17,7 +17,6 @@ interface AstroPluginOptions {
 }
 
 const VIRTUAL_MODULE_ID_PREFIX = 'astro:markdown';
-const VIRTUAL_MODULE_ID = '\0' + VIRTUAL_MODULE_ID_PREFIX;
```
Comment (bholmesdev) [inline packages/astro/src/vite-plugin-markdown/index.ts:20]: This `\0` prefix breaks module graph resolution for some reason. Since it appends `/@id/` to each entry, I assume this character messes with the path construction. Removing with the assumption others won't slap the `astro:markdown` prefix on us [as warned about here](https://vitejs.dev/guide/api-plugin.html#virtual-modules-convention)!

File: packages/astro/src/core/render/dev/css.ts [hunk 2]
```diff
@@ -30,8 +33,13 @@ export function getStylesForURL(filePath: URL, viteServer: vite.ViteDevServer):
 				continue;
 			}
 			if (id === entry.id) {
+				let upToDateEntry = entry;
+				if (!entry.ssrTransformResult) {
```
Comment (FredKSchott) [inline packages/astro/src/core/render/dev/css.ts:37]: can you add a comment explaining why you do this, for future readers? Given the "magic incantation" vibes we're starting to get from this function, we should probably comment everything here very liberally.

File: packages/astro/src/vite-plugin-markdown/index.ts (hunk 1 above)
Comment (FredKSchott) [reply packages/astro/src/vite-plugin-markdown/index.ts:20]: can you leave a comment here that `\0` breaks things, so that a future reader doesn't think to add it back?

**Review by FredKSchott — APPROVED** [review]
LGTM if you can get tests passing

File: packages/astro/src/vite-plugin-markdown/index.ts (hunk 1 above)
Comment (bholmesdev) [reply packages/astro/src/vite-plugin-markdown/index.ts:20]: switched back to special `?mdImport` flag bc of module resolution bugs. Removes the `VIRTUAL_MODULE_ID`!

**Review by natemoo-re — APPROVED** [review]
LGTM!

**Comment by matthewp** [comment]
lgtm
