### PR TITLE
[MDX] Pass injected frontmatter to layouts

### LINKED ISSUE #4216: Frontmatter injection in remark plugins does not work for MDX files
### What version of `astro` are you using?

1.0.0-rc.8

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows with WSL2 Arch, also tested on Linux Ubuntu

### Describe the Bug

When trying to convert my Astro flavored markdown files to MDX I've found that injecting in frontmatter does not work on remark plugins when using the `@astro/mdx` integration (I was trying to add a reading time computation).

I linked in the reproduction section the repo I've been working on. This might not be a "minimal" reproduction so if needed just ask me and I'll provide one. When checking my repo be sure to stay on the `chore/update-astro` branch as this is the branch that the changes are about.

Because when using MDX you cannot access the content of the file from the layout like you could with Astro Markdown, you can no longer access it without injecting frontmatter variables.

If you need any details I'll be glad to answer. Have a wonderful day.

### Link to Minimal Reproducible Example

https://github.com/ColinEspinas/personal-website/tree/chore/update-astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #4216
- Moves layout generation to our frontmatter rehype plugin. This lets us parse injected frontmatter before passing as a layout prop, and aligns our MDX code with `vite-plugin-markdown`!

## Testing

Test injected frontmatter in layouts

## Docs

N/A

### CODE REVIEW

File: packages/integrations/mdx/src/astro-data-utils.ts [hunk 1]
```diff
@@ -19,6 +19,42 @@ export function rehypeApplyFrontmatterExport(pageFrontmatter: Record<string, any
...
+						get() {
+							throw new Error('The "astro" property is no longer supported! To access "html" from your layout, try using "Astro.props.compiledContent()."')
+						}
+					});
+					Object.defineProperty(content.astro, 'source', {
+						get() {
+							throw new Error('The "astro" property is no longer supported! To access "source" from your layout, try using "Astro.props.rawContent()."')
+						}
+					});
+					return layoutJsx(Layout, {
```
Comment (bholmesdev) [inline packages/integrations/mdx/src/astro-data-utils.ts:47]: Now using `astro/jsx-runtime` manually instead of raw JSX expressions. Otherwise, acorn can't properly parse to an ES tree entry.

Comment (natemoo-re) [reply packages/integrations/mdx/src/astro-data-utils.ts:47]: Makes sense!

File: packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/layouts/Base.astro [hunk 2]
```diff
@@ -0,0 +1,17 @@
...
+const { frontmatter = defaults, content = defaults } = Astro.props;
+---
+
+<!DOCTYPE html>
+<html lang="en">
+<head>
+  <meta charset="UTF-8">
+  <meta http-equiv="X-UA-Compatible" content="IE=edge">
+  <meta name="viewport" content="width=device-width, initial-scale=1.0">
+  <title>{frontmatter.title ?? content.title}</title>
```
Comment (natemoo-re) [inline packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/layouts/Base.astro:12]: Shouldn't this only test `frontmatter.title`?

**Review by natemoo-re — APPROVED** [review]
LGTM!

File: packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/layouts/Base.astro (hunk 2 above)
Comment (bholmesdev) [reply packages/integrations/mdx/test/fixtures/mdx-frontmatter-injection/src/layouts/Base.astro:12]: `content` and `frontmatter` are the same thing! Other tests cover that these each exist. I can remove though since `content` is removed from docs
