### PR TITLE
fix(react): Fix hydration mismatch for experimentalReactChildren

### LINKED ISSUE #15102: experimentalReactChildren flag doesn't map node.class and children keys on client
### Astro Info

```block
Astro                    v5.16.3
Node                     v20.15.0
System                   Windows (x64)
Package Manager          unknown
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/react
                         @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

I’m not entirely sure whether this is intended behavior, but from what I can tell this appears to be missing functionality, or at least a bug.

When `experimentalReactChildren=true`, classes on children passed into React components are not mapped to `className` on the client but only on server-side. Additionally, all children appear to be missing `key` props on the client as well.

There is an existing discussion that touches on this and explains it better than I can from nearly two years ago:
https://github.com/withastro/roadmap/discussions/917

### `children` logged on client
```js
[
    {
        "type": "span",
        "key": null,
        "props": {
            "class": "title",
            "data-astro-source-file": "/home/projects/bnmijzjyny.github/src/pages/index.astro",
            "data-astro-source-loc": "15:25",
            "children": [
                "Hello"
            ]
        },
        "_owner": null,
        "_store": {}
    },
    {
        "type": "span",
        "key": null,
        "props": {
            "class": "subtitle",
            "data-astro-source-file": "/home/projects/bnmijzjyny.github/src/pages/index.astro",
            "data-astro-source-loc": "16:28",
            "children": [
                "World"
            ]
        },
        "_owner": null,
        "_store": {}
    }
]
```
### Subsequent Client errors:
- Each child in a list should have a "key" prop
- Invalid DOM property 'class.' DId you mean *'className'*?
```
A tree hydrated but some attributes of the server rendered HTML didn't match the client properties. 

  <MyReactComponent>
    <div>
      <span
        class="title"
+       data-astro-source-file="/home/projects/bnmijzjyny.github/src/pages/index.astro"
-       data-astro-source-file={null}
+       data-astro-source-loc="15:25"
-       data-astro-source-loc={null}
      >
      <span
        class="subtitle"
+       data-astro-source-file="/home/projects/bnmijzjyny.github/src/pages/index.astro"
-       data-astro-source-file={null}
+       data-astro-source-loc="16:28"
-       data-astro-source-loc={null}
      >
```
### `children` logged on server (expected on client)
```js
[
  {
    '$$typeof': Symbol(react.transitional.element),
    type: 'span',
    key: '85-0',
    props: {
      'data-astro-source-file': '/home/projects/bnmijzjyny.github/src/pages/index.astro',
      'data-astro-source-loc': '15:25',
      className: 'title',
      children: [Array]
    },
    _owner: null,
    _store: {}
  },
  {
    '$$typeof': Symbol(react.transitional.element),
    type: 'span',
    key: '85-1',
    props: {
      'data-astro-source-file': '/home/projects/bnmijzjyny.github/src/pages/index.astro',
      'data-astro-source-loc': '16:28',
      className: 'subtitle',
      children: [Array]
    },
    _owner: null,
    _store: {}
  }
]
```

There is a full reproduction of this attached below. You'll need to open the preview in a separate tab to view console logs 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-2mtqsque?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by kedarvartak**
Fixes hydration mismatch when using `experimentalReactChildren` option.

### Problem

When `experimentalReactChildren=true`, children passed to React components had inconsistent prop handling between server and client:

- Server correctly mapped `class` to `className` and generated unique `key` props
- Client read DOM attributes directly without applying the same transformations

This caused React warnings and hydration errors:
- "Invalid DOM property 'class'. Did you mean 'className'?"
- "Each child in a list should have a unique 'key' prop."

### Solution

Updated the client-side [createReactElementFromDOMElement](cci:1://file:///home/shashank/Desktop/side%20pros/astro/packages/integrations/react/src/client.ts:19:0-53:1) function in [client.ts](cci:7://file:///home/shashank/Desktop/side%20pros/astro/packages/integrations/react/src/client.ts:0:0-0:0) to:
- Map DOM attribute names to React prop names (class to className, for to htmlFor)
- Generate unique key props for each child element

### Testing

Added unit tests for class-to-className mapping and key generation. All existing tests pass.

Closes #15102

### CODE REVIEW

**Comment by matthewp** [comment]
Can you change this to go against `next` instead?

File: packages/integrations/react/src/client.ts [hunk 1]
```diff
@@ -28,7 +44,7 @@ function createReactElementFromDOMElement(element: any): any {
 				if (c.nodeType === Node.TEXT_NODE) {
 					return c.data;
 				} else if (c.nodeType === Node.ELEMENT_NODE) {
-					return createReactElementFromDOMElement(c);
+					return createReactElementFromDOMElement(c, id, childKey++);
```
Comment (ematipico) [inline packages/integrations/react/src/client.ts]: If possible, please avoid post update expressions like this, because they are very easy to get wrong. Instead, let's do this


```suggestion
					childKey += 1;
					return createReactElementFromDOMElement(c, id, childKey);
```

File: packages/integrations/react/src/client.ts [hunk 2]
```diff
@@ -10,16 +10,32 @@ function isAlreadyHydrated(element: HTMLElement) {
...
+const reactPropsMap: Record<string, string> = {
+	class: 'className',
+	for: 'htmlFor',
+};
+
+let clientIds = 0;
+
+function createReactElementFromDOMElement(element: any, id?: number, key?: number): any {
+	if (id === undefined) {
+		id = clientIds++;
```
Comment (ematipico) [inline packages/integrations/react/src/client.ts]: Same here

```suggestion
		clientIds += 1;
		id = clientIds;
```

**Review by ematipico — DISMISSED** [review]

**Comment by kedarvartak** [comment]
@ematipico hi so sorry for the massive delay, i have updated the pr as per your change requests. thanks
