### PR TITLE
fix: add render() to stub content type defs

### LINKED ISSUE #12837: Module '"astro:content"' has no exported member 'render'.ts
### Astro Info

```block
Astro                    v5.1.1
Node                     v23.3.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/vercel
Integrations             @astrojs/react
                         @astrojs/tailwind
                         @astrojs/mdx
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

截圖 2024-12-27 晚上9 23 29

### What's the expected result?

without type error

### Link to Minimal Reproducible Example

https://github.com/leochiu-a/astro-practice

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

The generated `astro:content` runtime includes a `render` function, which has types that are created using typegen. However these types are missing from the stub types used before the first sync. This PR adds a stub declaration.

Fixes #12837 

## Testing
Tested a preview build. It's hard to test in the monorepo because it tends to find random `content.d.ts` files scattered throughout the repo.

### CODE REVIEW

**Comment by ascorbic** [comment]
!preview render-type

**Review by ematipico — APPROVED** [review]

File: packages/astro/types/content.d.ts [hunk 1]
```diff
@@ -89,27 +89,29 @@ declare module 'astro:content' {
 		input: CollectionConfig<S>,
 	): CollectionConfig<S>;
 
-	/** Run `astro sync` to generate high fidelity types */
+	/** Run `astro dev` or `astro sync` to generate high fidelity types */
```
Comment (ascorbic) [inline packages/astro/types/content.d.ts:92]: I've changed the jsdocs for these because most people will run `astro dev` rather than `astro sync`
