### PR TITLE
Fix: `astro:server:setup` middleware

### LINKED ISSUE #6729: Error using Astro and Partytown plugin: 404 Not Found for partytown-sandbox-sw.js and partytown-sw.js
### What version of `astro` are you using?

2.1.9

### Are you using an SSR adapter? If so, which one?

no

### What package manager are you using?

npm

### What operating system are you using?

MacOS

### What browser are you using?

Chrome, Safari, Firefox

### Describe the Bug

I am encountering an error when using the Astro framework version 2.1.9 and the Partytown plugin. The error message is:

```bash
09:41:25 PM [serve]    404 /~partytown/debug/partytown-sandbox-sw.js
09:41:26 PM [serve]    404        /~partytown/debug/partytown-sw.js
```
I have tested this issue with Partytown versions 1.1.1 and 1.2.0. However, when using Astro version 2.1.7, both versions of Partytown work without any issues.

I am unsure whether this is a problem with Astro or the Partytown plugin.

### Link to Minimal Reproducible Example

https://github.com/alexsedeke/astropartytown.git

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bholmesdev**
## Changes

- Resolves #6729 
- #6693 removed a duplicate `astro:server:setup` call from `create-vite`. Turns out, _this_ is where the setup hook should be run! By only calling from the `container`, we were attaching middlewares after Vite had setup the server. Moving this call to the original plugin with `configureServer` solves the issue.

## Testing

- Add middlewares test to make sure integration API example works https://docs.astro.build/en/reference/integrations-reference/#astroserversetup

### CODE REVIEW

File: examples/minimal/src/env.d.ts [hunk 1]
```diff
@@ -1 +1,2 @@
+/// <reference path="../.astro/types.d.ts" />
```
Comment (ematipico) [inline examples/minimal/src/env.d.ts:1]: Is the change intended?

**Review by ematipico — APPROVED** [review]

File: examples/minimal/src/env.d.ts (hunk 1 above)
Comment (bholmesdev) [reply examples/minimal/src/env.d.ts:1]: Nope! Reverting
