### PR TITLE
fix(assets): resolve Picture TDZ error when combined with content render()

### LINKED ISSUE #16036: Image breaks on prerendering whenever there is another file with getStaticPaths and render(content)
### Astro Info

```block
Astro                    v6.0.8
Node                     v25.8.1
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  @astrojs/cloudflare
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

Whenever there is another file with `await render(post)` the image optimization for prerendered pages returns the following error

22:40:55   ├─ /index.html22:40:55 [ERROR] ReferenceError: Cannot access '$$Picture' before initialization
    at file:///Users/alexanderniebuhr/Developer/tmp/astro-repro-css/dist/server/.prerender/chunks/Picture_BgQajNq-.mjs:745:12

### What's the expected result?

Image optimization works in prerendering

### Link to Minimal Reproducible Example

https://github.com/alexanderniebuhr/astro-v6-repro/tree/bug-2

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by Desel72**
Introduce an internal virtual module (`virtual:astro-get-image`) that exports only `getImage` and `imageConfig` without any Astro component references. The content runtime now imports from this narrower module instead of `astro:assets`, breaking the circular initialization dependency that caused a TDZ ReferenceError when prerendered pages using `<Picture>` were bundled in the same chunk as content collection `render()` calls.

Closes #16036

## Changes

- Added a new internal virtual module `virtual:astro-get-image` in `packages/astro/src/assets/consts.ts` that exports only `getImage` and `imageConfig` — no `Image`, `Picture`, or `Font` component references.
- Extended the `astro:assets` Vite plugin in `packages/astro/src/assets/vite-plugin-assets.ts` to resolve and load the new virtual module.
- Changed `packages/astro/src/content/runtime.ts` to import `getImage` from `virtual:astro-get-image` instead of `astro:assets`, avoiding the TDZ caused by Rollup eagerly referencing `$$Picture` in the namespace object before its declaration is initialized.
- Uses `virtual:` prefix (like existing `virtual:image-service`) rather than `astro:` prefix to keep this as an internal module and avoid exposing new public API surface.

## Testing

Added a regression test (`content-collection-picture-render.test.js`) with a fixture that reproduces the exact scenario:
- A prerendered page using `<Picture>` from `astro:assets`
- A content collection page using `getStaticPaths()` + `render(entry)` with images in markdown body

Without the fix, `astro build` fails with:
ReferenceError: Cannot access '$$Picture' before initialization

With the fix, the build succeeds and all 4 test assertions pass. Existing related test suites also pass with zero regressions:
- `content-collection-tla-svg.test.js` (3/3)
- `content-collections-render.test.js` (13/13)
- `core-image-picture-emit-file.test.js` (6/6)
- `units/content-collections/image-references.test.js` (9/9)

## Docs

No docs changes needed. This is a bug fix for an internal module resolution issue — no user-facing API changes.

### CODE REVIEW

**Comment by Daedalus-Icarus** [comment]
Hi @matthewp I think this is not related with my change. If you have some free time, please check this PR.

**Comment by alexanderniebuhr** [comment]
@Desel72 thank you for your PR. Will get this reviewed.

File: packages/astro/src/content/runtime.ts [hunk 1]
```diff
@@ -454,8 +454,9 @@ async function updateImageReferencesInBody(html: string, fileName: string) {
 
 	const imageObjects = new Map<string, GetImageResult>();
 
-	// @ts-expect-error Virtual module resolved at runtime
-	const { getImage } = await import('astro:assets');
+	// @ts-expect-error Internal virtual module that exports only getImage (no component
+	// references like Image/Picture) to avoid TDZ errors during prerender bundling (#16036).
+	const { getImage } = await import('virtual:astro:get-image');
```
Comment (ematipico) [inline packages/astro/src/content/runtime.ts]: We must add this module to `dev-only.d.ts`, so that we don't need the ts directive

**Review by ematipico — CHANGES_REQUESTED** [review]

**Comment by Daedalus-Icarus** [comment]
Hi @alexanderniebuhr Can this be merged?

File: packages/astro/src/content/runtime.ts (hunk 1 above)
Comment (alexanderniebuhr) [reply packages/astro/src/content/runtime.ts]: @Desel72 can you address this comment please?

**Comment by matthewp** [comment]
@Desel72 you need to address Ema's feedback: https://github.com/withastro/astro/pull/16171#discussion_r3022150487

**Comment by Daedalus-Icarus** [comment]
Hi @matthewp @ematipico @alexanderniebuhr I've done. Please check.

**Comment by Daedalus-Icarus** [comment]
Hi @alexanderniebuhr Thanks. I am going to move to https://github.com/withastro/astro/issues/16035. I've created PR: https://github.com/withastro/astro/pull/16194. Please review asap.

**Comment by alexanderniebuhr** [comment]
Tested the preview in a real-life project and it works.

**Comment by matthewp** [comment]
@ematipico this is ready for another look when you have the chance

File: .changeset/fix-picture-tdz-content-render.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'astro': patch
+---
+
+Fixes a build error (`Cannot access '$$Picture' before initialization`) that occurred when a prerendered page used the `<Picture>` component and another page called `render()` on content collection entries
```
Comment (alexanderniebuhr) [inline .changeset/fix-picture-tdz-content-render.md]:
```suggestion
Fixes a build error that occurred when a pre-rendered page used the `<Picture>` component and another page called `render()` on content collection entries.
```
