### PR TITLE
Warn for third-party template installs with --yes

### LINKED ISSUE #15939: Potential Arbitrary Remote Code Execution via Third-Party Template
### Astro Info

```block
Astro                    v6.0.5
Node                     v25.5.0
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Summary
`create-astro` allows untrusted third-party templates to be downloaded and then runs dependency installation in the generated project. A malicious template can include lifecycle scripts (for example `postinstall`) that execute arbitrary OS commands on the victim machine during initialization.

This creates a trust-boundary violation and supply-chain RCE scenario when a user initializes a project with a third-party template.

### Details
Relevant behavior in source:

1. Third-party template identifiers are accepted directly:
- `packages/create-astro/src/actions/template.ts:120`
- `packages/create-astro/src/actions/template.ts:122`

Code path:
- `const isThirdParty = tmpl.includes('/');`
- `if (isThirdParty) return tmpl;`

This means values like `github:<owner>/<repo>` are treated as valid template targets without trust restrictions.

2. Template is downloaded into the target project directory:
- `packages/create-astro/src/actions/template.ts:140`

Code path:
- `await downloadTemplate(templateTarget, { ... })`

3. Verification step only checks that the template exists/reachable:
- `packages/create-astro/src/actions/verify.ts:23`

Code path:
- `const ok = await verifyTemplate(target);`

No integrity/trust policy is enforced for third-party template contents.

4. Dependency install is executed as part of initialization flow:
- `packages/create-astro/src/actions/dependencies.ts:23` (default prompt is install = true)
- `packages/create-astro/src/actions/dependencies.ts:109`

Code path:
- `return shell(packageManager, ['install'], { cwd, ... })`

Because install runs in the downloaded template directory, malicious `package.json` lifecycle scripts execute on the victim machine.

### PoC
Environment used:
- macOS
- npm
- `npm create astro@latest`

Malicious public template repository used:
- `github:resxar/asdvnaksndfkansdkfn`

PoC repository includes a `package.json` with a lifecycle script that writes `RCE_PROOF.txt` during install.

Reproduction steps:

1. Run initialization with third-party template:

```sh
npm create astro@latest victim-app -- --template github:resxar/asdvnaksndfkansdkfn --yes
```

2. Observe successful setup output showing dependency installation:

```text
Project initialized!
	- Template copied
	- Dependencies installed
	- Git initialized
```

3. Verify proof file created by malicious lifecycle script:

```sh
ls -la victim-app
```

Observed result:

```text
-rw-r--r--   1 shulkhan  staff   20 Mar 16 00:30 RCE_PROOF.txt
```

This confirms template-controlled code executed on the local machine during `create-astro` setup.

### Impact
Type:
- Arbitrary code execution on developer machine via supply-chain/trust-boundary violation.

Impacted users:
- Developers who run `npm create astro` with an untrusted third-party template.
- CI/bootstrap environments that automate project scaffolding with third-party template references.

Security impact:
- Confidentiality: malicious scripts can read local files/tokens.
- Integrity: scripts can modify source/config or install backdoors.
- Availability: scripts can delete/corrupt files or disrupt environment.

#### Ecosystem
- npm

#### Package name
- `create-astro`

### What's the expected result?

If it's installing a template from 3rd party, it should return 

```
  "Warning: this is a third-party template. Dependencies including lifecycle scripts 
   will be installed automatically. Use --no-install to skip."
```

This is consistent with how npm exec and npx handle untrusted package execution.
The ask is not to remove the feature, but to add appropriate friction for untrusted sources.

### Link to Minimal Reproducible Example

just run npm create astro@latest victim-app -- --template github:resxar/asdvnaksndfkansdkfn --yes

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- Add a warning when `--yes` is used with a third-party template, clarifying that dependency installation may run lifecycle scripts.
- Keep behavior unchanged for interactive installs and non-third-party templates.
- Closes #15939.

## Testing

- Test added

## Docs

- No docs update needed. This is CLI warning text for an existing workflow.

### CODE REVIEW

File: packages/create-astro/src/actions/template.ts [hunk 1]
```diff
@@ -132,6 +131,11 @@ export function getTemplateTarget(tmpl: string, ref = 'latest') {
 	}
 }
 
+export function isThirdPartyTemplate(tmpl: string) {
+	if (tmpl.startsWith('starlight')) return false;
```
Comment (Princesseuh) [inline packages/create-astro/src/actions/template.ts]: Doesn't this mean you could name your template starlightevil and not get the warning?

File: packages/create-astro/src/actions/dependencies.ts [hunk 2]
```diff
@@ -33,6 +42,13 @@ export async function dependencies(
 		}
 	}
 
+	if (ctx.yes && deps && ctx.template && isThirdPartyTemplate(ctx.template)) {
```
Comment (Princesseuh) [inline packages/create-astro/src/actions/dependencies.ts]: I feel like maybe we should always warn, not just when using yes?

File: packages/create-astro/src/actions/template.ts [hunk 3]
```diff
@@ -132,6 +131,11 @@ export function getTemplateTarget(tmpl: string, ref = 'latest') {
 	}
 }
 
+export function isThirdPartyTemplate(tmpl: string) {
```
Comment (ematipico) [inline packages/create-astro/src/actions/template.ts:134]: It would be nice to add a comment that explains the criteria that deem a template "third party"

File: packages/create-astro/src/actions/template.ts (hunk 1 above)
Comment (matthewp) [reply packages/create-astro/src/actions/template.ts]: starlightevil wouldn't download anything, as you have to have a `owner/repo` if its 3rd party. I changed it anyways.

File: packages/create-astro/src/actions/dependencies.ts (hunk 2 above)
Comment (matthewp) [reply packages/create-astro/src/actions/dependencies.ts]: Made it so it always warns 👍

File: packages/create-astro/src/actions/template.ts (hunk 3 above)
Comment (matthewp) [reply packages/create-astro/src/actions/template.ts:134]: Added an explanation, should have done it to start!
