### PR TITLE
Fix MDX heading IDs generation when using a frontmatter reference

### LINKED ISSUE #5780: Generated heading id from MDX is not expanded
### What version of `astro` are you using?

1.9.0

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Interpolated strings are not expanded before generating heading ids.

Example:

```mdx
---
title: 'MDX'
---

# {frontmatter.title}
```

will generate `<h1 id="frontmattertitle">MDX</h1>` instead of `<h1 id="mdx">MDX</h1>` as expected.

Repro: Build and check h1 id in `dist/mdx/index.html`

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-cbd34s

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by HiDeoo**
## Changes

This PR fixes #5780.

When using a frontmatter reference in a MDX heading, the ID generated for the heading is not using the reference value. For example,

```mdx
---
title: The Title
---

# {frontmatter.title}
```

would generate `<h1 id="frontmattertitle">The Title</h1>` instead of `<h1 id="the-title">The Title</h1>`.

This pull request updates the `@astrojs/markdown-remark` rehype plugin generating these IDs to fix this behavior:

1. For MDX document, if the heading is a `MDXTextExpression`, e.g. `# {frontmatter.title}`, the plugin will use the associated ESTree entry to get the variable path, e.g. `['frontmatter', 'title']`.
2. If the variable is referencing a frontmatter value, the plugin try to get the value from the Astro data containing the frontmatter.
3. If the value is found, the plugin will use it to generate the heading ID.

*Note: the added dev dependencies to `@astrojs/markdown-remark` are only used to reference types.*

## Testing

I added a new fixtures `test-with-frontmatter.mdx` to the `@astrojs/mdx` test suite to test the changes.

The tests covers various cases and syntaxes from a basic variable to nested list items:

```mdx
---
title: The Frontmatter Title
keywords: [Keyword 1, Keyword 2, Keyword 3]
tags:
  - Tag 1
  - Tag 2
  - Tag 3
items:
  - value: Item 1
  - value: Item 2
  - value: Item 3
nested_items:
  nested:
    - value: Nested Item 1
    - value: Nested Item 2
    - value: Nested Item 3
---

# {frontmatter.title}
## frontmatter.title
### {frontmatter.keywords[1]}
### {frontmatter.tags[0]}
#### {frontmatter.items[1].value}
##### {frontmatter.nested_items.nested[2].value}
###### {frontmatter.unknown}
```

## Docs

I could not find any specific mention regarding this specific behavior in the docs and I'm not sure if it's worth mentioning it.

### CODE REVIEW

**Review by natemoo-re — COMMENTED** [review]
Changes look good to me but want to pull @bholmesdev in since I know he's been working with MDX a lot lately

File: packages/markdown/remark/src/rehype-collect-headings.ts [hunk 1]
```diff
@@ -31,7 +34,18 @@ export function rehypeHeadingIds(): ReturnType<RehypePlugin> {
 				}
 				if (rawNodeTypes.has(child.type)) {
 					if (isMDX || codeTagNames.has(parent.tagName)) {
-						text += child.value;
+						let value = child.value;
+						const astroData = safelyGetAstroData(file.data);
```
Comment (bholmesdev) [inline packages/markdown/remark/src/rehype-collect-headings.ts:38]: Good catch! Nit: might move this call to the top of the function to avoid reparsing on every pass

File: packages/markdown/remark/src/rehype-collect-headings.ts [hunk 2]
```diff
@@ -57,3 +71,58 @@ export function rehypeHeadingIds(): ReturnType<RehypePlugin> {
...
+ * Check if an ESTree entry is `frontmatter.*.VARIABLE`.
+ * If it is, return the variable path (i.e. `["*", ..., "VARIABLE"]`) minus the `frontmatter` prefix.
+ */
+function getMdxFrontmatterVariablePath(node: MdxTextExpression): string[] | Error {
+	if (!node.data?.estree || node.data.estree.body.length !== 1) return new Error();
+
+	const statement = node.data.estree.body[0];
+
+	// Check for "[ANYTHING].[ANYTHING]".
+	if (statement.type !== 'ExpressionStatement' || statement.expression.type !== 'MemberExpression')
```
Comment (bholmesdev) [inline packages/markdown/remark/src/rehype-collect-headings.ts:85]:
```suggestion
	if (statement?.type !== 'ExpressionStatement' || statement.expression.type !== 'MemberExpression')
```

Nit: check `statement` isn't null

**Review by bholmesdev — COMMENTED** [review]
A few nits, but _amazing_ work. Thorough checks and unit testing here. An `ID`eal fix 👏

**Review by natemoo-re — APPROVED** [review]

**Review by bholmesdev — APPROVED** [review]
