### PR TITLE
fix(fonts): take build config into account

### LINKED ISSUE #13779: Experimental fonts API does not respect build.assetsPrefix
### Astro Info

```block
Astro                    v5.7.12
Node                     v20.11.0
System                   macOS (arm64)
Package Manager          yarn
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using the new Fonts feature in Astro, the generated font files do not respect the build.assetsPrefix configuration option. This results in incorrect asset URLs in the final build output, causing 404 errors when the site is deployed with a custom asset prefix (e.g., on a CDN or subpath).

### What's the expected result?

Expected behavior is that all font file URLs should be prefixed with the value set in build.assetsPrefix

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-vxyymqdj

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by florian-lefebvre**
## Changes

- Closes #13779
- Updates the vite plugin to take `config.build.assets` and `config.build.assetsPrefix` into account. This required updating most paths handling as it was not robust enough
- Refactors the fixture test

## Testing

- Updates existing unit tests
- Adds unit tests
- Refactors the fixture tests
- Adds fixture tests
- Manually tested

## Docs

Changeset

### CODE REVIEW

File: packages/astro/src/assets/fonts/vite-plugin-fonts.ts [hunk 1]
```diff
@@ -78,7 +80,10 @@ export function fontsPlugin({ settings, sync, logger }: Options): Plugin {
 	// We don't need to take the trailing slash and build output configuration options
 	// into account because we only serve (dev) or write (build) static assets (equivalent
 	// to trailingSlash: never)
-	const baseUrl = removeTrailingForwardSlash(settings.config.base) + URL_PREFIX;
+	const assetsDir = prependForwardSlash(
+		appendForwardSlash(joinPaths(settings.config.build.assets, ASSETS_DIR)),
+	);
+	const baseUrl = joinPaths(settings.config.base, assetsDir);
```
Comment (ematipico) [inline packages/astro/src/assets/fonts/vite-plugin-fonts.ts:86]: Why don't we remove the trailing slash anymore? Also, the comment must be updated. Line 82 still talks about trailing slash

**Review by ematipico — APPROVED** [review]

File: packages/astro/src/assets/fonts/vite-plugin-fonts.ts (hunk 1 above)
Comment (florian-lefebvre) [reply packages/astro/src/assets/fonts/vite-plugin-fonts.ts:85]: I've updated the comment thanks! We don't need to care about the trailing slash here anymore because this is handled by each `UrlResolver`, which use `joinPaths()` under the hood
