### PR TITLE
Graceful error recovery in the dev server

### LINKED ISSUE #5141: HMR: Creating a file after importing it does not refresh
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Add an import statement to a .astro file, for ex. `import '../script.js';` where the file does not exist.
2. An error message is displayed.
3. Create the file.
4. It should refresh but does not.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5143: HMR: Syntax error in Astro CSS does not refresh after fixed
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. In any .astro file create a syntax error in a `<style>` tag.
2. You will get an error message.
3. Fix the syntax error.
4. Should reload the browser; must reload yourself.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5144: HMR: Adding lang=scss when sass not installed, must refresh after fixing
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Do not install `sass`
2. In a style tag a .astro file add `lang="scss"`
3. You will get an error.
4. Remove the attribute to fix it.
5. It should reload, have to reload manually.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5155: HMR: Creating a file after @import does not refresh the browser
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Add an `@import` to a file that does not exist in your Astro CSS.
2. Create that file.
3. It should refresh the browser but does not.
4. Works after manual refresh.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5157: HMR: svelte - Importing a module before creating it does not refresh after fixing
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Use the svelte adapter.
2. In a svelte file, import a module that does not exist.
3. You get an error
4. Create that file
5. Browser does not reload

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5158: HMR: SolidJS Importing a module before creating it does not refresh after fixing
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Use the Solid adapter
2. Add an import to a module that does not exist
3. Create that module
4. The browser does not refresh.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5160: HMR: Vue - errors in script do not refresh after fixed
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Create an error in a `<script>` in a .vue file
2. No error overlay shown
3. Fix the error
4. The browser does not refresh

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5161: HMR - Vue, Creating file after importing does not refresh when fixed
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Use the vue adapter
2. Add an import statement in a .vue file to a file that does not exist.
3. You get an error
4. Create the file
5. The browser does not refresh.

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### LINKED ISSUE #5162: HMR - Vue, changing a dependency does not update the Vue module
### What version of `astro` are you using?

1.5.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

1. Use the vue adapter
2. Import a module in a .vue file
3. Make a change to the imported module
4. Changes do not reflect on the Vue side

### Link to Minimal Reproducible Example

n/a

### Participation

- [X] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
> Note that this PR is in draft mode and is not ready for review. It is intended to be tested against the current set of known HMR issues before it is marked as ready.

## Changes

- Refactors the vite-plugin-astro-server primary. This is to make it recovery from errors more easily.
- When an error occurs during a request or during an HMR update we save the state. When another HMR update occurs (hopefully to fix it), we reset the state and refresh the browser.

### Issues affected

- Fixes #5143
- Fixes #5158
- Fixes #5161
- Fixes #5160
- Fixes #5162
- Fixes #5141
- Fixes #5157
- Fixes #5155
- Fixes #5144

## Testing

- Unit testing added for the plugin, both for requests and for the new error state concept.
- Refactor for `core/dev`, which is meant to encompass all of what dev does. This essentially makes the dev server unit-testable without needing to start the actual dev server and send HTTP requests. You can also define .astro (or other modules) in a virtual filesystem, so no more fixture tests.

## Docs

N/A

### CODE REVIEW

**Comment by matthewp** [comment]
!preview hmr-recovery

**Comment by natemoo-re** [comment]
@matthewp No more fixture tests? That's amazing, very excited to give this a thorough review when I can!

File: packages/astro/src/vite-plugin-astro-server/plugin.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+		},
+		// HACK: hide `.tip` in Vite's ErrorOverlay and replace [vite] messages with [astro]
+		transform(code, id, opts = {}) {
+			if (opts.ssr) return;
+			if (!id.includes('vite/dist/client/client.mjs')) return;
+			return code
+				.replace(/\.tip \{[^}]*\}/gm, '.tip {\n  display: none;\n}')
+				.replace(/\[vite\]/g, '[astro]');
+		},
+	};
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-astro-server/plugin.ts:65]: cc @Princesseuh with this refactor, maybe it makes more sense to move this logic out of the `astro:server` plugin? Not sure if that's already on your radar.

File: packages/astro/src/vite-plugin-astro-server/server-state.ts [hunk 2]
```diff
@@ -0,0 +1,54 @@
+import type { ManifestData, RouteData } from '../@types/astro';
+
+export type ErrorState = 'fresh' | 'error' | 'unresponsive';
```
Comment (natemoo-re) [inline packages/astro/src/vite-plugin-astro-server/server-state.ts:3]: Not seeing where `unresponsive` is being used... remove?

File: packages/astro/test/units/dev/dev.test.js [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+				const name = 'Testing';
+				---
+				<html>
+					<head><title>{name}</title></head>
+					<body>
+						<h1>{name}</h1>
+					</body>
+				</html>
+			`
+		}, root);
```
Comment (natemoo-re) [inline packages/astro/test/units/dev/dev.test.js:23]: This is super nice. Great work!

**Review by natemoo-re — APPROVED** [review]
Looks awesome!

Very curious about the test structure here. I suppose `packages/astro/test/units/**` is the path of least resistance, but would it make more sense to have unit tests next to the files they are testing? Maybe that's something we can follow-up with.

Edit: Realized this is still a draft, dismissing my approval. Happy to circle back when this is ready!

File: packages/astro/src/vite-plugin-astro-server/base.ts [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+	logging: LogOptions
+): vite.Connect.NextHandleFunction {
+	const { config } = settings;
+	const site = config.site ? new URL(config.base, config.site) : undefined;
+	const devRoot = site ? site.pathname : '/';
+
+	return function devBaseMiddleware(req, res, next) {
+		const url = req.url!;
+
+		const pathname = decodeURI(new URL(url, 'http://vitejs.dev').pathname);
```
[the remark this answers is not in the document]
Comment (matthewp) [reply packages/astro/src/vite-plugin-astro-server/base.ts:20]: The new parts are the server-state.ts and controller.ts modules.

File: packages/astro/src/vite-plugin-astro-server/server-state.ts (hunk 2 above)
Comment (matthewp) [reply packages/astro/src/vite-plugin-astro-server/server-state.ts:3]: It is unused for now. I'll remove it if it's not used by the time this is ready for review.

**Comment by matthewp** [comment]
!preview hmr-recovery

File: packages/astro/src/@types/typed-emitter.ts [hunk 5]
```diff
@@ -0,0 +1,49 @@
+/**
+ * The MIT License (MIT)
+ * Copyright (c) 2018 Andy Wermke
+ * https://github.com/andywer/typed-emitter/blob/9a139b6fa0ec6b0db6141b5b756b784e4f7ef4e4/LICENSE
```
Comment (matthewp) [inline packages/astro/src/@types/typed-emitter.ts:4]: Note that I brought this package internally because when Vite crawls through package.jsons, this one has a main but the main doesn't export anything so Vite warns about it not being a real ESM module. This is only a (small) types package, so brought it in.

**Review by bluwy — APPROVED** [review]
Looks great! With the amount of refactor for `ModuleLoader`, I might've gave up and mock fs directly instead 😄 But it'll be interesting to see how this plays out too.

**Review by natemoo-re — APPROVED** [review]
Looks straightforward. Nice refactors!

File: packages/astro/src/core/module-loader/loader.ts [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+	ssrError: Error | null;
+	importedModules: Set<ModuleNode>;
+}
+
+export interface ModuleInfo {
+	id: string;
+	meta?: Record<string, any>;
+}
+
+export function createLoader(overrides: Partial<ModuleLoader>): ModuleLoader {
```
Comment (tony-sull) [inline packages/astro/src/core/module-loader/loader.ts:54]: Very nice, I really like how the loader interface cleaned up the code flow here :+1:

**Review by tony-sull — APPROVED** [review]
Nice!  Big fan of the refactor to a `loader` interface for module resolution **and** the breakup of the dev server logic, makes for a much cleaner code base 🚀
