### PR TITLE
fix: make SVG ImageMetadata serializable

### LINKED ISSUE #13979: `JSON.stringify` does not work for SVG image objects since Astro 5.7.0
### Astro Info

```block
Astro                    v5.10.0
Node                     v20.19.1
System                   Linux (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

`JSON.stringify` does not work for SVG image objects (`ImageMetadata`) since Astro 5.7.0,  possibly due to commit 406501aeb7f314ae5c31f31a373c270e3b9ec715 which unflagged the SVG component feature and added extra properties to SVG image objects.

For example, the following code (see Minimal Reproducible Example) works in Astro 5.6.2 but not 5.7.0 and later versions:
```
import svgimage from '../assets/astro.svg';

console.log("SVG Image JSON:", JSON.stringify(svgimage));

// 5.6.2: {"src":"...", ...}
// 5.10.0: undefined
```
The bug also breaks pages where content collection entries with images are serialized.

## To reproduce:
1. Go the Minimal Reproducible Example
2. Run `pnpm install`
3. Run `pnpm run astro build --verbose`
4. Check the output

For expected result, replace `pnpm install` with `pnpm install astro@5.6.2`.

### What's the expected result?

`JSON.stringify` should output a serialized string as in the version 5.6.2.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-gbxuffpc?file=src%2Fpages%2Findex.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by ascorbic**
## Changes

When SVG components were introduced, the metadata was attached to the component so that they were backwards-compatible with former usage. However because they are now component factories they're not serializable with JSON.stringify anymore. This is a particular issue when they are attached to content entries, which may be returned by an endpoint.

This PR adds a `toJSON` method to the component that returns just the metadata. This makes it serialisable again.

Fixes #13979

## Testing

Added a test

### CODE REVIEW

File: packages/astro/src/assets/runtime.ts [hunk 1]
```diff
@@ -29,6 +29,11 @@ export function createSvgComponent({ meta, attributes, children }: SvgComponentP
 		});
 	}
 
+	Object.defineProperty(Component, 'toJSON', {
```
Comment (florian-lefebvre) [inline packages/astro/src/assets/runtime.ts:32]: Should it be `toString` instead?

Comment (ascorbic) [reply packages/astro/src/assets/runtime.ts:32]: No, this is specifically for `JSON.stringify`. [This section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) has a bit about it.

**Review by florian-lefebvre — APPROVED** [review]
