### PR TITLE
Fix JPEG image size determination

### LINKED ISSUE #12530: Incorrect image size determination with `inferRemoteSize()` or `inferSize=true` when JPEG image has specific metadata
### Astro Info

```block
Astro                    v4.16.14
Node                     v20.18.0
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             none
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

### Describe the Bug

When using `astro` to generate a static site, I've encountered an issue where the size of remote images is incorrectly determined using `inferRemoteSize()` or by passing `inferSize=true` to the `Image` or `Picture` component.

In the minimal reproducible example, a sample photo with a size of 3730 x 5535 pixels is incorrectly reported as 48719 x 62538. This causes the `Picture` or `Image` image optimization to fail with the error "Processed image is too large for the HEIF format".

```
 generating optimized images 
[CouldNotTransformImage] Could not transform image `https://live.staticflickr.com/65535/54163807312_d8456912ba_o_d.jpg`. See the stack trace for more information.
  Hint:
    This is often caused by a corrupted or malformed image. Re-exporting the image from your image editor may fix this issue.
  Error reference:
    https://docs.astro.build/en/reference/errors/could-not-transform-image/
  Location:
    /workspaces/astro-image-size/node_modules/astro/dist/assets/build/generate.js:134:21
  Stack trace:
    at generateImageInternal (file:///workspaces/astro-image-size/node_modules/astro/dist/assets/build/generate.js:134:21)
    at async file:///workspaces/astro-image-size/node_modules/p-queue/dist/index.js:187:36
  Caused by:
  Processed image is too large for the HEIF format
    at Sharp.toBuffer (/workspaces/astro-image-size/node_modules/sharp/lib/output.js:163:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateImage (file:///workspaces/astro-image-size/node_modules/astro/dist/assets/build/generate.js:71:28)
```

I've tried adjusting export options in Darktable, such as resolution, color space, and applied effects, but the reported image size remains incorrect. However, if I remove all metadata from the image, the size is correctly determined.

It appears that specific metadata in the JPEG file is conflicting with the way `inferRemoteSize()` determines image size.

### What's the expected result?

`inferRemoteSize()` and `inferSize=true` should correctly determine the image size, regardless of metadata.

### Link to Minimal Reproducible Example

https://github.com/kadykov/astro-image-size

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by kadykov**
Fixes #12530

## Changes

* Fixed incorrect handling of non-`0xFF` blocks in the JPEG image size calculation. Instead of skipping one byte, the entire block is now skipped, improving performance and accuracy.
* Before this change, the code would incorrectly enter and parse non-`0xFF` blocks, leading to incorrect image size determination. This change ensures that only valid JPEG blocks are processed, skipping unnecessary metadata blocks.

## Testing

This change was tested manually by verifying that the image size calculation is accurate for JPEG images with various metadata blocks. No new tests were added, as the existing tests should cover this scenario.

## Docs

This change does not affect user behavior, so no documentation updates are required. The fix is internal to the JPEG image size calculation logic and does not introduce any new features or APIs.

### CODE REVIEW

**Comment by Princesseuh** [comment]
This folder is a vendored version of `image-size`, I would suggest sending a PR there as well: https://github.com/image-size/image-size

Since the upstream package here is rarely updated, it should be fine to update our copy, though

File: packages/astro/src/assets/utils/vendor/image-size/types/jpg.ts [hunk 1]
```diff
@@ -122,7 +122,7 @@ export const JPG: IImage = {
 
       // Every JPEG block must begin with a 0xFF
       if (input[i] !== 0xff) {
-        input = input.slice(1)
+        input = input.slice(i)
```
Comment (Princesseuh) [inline packages/astro/src/assets/utils/vendor/image-size/types/jpg.ts:125]: Could you add a comment saying this is a change from upstream?

**Review by Princesseuh — APPROVED** [review]
Code looks great, thank you!
