### PR TITLE
Warn when Vite 8 is detected, and pin Vite 7 when adding the Cloudflare adapter

### LINKED ISSUE #16029: `require_dist is not a function` — Astro 6 + Cloudflare Adapter v13
### Astro Info

```block
Astro                    v6.0.8
Node                     v25.2.1
System                   macOS (arm64)
Package Manager          unknown
Output                   server
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/sitemap
```

### If this issue only occurs in one browser, which browser is a problem?

_No response_

## Environment

| | |
|---|---|
| Node.js | 25.2.1 |
| `astro` | 6.0.8 |
| `@astrojs/cloudflare` | 13.1.3 |
| `@cloudflare/vite-plugin` | 1.30.0 |
| `vite` (astro's) | 7.3.1 |
| `vite` (@cloudflare/vite-plugin's) | 8.0.1 ← **different version** |
| `rolldown` | 1.0.0-rc.10 |
| `cookie` | 1.1.1 |
| OS | macOS Darwin 24.6.0 |

**Config:** `output: 'server'`, `adapter: cloudflare()`

---

## Error

```
require_dist is not a function
TypeError: require_dist is not a function
    at null.<anonymous> (.vite/deps_ssr/logging-C3Ufh6FJ.js:15:19)
    at CustomModuleRunner.directRequest (workers/runner-worker/vite/module-runner:1204:59)
    at null.<anonymous> (.vite/deps_ssr/astro_app_entrypoint_dev.js:17:1)
    at CustomModuleRunner.directRequest (workers/runner-worker/vite/module-runner:1204:59)
    at null.<anonymous> (/virtual:astro:app:1:1)
```

Crashes on both `astro dev` and `astro build`. No routes are ever served.

---

### 1. Astro's `cookies.js` imports `cookie` as ESM

```js
// node_modules/astro/dist/core/cookies/cookies.js
import { parse, serialize } from "cookie";
```

### 2. `cookie@1.1.1` ships CJS only

No ESM export, no `"type": "module"`, no exports map. `"main": "dist/index.js"` points to:

```js
// node_modules/cookie/dist/index.js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parseCookie = parseCookie;
// ...
```

### 3. Rolldown wraps it with a `__commonJSMin` shim in `.vite/deps_ssr/`

```js
// .vite/deps_ssr/chunk-DOseaPKx.js  (rolldown/runtime.js)
var __commonJSMin = (cb, mod) => () => (mod || cb((mod = { exports: {} }).exports, mod), mod.exports);

// .vite/deps_ssr/astro___cookie.js
import { t as __commonJSMin } from "./chunk-DOseaPKx.js";
var require_dist = /* @__PURE__ */ __commonJSMin(/* full cookie CJS body */);
export { require_dist as t };
```

`require_dist` is a lazy initializer — calling `require_dist()` runs the CJS module and returns its exports.

### 4. The crash in `logging-C3Ufh6FJ.js`

```js
// .vite/deps_ssr/logging-C3Ufh6FJ.js
import { t as require_dist } from "./astro___cookie.js";  // line 10
// ...
var import_dist = require_dist();  // line 15 ← TypeError: require_dist is not a function
```

In Node.js this works fine. In workerd's `CustomModuleRunner`, the live binding resolves to `undefined` — meaning `astro___cookie.js` has not finished initializing its exports when line 15 executes.

### 5. Compounding factor — two Vite versions in the tree

`astro@6.0.8` depends on Vite 7.3.1. `@cloudflare/vite-plugin@1.30.0` depends on Vite 8.0.1. These are **not deduped** — both are installed simultaneously. The SSR pre-bundled deps in `.vite/deps_ssr/` are produced by one Vite version's pipeline and then executed by the `CustomModuleRunner` from the other. This version split is a likely contributor to the binding timing issue.

```
├─┬ @astrojs/cloudflare@13.1.3
│ ├─┬ @cloudflare/vite-plugin@1.30.0
│ │ └── vite@8.0.1 deduped
│ └── vite@7.3.1
├─┬ @tailwindcss/vite@4.2.2
│ └─┬ vite@8.0.1
│   └── rolldown@1.0.0-rc.10
└─┬ astro@6.0.8
  └── vite@7.3.1
```

---

## What Was Tried

Adding `cookie` to `optimizeDeps.include` via a `configEnvironment` Vite plugin (as recommended in the [Cloudflare v13 upgrade docs](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#upgrading-to-v13-and-astro-6)) does **not** help. The module is part of Astro's own internal SSR entrypoint bundle — it is not an app-level dependency that can be targeted by `optimizeDeps`.

---

## Suggested Fix Directions

1. **Astro ships an ESM-native cookie import** in its SSR output, eliminating the `__commonJSMin` shim entirely.
2. **`CustomModuleRunner` binding initialization** — `@cloudflare/vite-plugin`'s module runner should fully initialize all module bindings before executing dependents, matching Node.js ESM live-binding semantics.
3. **Resolve the Vite 7/8 version split** — Astro and `@cloudflare/vite-plugin` should share one Vite instance so the dep-bundling pipeline and module runner operate on the same version.

---

## References

- [Astro v6 upgrade guide](https://docs.astro.build/en/guides/upgrade-to/v6/)
- [Cloudflare adapter v13 upgrade guide](https://docs.astro.build/en/guides/integrations-guide/cloudflare/#upgrading-to-v13-and-astro-6)
- Related open issues in `withastro/astro` (Cloudflare v13 / Astro 6 area, found during search):
  - #15923 — workerd prerender + @sentry/astro writes empty prerendered HTML
  - #15970 — Cloudflare v13 ignores `imageService: 'compile'` in dev mode
  - #15722 — `<Prism />` throws on `astro dev` with Cloudflare Workers integration
  - #15878 — vitest + Cloudflare: "Avoid setting resolve.external" error

### What's the expected result?

I was expecting the system to simply come up but instead it reports a rather cryptic stack trace. Claude Code helped me pinpoint where it was coming from.

### Link to Minimal Reproducible Example

https://github.com/gregturn/mountainsummitpress.com

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by matthewp**
## Changes

- When `astro dev` starts, Astro now checks if `vite@8` is installed at the top level of the user's project and emits a warning directing them to add `"overrides": { "vite": "^7" }` to their `package.json`. Vite 8 at the top level causes subtle breakage with the Cloudflare adapter because `@cloudflare/vite-plugin` resolves `vite` via Node's normal module resolution (no nested copy of its own), so it picks up the user's hoisted Vite 8 instead of Astro's Vite 7 — leading to a `require_dist is not a function` crash in workerd's `CustomModuleRunner`.
- `astro add cloudflare` now prompts the user to add `"overrides": { "vite": "^7" }` to their `package.json` automatically. This prevents the issue from being introduced later (e.g. if the user installs `@tailwindcss/vite` after adding the Cloudflare adapter, which hoists Vite 8 to the top level).

## Testing

- Reproduced the crash manually: `npm create astro@latest` with `--add cloudflare --add tailwind`, delete `node_modules` + `package-lock.json`, reinstall — `astro build` fails with `require_dist is not a function`. Adding `"overrides": { "vite": "^7" }` resolves it.

## Docs

No docs update needed — the warning itself is user-facing guidance, and the `astro add` prompt explains the change inline.

Closes #16029

### CODE REVIEW

File: packages/astro/src/core/dev/dev.ts [hunk 1]
```diff
@@ -24,6 +25,19 @@ import {
...
+	try {
+		const require = createRequire(root);
+		const { version } = require('vite/package.json') as { version: string };
+		if (major(version) >= 8) {
+			logger.warn('SKIP_FORMAT', msg.vite8Warning({ viteVersion: version }));
+		}
+	} catch {
+		// If vite can't be resolved from the project root, skip the warning
+	}
+}
```
Comment (ematipico) [inline packages/astro/src/core/dev/dev.ts:40]: Vite already exposes its version number via APIs. We can use that

```js
import { version  } from "vite"
```

Comment (matthewp) [reply packages/astro/src/core/dev/dev.ts:40]: `import { version  } from "vite"` would load our version of Vite, but the goal here is to check the top-level version (which is owned by the user) to see if it's an incompatible version.

**Comment by gregturn** [comment]
Thanks @matthewp for jumping on this. I agree that a user-facing warning from Astro itself is miles better than a doc update. I'll withdraw the docs PR.

**Comment by sebastienbarre** [comment]
Just curious, how will this be actually fixed? By supporting Vite 8 I assume? On Cloudflare side? What would be the best place to monitor such progress? Thank you.

**Comment by matthewp** [comment]
@sebastienbarre the long term fix is Vite 8, yes. We'll have an alpha with that soon, but it will probably require a new major version of Astro.
