### PR TITLE
Show injected custom 404 route in dev

### LINKED ISSUE #6937: Custom 404 page injected using `injectRoute` not used
### What version of `astro` are you using?

2.3.2

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm/pnpm

### What operating system are you using?

macOS / Stackblitz

### What browser are you using?

Firefox

### Describe the Bug

When a project includes `src/pages/404.astro`, this route gets used as a custom 404 page, including in dev.

However, if an integration uses the `injectRoute` hook to inject a custom page at `/404`, Astro does not treat this the same way: the injected page is only available at `/404`, other 404 errors continue to show the standard Astro 404 screen during dev. (The injected route _does_ get correctly built as `404.html` though, so should work in production on static hosts that support that pattern like Netlify.)

I’d expect injecting a route to `/404` to allow an integration to set the 404 users see during dev.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3u16qb?file=astro.config.mjs

### Participation

- [x] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by delucis**
## Changes

- Fixes #6937
- Updates `getCustom404Route` logic to find 404s added via `injectRoute`
- As a side effect, also adds support for `src/pages/404.html`, which we don’t have currently.

## Testing

Added a fixture + test like we have for the current custom 404 strategies and also a dev server unit test.

I also applied the same changes in a patch inside a monorepo project to test the logic when the injected route comes from a separate package.

## Docs

Bug fix, no docs needed.

### CODE REVIEW

File: packages/astro/src/vite-plugin-astro-server/route.ts [hunk 1]
```diff
@@ -35,11 +33,9 @@ interface MatchedRoute {
...
 }
 
-function getCustom404Route({ config }: AstroSettings, manifest: ManifestData) {
-	// For Windows compat, use relative page paths to match the 404 route
-	const relPages = resolvePages(config).href.replace(config.root.href, '');
-	const pattern = new RegExp(`${appendForwardSlash(relPages)}404.(astro|md)`);
-	return manifest.routes.find((r) => r.component.match(pattern));
+function getCustom404Route(manifest: ManifestData): RouteData | undefined {
+	const route404 = /^\/404\/?$/;
+	return manifest.routes.find((r) => route404.test(r.route));
```
Comment (delucis) [inline packages/astro/src/vite-plugin-astro-server/route.ts:38]: I think this is safe? Previously we only supported `404.astro`, `404.md`, `404.mdx`, and `404.mdoc` as custom 404 routes. Those would all have a `route` of `/404` or `/404/`, so are still supported. This change adds custom 404 support for `src/pages/404.html` or for `injectRoute('404', ...)` in dev.

File: packages/astro/test/units/dev/dev.test.js [hunk 2]
```diff
@@ -158,6 +158,68 @@ describe('dev container', () => {
...
+					expect(r.res.statusCode).to.equal(200);
+				}
+				{
+					// `/404` serves the custom 404 page as expected.
+					const r = createRequestAndResponse({ method: 'GET', url: '/404' });
+					container.handle(r.req, r.res);
+					await r.done;
+					const doc = await r.text();
+					expect(doc).to.match(/<h1>Custom 404<\/h1>/);
+					expect(r.res.statusCode).to.equal(200);
```
Comment (delucis) [inline packages/astro/test/units/dev/dev.test.js:208]: Not quite sure whether we should expect a 404 status here or whether this request/response mock always returns 200?

**Comment by delucis** [comment]
Looks like the logic that renders custom 404s is failing for injected routes on Windows only 🤔

**Review by matthewp — APPROVED** [review]
