### PR TITLE
Remove proload for config loading

### LINKED ISSUE #5459: Issue with `astro add` and `@astrojs/mdx`
### What version of `astro` are you using?

1.6.10

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

pnpm

### What operating system are you using?

Windows [WSL]

### Describe the Bug

The addition of Preact leads to an error:
```txt
hp@DESKTOP-H1T4LNI MINGW64 ~/My Repositories/personal/peppered-pen (main)
$ pnpm astro add preact

> @example/basics@0.0.1 astro C:\Users\hp\My Repositories\personal\peppered-pen
> astro "add" "preact"

⠋ Resolving packages...(node:9628) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Resolving packages...

  Astro will run the following command:
  If you skip this step, you can always run it yourself later

 ╭──────────────────────────────────────────╮
 │ pnpm add @astrojs/preact preact@^10.6.5  │
 ╰──────────────────────────────────────────╯

√ Continue? ... yes
✔ Installing dependencies...
 error   Failed to resolve entry for package "estree-walker". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "estree-walker" package    
  File:
    C:\Users\hp\My Repositories\personal\peppered-pen\node_modules\.pnpm\vite@3.2.4\node_modules\vite\dist\node\chunks\dep-67e7f8ab.js:34100:11
  Code:
      34099 | function packageEntryFailure(id, details) {
    > 34100 |     throw new Error(`Failed to resolve entry for package "${id}". ` +
            |           ^
      34101 |         `The package may have incorrect main/module/exports specified in its package.json` +
      34102 |         (details ? ': ' + details : '.'));
      34103 | }

  Stacktrace:
Error: Failed to resolve entry for package "estree-walker". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "estree-walker" package      
    at packageEntryFailure (file:///C:/Users/hp/My%20Repositories/personal/peppered-pen/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34100:11)
    at resolvePackageEntry (file:///C:/Users/hp/My%20Repositories/personal/peppered-pen/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:34095:9)
    at tryNodeResolve (file:///C:/Users/hp/My%20Repositories/personal/peppered-pen/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:33838:20)
    at viteResolve (file:///C:/Users/hp/My%20Repositories/personal/peppered-pen/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:53085:26)
    at Function._resolveFilename (file:///C:/Users/hp/My%20Repositories/personal/peppered-pen/node_modules/.pnpm/vite@3.2.4/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:53105:32)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\hp\My Repositories\personal\peppered-pen\node_modules\.pnpm\estree-util-build-jsx@2.2.0\node_modules\estree-util-build-jsx\lib\index.js:23:28)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

 ELIFECYCLE  Command failed with exit code 1.
```

Not sure how to replicate this in stackblitz.

### Link to Minimal Reproducible Example

-

### Participation

- [ ] I am willing to submit a pull request for this issue.

### PR DESCRIPTION
**Pull request by bluwy**
## Changes

Close https://github.com/withastro/astro/issues/5748
Fix https://github.com/withastro/astro/issues/5459

- Remove proload, so only fallback to load with Vite only.
- Refactor `resolveConfigPath` to only search for a config path, and not load the config itself, this fixes #5459

Note: I tried to use Vite's `loadConfigFromFile` instead, but it doesn't bring much benefit for us, and prevents named exports from the Astro config if we ever need it. It's also harder to test with `createFs` since `loadConfigFromFile` always read from the actual filesystem.
## Testing

Existing config loading test should work. Since this _removes_ a proload feature, I don't think there's new test to add.

## Docs

n/a. Ideally loading the config with Vite should always work, so this change shouldn't need a docs update.

### CODE REVIEW

File: packages/astro/src/content/utils.ts [hunk 1]
```diff
@@ -207,9 +206,6 @@ export async function loadContentConfig({
 		return new NotFoundError('Failed to resolve content config.');
 	} finally {
 		await tempConfigServer.close();
-		// Reset NODE_ENV to initial value
-		// Vite's `createServer()` sets NODE_ENV to 'development'!
-		process.env.NODE_ENV = nodeEnv;
```
Comment (bluwy) [inline packages/astro/src/content/utils.ts:212]: This removal undoes https://github.com/withastro/astro/pull/5700#pullrequestreview-1232968289 since we're already using Vite 4. Thought I'll make this change since this PR is config related.

File: packages/astro/src/core/config/config.ts [hunk 2]
```diff
@@ -136,6 +136,23 @@ function mergeCLIFlags(astroConfig: AstroUserConfig, flags: CLIFlags, cmd: strin
...
+		'astro.config.mjs',
+		'astro.config.js',
+		'astro.config.ts',
+		'astro.config.mts',
+		'astro.config.cjs',
+		'astro.config.cts',
+	].map((p) => path.join(root, p));
+
+	for (const file of paths) {
+		if (fsMod.existsSync(file)) {
```
Comment (bluwy) [inline packages/astro/src/core/config/config.ts:150]: The previous function uses `stat` to check file existence, I switched to `existsSync` since it should be the same.
